### ISSUE TITLE
version 4.10.7 compile fails - calling nonexistant file

### ISSUE THREAD

**Issue by zug** [MapServer/MapServer#4278]
I'm running RHEL v 5.6, and I'm attempting to compile version 4.10.7

configure (no options) works, but make fails:

[acpbwork@416239-db1 mapserver-4.10.7]$ make
: -Pmsyy -i -omaplexer.c maplexer.l
gcc -c -O2 -fPIC -Wall     -DHAVE_VSNPRINTF -DNEED_STRLCAT  -DUSE_EPPL      -DUSE_JPEG -DUSE_GD_GIF -DUSE_GD_PNG -DUSE_GD_JPEG -DUSE_GD_WBMP -DUSE_GD_FT -DGD_HAS_FTEX_XSHOW -DGD_HAS_GDIMAGEGIFPTR -DGD_HAS_GETBITMAPFONTS       -DUSE_ICONV       -DUSE_ZLIB -I/usr/include                   maplexer.c -o maplexer.o
gcc: maplexer.c: No such file or directory
gcc: no input files
make: **\* [maplexer.o] Error 1

maplexer.c doesn't exist, either in my tarball or in the branch repository for 4.10.7. Bug? Is there a workaround?

**Comment by Maritimo** [comment]
I have the same problem. The answers are useless.

**Comment by jratike80** [comment]
Answers may have been useful back then soon 9 years ago.

Are you really running RHEL v 5.6 and attempting to compile version 4.10.7?
