### ISSUE TITLE
Labelling Enhancement - Draw labels that start outside requested extents

### ISSUE THREAD

**Issue by DonaldKerr** [mapserver/mapserver#4284]
The is a request to create an enhancement to the labelling process whereby labels that have their origin outside the requested extents draw that part of the label that should appear within the extents.

The problem is obvious when tiling map images using the likes of OpenLayers and a WMS request. Labels that cross tile boundaries are clipped. The following link shows an example of the problem (I have rendered some tiles in grey scale to make the boundaries more obvious):

[Clipped Labels Example (png)](https://github.com/DonaldKerr/dump/blob/master/02.png)

The following example shows how the labels should appear when a larger tile is requested:

[Unclipped Labels Example (png)](https://github.com/DonaldKerr/dump/blob/master/01.png)

I know there are various methods for alleviating the problem both in Mapserver and OpenLayers but none of the solutions sort the problem absolutely.

The solution, I think, would be to add an option in LAYER/CLASS/LABEL that can be set so that labels with an anchor position outside any requested extents, that would normally render part of the resultant label within those extents, can be drawn as part of the resultant image.

EDGEBUFFER [double] - default of 1.

So, for example, if the requested image has a width and height of 256 px, the following would be the case:

EDGEBUFFER 1 - 1 x image width/height (256) - Only labels with a starting position inside the 256 x 256 px image are drawn.

EDGEBUFFER 1.5 - 1.5 x image width/height (384) - The part of any label, with a starting position inside the 384 px square, that encroaches on the 256 px square is drawn.

EDGEBUFFER 2 - 2 x image width/height (512) - The part of any label, with a starting position inside the 512 px square, that encroaches on the 256 px square is drawn.

... and so on.

**Comment by chbhhz** [comment]
symbol was cutted on 7.0.7 version also.
If  use  "PARTIALS false",some levle the symbol display
