### ISSUE TITLE
TinyOWS Invalid JSON

### ISSUE THREAD

**Issue by zygous** [mapserver/mapserver#4323]
TinyOWS responds to a Get Feature request with a JSON array of features that ends with ",]", i.e. the last 3 characters of the response are ",]}". This is valid JavaScript, but not valid JSON and therefore the native JSON.parse() method in Firefox 10, which is called by OpenLayers, fails to parse the JSON.

Example (with lots of coordinates removed):
```json
{"type": "FeatureCollection", "crs":{"type":"name","properties":{"name":"EPSG:3857"}}, "features": [{"type":"Feature", "properties":{"ogc_fid": "2", "key": "AL                       "}, "geometry":{"type":"Polygon","bbox":[-55411,6745360,-14308,6774775],"coordinates":[[[-29123,6747479],[-30041,6747137]]]}},]}
```

**Comment by jratike80** [comment]
GeoJSON from my TinyOWS server http://hip.latuviitta.org/cgi-bin/tinyows?service=wfs&version=1.0.0&maxfeatures=1&request=getfeature&typename=lv:pks_juna_asemat&outputformat=application/json

comes out as:
{"type": "FeatureCollection", "crs":{"type":"name","properties":{"name":"EPSG:3067"}}, "features": [{"type":"Feature", "id": "pks_juna_asemat.1", "properties":{"ogc_fid": "1", "fid": "l_jasema.0", "asemapaikka": "Mankki", "mtryhm": "81"}, "geometry":{"type":"Polygon","bbox":[366018.35,6674464.56,366176.96,6674523.92],"coordinates":[[[366019.8,6674464.56],[366018.35,6674519.79],[366175.5,6674523.92],[366176.96,6674468.69],[366019.8,6674464.56]]]}}
]}

and response validates in http://jsonlint.com/.  Issue seems to be fixed.
