### ISSUE TITLE
MapScript-PHP does not load params encoded in XML passed through "request body"

### ISSUE THREAD

**Issue by iacovlev-pavel** [mapserver/mapserver#4330]
MapScript-PHP does not load params encoded in XML passed through "request body". At the moment this is a standard way for OpenLayers to request data via WFS protocol.

In php I can read the request body thought: 
```php
<?php
$request_body = file_get_contents('php://input'); 
```
But I don't know how to pass this data to OwsrequestObj, there are just set/get method for single params available in API.
Also from the documentation only the following inputs are supported by load params
loadParams(): REQUEST_METHOD, QUERY_STRING and HTTP_COOKIE.

**Comment by jratike80** [comment]
Proofed to work with MS 6.2.0 and 6.3-dev.
