### ISSUE TITLE
GetStyles SLD does not include LAYER's Opacity value

### ISSUE THREAD

**Issue by myGitHubUName** [mapserver/mapserver#4340]
In creating the GetStyles response, the code should look at the LAYER's OPACITY as well as the CLASS STYLE's OPACITY to determine whether the fill-opacity CssParameter should be added to the Rule. To be consistent with the getMap and getLegendGraphic requests, the LAYER's OPACITY should override the CLASS STYLE's definition (should they both exist). 

On our 6.0.1 version of Mapserver, we have introduced the code below in mapogcsld.c's msSLDGeneratePolygonSLD  (in the section where it's dealing with the fill-opacity). I don't know if it's good enough or if there are farther-reaching ramifications to introducing this change than we are aware of. I simply provide it here as a starting point to illustrate what I'm talking about.

```
    if(psLayer->opacity != 100 && psLayer->opacity != -1) {
        snprintf(szTmp, sizeof(szTmp),
              "<%s name=\"fill-opacity\">%.2f</%s>\n",
              sCssParam, (float)psLayer->opacity/100, sCssParam);
        pszSLD = msStringConcatenate(pszSLD, szTmp);
     }
     else if(psStyle->color.alpha != 255 && psStyle->color.alpha!=-1) {
        snprintf(szTmp, sizeof(szTmp),
              "<%s name=\"fill-opacity\">%.2f</%s>\n",
              sCssParam, (float)psStyle->color.alpha/255, sCssParam);
        pszSLD = msStringConcatenate(pszSLD, szTmp);
     } 
```

Similarly, stroke-opacity should be addressed; for both the PolygonSymbolizer (outlines) and LineSymbolizer (related issues of which are discussed in: https://github.com/mapserver/mapserver/issues/4132)

**Comment by jratike80** [comment]
Seems to be true also in Mapserver 7.0, Opacity setting is not written into SLD.

**Comment by jratike80** [comment]
Opacity mentioned in https://mapserver.github.io/development/rfc/ms-rfc-124.html.
