### ISSUE TITLE
Hanging Mapserv Processes for WMS Layer maxout CPU

### ISSUE THREAD

**Issue by thebigspoon** [mapserver/mapserver#4343]
This issue was first reported at http://lists.osgeo.org/pipermail/mapserver-users/2012-June/072446.html 

Since then I've been able to reproduce the issue on four different Debian servers.

# General Description

The combination of the following three  elements ( I'm still suspicious how much ANGLE plays a role in this) seems to max out CPU:

1. SYMBOL of type 'hatch'

2. SYMBOL > ANGLE of any degree

3. A single multipolygon record with a geometry on either side of the international dateline (IDL) 

# Build Description

Debian 6.0.4 or 6.0.5 or 6.03

MapServer version 6.0.2 OUTPUT=GIF OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=ICONV SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=FASTCGI SUPPORTS=GEOS INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE

                                                postgresql version                                                
-------------------------------------------------------------------------------------------------------
 PostgreSQL 9.1.3 on x86_64-unknown-linux-gnu, compiled by gcc-4.4.real (Debian 4.4.5-8) 4.4.5, 64-bit
(1 row)

                                                            postgis_full_version                                                            
--------------------------------------------------------------------------------------------------------------------------------------------
 POSTGIS="2.0.0 r9605" GEOS="3.3.3-CAPI-1.7.4" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.9.0, released 2011/12/29" LIBXML="2.7.8" RASTER
(1 row)

# Mapfile

```bash
MAP
  NAME upload_1170
  UNITS METERS
  EXTENT -20042508.3427892 2139661.75 20042508.3427892 13006341.025845
  IMAGETYPE PNG

  OUTPUTFORMAT
    NAME PNG
    DRIVER 'GD/PNG'
    MIMETYPE 'image/png'
    IMAGEMODE RGBA
    EXTENSION "png"
    TRANSPARENT ON
  END

  PROJECTION
    "init=epsg:900913"
  END

  WEB
    IMAGEPATH "/tmp/"
    IMAGEURL "/tmp/"
    METADATA
      "wms_feature_info_mime_type" "text/html"
      "ows_feature_info_mime_type" "text/html"
      "wms_enable_request" "*"
      "ows_enable_request" "*"
      "wms_include_items" "text/html"
      WMS_TITLE "upload_1170"
      WMS_ABSTRACT "upload_1170"
      WMS_ACCESSCONSTRAINTS "none"
      WMS_ONLINERESOURCE "https://<url-here>"
      WMS_SRS "epsg:900913"
      OWS_ENABLE_REQUEST "*"
    END
  END

  FONTSET "/home/fonts/fontset.txt"

SYMBOL
    NAME 'hatched'
    TYPE HATCH
END

LAYER
  NAME "dissolved_idl"
  CONNECTIONTYPE POSTGIS
  PROCESSING "CLOSE_CONNECTION=DEFER"
  CONNECTION "user=<> password=<> dbname=<> host=localhost port=5432 application_name='<>'"
  DATA "web_geometry from shapefile_12707 using unique gid using srid=900913"
  PROJECTION
    "init=epsg:900913"
  END

  TYPE polygon
  STATUS ON
  DUMP TRUE
  TOLERANCE 10
  CLASSITEM "spcode"
  OPACITY 100
  CLASS 
    NAME "CRAB_KG"
    EXPRESSION "CRAB_KG"
    STYLE 
      SYMBOL "hatched"
      COLOR 0 0 255 
      SIZE 5
      ANGLE 45
    END   
    STYLE 
      OUTLINECOLOR 0 0 0 
    END   
  END
  METADATA
    WMS_TITLE "dissolvedIDL"
    WMS_ABSTRACT "dissolvedIDL"
    WMS_SRS "epsg:900913"
    GML_INCLUDE_ITEMS "all" 
    GML_EXCLUDE_ITEMS "the_geom"
  END
END
END # MAP 
```

# Data

The data can be found here:
https://gist.github.com/2920609

**Comment by jratike80** [comment]
GD renderer removed http://mapserver.org/development/rfc/ms-rfc-99.html
