### ISSUE TITLE
map.RESOLUTION in WMS requests does not produce always the right style

### ISSUE THREAD

**Issue by astroidex** [MapServer/MapServer#4401]
Tested wit MapServer 6.0.2 and MapServer 6.2 beta1

We tested with MAP.RESOLUTION=288&MAP.DEFRESOLUTION=72, SIZEUNINTS Meters, the scaled layers with SYMBOLSCALEDENOM 10000

This is what we found out:

POINTS
    \* scaled or not scaled Points/Symbols: displayed correct, scaled and
notscaled are the same in the map

LINES
    \* scaled lines: displayed correct
    \* unscaled lines: too small (1:2000, 1:5000, 1:1000), correct (1:20000)

POLYGON
    \* scaled Polygone/Outline: displayed correct
    \* not scaled Polygone/Outline: too small (1:2000), correct (1:5000,
1:10000,1:20000)
    \* scaled or not scaled Polygone with symbols: displayed correct

LABEL
    \* scaled Label: too small
    \* not scaled Label: too big (1:1000, 1:2000, 1:5000, too small (1:20000)

The behaviour of MapServer 6.0 and MapServer 6.2 is just the same. This time
we have a demo project where we tried the different cases. You can download
it at:

MapServer files:
https://svn.wheregroup.com/download/mapserver_resolution.zip

PDF with results:
https://svn.wheregroup.com/download/mapserver_resolution_pdf.zip

Example MapRequest:
http://localhost/cgi-bin/mapserv62b1?map=/data/umn/resolution/map/resolution_test.map&MAP.RESOLUTION=288&MAP.DEFRESOLUTION=72"&VERSION=1.1.1&REQUEST=GetMap&SERVICE=WMS&LAYERS=notscaledPoint,scaledPoint,notscaledLine,scaledLine,notscaledPolygon,scaledPolygon,Polygon_with_symbols,notscaledLabel,scaledLabel&STYLES=,,,,,,,,&SRS=EPSG:31466&BBOX=2517600,5672315,2518960,5673675&WIDTH=2000&HEIGHT=2000&FORMAT=image/png&BGCOLOR=0xffffff&TRANSPARENT=TRUE&EXCEPTIONS=application/vnd.ogc.se_xml

Have a look at the thread in the Mailinglist:
http://lists.osgeo.org/pipermail/mapserver-users/2011-December/071077.html (12/2011)
http://lists.osgeo.org/pipermail/mapserver-users/2012-July/072804.html (07/2012)

**Comment by taviroquai** [comment]
Hi,

I was looking for documentation regarding MAP_RESOLUTION parameter, but only found this issue.

I found by using OpenLayers 3 that the parameter is MAP_RESOLUTION (with underscore), but you reference MAP.RESOLUTION (with dot).

I though I needed to share this here.

**Comment by romeroabelleira** [comment]
> using `SIZEUNITS meters` along with `SYMBOLSCALEDENOM` results in undefined behavior, they cannot both be specified at the same time. Closing as invalid for now, I'll reopen if you comment on this issue with updated results showing an incorrect behavior.

@tbonfort does this still hold true? I haven't found any mention of this in the docs.
