### ISSUE TITLE
Problem resolving CURL_CA_BUNDLE environment variable on windows 64 bit

### ISSUE THREAD

**Issue by prburbano** [MapServer/MapServer#4436]
Hi,

We did a build of mapServer 6.2 64 bit for windows and while testing cascading wms for secure https endpoints, the code in maphttp.c that reads the value of CURL_CA_BUNDLE does not work.  It returns null all the time.  

To get it to work, I had to use the following function from the windows API in msHTTPExecuteRequests:

```
            wchar_t *longTempPath= _wgetenv(L"CURL_CA_BUNDLE");
            // Convert wchar_t* to a char*
    size_t origsize = wcslen(longTempPath) + 1;
    const size_t newsize = 100;
    size_t convertedChars = 0;
    char nstring[100];
    wcstombs_s(&convertedChars, nstring, origsize, longTempPath, _TRUNCATE);
    pszCurlCABundle = nstring;
```

For now we are using this custom code inside maphttp.c for our purposes, but it would be great if it is included officially.

Thanks,

Patricio

**Comment by geographika** [comment]
Just to add I have also run into the same issue where my certificate store is not picked up by MapServer on a Windows machine. I'm using the binaries from gisinternals.com

Further details at http://lists.osgeo.org/pipermail/mapserver-users/2015-February/077410.html

Came up last year too: http://lists.osgeo.org/pipermail/mapserver-users/2014-February/075983.html

Possible related: http://blog.gisinternals.com/2010/12/daily-built-binary-packages-for.html

> Note: CURL_CA_BUNDLE can be set up system wide (in My Computer->Properties), however you may prefer to apply this environment setting only for the process hosting the mapserver libraries so as not to cause side effects for other applications using libcurl and openSSL. The main issue here is that most of the libararies use getenv to retrieve the environment setting, which operates only on the data structures accessible to the run-time library (msvcrt) and not on the environment "segment" created for the process by the operating system. In this regard the libraries work only on a snapshot of the variables that have been set during the process startup. In this regard you may choose to set up the environment before the process has been started (by using a startup script) or use _putenv to set up the environment variable at run time. I will be trying to discuss this topic in more detail in a subsequent post.

Also StackOverflow post at: http://stackoverflow.com/questions/28432965/getenv-returns-null-in-iis-using-fastcgi

**Comment by jmckenna** [comment]
I can reproduce this also through Apache on Windows, using MS4W, but only on some 64bit systems.  It probably applies to any getenv() call in the MapServer and MapCache source.

**Comment by geographika** [comment]
Fixed with the introduction of the `CONFIG` file and #6305
