### ISSUE TITLE
Expression bug using a inline layer

### ISSUE THREAD

**Issue by aboudreault** [mapserver/mapserver#4453]
The following expression doesn't work using a layer with inline features:
```
EXPRESSION (600 > 500)
```

However, it works if I use a shapefile rather than inline features. Also, the following expression *works* properly:
```
EXPRESSION ([length] > 500)
```

**Comment by jratike80** [comment]
I used the LAYER with Mapserver 7.0 and edited  it to contain "EXPRESSION (600 > 500)". WMS client shows some blue linestrings. Closing.
