### ISSUE TITLE
mapserv.exe doesn't flush file buffers during process termination

### ISSUE THREAD

**Issue by szekerest** [MapServer/MapServer#4505]
We have experienced strange behaviour of the WMS GetCapabilities response of MapServer CGI on Windows 2008 and Windows 7 which is truncated. The same thing happens when invoking mapserv from the command line and the output is redirected to a file.

After a bit of investigation, I came to the conclusion that the process termination doesn't necessarily flush the file buffers (incl. stdout and stderr) on Win 2008 and Win 7. This is primarily an OS behaviour which works correctly on Win2003/XP, but it should probably be fixed in MapServer by calling fflush(NULL) at the right place.

**Comment by raymondnijssen** [comment]
Today I ran into this on a Linux Server. My GetCapabilities response is truncated at 4096 bytes. GetMap works fine though.

**Comment by kannes** [comment]
Hello 10 years younger Raymond 👋 
Did you manage to solve this?

We have the same issue right now on:

- mapserver 8.2.2
- Apache 2.4.62
- Red Hat 9.6

**Comment by kannes** [comment]
Looking at the code I wonder if it would be fine to just flush at that point regardless of the platform?

**Comment by raymondnijssen** [comment]
> Hello 10 years younger Raymond 👋
> Did you manage to solve this?

Still working on this every day! 😉
