### ISSUE TITLE
mapserver 6.0.3 build problem

### ISSUE THREAD

**Issue by stereotyyp** [mapserver/mapserver#4509]
Ubuntu: 12.04
64 bit

./configure --with-proj=/usr --with-gdal=/usr/local/bin/gdal-config --with-ogr=/usr/local/bin/gdal-config --with-wmsclient --with-gd=/usr/local/ --with-freetype=/usr/ --with-jpeg --with-libiconv=/usr --with-png=/usr/local

Im trying to build mapserver, but im getting following error:

g++ -O2 -fPIC -Wall  -DNDEBUG    -DHAVE_VSNPRINTF -DNEED_STRLCPY -DNEED_STRLCAT -DNEED_STRRSTR           -DUSE_WMS_LYR    -DUSE_CURL -DUSE_CURLOPT_PROXYAUTH    -DUSE_WMS_SVR    -DUSE_GDAL -DUSE_OGR   -DUSE_PROJ -DUSE_AGG_SVG_SYMBOLS    -DUSE_GD_GIF -DUSE_GD_PNG -DUSE_GD_JPEG -DUSE_GD_WBMP -DUSE_GD_FT -DGD_HAS_FTEX_XSHOW -DGD_HAS_GDIMAGEGIFPTR -DGD_HAS_GETBITMAPFONTS -DGD_HAS_GET_TRUE_COLOR_PIXEL -DUSE_ICONV -DUSE_GIF -DUSE_PNG -DUSE_ZLIB -DUSE_FREETYPE   -DDISABLE_CVSID -I/usr/include/freetype2  -I/usr/local/include   -I/usr/local//include -Irenderers/agg/include    -I/usr/include   -I/usr/local/include      -I/usr/include      shp2img.o  -L. -lmapserver -L/usr/lib/x86_64-linux-gnu -lfreetype -lz -L/usr/local//lib -lgd -ljpeg -L/usr/lib/x86_64-linux-gnu -lfreetype -lz -L/usr/local/lib -lpng -lz -lXpm -lX11  -lexpat   -L/usr/lib -lproj -ljpeg -L/usr/local/lib -lpng -lgif  -L/usr/local/lib -lgdal   -L/usr/lib/x86_64-linux-gnu -lcurl -Wl,-Bsymbolic-functions -Wl,-z,relro    -L/usr/lib -lc    -lz   -lm -lstdc++    -o shp2img
/usr/bin/ld: ./libmapserver.a(mapimageio.o): undefined reference to symbol 'png_set_longjmp_fn@@PNG15_0'
/usr/bin/ld: note: 'png_set_longjmp_fn@@PNG15_0' is defined in DSO /usr/local/lib/libpng15.so.15 so try adding it to the linker command line
/usr/local/lib/libpng15.so.15: could not read symbols: Invalid operation
collect2: ld returned 1 exit status
make: *** [shp2img] Error 1

**Comment by jratike80** [comment]
Too old version 6.0.3, won't fix.
