### ISSUE TITLE
WFS gml:polygon geometry or polygon bounding box not  passed to Oracle SQL query

### ISSUE THREAD

**Issue by Lunieme** [MapServer/MapServer#4513]
I noticed that when using wfs gml:Polygon filter requests, polygon geometry is not  passed to Oracle SQL query. Mapserver simply send default layer extent to Oracle. Which significantly increases the response time of Oracle on big layers.

Mapserver should send the polygon geometry (or perhaps the bounding box of the polygon geometry) in the SQL query.

The following request :
http://myserve/mapserv?map=/mymap.map&version=1.1.0&service=WFS&REQUEST=GetFeature&TYPENAME=ms:mylayer&Filter= <Filter><Intersects><PropertyName>Geometry</PropertyName>gml:Polygongml:outerBoundaryIsgml:LinearRinggml:coordinates772507,70056 889500,70056 889500,66553 772507,66553 772507,70056/gml:coordinates/gml:LinearRing/gml:outerBoundaryIs/gml:Polygon</Intersects></Filter>

Generates the following Oracle query:
SELECT UNIQUE_ID, rownum, GEOM FROM ( SELECT GEOM, UNIQUE_ID FROM MYLAYER ) WHERE SDO_FILTER( GEOM, MDSYS.SDO_GEOMETRY(2003, :srid, NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3),:ordinates ),'querytype=window') = 'TRUE'

where ordinates = default extent of the layer

I would be great if Mapserver could send the polygon geometry or the bounding box of the polygon geometry in the SQL query.

**Comment by jratike80** [comment]
We have been waiting for 11 years, I am becoming suspicious.
