### ISSUE TITLE
Preventing DOS situation with WMS-T service specifying effective huge TIME range

### ISSUE THREAD

**Issue by akrherz** [MapServer/MapServer#4524]
I'm running the WMS-T service shown as the example in the MS documentation here :)

http://mapserver.org/ogc/wms_time.html#wms-time

The problem is that when a user specifies a CGI variable of 'TIME=2011', the database query ends up returning every raster for the year 2011 (a raster every 5 minutes).  This causes mapserver to do a lot of work and eventually DOSs the server...

The documentation notes that setting the metadata wms_timeformat should help limit the potential timestamp queries coming to the server, but this feature may not be implemented for PostGIS backed WMS-T queries?

```
Note that this functionality is only available on layers based on Shapefiles
and OGR.
```

tbonfort kindly helped me with this on IRC and asked if I might have a suggestion on how to deal with this.  I am not sure if the issue here is if the postgis backend is not supporting the wms_timeformat setting and implementing that would resolve this or if some syntax to the SQL query is needed to limit the number of rows that could be potentially returned.  In my mind, the wms_timeformat would be best and I would want to make sure a request has at least the minutes specified in the TIME CGI variable.

thanks

**Comment by akrherz** [comment]
Any updates on this issue?  I am testing out current master and see the DOS condition is still there :(

**Comment by tbonfort** [comment]
I still believe there is nothing much we can do on the mapserver side, as from what I understand its behavior in this case is correct. The logic of ordering and limiting the number of features from the tileindex is very specific to each scenario, and can't really be hardcoded into mapserver. I suggest you either use MAXFEATURES on your tileindex layer, or use a LIMIT+ORDER BY clause in your sql query.

**Comment by akrherz** [comment]
@tbonfort Thank you for your response.  For your suggestions, I could not make MAXFEATURES work and I found no method to inject a LIMIT clause into the DATA setting without breaking the layer entirely.  Could you kindly suggest a DATA setting that you had in mind?

Perhaps a PROCESSING or METADATA option could be added to disable this functionality entirely?  With 6.4.1, I simply made this change

```
--- mappostgis.c-orig	2015-06-17 07:59:44.793284497 -0500
+++ mappostgis.c	2015-06-15 14:28:40.717011966 -0500
@@ -3258,7 +3258,8 @@
         strlcat(buffer, bufferTmp, buffer_size);
       } else if(numranges == 2) {
         /* we have a range */
-        createPostgresTimeCompareRange(timefield, aranges[0], aranges[1], bufferTmp, buffer_size);
+        createPostgresTimeCompareSimple(timefield, atimes[i], bufferTmp, buffer_size);
+        //createPostgresTimeCompareRange(timefield, aranges[0], aranges[1], bufferTmp, buffer_size);
         strlcat(buffer, bufferTmp, buffer_size);
       } else {
         return MS_FALSE;
```

I see the code has changed for 7.0.0, so will try to manually hack it out of the code again.
