### ISSUE TITLE
mapscript-perl 6.2.0 does not link to libmapserver

### ISSUE THREAD

**Issue by heikoklein** [mapserver/mapserver#4528]
mapscript-perl in release 6.2.0 does not link to libmapserver and thus does not work at all.

In Makefile.PL.in the libraries link to -lmapserver, which is not installed in /usr/lib at that stage, and perl therefore removes that libraries.

Adding the build-directories library like

$libs = "-L$libdir -L$home/.libs -lmapserver";

links to libmapserver, both in /usr/lib and mapserver-6.2.0/.libs.

Heiko

**Comment by unicolet** [comment]
closing old issues
