### ISSUE TITLE
PHP/Mapscript 6.2.0 : no way to unset a property of a layer other than TEMPLATE

### ISSUE THREAD

**Issue by avsilva** [MapServer/MapServer#4531]
Following #4443, it is no more possible to unset the property of a layer using php mapscript.

Fix 4443 only allows setting NULL template.

example:
$layer->set('labelitem', null);

returns:
LABELITEM ""

which causes is requesting the server for a column with empty name:
msPostGISLayerWhichShapes(): Query error. Error executing query: ERROR:  zero-length delimited identifier

**Comment by jbelien** [comment]
Hi,

Has the thinking on this subject progressed ?
I think this is an important capability missing in MapScript.

Thanks a lot.

**Comment by dmorissette** [comment]
Nope. No progress that I am aware of, and unfortunately with aboudreault now gone, we do not have anyone to tackle this. @sdlime: I wonder what other MapScripts do for this (Python, etc.) i.e. unsetting is not enough, you need to know what the default value was to set the value to the default after the unset.

**Comment by sdlime** [comment]
I need to research the SWIG side of things. So much of the get/set code is handled by default as part of SWIG. That said, string (char *) properties of objects are by default NULL in the vast majority of cases. I checked layerObj and that's the case for all strings (template, classitem, ...) with the exception of tileitem which defaults to "location".  Couldn't we in the PHP set method detect the case where we're modifying 1) any string property with 2) a NULL value and do:

    msFree(php_layer->layer->template);
    php_layer->layer->template = NULL;

in a general sense? Then treat the outliers like tileitem specially (if we even care).

Steve

**Comment by jratike80** [comment]
This deals with PHP/Mapscript 6.2.0. At least some refreshing would be needed but I would prefer to create a new issue for 8.x if that is reasonable.
