### ISSUE TITLE
gml_[item name]_type documentation should include xsd:double 

### ISSUE THREAD

**Issue by jeabraham** [MapServer/MapServer#4549]
I found that if I specify the gml_[item name]_type as "Real" various WFS clients cannot load data properly from my Mapserver WFS server URL.  QGIS treats the data as a categorical variable in the symbology selections, while the interoperability extensions of Arc Catalog 10.1 will produce an error and refuse to load the data at all.

The correct type to use is apparently "xsd:double".  With gml_[item name]_type specified as "xsd:double" the WFS layer loads correctly in both QGIS and Arc Catalog.

The documentation says "Valid values are Integer|Real|Character|Date|Boolean."  I believe that "Real" should be changed to "xsd:double" and I wonder if there are better options for "Integer", "Character", "Date" and "Boolean" that conform better to the GML published standard or GML standard practice.

**Comment by jratike80** [comment]
Still "Valid values are the OGR data types: Integer|Real|Character|Date|Boolean." in http://mapserver.org/ogc/wfs_server.html.

**Comment by jeabraham** [comment]
The new(er) versions of QGIS now work with gml_[item name]_type specified as "Real" in the WFS service, and QGIS _no longer_ works with gml_[item name]_type specified as "xsd:double".  Note that this is the opposite of QGIS's past behavior.  I haven't had a chance to check recently with Arc Catalog.

**Comment by sdlime** [comment]
So you're saying we waited long enough that documentation is now correct?

**Comment by havatv** [comment]
@sdlime, the type names specified with `gml_[item name]_type` are translated ("Real" in the Map file results in "Double" in the WFS describefeaturetype document), so this issue should be closed.
If the translations are wrong or some data types are missing, then a new issue should be created.
