### ISSUE TITLE
Labeling - Compressed Label Overwrite

### ISSUE THREAD

**Issue by DonaldKerr** [mapserver/mapserver#4581]
For some time, and with various Mapserver versions (currently, I'm using MS4W 6.2-beta4 ), I am getting a strange compressed label overwrite as demonstrated in the following video file (5Mb): http://www.dkerr.co.uk/LabelIssue.wmv

Apologies for the file size but a video seems like the best way to demonstrate the issue.

It appears to be completely random in that the label will be written correctly most times but will then, for no apparent reason, will appear to compress and overwrite.

Here is the layer definition:

```
LAYER
	NAME "Test"
	TYPE POINT

	STATUS OFF

	METADATA
		"wms_title" "Test"
		"wfs_title" "Test"
		"wfs_extent" "0 0 670000 1230000"
		"wms_extent" "0 0 670000 1230000"
		"gml_exclude_items" "all" # No spaces
		"gml_featureid" "MyID"
	END # METADATA

	HEADER "header.html"
	TEMPLATE "blank.html"
	FOOTER "footer.html"

	PROJECTION # Required for WFS reprojection
		"init=epsg:27700"
	END # PROJECTION

	TOLERANCE 0
	TOLERANCEUNITS pixels # "pixels" broken in Mapserver 6.0.2

	CONNECTIONTYPE OGR
	CONNECTION "ODBC:Risks,Layer_Test" # Requires GEOMETRY_COLUMNS table (SPATIAL_REF_SYS optional) - Fails if DATA included in this map file

	CLASS
		Name "FullOILabelShadow"
		STYLE
			SYMBOL "WarningShadow"
			SIZE 35
			MAXSIZE 35
			MINSIZE 35
			OFFSET 9 0
		END #STYLE
		STYLEbbb
			SYMBOL "WarningRed"
			SIZE 35
			MAXSIZE 35
			MINSIZE 35
		END #STYLE
		TEXT ('[NameStr]')
		LABEL
			PRIORITY 10
			FONT arialbold
			SIZE 11
			TYPE truetype
			ANTIALIAS TRUE
			COLOR  0 0 0
			OUTLINECOLOR 255 255 192
			OUTLINEWIDTH 3
			#SHADOWCOLOR 192 192 192
			#SHADOWSIZE 12 12
			POSITION lr
			FORCE TRUE
			PARTIALS TRUE
			OFFSET -48 3
			WRAP "|"
		END #  LABEL
	END # CLASS

END # LAYER
```

Is there a problem with the LABEL part of the above layer definition or is this a bug?

Some sample images (screenshots):

Correct display of the label:
![Correct](https://f.cloud.github.com/assets/1557299/123318/d58081a2-6eba-11e2-9b65-3b64184e7086.jpg)

Incorrect display of the label:
![Wrong](https://f.cloud.github.com/assets/1557299/123319/d581af6e-6eba-11e2-935c-241225e40e47.jpg)

The above labels are multiline with WRAP using the "|" character. This is also a problem with single line (non-wrapped) labels as shown in the video link above and the examples below.

Correct display of the label:
![CorrectSingle](https://f.cloud.github.com/assets/1557299/123362/952b6052-6ebc-11e2-8927-641ddd46eae7.jpg)

Incorrect display of the label:
![WrongSingle](https://f.cloud.github.com/assets/1557299/123364/95bb7674-6ebc-11e2-8876-a85add931e5b.jpg)

Many thanks.

Regards,

Donald

**Comment by jratike80** [comment]
Entertaining ticket to read. @DonaldKerr , have you tried if current versions of Mapserver, IIS, and Cairo show the same issue?

**Comment by DonaldKerr** [comment]
Thank you. I haven't carried out any recent development as I have changed jobs and no longer support or develop the system in question. I might revisit this in the future as I may look at developing a replacement system on a commercial basis.

**Comment by tbonfort** [comment]
closing now as label handling has been rewritten for mapserver 7.0
