### ISSUE TITLE
Error reporting in PHP mapscript

### ISSUE THREAD

**Issue by jezaustin** [mapserver/mapserver#4584]
Sometimes when mapscript fails to create an object, it does not trigger a descriptive error. Descriptive errors are a hard problem(!), but I think I found a simple typo which is easy to fix.

<pre>diff --git a/mapscript/php/php_mapscript.c b/mapscript/php/php_mapscript.c
index f757d9f..1b36f46 100644
--- a/mapscript/php/php_mapscript.c
+++ b/mapscript/php/php_mapscript.c
@@ -131,8 +131,8 @@ PHP_FUNCTION(ms_newMapObj)
   if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "s|s",
                             &filename, &filename_len,
                             &path, &path_len) == FAILURE) {
-    return;
     PHP_MAPSCRIPT_RESTORE_ERRORS(TRUE);
+    return;
   }
   PHP_MAPSCRIPT_RESTORE_ERRORS(TRUE);
</pre>

**Comment by jratike80** [comment]
Patch is not applied. The place in the code is probably this:
https://github.com/mapserver/mapserver/blob/branch-7-0/mapscript/php/php_mapscript.c#L134

**Comment by jratike80** [comment]
I guess that due to recent heavy work with PHP mapscript the patch is outdated. Reopen if my guess is wrong.
