### ISSUE TITLE
Enable/disable OWS layers by IP list

### ISSUE THREAD

**Issue by szekerest** [MapServer/MapServer#4588]
According to the requirement of Faunalia (​http://www.faunalia.it) we need to
add two new parameters to the WEB section of the mapfile, or in the METADATA section of every single layer:
1. "ows_allowed_ip_list"
2. "ows_denied_ip_list"

Both should point to a file with a list of IP addresses.

The aim is to let the admin to define list of users, identified through their IPs to
allow or deny access to one or more specific WMS or WFS layers.

**Comment by vlasvlasvlas** [comment]
this is not working on my mapserver.. why is that?

./mapserv_wfs -v

MapServer version 6.4.1 OUTPUT=GIF OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=GD SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=ICONV SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=GEOS INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE


on web metadata (top of mapfile) :

"ows_denied_ip_list" "*"

but i still see the requested layer....

![20-04-2015 17-05-25](https://cloud.githubusercontent.com/assets/4071796/7239565/50676188-e781-11e4-8619-2532a26744f6.jpg)
