### ISSUE TITLE
MapServer branch-6-0 doesn't build on recent platforms

### ISSUE THREAD

**Issue by aboudreault** [mapserver/mapserver#4589]
Due to recent gd and geos versions, branch-6-0 doesn't build on recent platform. Here's a patch to allow it to build... however the gd part change breaks the build on old platforms. I'll let the patch here for the moment....

http://dl.mapgears.com/ad-tmp/branch-6-0-build.patch

**Comment by jratike80** [comment]
After branch 6.0 there are branches 6.2, 6.4, and 7.0. I suppose that if 6.0 does not build it won't fix either.
