### ISSUE TITLE
allow metadataurl by layer group

### ISSUE THREAD

**Issue by landryb** [mapserver/mapserver#4598]
As of now if you have a layer group via the GROUP keyword, the getCapabilities document doesnt return a metadataURL object for the layer group, only for the children layers if ows_metadataurl_* is set.

It would be nice to have smth similar to wms_group_abstract for the layergroup, wms_group_metadataurl_{href,format,type} maybe ? If it's set in one of the layers of the group it sets the information for the layergroup, as wms_group_abstract does..

**Comment by landryb** [comment]
Well, still valid as a feature request.. and even if i reported it, i cant reopen it.

**Comment by tbonfort** [comment]
You can create a "fake" layer for this:

```
layer
    #fake layer for WMS capabilities
    name "global"
    type raster
    extent -180 -90 180 90
    metadata
      "wms_enable_request" "GetCapabilities !GetMap"
      "ows_title" "Global World Cover"
    end
  end
  layer
    name "world"
    extent -180 -90 180 90
    group "global"
    metadata
      "wms_enable_request" "GetMap !GetCapabilities"
    end
    ...etc....
```

**Comment by landryb** [comment]
Nice trick, maybe worth documenting somewhere ? Havent seen that in the website doc..
