### ISSUE TITLE
Track RFC98: Text Placement Refactoring

### ISSUE THREAD

**Issue by tbonfort** [MapServer/MapServer#4673]
Track RFC98 implementation
- [x] remove GD support (RFC99)
- [x] remove ANNOTATION layers
- [x] implement a global freetype glyph/font cache
- [x] agg and cairo renderer glyph handling rewrite
- [x] truetype symbol marker placements
- [x] truetype line markers (gap != 0)
- [x] baseline adjustments
- [x] iconv/bidi
- [x] harfbuzz shaping
- [x] labelcache speedups
- [x] leader labels
- [x] text alignment
- [x] bitmap labels
- [x] non labelcache'd layers (kml)
- [ ] #4408 labelpoly scalefactor

**Comment by NathanW2** [comment]
@tbonfort I was just wondering for this item "implement a global freetype glyph/font cache" does that mean that there should be a single global font cache for all threads?  Seems the code only uses it if not using `USE_THREAD`

```
ft_cache* msGetFontCache() {
102
#ifndef USE_THREAD
103
  return &global_ft_cache;
104
#else
```

**Comment by szekerest** [comment]
@NathanW2 I assume this has been implemented to avoid the cost of thread locking in exchange for the cost of duplicating the cache elements (for the same file). It may also be OS dependent that keeping the file open or limit the lifetime of the open handles would be more sufficient. I think on a production server with high load (ie. high number of thread in a process and high number of drawing sessions per second) limiting the lifetime of the open handles would be more scalable.

**Comment by NathanW2** [comment]
The locking be from the cache being read/write vs just read right?

**Comment by szekerest** [comment]
Not sure what you mean, we might either read or write the cache structure in a single operation.
