### ISSUE TITLE
Mapscript Documentation - shapeObj incorrect method name: topologySimplifyPreservingSimplify

### ISSUE THREAD

**Issue by bryguy** [mapserver/mapserver#4721]
I believe this should be "topologyPreservingSimplify".

**Comment by jratike80** [comment]
Where is this mapscript document and why do you believe it is wrong? Pointer to description of the method would help.

**Comment by bryguy** [comment]
I should have reported this in the docs repo (for [the incorrectly documented method name](https://github.com/mapserver/docs/blob/branch-7-0/en/mapscript/php/phpmapscript.txt#L2505) of [this function](https://github.com/mapserver/mapserver/blob/branch-7-0/mapscript/php/shape.c#L1079)). Old me was apparently not paying close enough attention. Sorry for the extra noise.

**Comment by bryguy** [comment]
https://github.com/mapserver/docs/issues/138
