### ISSUE TITLE
allow clients to set maximum features returned on ITEMNQUERY

### ISSUE THREAD

**Issue by markvolzlyoncounty** [MapServer/MapServer#4726]
Currently we can limit the number of features returned in an ITEMNQUERY by setting MAXFEATURES on the map file.  This is very useful for someone to limit the amount of data that they are serving.  Now that there are more mobile clients out there, I think it would be useful to allow clients to further limit the number of features returned.  There may be some cases where someone serving data may be willing to share 1000 features when clients only want to deal with 30 features at a time.

The amount of features returned should always be the lower value of what is set on MAXFEATURES on the server or what the client would like

For example:
MAXFEATURES = 1000, LIMIT = 30, Result= 30 features returned
MAXFEATURES = 100, LIMIT = 300, Result= 100 features returned

**Comment by jratike80** [comment]
Number of features can be set in the http request by using maxfeatures= (WFS 1.x) or count= (WFS 2.0), or  &limit= (OGC API Features). Unfortunately I am not familiar with ITEMNQUERY. At least it is possible to define the DATA in a mapfile with a variable `limit=%limit%`" and use runtime substitution https://mapserver.org/cgi/runsub.html.

I think that runtime substitution is good enough answer for this feature request even it requires some database backend (PostGIS, GeoPackage).
