### ISSUE TITLE
Bad BBOX passed to db query

### ISSUE THREAD

**Issue by waltersjack** [MapServer/MapServer#4755]
We are updating to mapserver 6.2.1 from 5.6.5 and have found that several polygons/polylines/labels in western North America are not being drawn.

We are using:
- epsg 4326
- DB Postgres
- "tile_map_edge_buffer" "256"
- "tile_metatile_level" "2"
- Bing map tile quadrant key example 0231

I have tried:
- changing the tile_map_edge_buffer and tile_metatile_level
- made sure the Proj.4 was up to date and definition was set with '+over' 
  -- http://lists.osgeo.org/pipermail/mapserver-users/2012-June/072538.html
- manipulating labels with labelcache_map_edge_buffer

No luck.  The polygons and polylines will draw if I remove tile_map_edge_buffer and tile_metatile_level, but then the labels are bad.

I set up debugging and the only real difference from the previous version to the new one was the bounding box passed to the db call was different.
- I did note that the msTileSetExtent from both are the same:
  msTileSetExtent (-22537304.912690, -2499796.572690) (-7518957.597310, 12518550.742690)

The resulting bounding boxes:

mapserver 5.6.5:
GeomFromText('POLYGON((-179.52099606876 -21.9022779637684,-179.52099606876 74.0074402855723,179.129882837677 74.0074402855723,179.129882837677 -21.9022779637684,-179.52099606876 -21.9022779637684))',4326)

mapserver 6.2.1:
ST_GeomFromText('POLYGON((157.543945340682 -21.9022779637684,157.543945340682 74.0074402855723,292.456054696902 74.0074402855723,292.456054696902 -21.9022779637684,157.543945340682 -21.9022779637684))',4326) 

Any ideas?  Maybe a bad compile?

Thanks,
Jack Walters
Web Development Engineer III
Zonar Systems

**Comment by jratike80** [comment]
Have you had the same issue with Mapserver 6.4 or 7.0? I suppose that you are using mode=tile.

**Comment by jratike80** [comment]
We have now also 7.0.6. Please test again.

**Comment by jratike80** [comment]
No feedback in 6 years, closing.
