### ISSUE TITLE
RFC103: Layer Level Encoding tracking issue

### ISSUE THREAD

**Issue by tbonfort** [MapServer/MapServer#4758]
This is to track updates related to RFC103: http://mapserver.org/development/rfc/ms-rfc-103.html

**Comment by havatv** [comment]
Someone forgot that this should have been documented.  Has now been discovered and reported in https://github.com/mapserver/docs/issues/146.

**Comment by tbonfort** [comment]
:+1: Someone thanks you for taking care of this @havatv ;)

**Comment by havatv** [comment]
@tbonfort , should label-> encoding be marked as deprecated?  In that case, do you have a suggestion for an explanation of why it is being deprecated?

**Comment by tbonfort** [comment]
@havatv yes it should even be marked as removed in 7.0, although there is some fallback mechanism to understand label->encoding if present. The rationale for moving to LAYER was that the encoding of a dataset affects the whole layer, not only its labels: expression filtering should be done when knowing how the data is encoded, and xml documents (e.g. GetFeature) should be emitted with a converted encoding (the xml doc is utf8, so all of its content must be utf8)

**Comment by jmckenna** [comment]
@tbonfort currently PHP mapscript has the "encoding" attribute at the LABEL level only.  I've checked the 7.0.1 source and it is only available in php/label.c  

Swig seems to handle it at the layer level though (in python\mapscript.py).

**Comment by jmckenna** [comment]
I confirm that this issues exists with branch-7.0 and master, for PHP mapscript.

**Comment by jmckenna** [comment]
Fixed PHPmapscript missing layer encoding property through c7fa5aa
