### ISSUE TITLE
Cannot build with GEOS library

### ISSUE THREAD

**Issue by alasarr** [mapserver/mapserver#4809]
I can't build the latest version (mapserver 6.4.0) with GEOS. I've tried with geos-3.2.2 and geos-3.4.2 but no success.

However, if I disable GEOS I can build successfully. 

Any ideas?

These are the errors:

<pre>
Linking CXX shared library libmapserver.so
[ 92%] Built target mapserver
Scanning dependencies of target legend
[ 92%] Building C object CMakeFiles/legend.dir/legend.c.o
Linking C executable legend
libmapserver.so.6.4.0: undefined reference to `GEOSOverlaps_r'
libmapserver.so.6.4.0: undefined reference to `GEOSTouches_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGetCentroid_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGeom_createCollection_r'
libmapserver.so.6.4.0: undefined reference to `GEOSSimplify_r'
libmapserver.so.6.4.0: undefined reference to `GEOSContains_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGeom_destroy_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGeom_createLinearRing_r'
libmapserver.so.6.4.0: undefined reference to `GEOSCoordSeq_setX_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGetGeometryN_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGeomFromWKT_r'
libmapserver.so.6.4.0: undefined reference to `GEOSCoordSeq_getY_r'
libmapserver.so.6.4.0: undefined reference to `GEOSCrosses_r'
libmapserver.so.6.4.0: undefined reference to `GEOSBuffer_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGeom_createPoint_r'
libmapserver.so.6.4.0: undefined reference to `initGEOS_r'
libmapserver.so.6.4.0: undefined reference to `GEOSWithin_r'
libmapserver.so.6.4.0: undefined reference to `GEOSLength_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGetNumGeometries_r'
libmapserver.so.6.4.0: undefined reference to `GEOSDifference_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGetNumInteriorRings_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGetNumCoordinates_r'
libmapserver.so.6.4.0: undefined reference to `GEOSBoundary_r'
libmapserver.so.6.4.0: undefined reference to `GEOSTopologyPreserveSimplify_r'
libmapserver.so.6.4.0: undefined reference to `finishGEOS_r'
libmapserver.so.6.4.0: undefined reference to `GEOSCoordSeq_create_r'
libmapserver.so.6.4.0: undefined reference to `GEOSDisjoint_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGetInteriorRingN_r'
libmapserver.so.6.4.0: undefined reference to `GEOSisEmpty_r'
libmapserver.so.6.4.0: undefined reference to `GEOSUnion_r'
libmapserver.so.6.4.0: undefined reference to `GEOSisRing_r'
libmapserver.so.6.4.0: undefined reference to `GEOSIntersects_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGetExteriorRing_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGeomToWKT_r'
libmapserver.so.6.4.0: undefined reference to `GEOSCoordSeq_destroy_r'
libmapserver.so.6.4.0: undefined reference to `GEOSFree_r'
libmapserver.so.6.4.0: undefined reference to `GEOSConvexHull_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGeom_createPolygon_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGeom_getCoordSeq_r'
libmapserver.so.6.4.0: undefined reference to `GEOSIntersection_r'
libmapserver.so.6.4.0: undefined reference to `GEOSDistance_r'
libmapserver.so.6.4.0: undefined reference to `GEOSCoordSeq_setY_r'
libmapserver.so.6.4.0: undefined reference to `GEOSEquals_r'
libmapserver.so.6.4.0: undefined reference to `GEOSCoordSeq_getX_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGeomTypeId_r'
libmapserver.so.6.4.0: undefined reference to `GEOSGeom_createLineString_r'
libmapserver.so.6.4.0: undefined reference to `GEOSArea_r'
libmapserver.so.6.4.0: undefined reference to `GEOSSymDifference_r'
collect2: ld returned 1 exit status
make[2]: *** [legend] Error 1
make[1]: *** [CMakeFiles/legend.dir/all] Error 2
make: *** [all] Error 2
</pre>

**Comment by jratike80** [comment]
Reopen if you can indicate where's the bug and what must be fixed. Probably it will be documentation issue then "How to build when GEOS is not in the default folder".
