### ISSUE TITLE
WMS feature request: new 512x512 tilesize when using tilemode=gmap for retina devices

### ISSUE THREAD

**Issue by julich** [mapserver/mapserver#4818]
When using Mapserver's `tilemode=gmap` parameter, the default and only tile size is `256x256`.

We should be able to request for a `512x512` tile size in order to provide retina-screen devices with HD tiles.

Thanks,

Julien.

**Comment by anhln8x** [comment]
Nearly ten years have passed and still no one supports this issue. 256x256 rendering on the phone is lousy.

**Comment by rouault** [comment]
> Nearly ten years have passed and still no one supports this issue.

that has been implemented in master very lately: https://github.com/MapServer/MapServer/pull/6444

**Comment by anhln8x** [comment]
> > Gần chục năm trôi qua vẫn không có ai ủng hộ vấn đề này.
> 
> gần đây đã được triển khai ở chế độ chính: [# 6444](https://github.com/MapServer/MapServer/pull/6444)

Thanks for your useful information.
