### ISSUE TITLE
Clustering enhancements

### ISSUE THREAD

**Issue by szekerest** [MapServer/MapServer#4822]
The following enhancements should be added to mapcluster.c based upon user request:
1. Include the FID for the base cluster point as an attribute (Cluster:BaseFID)
2. Add processing option CLUSTER_KEEP_LOCATIONS to set whether the location of the cluster shape should be preserved (no averaging)
3. Add processing option CLUSTER_USE_MAP_UNITS to provide scale independent clustering (maxdistance and the buffer parameters are specified in map units)

**Comment by jmckenna** [comment]
Documented these processing options through mapserver/docs#149
