### ISSUE TITLE
Dead link to workshop-5.4.zip in documentation

### ISSUE THREAD

**Issue by arneke** [mapserver/mapserver#4851]
http://mapserver.org/introduction.html#introduction-to-the-mapfile

The section "Get Demo Running"  links to

http://maps.dnr.state.mn.us/mapserver_demos/workshop-5.4.zip

but there's nothing there.

**Comment by jratike80** [comment]
Ticket was about dead link and the link is now live so I am closing it. The suggestion to consider housing the file in some other place has been open for 19 months which is long enough for a reaction time.

**Comment by jmckenna** [comment]
I've placed the workshop on the OSGeo download server (http://download.osgeo.org/mapserver/docs/workshop-5.4.zip) and updated the doc.
