### ISSUE TITLE
Enhancement: export zipfle including also more information documents

### ISSUE THREAD

**Issue by aperi2007** [mapserver/mapserver#4884]
Actually mapserver will allow , using the wfs engine, to distribute the
datasets using zipped shapefiles. This is a useful opportunity to distribute our data using the wfs interoperability of mapserver.

We will project to use this feature to allow the download of our datasets, using the shapefile zipped format.

But we have a problem to use this.
Infact we need to add to the zip file some other files, tipically a licence file (pdf) and perhaps some other files like technical information or metadata files.
All of this could be of-course inside a single zip file . So we could think to add to the zipped shapefile a df file
or a zip file (that host more than one file).

To have this result is necessary an enhance to the actual options of mapserver.

I think a good solution could be add a new tag setting in the metadata part of layer section of the mapfile.

A new tag to include in a zip file an external resource (I think to a zip file or to a pdf file).

something like this:

LAYER
  ...
  METADATA
    wfs_include_resource_in_zip_output "/path-to-file/license.pdf"

or this other (for mapserver on windows)

LAYER
  ...
  METADATA
    wfs_include_resource_in_zip_output "c:\path-to-file\license.pdf"

or also retrieve the document from internet 
(this is not useful for us, but I guess it could be useful in an intranet configuration to avoid host all documents in the same server)

LAYER
  ...
  METADATA
    wfs_include_zip "http://www.server.org/path-to-file/license.pdf"

Or with this other option:

LAYER
  ...
  METADATA
    wfs_include_resource_in_zip_output "/path-to-file/*"

In this case the mapserver is request to include in zip file ALL the documents find in the folder.

Obviously this command could not be supported on mapscript to avoid that an user could remotely set the mapserver to retrieve an arbitrary file from the server.
:)

**Comment by jratike80** [comment]
Tested with Mapserver 7.0 and zipped Spatialite output with metadata:
wfs_additional_files_in_output" "c:/ms4w/apps/README_APPS.txt

Word fine.
