### ISSUE TITLE
include setting to disable antialiasing (again)

### ISSUE THREAD

**Issue by ghollinger** [mapserver/mapserver#4893]
When working with thematic data and writing output to an image (GTIFF or PNG) I have experienced problems with antialiasing.

I have attempted to draw polygons (from a database) with attributes ([class] as integer and [colour] as a colour string, set according to [class]). In the resulting output image (at the borders of two polygons) I have encountered pixel values that are not among the class IDs I had defined or seemed misplaced. 

Instead of having the values of say "10" for "water" and "4" for bordering "road" I got "7" which would be "grassland" and therefore a bad value (for this pixel).

After looking into that matter (and some experimenting with borderwidth etc.) I have tracked the problem back to antialiasing.
Since Mapserver 6.X has built in antialising and the ANTIALIAS setting in STYLE has been put out of use.

A switch back to Mapserver 5.X has solved the problem for me.

I would suggest to bring back the "ANTIALIAS FALSE" setting in STYLE or any other method that would allow the user to turn OFF antialiasing for a layer in the Mapfile.

**Comment by jratike80** [comment]
I suppose that turning antialias off is generally not possible with AGG renderer but doable for polygons and lines with width=1 http://osgeo-org.1560.x6.nabble.com/Turn-off-anti-alias-Mapserver-6-0-td4842613.html.

**Comment by jratike80** [comment]
I suppose I were right with my comment two years ago, closing.
