### ISSUE TITLE
Compiling Mapserver 6.4.1 fail on windows

### ISSUE THREAD

**Issue by chenzhuo8804** [MapServer/MapServer#4897]
Hi I am trying to compile Mapserver 6.4.1 on 64 bit Windows8
I downloaded source code from http://mapserver.org/download.html#download
Then modified nmake.opt to point to GD and regx library
Then I tried to use Visual Studio 2008 Win64 Command Prompt to build the project using nmake
It says cant not find mapserver-config.h
Then I found mapserver-config.h.in and changed its extension to .h , did the same thing to mapserver-version.h.in
Then using nmake /f Makefile.vc gave me this error
c:\mapserver\mapserver-6.4.1\mapserver-config.h(4) : fatal error C1021: invalid
preprocessor command 'cmakedefine'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 9.0\
VC\BIN\cl.EXE"' : return code '0x2'
Stop.
Looks like cmakedefine is not a valid preprocessor here
Any suggestions?
Thanks

**Comment by kellyelton** [comment]
One thing I've noticed is that the documentation for compiling on windows doesn't even mention cmake as a requirement.

**Comment by jratike80** [comment]
Isn't this document badly outdated http://www.mapserver.org/installation/win32.html? Jeff, you must know how to compile and also know that it is possible.
