### ISSUE TITLE
Blank WMS images in 6.4.0

### ISSUE THREAD

**Issue by spruceboy** [mapserver/mapserver#4902]
I am having problems with 6.4.0 generating blank images for wms getmap requests that work fine in 6.2.2.   I made a small example with this problem, hopeful this helps.  

Please let me know if if this is not the right place to submit this, and I will move it else were.
Thanks!

Works in 6.2.2:
```
[webdev@dib bug]$ mapserv -v
MapServer version 6.2.2 OUTPUT=GIF OUTPUT=PNG OUTPUT=JPEG SUPPORTS=PROJ SUPPORTS=GD SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=ICONV SUPPORTS=XMP SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=SOS_SERVER INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE

[webdev@dib bug]$ gdal-config --version
1.8.1

mapserv -nh "QUERY_STRING=SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-12823936.267549067735672,-7952222.17429961264133453,12866195.40293501317501068,17272477.83117564022541046&CRS=EPSG:3338&WIDTH=1000&HEIGHT=1000&LAYERS=test&STYLES=&FORMAT=image/png&DPI=72&MAP_RESOLUTION=72&FORMAT_OPTIONS=dpi:72&TRANSPARENT=TRUE&map=./map.map" >mapserver_6.2.2
sed '1d' mapserver_6.2.2 | sed '1d'  > mapserver_6.2.2.png
```
Does not work in 6.4.0:
```
[jcable@spam bug]$ mapserv -v 
MapServer version 6.4.0 OUTPUT=GIF OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=GD SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=ICONV SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=GEOS INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE

[jcable@spam bug]$ gdal-config --version
1.10.1
mapserv -nh "QUERY_STRING=SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-12823936.267549067735672,-7952222.17429961264133453,12866195.40293501317501068,17272477.83117564022541046&CRS=EPSG:3338&WIDTH=1000&HEIGHT=1000&LAYERS=test&STYLES=&FORMAT=image/png&DPI=72&MAP_RESOLUTION=72&FORMAT_OPTIONS=dpi:72&TRANSPARENT=TRUE&map=./map.map" > mapserver_6.4.0

sed '1d' mapserver_6.4.0 | sed '1d' > mapserver_6.4.0.png
```

The map file looks like this:
```
MAP	
	NAME TEST
        STATUS ON
        SIZE 260 260

        IMAGETYPE png
	PROJECTION
		"init=epsg:4326"
	END

	EXTENT -180 -90 180 90
	WEB
                METADATA
                        "wms_title"             "test"
                        "wms_name"              "test"
                        "wms_abstract"          "test"
                        "wms_enable_request"    "*"
                        "wms_srs" "4326 3338"
                END
	END

    LAYER
        name test
        type raster
        status on
        DATA "./test.tif"
	PROJECTION 
		"init=epsg:3338"
	END
    END
END
```

The test data file can be found here:
http://hippy.gina.alaska.edu/distro/mapserver_bug/test.tif

mapserver_6.4.0.png,  mapserver_6.2.2.png are below.

(6.4.0)
![mapserver_6 4 0](https://cloud.githubusercontent.com/assets/243433/2572268/fb4f9976-b910-11e3-8ebf-d08ca8e2a4d4.png)

(6.2.2)
![mapserver_6 2 2](https://cloud.githubusercontent.com/assets/243433/2572270/08c87898-b911-11e3-83d4-5585eefffbbf.png)

**Comment by jratike80** [comment]
Same behaviour with MS 7.0, blank image in browser with the given URL until adding PROCESSING "LOAD_WHOLE_IMAGE=TRUE" into LAYER.

However, this request and even much larger BBOX does show an image even without PROCESSING:

http://localhost:8060/cgi-bin/mapserv.exe?map=c:/ms4w/apps/tiftest.map&REQUEST=GetMap&SERVICE=WMS&VERSION=1.3.0&WIDTH=1373&HEIGHT=730&LAYERS=test&TRANSPARENT=TRUE&FORMAT=image%2Fpng&BBOX=-1.961817608898629E8,-1.1603973412191781E8,1.9020142607342482E8,8.939342427808222E7&CRS=EPSG:3338&STYLES=

Service works well in OpenJUMP and in QGIS and "Zoom to layer extent" is OK as well. Closing because there seems to be more wrong in the client than in Mapserver.
