### ISSUE TITLE
GRID setting in mapfile doesn't work as expected

### ISSUE THREAD

**Issue by szekerest** [MapServer/MapServer#4913]
When I open a map file (with graticule grid) and then draw the map, the grid settings are getting lost because drawlayer closes the layer implicitly and the grid settings are stored in layerinfo (which is the problem primarily).

In order to fix this issue I suggest making the following changes?
1. add graticuleObj to layerObj (mapserver.h)
2. load grid settings to layerObj->graticuleObj instead of layerinfo (mapfile.c)
3. destroy graticuleObj in freeLayer instead of msGraticuleLayerClose
4. Modify the vtable handlers to use layerObj->graticuleObj instead of layerinfo
5. copy the relevant settings of graticuleobj in mapcopy.c
6. Expose graticuleObj in mapscript. (if needed)

**Comment by tbonfort** [comment]
I very much suspect that this commit is causing #5159 for php mapscript
