### ISSUE TITLE
WFS Server featureid parameter doesn't like typename containing a dot.

### ISSUE THREAD

**Issue by gsueur** [mapserver/mapserver#4925]
when playing with this kind of request : 
https://download.data.grandlyon.com/wfs/grandlyon?SERVICE=WFS&REQUEST=GetFeature&typename=fpc_fond_plan_communaut.fpcbaticonstruction&VERSION=2.0.0&featureid=fpc_fond_plan_communaut.fpcbaticonstruction.1

if your typename contains a dot, it doesn't work. You have this message : msWFSGetFeature(): WFS server error. Invalid FeatureId in GetFeature. Expecting layername.value : fpc_fond_plan_communaut.fpcbaticonstruction.1

Best regards

**Comment by jratike80** [comment]
Test with Mapserver 7.0 with Spatialite data source. Success with request:
http://localhost:8060/cgi-bin/mapserv.exe?map=c:/ms4w/apps/wms-wfs.map&service=wfs&version=1.1.0&request=getfeature&typename=states.table&featureid=states.table.2
