### ISSUE TITLE
PHP MapScript ignores PROJ_LIB environment variable

### ISSUE THREAD

**Issue by fredmorin** [mapserver/mapserver#4930]
Loading a MapFile with PHP MapScript ignores Apache SetEnv PROJ_LIB value.

$map = new MapObj($file);
The MapObject has a setconfigoption method, unfortunatly it cannot be called before the constructor. 

A solution would be to add a loadMapFile method to the MapObj which would allow to 

$map = new MapObj();
$projLib = getenv("PROJ_LIB");
$map.setConfigOption("PROJ_LIB", $projLib);
$map.loadMapFile($file);

**Comment by tbonfort** [comment]
applied with #5057 in e17e69b
