### ISSUE TITLE
WFS 2.0 wrong extension response to a spatialite zip request

### ISSUE THREAD

**Issue by aperi2007** [mapserver/mapserver#4933]
Mapserver use wrong extension in a response to a spatialite zipped request.

Starting from this setting:

OUTPUTFORMAT
NAME "SPATIALITE"
DRIVER "OGR/SQLITE"
MIMETYPE "application/zip"
FORMATOPTION "DSCO:SPATIALITE=YES"
FORMATOPTION "STORAGE=memory"
FORMATOPTION "FORM=zip"
FORMATOPTION "FILENAME=result.db.zip"
END

The zip resulted will not contain a file .sqlite but instead a file with zip extension.
But this is not a zip file.It is instead a real spatialite db. The MapServer has named its extension .zip instead of .sqlite

**Comment by jratike80** [comment]
I believe that this one can be closed like the referenced #4856.
