### ISSUE TITLE
Label outline gets scaled with changing map scale

### ISSUE THREAD

**Issue by ejn** [mapserver/mapserver#4942]
According to the [docs for OUTLINEWIDTH in STYLE](http://mapserver.org/de/mapfile/style.html#index-39);

>  The thickness of the outline will not depend on the scale.

The [corresponding docs in LABEL](http://mapserver.org/mapfile/label.html#index-20) don't specify any behaviour in this regard, but the behaviour as specified in STYLE would seem a reasonable expectation.

Currently however, the outline for labels gets scaled up with the map scale - see images below - with seemingly no way to prevent this.

It doesn't appear to be the fault of the font (c.f #4774) since I've tested it with various fonts (including major ones such as Arial).

I've put up the self-contained minimalist test case used for generating the images at https://github.com/faegi/testcases/tree/master/mapserver-outlinewidth - tested using a recent build from master.

~1:500 000: ![test500](https://cloud.githubusercontent.com/assets/1106824/3310339/48cc3a40-f6b2-11e3-8e0a-d757f431ce59.png)
~1:50 000: ![test50](https://cloud.githubusercontent.com/assets/1106824/3310338/4604ad9c-f6b2-11e3-8c18-bd595804dc2b.png)
~1:5 000: ![test5](https://cloud.githubusercontent.com/assets/1106824/3310326/23522090-f6b2-11e3-8c5a-b0dea4b3d918.png)

**Comment by ejn** [comment]
Appears to only occur when SYMBOLSCALEDENOM is set on the layer.

Does anyone have time to check this before the 7.0 release? I had a quick look through but couldn't see where this was going wrong.

**Comment by tbonfort** [comment]
untested patch attached here, can you give it a spin?

```diff
diff --git a/maprendering.c b/maprendering.c
index bf96a3f..f7c5c50 100644
--- a/maprendering.c
+++ b/maprendering.c
@@ -1023,7 +1023,7 @@ int msDrawTextSymbol(mapObj *map, imageObj *image, pointObj labelPnt, textSymbol
     c = &ts->label->color;
   if(MS_VALID_COLOR(ts->label->outlinecolor))
     oc = &ts->label->outlinecolor;
-  ow = ts->label->outlinewidth * ts->scalefactor;
+  ow = ts->label->outlinewidth * (ts->textpath->glyph_size / ts->label->size);
   if(!renderer->renderGlyphs) return MS_FAILURE;
   return renderer->renderGlyphs(image,ts->textpath,c,oc,ow);
```

**Comment by ejn** [comment]
Looks good - the width always stays at 1 pixel now with your patch, just as documented.

**Comment by tbonfort** [comment]
hmm, it should scale along with the label size, as that's the intended behavior. I suspect you're fixing the label size with minsize/maxsize, which is why the outline stays at 1 pixel in your case, correct?

**Comment by ejn** [comment]
Correct: MINSIZE == MAXSIZE == 10

If the intended behaviour is that it scales with the label then the documentation should be corrected!

**Comment by ejn** [comment]
Still with your patch, if I remove MINSIZE and MAXSIZE then the label and the outline width both scale proportionally - I guess this is probably the "expected" behaviour for most use cases (?), even if it is not what the documentation currently states.

**Comment by sdlime** [comment]
Thomas: Could we use the label's min/maxsize relative to the normal size to also derive min/max outline width bounds? I'd think the two should behave exactly the same. That is, stop scaling the outline if the size has hit a min/max threshold.

Steve

**Comment by tbonfort** [comment]
@sdlime that's what the patch intends to do: scale the label outlinewidth by the scaling factor that was effectively applied to the label->size.
