### ISSUE TITLE
Incorrect documentation about expressions

### ISSUE THREAD

**Issue by drnextgis** [mapserver/mapserver#4968]
[Documentation](http://mapserver.org/mapfile/class.html) says that:

```
Logical expressions allow the building of fairly complex tests based on one or more
attributes and therefore are only available with shapefiles.
```

But it is incorrect. Logical expressions also works at least for PostGIS layers.

**Comment by jratike80** [comment]
In one way or another? Feels like innocent users would need improved documentation about the expression support in different drivers.

**Comment by jratike80** [comment]
Documentation is still the same.

**Comment by jmckenna** [comment]
this was fixed by @SunveerSingh as part of the GCI contest!!!  https://github.com/mapserver/docs/pull/205

**Comment by havatv** [comment]
Doc issues are resolved sooner if they are filed where they are more easily found (http://github.com/mapserver/docs -  since 2012).
