### ISSUE TITLE
Layer Filter ignored when using OGC Filters Parameters (SQL Server 2008 Driver)

### ISSUE THREAD

**Issue by geographika** [mapserver/mapserver#4969]
I've set up a MapServer layer with a FILTER. When accessing this layer as a WFS any ogc filters sent by the client (in this case OpenLayers) means that the layer's FILTER is ignored. This can be checked by running the SQL Profiler on the database. This allows a user to access data they are not supposed to.

ogc:BBOX filters however respect the LAYER FILTER - it is only when properties are filtered by the client that it is ignored. 

This is similar to the issue that was resolved for WMS layers: https://github.com/mapserver/mapserver/issues/3795

**Comment by sdlime** [comment]
I'm going to close this with the pending 7.0 release. I'll create a document ticket(s) to address those changes... --Steve
