### ISSUE TITLE
weird black horizontal lines at some zoom levels when using TILEINDEX

### ISSUE THREAD

**Issue by landryb** [mapserver/mapserver#4975]
Using mapserver 6.4.1 / gdal 1.10.1 on debian wheezy, i'm sometimes seeing weird artifacts when serving ortho-imagery using a TILEINDEX layer. The imagery are a large bunch of jp2 files (shipped with 2/4/8/16 overviews), gdal reads them via the ecw driver. See the attached file for an example of such a black artifact. The artifacts only show up at 'high' scales (in that case, 1:40000 for a 25cm px image) I can see the same thing on resamples (6m, 24m) of the whole dataset (using a vrt) done via gdal_translate, at some zoom levels the black lines are displayed, and disappear when zooming in.

The images are all complete, no missing lines on their respective borders.

At this point, i dont know if its a gdal or mapserver issue, but this was working fine (in more or less the same configuration) with mapserver 5.6.5/gdal 1.6.3, and i'd really like to find the source of the issue.

**Comment by landryb** [comment]
Fwiw, i'm still seeing this issue with 6.4 on jp2 images, using (sadly) jp2ecw driver (i still have some ecw in the same server..), and with non-truncated internal overviews... that seems to be totally random. Will try with mapserver 7 but i dont have much hope. 

![montlu-dev2](https://cloud.githubusercontent.com/assets/3421760/22328626/7c5e8322-e3bd-11e6-83a7-3949e15df0b4.jpeg)

Is there a way via PROCESSING directives to pass GDAL_SKIP to the underlying gdal call, but depending on the layer ? I know i'm probably asking for the impossible... ideally, JP2ECW should be used only for .ecw files, and JP2OpenJPEG for .jp2 files..

**Comment by msmitherdc** [comment]
I think you can do this with the CONFIG keyword. You can also do it with an environment variable for your particular web server. 

Michael Smith
Remote Sensing/GIS Center
US Army Corps of Engineers

**Comment by landryb** [comment]
Doing it globally in the webserver env is indeed possible, but it disables JP2ECW for the whole server workers, while i'd have preferred doing this only on the layers where i know i have those empty lines. Anyway, since JP2ECW and ECW are distinct drivers, guess that's not really an issue, and i can disable JP2ECW while keeping ECW...

**Comment by tbonfort** [comment]
@landryb do try latest branch-7-0 with 026847b1c962c

**Comment by landryb** [comment]
> @landryb do try latest branch-7-0 with 026847b

hmmm, even if no reprojection should be involved in my case, from the description of #1715 that looks definitely relevant... will test first with JP2ECW skipped, then with tip from 7.0.

**Comment by landryb** [comment]
Using shp2img and disabling JP2ECW via GDAL_SKIP in the env produces a different image in terms of size and md5, so i *suppose* the JP2OpenJPEG driver is used as a fallback, but alas i still have the artefacts.

Enabling `-all_debug 5` on the cmdline shows an interesting fact: for a query on a certain bbox, i see that postgis returns 56 source tiles, and for each source tile i see in the debug log `msResampleGDALToMap in effect: cellsize ` message, for 40 of them the cellsize is 0.530504, for 8 of them (the left-side ones ?) cellsize is 0.529839, and for 8 of them (rightmost ones?) cellsize is 0.530826. That looks fishy, since on my test-request-bbox showing the bug, the white artefacts appear on the horizontal limit of a source tile, and mostly in the 'left column' of the source tile grid, as can be seen below.

![out_jp2ecw](https://cloud.githubusercontent.com/assets/3421760/22332533/b00d3f4c-e3d1-11e6-8bf8-145cd106c68a.jpeg)

**Comment by landryb** [comment]
After backporting 026847b1c962cdd666d28cfbe38ac40fff54ffbb to my local 6.4 debian build, i can confirm that it fixes my issue, both in shp2img test and with mapserver via WMS. Such a relief.... thanks @rouault and @tbonfort  :)
