### ISSUE TITLE
DATARANGE serialization type invalid [MAPSCRIPT]

### ISSUE THREAD

**Issue by geonux** [mapserver/mapserver#4992]
I have detected a serialization problem with the `DATARANGE` fields when using the Mapscript methods `mapfile.convertToString ()` and `mapfile.save ()` causing information loss. Indeed, the DATARANGE (type double) are serialized as  integer.

This seems to happen in the file `mapfile.c` :
In the `writeStyle` function, the `DATARANGE` is serialized with the `writeDimension` function which use `msIO_fprintf(stream, "%s %d ", name, x);` (note : remark the `%d`).
Another `write*` function must be created to handle a couple of double values.

For ex. (not tested yet):
```
static void writeDataRange(FILE *stream, int indent, const char *name, double x, double y)
{
  writeIndent(stream, ++indent);
  msIO_fprintf(stream, "%s %f.4 %f.4\n", name, x, y);
}
```

**Comment by jratike80** [comment]
Correct me and reopen the ticket if I am wrong, but if the patch is merged and comment says that it corrects issue #4992, isn't this issue fixed then?
