### ISSUE TITLE
Inconsistent WFS Filter results between OGR vs. shapelib

### ISSUE THREAD

**Issue by tbonfort** [mapserver/mapserver#4995]
with 6.4, in msautotest/wxs using 
```
mapserv QUERY_STRING="map=wfs_ogr.map
&SERVICE=WFS
&VERSION=1.0.0
&REQUEST=GetFeature
&TYPENAME=road
&OUTPUTFORMAT=MultiMIDMIF
&FILTER=
<Filter>
 <BBOX>
  <PropertyName>POINT</PropertyName>
  <Box+srsName=%22EPSG:4326%22>
   <coordinates>-65.86,44.56+-65.76,44.68</coordinates>
  </Box>
 </BBOX>
</Filter>"
```

 * using native shapefile access (which is what is used by default in wfs_ogr.map), the query returns 3 features.
 * using OGR access (replacing ```DATA roads``` by ```CONNECTIONTYPE OGR CONNECTION "data/roads.shp"```, the query returns 5 features, which seems to be the correct result given the requested bbox

with master after RFC91 (#4974), the OGR driver returns 0 features, and the native shapefile driver returns 5 features

cc @sdlime

**Comment by sdlime** [comment]
These changes are in master, correct? --Steve

**Comment by sdlime** [comment]
I think this can be safely closed now. --Steve
