### ISSUE TITLE
Mapserver 6.4.1 GetFeature with featureid doesn't work

### ISSUE THREAD

**Issue by kurteknikk** [mapserver/mapserver#5004]
Hi,

I've been looking for this issue for quiet some time now, but I can't find any further info.

My basic request looks something like:
http://mapserver.domain...&TYPENAME=live&REQUEST=GetFeature&featureid=live.15&service=wfs&version=1.0.0

And the response is:
```

<?xml version='1.0' encoding="ISO-8859-1" ?>
<ServiceExceptionReport version="1.2.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wfs/1.0.0/OGC-exception.xsd">
  <ServiceException code="NoApplicableCode" locator="mapserv">
msWFSGetFeature: WFS server error. FLTApplyFilterToLayer() failed
msQueryByFilter(): Search returned no results. No matching record(s) found.
  </ServiceException>
</ServiceExceptionReport>

```

I specifically checked that live.15 exists.
I also read that I should have gml_featureid specified, so I made sure that's also in.
I read multiple posts were in older versions this was broken, but at the end everybody says it should be working as expected now.

I'm really running out of options. Can anybody help me figure out what am I doing wrong ?

```
MAP
	IMAGETYPE			PNG
	SIZE					400 300
	MAXSIZE				2400
	SHAPEPATH			"/var/www/maps/demo/shp/"
	IMAGECOLOR		"#FFFFFF"
	WEB
		METADATA
			"wfs_srs"             "EPSG:3857 EPSG:900913"
			"wfs_enable_request"	"GetMap GetFeature GetCapabilities GetLegendGraphic"
		END
	END
	PROJECTION
		"init=epsg:3857"
	END
	LAYER
		NAME         live
		METADATA
			"wfs_title"         "live"
			"wfs_srs"             "EPSG:3857 EPSG:900913"
			"gml_include_items" "all"
			"gml_featureid"     "id"
			"wfs_enable_request"	"*"
		END
		DATA         demo_2014_live
		STATUS       ON
		TYPE         POLYGON
		PROJECTION
			"init=epsg:4326"
		END
		CLASS
			NAME       "Done"
			EXPRESSION ([boxesMatch] / [boxes] > 0.1)
			STYLE
				COLOR   "#008000"
				SIZE 4.0
				WIDTH 3.0
			END
		END
		CLASS
			NAME       "Todo"
			EXPRESSION (true)
			STYLE
				COLOR   "#C0C0C0"
				SIZE 4.0
				WIDTH 3.0
			END
		END
	END
END
```

**Comment by jratike80** [comment]
It may be that the importance of correct extent is not emphasized but I close still this issue.

http://www.mapserver.org/mapfile/map.html

EXTENT [minx] [miny] [maxx] [maxy]
    The spatial extent of the map to be created. In most cases you will need to specify this, although MapServer can sometimes (expensively) calculate one if it is not specified.
