### ISSUE TITLE
"PARTIALS" flag for label not saved using save() (Python mapscript)

### ISSUE THREAD

**Issue by stodge** [mapserver/mapserver#5015]
I am setting PARTIALS to true using the following python code:

```
l.partials = True
```

When I create the mapfile using:

```
m.save()
```

The PARTIALS entry is missing from the label definition:

```
      LABEL
        FONT "free-vera"
        SIZE 15
        COLOR 0 255 0
        FORCE TRUE
        OFFSET 0 0
        OUTLINECOLOR 0 255 0
        POSITION CC
        SHADOWSIZE 1 1
        TYPE TRUETYPE
      END # LABEL
```

Is my code wrong or is there a bug in mapscript? Thanks

**Comment by jratike80** [comment]
@stodge I suppose you got your minute, closing.
