### ISSUE TITLE
Python mapscript mapObj instance can't be pickled?

### ISSUE THREAD

**Issue by stodge** [mapserver/mapserver#5016]
This might seem like a crazy thing to report, but I need to pickle a Python mapscript mapObj instance to Memcached but Python complains that the instance can't be pickled. I guess I shouldn't be surprised as it's using Swig. Does anyone know of an alternative way to serialize a mapObj instance into a cache? I know that I could save the map file contents but that's a lot of text to cache and it requires a lot of processing to rebuild the map object. Thanks

**Comment by jratike80** [comment]
I don't believe that you will get an answer to your question from the issue tracker. Try mapserver-users mailing list, or gis.stackexchange instead.
