### ISSUE TITLE
Time parsing Issue on time ranges

### ISSUE THREAD

**Issue by geographika** [mapserver/mapserver#5045]
This only occurs with the latest builds based on Master (since 6.4 release), and seem related to https://github.com/mapserver/mapserver/commit/0cc47e3027a75cf18c5310694877999c6b245371

I pass in a TIME parameter through a WMS request, which worked fine in the 6.4 release. However now I get the following:

```
msWMSApplyTime: WMS server error. Time value(s) 2008-01-01/2020-12-31,1900-1-1/1900-1-1 given is invalid or outside the time extent defined (1900-1-1/2030-12-31).
msParseTime(): Regular expression error. Unrecognized date or time format (1900-1-1).
```

My metadata for the layer includes:

```
"ows_timeextent" "1900-1-1/2030-12-31"
```

My WMS request includes the following time range as part of the querystring:

```
TIME=2008-1-1/2020-12-31
```

I am using a Windows server (so line endings in the .map file are Windows style). Changing these to UNIX style line endings did not make a difference.
I presume this relates to the time range syntax, which is a valid WMS TIME parameter. 

A typical URL causing this issue is:

```
http://localhost/mapserver/?LAYERS=MyLayer&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&FORMAT=image/png&TIME=2008-01-01/2020-12-31&SRS=EPSG:3857&BBOX=-1384006.0342831,6577719.3347518,-625444.96571687,6990020.6652482&WIDTH=2481&HEIGHT=1348
```

Sometimes I have multiple ranges e.g.

```
http://localhost/mapserver/?LAYERS=MyLayer&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&FORMAT=image/png&TIME=2008-01-01/2020-12-31,1900-1-1/1900-1-1&SRS=EPSG:3857&BBOX=-1384006.0342831,6577719.3347518,-625444.96571687,6990020.6652482&WIDTH=2481&HEIGHT=1348
```

**Comment by sdlime** [comment]
I ended up reverting the end-of-line anchor change so I'm thinking this is fixed now. There is a regression test that uses multiple ranges and it now passes. --Steve
