### ISSUE TITLE
MapServer WCS GetCapabilites request doesn't return list of all versions supported

### ISSUE THREAD

**Issue by nmtoken** [mapserver/mapserver#5046]
I'm looking at WCS 2.0.1 support in MapServer version 6.4.1.

I've noticed that a GetCapabilities request doesn't return all the versions of WCS supported by the server.

[GetCapabilities with acceptversions=2.0.1 reports only 2.0.1 support](http://194.66.252.155/cgi-bin/BGS_EMODnet_bathymetry/ows?service=WCS&acceptversions=2.0.1&request=GetCapabilities&) 

[GetCapabilities with no versions reports only 2.0.1 support](http://194.66.252.155/cgi-bin/BGS_EMODnet_bathymetry/ows?service=WCS&request=GetCapabilities&)

[GetCapabilities with version=1.1.0 reports only 1.1.0 support](http://194.66.252.155/cgi-bin/BGS_EMODnet_bathymetry/ows?service=WCS&request=GetCapabilities&version=1.1.0&)

This appears to be a bug

**Comment by Schpidi** [comment]
Should be corrected for WCS now. I guess this also applies to WFS and probably other OGC services? @rouault, what do you think about WFS?
