### ISSUE TITLE
WCS 2.0.1 GetCoverage Subsetting request returns tiny image

### ISSUE THREAD

**Issue by nmtoken** [mapserver/mapserver#5047]
WCS 2.0.1 subsetting request in MapServer 6.4.1 returns a tiny image.  I can't work out if this is just a scaling issue or some other error.

[WCS 2.0.1 GetCoverage ~ returns expected image](http://194.66.252.155/cgi-bin/BGS_EMODnet_bathymetry/ows?service=WCS&version=2.0.1&request=GetCoverage&CoverageId=BGS_EMODNET_AegeanLevantineSeas-MCol&format=image/png&)

[WCS 2.0.1 GetCoverage SUBSETing with lat(34.53627,38.88686) long(25.43366,31.32234) returns a tiny image](http://194.66.252.155/cgi-bin/BGS_EMODnet_bathymetry/ows?service=WCS&version=2.0.1&request=GetCoverage&CoverageId=BGS_EMODNET_AegeanLevantineSeas-MCol&format=image/png&subset=lat(34.53627,38.88686)&subset=long(25.43366,31.32234)&)

The same subsetting request on the same coverage (natively a 3-band tiff) using GeoServer returns the expected  image.  

[GeoServer subsetting on the same coverage by comparison](http://194.66.252.155/geoserver/OneGDev/wcs?service=WCS&version=2.0.1&CoverageId=OneGDev__AegeanLevantineSeas-MCol&request=GetCoverage&format=image/png&subset=Lat(34.53627,38.88686)&subset=Long(25.43366,31.32234)&)

**Comment by Schpidi** [comment]
@nmtoken please test and reopen if you find anything wrong. Thanks.

**Comment by nmtoken** [comment]
Testing against the same server (http://194.66.252.155) was MapServer 6.4.1 on initial report but is now MapServer version 7.1-dev.

The subsetting request without the optional CRS part of the subset value, is still not working for me:

http://194.66.252.155/cgi-bin/BGS_EMODnet_bathymetry/ows?service=WCS&version=2.0.1&request=GetCoverage&CoverageId=BGS_EMODNET_AegeanLevantineSeas-MCol&format=image/png&subset=lat(34.53627,38.88686)&subset=long(25.43366,31.32234)&

To get the subset still need to supply the optional bit...

http://194.66.252.155/cgi-bin/BGS_EMODnet_bathymetry/ows?service=WCS&version=2.0.1&request=GetCoverage&CoverageId=BGS_EMODNET_AegeanLevantineSeas-MCol&format=image/png&subset=lat,http://www.opengis.net/def/crs/EPSG/0/4326(34.53627,38.88686)&subset=long,http://www.opengis.net/def/crs/EPSG/0/4326(25.43366,31.32234)&

Do I need to update my version of MapServer?

**Comment by Schpidi** [comment]
@nmtoken sorry, I forgot to merge to master. Please use either latest branch-7-0 or master. Thanks.
