### ISSUE TITLE
BBOX vs EXTENT difference in rfc-101

### ISSUE THREAD

**Issue by strk** [mapserver/mapserver#5050]
In RFC101 http://www.mapserver.org/development/rfc/ms-rfc-101.html it is reported that contextual legend is activated whenever user passes BBOX, CRS/SRS and EXTENT. But then it doesn't explain what is the difference between BBOX and EXTENT, nor it includes EXTENT in the example.

**Comment by tbonfort** [comment]
fixed in 716f3b

**Comment by strk** [comment]
thanks!
