### ISSUE TITLE
Image height limit with AGG renderer???

### ISSUE THREAD

**Issue by dmorissette** [mapserver/mapserver#5054]
Paul Spencer (@pagameba) and Christy Nieman have come across an issue that seems related to a limitation in the image height with the AGG renderer, this issue can be reproduced using the current git master version (6.5-dev, future 7.0)

They sent me a simple test case to reproduce it, I ran it in GDB and saw that everything seems to run normally (shape is transformed properly, etc.) until we hit agg2RenderPolygon() in mapagg.cpp which calls mapserver::render_scanlines(), and in the case where we get the bug, render_scanlines loops only once on the scanlines and returns on the second scanline. OTOH, the case that works fine loops properly on all scanlines. 

I don't know enough about the AGG stuff to dig further without spending much more time trying to understand the code., so I'm hoping that @tbonfort or someone else who knows that code can have a look.

I will attach the mapfile to reproduce the issue. It contains a single layer with a single inline polygon feature in it. Setting "SIZE16079 19678 " in the mapfile causes the polygon to not be rendered, whereas a smaller size (e.g. SIZE 8040 9839) then the polygon is rendered properly.

Paul also sent the following additional info: "Christy was able to narrow down the range of the problem a bit.  The problem seems to occur when the height of the map is around 16380px but not when it is 16370px (both with a width of 1771px).  The problem did not occur when the horizontal dimension was very large and the vertical was small (28818px x 1771px).  It seems that a vertical height of something more than 16370px (suspiciously close to 2^14) triggers the issue and width does not affect it (although we didn't push it further than 28818).  Also not sure if some combinations of height and width (i.e. total pixels) might reproduce)"

BTW, with Google I found a matplotlib ticket referring to an AGG image size limitation which may or may not apply to the MapServer case since the implementation is different in MapServer. Hopefully all this will ring a bell to @tbonfort.

**Comment by cnieman** [comment]
Hi @tbonfort.  Paul and I were wondering if you happened to have any further insight about this.

**Comment by jratike80** [comment]
Works for me with mode=map and &map_size=5000+30000 in the same way than with &map_size=30000+5000 with Mapserver 7.0.6 from MS4W 3.2.2. I believe that the issue has gone.
