### ISSUE TITLE
Fix builds with Visual Studio 2013

### ISSUE THREAD

**Issue by szekerest** [mapserver/mapserver#5059]
When building mapserver with VS2013, the following errors:

..renderers/agg/include/agg_conv_clipper.h(72): error C2039: 'max' : is not a member of 'std'

Due to a breaking change in VS2003, you must use #include <algorithm> when you call std::min() or std::max()

For more information refer to the STL section of the following document:
http://msdn.microsoft.com/en-us/library/vstudio/bb531344%28v=vs.120%29.aspx

**Comment by jmckenna** [comment]
I believe all of the work now should go to making sure Visual Sudio 2014 is supported in our MapServer environments. Dane Springmeyer has recently done a lot of work to make sure of this, for Mapnik and Mapbox: 
* https://github.com/mapbox/node-pre-gyp/issues/119
* https://github.com/mapnik/node-mapnik/issues/348

**Comment by jmckenna** [comment]
..which I believe is now referred to as "Visual Studio 2015 preview"

**Comment by szekerest** [comment]
I prefer to work with release versions only. 
Once VS2015 is released, I'm going to switch my builds to that version shortly.

**Comment by jmckenna** [comment]
ok.  I will also upgrade my builds to 2013 now.  Thanks.
