### ISSUE TITLE
MapScript convertToString writes to stdOut

### ISSUE THREAD

**Issue by geographika** [mapserver/mapserver#5060]
When using Python MapScript (although I assume it is the same for other MapScript languages), using the layer.convertToString function writes to the stdOut, as well as returning a string.

This leads to the Python script writing output when the string is simply required:

E.g. `s = layer_obj.convertToString()`

Produced:

```
OUTLINECOLOR 220 220 220
COLOR 255 0 0
```

Looking at an example for writing a layer to string in mapfile.c the writeLayer(stdout..) appears to be responsible. 

```
char* msWriteLayerToString(layerObj *layer)
{
  msIOContext  context;
  msIOBuffer buffer;

  ...
  msIO_installHandlers( NULL, &context, NULL );

  writeLayer(stdout, -1, layer);
  msIO_bufferWrite( &buffer, "", 1 );

  msIO_installHandlers( NULL, NULL, NULL );

  return (char*)buffer.data;
}
```

I used the approach described at http://stackoverflow.com/questions/11130156/suppress-stdout-stderr-print-from-python-functions to suppress this output, however it may be prudent to remove this as it leads to some confusion when trying to find the source of this rogue output, and can produce unexpected side effects in a script.

**Comment by szekerest** [comment]
I've tried that in C#, but I couldn't reproduce this (in mapserver-master). 
Actually mapserver should not write to stdout because is redirected to a buffer.

**Comment by jratike80** [comment]
@geographika, can you reproduce?

**Comment by geographika** [comment]
Can't recreate this anymore. It may have been related to running scripts through Python Tools for Visual Studio.
