### ISSUE TITLE
classes display order wrong

### ISSUE THREAD

**Issue by murdav** [mapserver/mapserver#5063]
Dear All,

I'm using mapserver-6.0.3-13.el6.x86_64 on RedHat Enterprise (latest available yum package version).
Same issue using mapserver 6.2.2 on Ubuntu.

The point layer (OGR geojson) has several classes, briefly 0,1,2,3,4.
4 should be on top of 3, 3 on top of 2 and so on.
In the mapfile the layer definition classes order is 0,1,2,3,4, as it must be to keep the display order (on top 4-3-*).
But it's not visualized correctly, class 0 which contains more points is always on top, instead 

I tried to implement:
http://www.mapgears.com/en/blog/archive/2013-03-05-roads_network_mapping
and
https://github.com/mapserver/mapserver/issues/4612

But without having success. Any idea?

Thanks,

	LAYER
		NAME "Stations"
		METADATA
			"ows_title"			""
			"ows_description"	""
	  	END	
		PROJECTION
			"init=epsg:3857"
		END
	    PROCESSING "LABEL_NO_CLIP=1"
	    TOLERANCE 10
	    TYPE POINT
	    STATUS OFF
	    CONNECTIONTYPE OGR
	    LABELITEM "Station"
	    #LABELCACHE on
	    TEMPLATE "templates/stations.tmpl"
	    SYMBOLSCALEDENOM 1000000
	    CLASSITEM "threshold"
	
	    CLASS
	        NAME "Available stations (0)"
	        EXPRESSION ('[threshold]'='0')
	        STYLE
				COLOR 0 128 0
				OUTLINECOLOR 33 99 66
				OUTLINEWIDTH 1		
	            SYMBOL 'circle'
	            SIZE 8
	            MINSIZE 6
	            MAXSIZE 11
	            MINWIDTH 1
	            MAXWIDTH 2
	        END
	        LABEL            
	            MAXSCALEDENOM 1000000
				POSITION auto     
				COLOR 0 128 0
	        	OUTLINECOLOR 255 255 255
	        	OUTLINEWIDTH 2
				FONT verdana
				TYPE truetype
	            SIZE 6
	            MINSIZE 5
	            MAXSIZE 7
	            #ANTIALIAS true           
	            BUFFER 10            
	            PARTIALS false
	        END
	    END 
	
	    CLASS
	        NAME "No data received (1)"
	        EXPRESSION ('[threshold]'='1')
	        STYLE            
	            OUTLINECOLOR 255 0 0			
				COLOR 255 255 255 
	            SYMBOL 'circle'
	            SIZE 8
	            MINSIZE 6
	            MAXSIZE 11
	            MINWIDTH 1
	            MAXWIDTH 2
	        END
	        LABEL
	            MAXSCALEDENOM 1000000
				POSITION auto       
				COLOR 0 128 0
	        	OUTLINECOLOR 255 255 255
	        	OUTLINEWIDTH 2
				FONT verdana
				TYPE truetype
	            SIZE 6
	            MINSIZE 5
	            MAXSIZE 7       
	            BUFFER 10            
	            PARTIALS false   
	        END
	    END    
	
	    CLASS
	        NAME "Lowest level (2)"
	        EXPRESSION ('[threshold]'='2')      
	        STYLE
	            SYMBOL 'level_alert1'
	            SIZE 22
	            MINSIZE 20
	            MAXSIZE 26
	        END
	        LABEL
	            MAXSCALEDENOM 1000000
				POSITION UL            
				COLOR 255 255 0
	        	OUTLINECOLOR 0 0 0
	        	OUTLINEWIDTH 2
				FONT verdana
				TYPE truetype
	            SIZE 7
	            MINSIZE 6
	            MAXSIZE 8      
	            BUFFER 10            
	            PARTIALS false
	        END
	    END	
	
	    CLASS
	        NAME "Second lowest level (3)"
	        EXPRESSION ('[threshold]'='3')        
	        STYLE
	            SYMBOL 'level_alert2'
	            SIZE 22
	            MINSIZE 20
	            MAXSIZE 26
	        END
	        LABEL
	            MAXSCALEDENOM 1000000
				POSITION UL            
				COLOR 255 165 0
	        	OUTLINECOLOR 0 0 0
	        	OUTLINEWIDTH 2
				FONT verdana
				TYPE truetype
	            SIZE 7
	            MINSIZE 6
	            MAXSIZE 8          
	            BUFFER 10            
	            PARTIALS false                            
	        END
	    END
	
	    CLASS
	        NAME "Second highest level (4)"
	        EXPRESSION ('[threshold]'='4')        
	        STYLE
	            SYMBOL 'level_alert3'
	            SIZE 22
	            MINSIZE 20
	            MAXSIZE 26
	        END
	        LABEL
	            MAXSCALEDENOM 1000000
				POSITION UL
				COLOR 255 0 0
	        	OUTLINECOLOR 255 255 255
	        	OUTLINEWIDTH 2
				FONT verdana
				TYPE truetype
	            SIZE 7
	            MINSIZE 6
	            MAXSIZE 8
	            BUFFER 10            
	            PARTIALS false
	        END
	    END
	END

**Comment by tbonfort** [comment]
Not a bug, the class order does not define the drawing order. Each feature is tested against the class expression and the the first class that matches is used. If you need to order your features that must be done at the datasource level (i.e. using sortshp for shapefiles, order by clauses for sql backends, and (I've personally never tested) OGR SQL in your case. Features returned last are rendered on top, in your case you'd use something like ```order by threshold asc```

**Comment by murdav** [comment]
Thanks tbonfort for replying.
The input is a geojson file format.
I'm going to implement what you suggested. Having read the documentation I believed it was possible to display in such order based on the layer classes definition order.

D

**Comment by murdav** [comment]
I just modified the GEOJSON file adding at the end the points with threshold>1 and they are displayed on top of 0<threshold<1.
Thanks again.

D
