### ISSUE TITLE
Support Oracle for msautotests

### ISSUE THREAD

**Issue by msmitherdc** [mapserver/mapserver#5072]
Either with an external Oracle instance with configuration to Travis or with a separate jenkins instance.

**Comment by rouault** [comment]
Note: this would be of interest for GDAL for the OGR OCI driver as well. Wondering if/how you can download the OCI SDK from Travis...

**Comment by msmitherdc** [comment]
@rouault I will probably host the instant cleint sdk files for downloading to travis (https://help.ubuntu.com/community/Oracle%20Instant%20Client). Once i have this all worked out for mapserver, we can work on this for OGR.

**Comment by msmitherdc** [comment]
Or, we;ll get the xe client directly from oracle (see https://oss.oracle.com/debian/)

**Comment by msmitherdc** [comment]
@rouault worked out the method to use the instant client. I'm hosting the instantclient files in dropbox and use a travis encrypted env variable to download. See https://github.com/msmitherdc/mapserver/tree/issues-5072. I can do the same thing for gdal/ogr.

**Comment by rouault** [comment]
Looks interesting. It seems I would need the unencrypted values of the env var to encrypt them with my key ?
It just tests the build right ?

**Comment by msmitherdc** [comment]
@rouault yes, I'll send you the URLs offline and you can reencrypt them.
