### ISSUE TITLE
MapObj->save ignores Symbol ANCHORPOINT property

### ISSUE THREAD

**Issue by traffin** [mapserver/mapserver#5073]
Symbols with ANCHORPOINT defined in will be saved without ANCHORPOINT when using MapObj->save method in PHP/MapScript

Version: MapServer 6.2.1 on Windows

**Comment by tbonfort** [comment]
Fixed for 7.0, remilestoning to 6.4.2

**Comment by traffin** [comment]
Thanks!
Do you know if there is a way to easily patch windows binaries please?

**Comment by tbonfort** [comment]
You'll have to backport the patch and recompile
