### ISSUE TITLE
MapScript Csharp symbolObj.imagepath cannot init

### ISSUE THREAD

**Issue by mamont80** [MapServer/MapServer#5074]
I am used Csharp MapScript.
symbolObj sym = new symbolObj("sym2", @"c:\img.png");
But sym.imagepath = null 

Or
symbolObj sym = new symbolObj("sym2", "");
sym.type = (int) MS_SYMBOL_TYPE.MS_SYMBOL_PIXMAP;
sym.inmapfile = 1;
sym.setImagepath(@"c:\img.png");
And also sym.imagepath = null

**Comment by jratike80** [comment]
@szekerest , you know Csharp, don't you?

**Comment by szekerest** [comment]
This seems to be a bug in msLoadImageSymbol, where imagepath should also be set.

**Comment by jratike80** [comment]
There has been so much changes in MapScript since 2015 that I am closing this issue as outdated.
