### ISSUE TITLE
GetFeatureInfo doesn't apply the FILTER parameter.

### ISSUE THREAD

**Issue by gsueur** [mapserver/mapserver#5076]
It seems that the getFeatureInfo request doesn't consider any FILTER condition in the request sent to a PostGIS Layer. 
It looks like a regression as the mapfiles used here were functionnal with MapServer 5.6

**Comment by sdlime** [comment]
What version are you talking about? There have been significant changes in 7.0 in this area including in how FILTERs are defined (MapServer syntax via driver SQL syntax). The specific changes are detailed in the migration guide. --Steve

**Comment by gsueur** [comment]
It's a 6.5 version from january I use. Actually, the FILTER section is applied for the GetMap request (I only see the filtered parcels on the image) but doesn't on the GetFeatureInfo request : nothing is returned though the SQL query I see in postgresql logs doesn't use any WHERE clause instead of the bbox one and returns objects. 

It seems a bit odd that the FILTER works in some cases and not others. But this may be a feature :-)

Guillaume

**Comment by sdlime** [comment]
Try the beta release (and check the migration docs). Filters should be very consistent now compared to past versions.

**Comment by gsueur** [comment]
I'll try version 7 on Friday. 

Best regards. 

Guillaume Sueur
Neogeo Technologies

**Comment by gsueur** [comment]
Fixed in 7.1-dev.
