### ISSUE TITLE
No Methods in MapScript to set colo(u)r RGBA

### ISSUE THREAD

**Issue by ejn** [mapserver/mapserver#5077]
Currently the colorObj does not provide any methods capable of setting the alpha value - only setRGB().

PHP- and SWIG MapScript should be extended with a setRGBA() method.

Current workaround is to use updateFromString on the parent object.

**Comment by tbonfort** [comment]
please go ahead and fix, seems pretty straightforward from what I've checked in the swig files. Please also update the fromHex() method so it also accepts #rrggbbaa forms of hex strings.

**Comment by ejn** [comment]
Also missing is:
in SWIG a toHex with alpha channel (lets call it toHexAlpha to avoid changing the signature of the existing toHex method)
in PHP toHex, setHex and toHexAlpha

I'll throw all those into a PR coming up (fairly) shortly

**Comment by tbonfort** [comment]
@ejn: can we close this one now #5078 is done?

**Comment by ejn** [comment]
@tbonfort - yes, should all be sorted now.
