### ISSUE TITLE
GetCapabilities request is extremely slow when “OWS_LAYER_GROUP” is used

### ISSUE THREAD

**Issue by aabhayas** [mapserver/mapserver#5081]
GetCapabilities request is extremely slow when the Mapfile has nested layers using “OWS_LAYER_GROUP”. This bug exists from the version 6.2 of Mapserver.

Following link has more details of this bug.

http://osgeo-org.1560.x6.nabble.com/Re-Getcapabilities-extremely-slow-in-version-6-4-1-td5191374.html

I have uploaded two map files and two map part files which can be used to reproduce this bug.

http://osgeo-org.1560.x6.nabble.com/file/n5194857/layer_group.map
http://osgeo-org.1560.x6.nabble.com/file/n5194857/layer_group.part
http://osgeo-org.1560.x6.nabble.com/file/n5194857/no_layer_group.map
http://osgeo-org.1560.x6.nabble.com/file/n5194857/no_layer_group.part

Map file layer_group.map uses layer_group.map.part which has LAYER_GROUPS defined.

Map file no_layer_group.map uses no_layer_group.map.part which has no LAYER_GROUPS defined.

I use the following command line in my server to time the getcapabilities requests.

time /web/cgi-bin/mapserv -nh "QUERY_STRING=map=/web/ms4w/apps/tutorial/htdocs/layer_group.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities"

time /web/cgi-bin/mapserv -nh "QUERY_STRING=map=/web/ms4w/apps/tutorial/htdocs/no_layer_group.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities"

**Comment by tbonfort** [comment]
fixed with #5094

**Comment by tomkralidis** [comment]
Is/should this be backported to 6.4.x?

**Comment by aabhayas** [comment]
Hi

I think we should backport this to 6.4

Regards
Anuruddha Abhayasinghe
[Description: Description: Description: Description: http://web.bom.gov.au/eiab/publishing/images/bureau_logo.gif]
Geospatial Data and Services
Delivery Section / Build Branch
Bureau of Meteorology
GPO Box 1289 Melbourne VIC 3001
Level 6, 700 Collins Street, Docklands VIC 3008
Tel: +61 3 9669 4589 | aabhayas@bom.gov.au<mailto:aabhayas@bom.gov.au>
www.bom.gov.au<http://www.bom.gov.au/>

**Comment by tomkralidis** [comment]
Backported to branch-6-4
