### ISSUE TITLE
Expression parser error in 7.0 beta release

### ISSUE THREAD

**Issue by geographika** [mapserver/mapserver#5083]
I've been testing the 7 release from http://www.gisinternals.com/ (version 7.0.0-beta1) and have come across errors in a previously working layer. 

Logs are showing the following:

```
[Tue Mar 24 16:29:54 2015].959000 msEvalExpression: Expression parser error. Failed to parse expression: (DATE >= '2008-01-01' AND DATE <= '2020-12-31')
[Tue Mar 24 16:29:54 2015].959000 yyparse(): Expression parser error. syntax error
```

My LAYER config allows filtering by date using WMS:

```
    METADATA
      "ows_timeitem"	"DATE"
      "ows_timeextent"	"1900-1-1/2030-12-31"

```

Dates are sent using the WMS TIME parameter by a client application:

```
&TIME=2008-01-01/2020-12-31
```

These match the patterns described at http://mapserver.org/ogc/wms_time.html#wms-time

Even using a single date causes the error:

```
&TIME=2008-01-01

[Tue Mar 24 16:33:02 2015].852000 msEvalExpression: Expression parser error. Failed to parse expression: DATE = '2014-12-31'
[Tue Mar 24 16:33:02 2015].852000 yyparse(): Expression parser error. syntax error

```

Changing the ows_timeitem to "[DATE]" had no effect. 

Is this related to the NATIVE_FILTER mentioned in the migration guide?
http://mapserver.org/MIGRATION_GUIDE.html#mapserver-6-4-to-7-0-migration

**Comment by sdlime** [comment]
What's backend being used by this particular layer?

**Comment by geographika** [comment]
Sorry forgot that critical info!
The MapServer MS SQL Server driver and a MS SQL 2008 database.

**Comment by sdlime** [comment]
Argh... It's impossible for me to test this as I have no access to a SQL Server environment. That backend did not have a MapServer expression to native SQL translator written as part of RFC91 (again, since I don't have access to that environment). So, what's supposed to happen the WMS config is represented as a MapServer expression and then evaluated by MapServer and not the database.

What do your WMS requests look like? I'd like to match what you're trying to do against one of the regression tests in msautotest/ows.

Is it possible for you to run this against a shapefile version of your data? If so, does it work?

Steve

**Comment by geographika** [comment]
Hi - I've done some more testing/debugging. 

In the 7.0 release with full debugging on, the SQL query runs successfully and returns all records without a time filter. It appears the filter is then applied to each feature individually (as you wrote - the feature is compared to a MapServer expression). An error message for the filter appears for each feature - so there are 1000s of these errors with each WMS request. 

```
[Tue Mar 31 07:52:04 2015].367000 msDrawMap(): rendering using outputformat named png (GDAL/PNG).
[Tue Mar 31 07:52:04 2015].367000 msDrawMap(): WMS/WFS set-up and query, 0.000s
[Tue Mar 31 07:52:04 2015].746000 LayerDefaultTranslateFilter(): General error message. This data driver does not implement filter translation support
[Tue Mar 31 07:52:05 2015].235000 yyparse(): Expression parser error. syntax error
[Tue Mar 31 07:52:05 2015].235000 msEvalExpression: Expression parser error. Failed to parse expression: (DATE >= '2013-01-01' AND DATE <= '2014-12-31') OR (DATE >= '1900-1-1' AND DATE <= '1900-1-1')
```

So it looks like the expression is not valid. 
Looking at http://mapserver.org/mapfile/expressions.html#temporal-expressions it seems as though it should be?

I exported the data to a shapefile with the same TIME filter and no errors were logged. It looks like there may be an issue with the features returned by SQL Server? 
The DATE field (I also tried renaming everything DATE_ in case of reserved words with no luck), is a datetime2 field type in SQL Server 2008 R2. 
In the shapefile the field type is DATE. 

Alternatively there may be an issue with which fields are returned for a feature, as if I change the "ows_timeitem" to a field that doesn't exist I get the exact same error:

```
[Tue Mar 31 10:58:59 2015].210000 msEvalExpression: Expression parser error. Failed to parse expression: (FAKEDATE >= '2013-01-01' AND FAKEDATE <= '2014-12-31')
[Tue Mar 31 10:58:59 2015].210000 yyparse(): Expression parser error. syntax error
```

In MapServer 6.4 the WMS TIME filter was applied directly to the data clause:

```
 tbl WHERE ((DATE >= '2013-01-01' AND DATE <= '2014-12-31') OR (DATE >= '1900-1-1' AND DATE <= '1900-1-1')) and GEOM.STIntersects(geometry::STGeomFromText('POLYGON((-1071593.14310681 6820375.1327
```

This is much more preferable as the features are directly filtered in the database. However it seems from 7.0 onwards the SQL Server driver needs updating to handle the native filter conversion.

**Comment by tbonfort** [comment]
@szekerest is 982f3e618b5 related to this issue ?

**Comment by szekerest** [comment]
Yes, this issue appears to be fixed now.

**Comment by tbonfort** [comment]
@geographika can you confirm and close this issue?

**Comment by geographika** [comment]
Yes all my failing layers are now working with time filters with the latest MS7 build from http://www.gisinternals.com/. 

I have over 80 of varying complexity all using the SQL Server driver so it is a good test of the 7.0 release. 

Many thanks to @szekerest for his work.
