### ISSUE TITLE
Labels disappear when selecting features

### ISSUE THREAD

**Issue by skafka** [MapServer/MapServer#5090]
When some features are selected by nquery or itemnquery, the labels remain only on selected features. It was tested on Shapefiles, PostGIS layers and inline feature data. 

_The labels are drawn properly when POSTLABELCACHE ON or LABELCACHE OFF_.

**MS version**: 6.4.0 and 6.4.1, (both CGI nad PHP mapscript). 

**Example map file**:

```
MAP
    EXTENT -5 -5 30 15
    SIZE 300 200

    QUERYMAP
        STATUS ON
        STYLE hilite
    END

    LAYER 
        NAME test
        TYPE POLYGON
        STATUS default
        PROCESSING "ITEMS=ID"
        FEATURE
            WKT "POLYGON((0 0, 0 10, 10 10, 10 0, 0 0))"
            ITEMS "1"
        END
        FEATURE
            WKT "POLYGON((15 0, 15 10, 25 10, 25 0, 15 0))"
            ITEMS "2" 
        END
        TEMPLATE dummy
        #POSTLABELCACHE ON
        #LABELCACHE OFF
        LABELITEM "ID"
        VALIDATION
            "qstring" "[0-9]+"
        END
        CLASS
            LABEL
                COLOR 0 0 0
            END
            STYLE
                COLOR 150 150 200
            END  
        END
    END
END  
```
- [The map without selection](http://gis.lesprojekt.cz/cgi-bin/mapserv?map=/home/dima/test_label.map&mode=map&layers=test)
- [First feature selected](http://gis.lesprojekt.cz/cgi-bin/mapserv?map=/home/dima/test_label.map&mode=nquery&layers=test&qlayer=test&mapxy=10%2010&qformat=png)
- [The same in Mapserver 6.0.1 on Windows](http://hsmap.cz/cgi-bin/mapserv.exe?map=/gis/projects/test_label_6.0.1.map&mode=nquery&layers=test&qlayer=test&mapxy=10%2010&qformat=png)

**Another problem**:
Whe I try to select this features with itemnquery, both features are selected regardles the querystring value: 

http://gis.lesprojekt.cz/cgi-bin/mapserv?map=/home/dima/test_label.map&mode=itemnquery&layers=test&qlayer=test&qitem=ID&qstring=2&qformat=png 

My fault?

Thank you

**Comment by sdlime** [comment]
What are you using to do the (spatial) selection? --Steve

**Comment by skafka** [comment]
I use mapxy parameter

 

There is the example (also on GitHub): http://gis.lesprojekt.cz/cgi-bin/mapserv?map=/home/dima/test_label.map <http://gis.lesprojekt.cz/cgi-bin/mapserv?map=/home/dima/test_label.map&mode=nquery&layers=test&qlayer=test&mapxy=10%2010&qformat=png> &mode=nquery&layers=test&qlayer=test&mapxy=10%2010&qformat=png 

 

Stepan

**Comment by skafka** [comment]
Steve, please, is there any solution of this issue? Thank you.

**Comment by jratike80** [comment]
Amazing that the server URL still answers!
https://gis.lesprojekt.cz/cgi-bin/mapserv?map=/home/dima/test_label.map&mode=itemnquery&layers=test&qlayer=test&qitem=ID&qstring=1&qformat=png
https://gis.lesprojekt.cz/cgi-bin/mapserv?map=/home/dima/test_label.map&mode=itemnquery&layers=test&qlayer=test&qitem=ID&qstring=2&qformat=png
<img width="100" alt="image" src="https://github.com/MapServer/MapServer/assets/1751612/92dee677-ca43-431b-b13f-5b6d9c387b6b">


<img width="100" alt="image" src="https://github.com/MapServer/MapServer/assets/1751612/4a0e6700-596f-43e3-99e2-e47e8f571e2b">

It seems that at least some of the issues have disappeared.
