### ISSUE TITLE
FriBidi

### ISSUE THREAD

**Issue by sbrunner** [mapserver/mapserver#5091]
Two question or issue on FriBidi:

On this line:
https://github.com/mapserver/mapserver/blob/branch-7-0/CMakeLists.txt#L105
FriBidi is relay for **left-to-right** languages, not for **right-to-left** languages ?

On this command:
https://github.com/mapserver/mapserver/blob/branch-7-0/scripts/vagrant/mapserver.sh#L26-L31
`WITH_FRIBIDI` is set on tine to 0 and an other to 1 ...

**Comment by tbonfort** [comment]
fixed, thanks
