### ISSUE TITLE
ows_allowed_ip_list / ows_denied_ip_list not working

### ISSUE THREAD

**Issue by vlasvlasvlas** [mapserver/mapserver#5092]
Hi.

i was testing "ows_denied_ip_list" or allowed ip list on my 6.4.1 mapserver and it does not work at all.

```
 ./mapserv -v
MapServer version 6.4.1 OUTPUT=GIF OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=GD SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=ICONV SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=GEOS INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE

```

```

METADATA


		"ows_denied_ip_list" "*"
#(other metadata..)
END

```
even blocking "*" (all ip's) it doesnt work,

i always receive a GetMap response using wms
..

i can still see my request (cgi-bin,wms,getmap) why?

:S

![cdd4_sjweaeqbax](https://cloud.githubusercontent.com/assets/4071796/7279612/8d9c16d4-e8f3-11e4-92c0-a3c862cac09f.jpg)

**Comment by vlasvlasvlas** [comment]
arrg

**Comment by jmckenna** [comment]
Please ask your questions on the MapServer mailing list: subscribe at http://lists.osgeo.org/mailman/listinfo/mapserver-users

The issue tracker is not for asking questions.
