### ISSUE TITLE
Mapserver 7 doesn'accept PATTERN tag in SYMBOL

### ISSUE THREAD

**Issue by mcomelli** [mapserver/mapserver#5101]
Trying to use this symbol in a map file:

    SYMBOL
      NAME "dreieck-kopf"
      TYPE VECTOR
      POINTS
        0 0
        0.5 1
        1 0
        0 0
      END
      PATTERN 1 20 1 20 END
      FILLED TRUE
    END

I get the error:

**loadSymbol(): Unknown identifier. Parsing error near (PATTERN):(line 186)**

while commenting the 'PATTERN' line the map is created correctly.

**Comment by sdlime** [comment]
This is intentional, not a bug... and something not specific to version 7. This changed at the 6.0 release (see the migration guide). Patterns are a STYLE-level setting. --Steve
