### ISSUE TITLE
labelpoly is not drawn for line follow with big angle

### ISSUE THREAD

**Issue by astroidex** [mapserver/mapserver#5121]
I have roads with a labelpoygon, that follows the line. For some lines (with a big angle) the labelpolygon is not drawn). This is a problem with SIZEUNITS meters and pixel.

![labelpolygon_not_displayed](https://cloud.githubusercontent.com/assets/996298/8761640/af3e13f8-2d5b-11e5-87df-ef12a41b399a.png)

Have a look at the example and screenshot.

                TEXT "Test Test Test Test"
                LABEL
                        TYPE TRUETYPE
                        COLOR 0 0 0  
                        FONT "arialbold"
                        POSITION uc
                        ANGLE follow
                        MAXOVERLAPANGLE 360
                        FORCE TRUE
                        SIZE 8  
                        MINSIZE 5
                        MAXSIZE 10
                        ENCODING "UTF-8"
                        STYLE # bbox
                                GEOMTRANSFORM 'labelpoly'
                                COLOR 250 250 250
                        END
                END

**Comment by tbonfort** [comment]
which mapserver version ? reproducible with another version?

**Comment by tbonfort** [comment]
'labelpoly' geomtransforms are not supported with FOLLOW labels. They do appear in your testcase as FOLLOW actually switches to AUTO for features with only two points. If you need a roughly same effect as a background on follow labels, use an outlinecolor on the text.
