### ISSUE TITLE
lanczos resample method

### ISSUE THREAD

**Issue by manelclos** [mapserver/mapserver#5128]
Hi,

Is mapserver going to support the lanczos resample method in the near future?

Thanks!

**Comment by sdlime** [comment]
This is a GDAL feature I take it, @rouault? --Steve

**Comment by rouault** [comment]
@sdlime. Yes it is available in GDAL, and in GDAL 2.0 in the GDALRasterIOEx()/GDALDatasetRasterIOEx() API. MapServer still use the old API (without Ex), but, quoting http://gdal.org/classGDALDataset.html#ad2a643880bf8b3c492783e1ab5fbc667 :
"the GDAL_RASTERIO_RESAMPLING configuration option can also be defined to override the default resampling to one of BILINEAR, CUBIC, CUBICSPLINE, LANCZOS, AVERAGE or MODE." This can be defined as a PROCESSING option in the mapfile.

**Comment by sdlime** [comment]
Thanks for the clarification! So I guess the answer is yes and we can close the ticket --Steve

**Comment by manelclos** [comment]
Just to see if I understood correctly, you mean "yes" for implementing it on the future, or "yes" given that mapserver is linked against gdal 2.0?

Thanks!

**Comment by sdlime** [comment]
Sorry, I meant that it’s currently supported assuming you’re linked against the right GDAL version.
