### ISSUE TITLE
Mapscript wrapper GetMap issue

### ISSUE THREAD

**Issue by drnextgis** [mapserver/mapserver#5130]
Mapscript wrapper described [here](http://mapserver.org/ogc/wms_server.html#mapscript-wrapper) works fine with WFS (GetCapabilities and GetFeature), but fails on WMS GetMap request (GetCapabilities works fine) - no errors, but return empty image (version with map path in URL also works as expected).

Windows, mapserver and mapscript packages from OSGeo4W installer.

**Comment by sdlime** [comment]
Closing this one in favor of a newer ticket seemingly detailing the same issue - #5798.
