### ISSUE TITLE
released tarball full of ._* OSX files

### ISSUE THREAD

**Issue by tigerfoot** [mapserver/mapserver#5138]
The actual 7.0.0 tarball contains thousands of file beginning by ._ which are installed on system with make install.

They should not be present in released tar 
a temporary fix in my specfile is to use 
in %prep section
find . -iname "._*" -exec rm -fv {} \;

**Comment by tigerfoot** [comment]
To be more precise only the tar.gz present here 
http://download.osgeo.org/mapserver/mapserver-7.0.0.tar.gz
contain thoses files. 
Which means there a difference between tar.gz proposed here on github and on mapserver.org.

**Comment by jmckenna** [comment]
I reported this issue to the Dev list on the day of the release.  Since no one tackled, I dove in and removed the junk OSX files, repackaged, and uploaded it to: http://download.osgeo.org/mapserver/mapserver-7.0.0.tar.gz

**Comment by tigerfoot** [comment]
Thanks Jeff
