### ISSUE TITLE
maprendering.c - too much debug

### ISSUE THREAD

**Issue by ianwalberg** [mapserver/mapserver#5139]
In the function msDrawTextSymbol there is debug every time it is called which is much more than I would have expected.

msDebug("setting outlinewidth to %d (%d, %d, %d)\n",ow,ts->label->outlinewidth, ts->textpath->glyph_size, ts->label->size);

**Comment by sdlime** [comment]
I agree... I'll remove.

**Comment by tbonfort** [comment]
fixed in 8b4418890263d8
