### ISSUE TITLE
OUTPUTFORMAT MidMif - Zip archive - 7.0

### ISSUE THREAD

**Issue by joathan00** [mapserver/mapserver#5155]
I try to create an OUTPUFORMAT MIDMIF in zip archive : 
```mapscript
OUTPUTFORMAT   
	NAME "MultiMIDMIF"
	DRIVER "OGR/MapInfo File"   
	FORMATOPTION "STORAGE=filesystem"  
	FORMATOPTION "FORM=zip"   
	FORMATOPTION "DSCO:FORMAT=MIF"
	FORMATOPTION "FILENAME=result.zip" 
END
```
I get this error : 
```error
msOGRWriteFromQuery(): General error message. OGR CreateDataSource failed for '/tmp/559cd585_334a_0/result.zip' with driver 'MapInfo File'.
```
If I change the line : 
```mapscript
FORMATOPTION "FILENAME=result.zip"
```
by 
```mapscript
FORMATOPTION "FILENAME=result"
```
I get my archive, but wihout the extention .zip !

Do you know this problem ?

Thank you.

**Comment by rouault** [comment]
See https://github.com/mapserver/docs/commit/3d3850d0edf85bb86d62cc0a233c9c8dd6168ea5

So try FORMATOPTION "FILENAME=result.mif.zip"

**Comment by joathan00** [comment]
Thank you for your proposal.

I have try your suggestion, but it doesn't work.
I get the same error.

More information :
If I set FORMATOPTION "FILENAME=result.mif" (or FORMATOPTION "FILENAME=result")
And try it with FireFox, firefox suggest to "open with : Windows" or "save the file".
If I save the file, I get result.mif (or result) and I can unzip file with my favorite unzip-Soft.
If I "open with - Windows", windows open unzip and all is OK. Moreover, I get a tempory file with name "result.mif.zip" (or result.zip).

I don't understand.

Thank you

**Comment by rouault** [comment]
Fixed in master and branch-7-0
