### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by Chirag19** [mapserver/mapserver#5160]
I am compiling mapserver in visual studio 2010 64bit. Both SDK and GDAL/Mapserver source I downloaded from  http://www.gisinternals.com. GDAL compiling without any problem but Mapserver give me following error. secondly why cmake is required  for compiling in 64bit? earlier 32bit version I tried without cmake and it was worked fine. please resolve my problem. 

//************************************************************

	echo MS_BASE=E:\MS_2015_64\release-1600-x64-dev\mapserver-6-4 > E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo SWIG-1.3.39 > E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo THREADS=-DUSE_THREAD >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo MSVC_VER=1600 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo WIN64=YES >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo SWIG=E:\MS_2015_64\release-1600-x64-dev\SWIG-1.3.39\swig.exe >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo GD_DIR=E:\MS_2015_64\release-1600-x64-dev\gd-2.0.35 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo GD_LIB=E:\MS_2015_64\release-1600-x64-dev\gd-2.0.35\gd.lib >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo gd-2.0.35 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo zlib-1.2.3 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo jpeg-6b >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo PROJ=-DUSE_PROJ -DUSE_PROJ_API_H >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo proj-4.8 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo FT_DIR=E:\MS_2015_64\release-1600-x64-dev\freetype-2.4.11 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo FT_LIB=E:\MS_2015_64\release-1600-x64-dev\freetype2411.lib >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo freetype-2.4.11 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo GEOS=-DUSE_GEOS >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo GEOS_DIR=E:\MS_2015_64\release-1600-x64-dev\geos-3.4 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo geos-3.4 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo PHP_HOME=C:\php-sdk\php53dev\vc9\x64\php-5.3.7 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo php-5.3.7 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo DOT_NET=YES >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo PNG_DIR=E:\MS_2015_64\release-1600-x64-dev\libpng-1.2.35 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo PNG_LIB=E:\MS_2015_64\release-1600-x64-dev\libpng-1.2.35\libpng.lib E:\MS_2015_64\release-1600-x64-dev\zlib-1.2.3\zdll.lib >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo RGBA_PNG_ENABLED=-DUSE_RGBA_PNG >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo libpng-1.2.35 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo GDAL=-DUSE_GDAL >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo OGR=-DUSE_OGR >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo GDAL_DIR=E:\MS_2015_64\release-1600-x64-dev\gdal >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo gdal >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo FCGIDEF=-DUSE_FASTCGI >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo FCGIDIR=E:\MS_2015_64\release-1600-x64-dev\fcgi-2.4.0 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo fcgi-2.4.0 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo PDF=-DUSE_PDF >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo PDF_DIR=E:\MS_2015_64\release-1600-x64-dev\PDFlib-Lite-7.0.4p1 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo PDFlib-Lite-7.0.4p1 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo FRIBIDI=-DUSE_FRIBIDI >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo FRIBIDI_DIR=E:\MS_2015_64\release-1600-x64-dev\fribidi-0.19.2 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo fribidi-0.19.2 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo GIF=-DUSE_GIF >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo GIFLIB_DIR=E:\MS_2015_64\release-1600-x64-dev\giflib-4.1.6 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo giflib-4.1.6 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo WMS=-DUSE_WMS_SVR >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo CURL=-DUSE_CURL -DUSE_CURLOPT_PROXYAUTH >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo WMSCLIENT=-DUSE_WMS_LYR >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo CURL_DIR=E:\MS_2015_64\release-1600-x64-dev\curl-7.37.1 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo CURL_INC=-IE:\MS_2015_64\release-1600-x64-dev\curl-7.37.1/include >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo CURL_LIB=E:\MS_2015_64\release-1600-x64-dev\curl-7.37.1\lib\libcurl_imp.lib >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo curl-7.37.1 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo WINSOCK_LIB =WS2_32.Lib >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo WFSCLIENT= -DUSE_WFS_LYR >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo WFS=-DUSE_WFS_SVR >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo WCS=-DUSE_WCS_SVR >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo JAVA_HOME=C:\Java\jdk1.8.0_51x64 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo REGEX_DIR=E:\MS_2015_64\release-1600-x64-dev\regex-0.12 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo AGG=-DUSE_AGG >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo AGG_DIR=E:\MS_2015_64\release-1600-x64-dev\agg-2.4 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo agg-2.4 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo CAIRO=-DUSE_CAIRO -DUSE_SVG_CAIRO >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo CAIRO_DIR=E:\MS_2015_64\release-1600-x64-dev\cairo-1.12.14 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo FONTCONFIG_DIR=E:\MS_2015_64\release-1600-x64-dev\fontconfig-2.10.91 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo cairo-1.12.14 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo libsvg-0.1.4 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo libsvg-cairo-0.1.6 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo pixman-0.28.2 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo fontconfig-2.10.91 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo OGL=-DUSE_OGL >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo FTGL_DIR=E:\MS_2015_64\release-1600-x64-dev\ftgl-2.1.3~rc5 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo ftgl-2.1.3~rc5 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo POSTGIS=-DUSE_POSTGIS >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo POSTGIS_DIR=E:\MS_2015_64\release-1600-x64-dev\postgresql-9.1.2 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo postgresql-9.1.2 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo ICONV=-DUSE_ICONV >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo ICONV_DIR=E:\MS_2015_64\release-1600-x64-dev\release-1600-x64 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo libiconv-1.11.1 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo gettext-0.13 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo SOS=-DUSE_SOS_SVR >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo XML2_ENABLED=-DUSE_LIBXML2 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo LIBXML_DIR=E:\MS_2015_64\release-1600-x64-dev\release-1600-x64 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo libxml2-2.7.7 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\doc\ms_deps.txt
	echo INCLUDES = -Irenderers\agg\include -IE:\MS_2015_64\release-1600-x64-dev\release-1600-x64\include  \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo -IE:\MS_2015_64\release-1600-x64-dev\regex-0.12 >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo EXTERNAL_LIBS = /LIBPATH:E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\lib gd.lib libpng.lib libjpeg.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo proj_i.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo libxml2.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo iconv.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo libfcgi.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo pdflib.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo fribidi.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo giflib.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo libpqdll.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	if not exist E:\MS_2015_64\release-1600-x64-dev\mapserver-6-4\renderers\agg echo agg.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo libexpat.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo cairo.lib libsvg.lib libsvg-cairo.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo ftgl.lib opengl32.lib glu32.lib user32.lib gdi32.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo gdal_i.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo libcurl_imp.lib WS2_32.Lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo freetype2411.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo geos_c.lib \>> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	echo libjpeg.lib zdll.lib >> E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\mapserver.opt
	cd E:\MS_2015_64\release-1600-x64-dev\mapserver-6-4
	set JAVA_HOME=C:\Java\jdk1.8.0_51x64
	set ORACLE_HOME=Oracle\instantclient_11_1_7_0-x64
	set PYTHONPATH=E:\MS_2015_64\release-1600-x64-dev\Python27-AMD64
	if exist vc10x64 rd /Q /S vc10x64
	if exist build rd /Q /S build
	if not exist vc10x64 mkdir vc10x64
	cd vc10x64
	C:\builds\cmake-2.8.12.1-win32-x86\bin\cmake ..\ -G "Visual Studio 10 Win64" "-DCMAKE_PREFIX_PATH=E:\MS_2015_64\release-1600-x64-dev\release-1600-x64;E:\MS_2015_64\release-1600-x64-dev\Oracle\instantclient_11_1_7_0-x64\sdk\lib\msvc" "-DJPEG_LIBRARY=E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\lib\libjpeg.lib" "-DZLIB_LIBRARY=E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\lib\zdll.lib" -DWITH_THREADS=1 -DWITH_PYTHON=1 -DWITH_JAVA=1 -DWITH_CSHARP=1 -DWITH_PHP=0 -DWITH_ORACLESPATIAL=0 -DWITH_ORACLE_PLUGIN=1 -DWITH_MSSQL2008=1 -DWITH_KML=1 -DWITH_SVGCAIRO=1 "-DSVG_LIBRARY=E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\lib\libsvg.lib" "-DSVGCAIRO_LIBRARY=E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\lib\libsvg-cairo.lib" "-DSWIG_EXECUTABLE=E:\MS_2015_64\release-1600-x64-dev\SWIG-1.3.39\swig.exe" "-DPYTHON_LIBRARY=E:\MS_2015_64\release-1600-x64-dev\Python27-AMD64\libs\python27.lib" "-DPYTHON_INCLUDE_DIR=E:\MS_2015_64\release-1600-x64-dev\Python27-AMD64\include" "-DPYTHON_EXECUTABLE=E:\MS_2015_64\release-1600-x64-dev\Python27-AMD64\python.exe" "-DORACLE_INCLUDE_DIR=E:\MS_2015_64\release-1600-x64-dev\Oracle\instantclient_11_1_7_0-x64\sdk\include" "-DHARFBUZZ_INCLUDE_DIR=E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\include\harfbuzz" -DWITH_GD=1 "-DGD_LIBRARY=E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\lib\gd.lib" "-DPOSTGRESQL_LIBRARY=E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\lib\libpqdll.lib" "-DICONV_DLL=E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\bin\iconv.dll" "-DFREETYPE_LIBRARY=E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\lib\freetype2411.lib" "-DPROJ_LIBRARY=E:\MS_2015_64\release-1600-x64-dev\release-1600-x64\lib\proj_i.lib" -DWITH_CLIENT_WMS=1 -DWITH_CLIENT_WFS=1 -DWITH_SOS=1 -DREGEX_DIR=E:\MS_2015_64\release-1600-x64-dev\regex-0.12 -DMS_EXTERNAL_LIBS=WS2_32.Lib "-DCMAKE_CXX_FLAGS_RELEASE=/MD /Oi /Ob2 /D NDEBUG" "-DCMAKE_C_FLAGS_RELEASE=/MD /Oi /Ob2 /D NDEBUG" "-DWITH_THREAD_SAFETY=1"
-- The C compiler identification is MSVC 16.0.30319.1
-- The CXX compiler identification is MSVC 16.0.30319.1
-- Check for working C compiler using: Visual Studio 10 Win64
-- Check for working C compiler using: Visual Studio 10 Win64 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 10 Win64
-- Check for working CXX compiler using: Visual Studio 10 Win64 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for strrstr
-- Looking for strrstr - not found
-- Looking for strcasecmp
-- Looking for strcasecmp - not found
-- Looking for strcasestr
-- Looking for strcasestr - not found
-- Looking for strdup
-- Looking for strdup - found
-- Looking for strlcat
-- Looking for strlcat - not found
-- Looking for strlcpy
-- Looking for strlcpy - not found
-- Looking for strlen
-- Looking for strlen - found
-- Looking for strncasecmp
-- Looking for strncasecmp - not found
-- Looking for vsnprintf
-- Looking for vsnprintf - found
-- Looking for lrintf
-- Looking for lrintf - not found
-- Looking for lrint
-- Looking for lrint - not found
-- Looking for dlfcn.h
-- Looking for dlfcn.h - not found
-- Performing Test HAVE_SYNC_FETCH_AND_ADD
-- Performing Test HAVE_SYNC_FETCH_AND_ADD - Failed
-- Found ZLIB: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/zdll.lib (found version "1.2.3") 
-- Found PNG: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/libpng.lib (found version "1.2.35") 
-- Found JPEG: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/libjpeg.lib  
-- Found Freetype: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/freetype2411.lib  
-- Found PROJ: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/proj_i.lib  
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Found FRIBIDI: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/fribidi.lib  
-- Found iconv library: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/iconv.lib
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Found CAIRO: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/cairo.lib  
-- Could NOT find ORACLE (missing:  ORACLE_LIBRARY) 
-- Found FCGI: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/libfcgi.lib  
-- Found GEOS: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/geos_c.lib  
-- Found POSTGRESQL: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/libpqdll.lib  
-- Looking for PQserverVersion in pq
-- Looking for PQserverVersion in pq - not found
-- Found GDAL: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/gdal_i.lib  
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Found SVG: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/libsvg.lib  
-- Found SVGCAIRO: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/libsvg-cairo.lib  
-- Found CURL: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/libcurl_imp.lib (found version "7.37.1") 
-- Found LibXml2: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/libxml2.lib (found version "2.7.7") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - not found
-- Found Threads: TRUE  
-- Performing Test GIF_GifFileType_UserData
-- Performing Test GIF_GifFileType_UserData - Success
-- Found GIF: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/giflib.lib (found version "4") 
-- Found SWIG: E:/MS_2015_64/release-1600-x64-dev/SWIG-1.3.39/swig.exe (found version "1.3.39") 
-- Found PythonInterp: E:/MS_2015_64/release-1600-x64-dev/Python27-AMD64/python.exe (found version "1.4") 
-- Found PythonLibs: E:/MS_2015_64/release-1600-x64-dev/Python27-AMD64/libs/python27.lib  
-- Found JNI: C:/Program Files/Java/jdk1.7.0_11/lib/jawt.lib  
-- Found Java: C:/Program Files/Java/jdk1.7.0_11/bin/java.exe (found version "1.7.0.11") 
-- Found CSharp compiler: C:/Windows/Microsoft.NET/Framework64/v4.0.30319/csc.exe
-- * Summary of configured options for this build
--  * Mandatory components
--   * png: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/libpng.lib
--   * jpeg: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/libjpeg.lib
--   * freetype: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/freetype2411.lib
--  * Optional components
--   * GDAL: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/gdal_i.lib
--   * OGR: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/gdal_i.lib
--   * GD: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/gd.lib
--   * GIF: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/giflib.lib
--   * MYSQL: disabled
--   * FRIBIDI: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/fribidi.lib
--   * GIF: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/giflib.lib
--   * CAIRO: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/cairo.lib
--   * SVGCAIRO: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/libsvg-cairo.lib
--   * RSVG: disabled
--   * CURL: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/libcurl_imp.lib
--   * PROJ: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/proj_i.lib
--   * LIBXML2: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/libxml2.lib
--   * POSTGIS: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/libpqdll.lib
--   * GEOS: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/geos_c.lib
--   * FastCGI: E:/MS_2015_64/release-1600-x64-dev/release-1600-x64/lib/libfcgi.lib
--   * Oracle Spatial: disabled
--   * MSSQL 2008 (Built as plugin): C:/Program Files (x86)/Microsoft SDKs/Windows/v7.0A/Lib/x64/odbc32.lib
--   * SDE: disabled
--   * Exempi XMP: disabled
--  * Optional features
--   * WMS SERVER: ENABLED
--   * WFS SERVER: ENABLED
--   * WCS SERVER: ENABLED
--   * SOS SERVER: ENABLED
--   * WMS CLIENT: ENABLED
--   * WFS CLIENT: ENABLED
--   * ICONV: ENABLED
--   * Thread-safety support: ENABLED
--   * KML output: ENABLED
--   * Z+M point coordinate support: disabled
--   * XML Mapfile support: disabled
--  * Mapscripts
--   * Python: ENABLED
--   * PHP: disabled
--   * PERL: disabled
--   * RUBY: disabled
--   * JAVA: ENABLED
--   * C#: ENABLED
--   * Apache Module (Experimental): disabled
-- 
-- Will install files to C:/Program Files/MapServer
-- Will install libraries to C:/Program Files/MapServer/lib
-- Configuring incomplete, errors occurred!
See also "E:/MS_2015_64/release-1600-x64-dev/mapserver-6-4/vc10x64/CMakeFiles/CMakeOutput.log".
See also "E:/MS_2015_64/release-1600-x64-dev/mapserver-6-4/vc10x64/CMakeFiles/CMakeError.log".

**Comment by tbonfort** [comment]
This should go to the mailing list
