### ISSUE TITLE
Opacity ignored when generating an image of WIDTH between 1941 & 1959 pixels

### ISSUE THREAD

**Issue by ochriste** [mapserver/mapserver#5181]
when generating a 24bit image with some opacity, if the image has a WIDTH between 1941 & 1959 pixels, the layers with an opacity value between 0 and 100 are generated with full opacity (100)

the following error message is visible when calling mapserv CGI:

*** BUG ***
In create_bits_image_internal: The expression bits == NULL || (rowstride_bytes % sizeof (uint32_t)) == 0 was false
Set a breakpoint on '_pixman_log_error' to debug

Since GitHub is broken I cant join a file to this issue, but you can get it there:

http://dev.camptocamp.com/files/mapserver/test.map

working query:
```bash
mapserv -nh "QUERY_STRING=map=test.map&LAYERS=test,test2&FORMAT=image%2Fpng&TRANSPARENT=TRUE&SERVICE=WMS&SRS=EPSG:21781&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=508675,142220,543000,165440&WIDTH=1716&HEIGHT=1161" > test_1716.png

mapserv -nh "QUERY_STRING=map=test.map&LAYERS=test,test2&FORMAT=image%2Fpng&TRANSPARENT=TRUE&SERVICE=WMS&SRS=EPSG:21781&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=508675,142220,543000,165440&WIDTH=1960&HEIGHT=1161" > test_1960.png
```

non-working query:
```bash
mapserv -nh "QUERY_STRING=map=test.map&LAYERS=test,test2&FORMAT=image%2Fpng&TRANSPARENT=TRUE&SERVICE=WMS&SRS=EPSG:21781&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=508675,142220,543000,165440&WIDTH=1950&HEIGHT=1161" > test_1950.png
```

Mapserver version 7.0.0

**Comment by tbonfort** [comment]
please disable pixman support on your build and report back.

**Comment by ochriste** [comment]
tests with disabled pixman support are conclusive: the problem could not be reproduced

what is pixman used for?

**Comment by ochriste** [comment]
"use pixman as an external dependency to enable use of SSE optimized operations inside the AGG renderer."
what kind of performance gain are we talking here ?

**Comment by tbonfort** [comment]
I haven't tested. The functionality is disabled by default and not advertized in the docs as it is still experimental.

**Comment by sebastic** [comment]
@tbonfort, can the PIXMAN support (and other experimental features) be more explicitly marked as experimental (e.g. like the experimental features in MapCache)? This will help packagers make better decisions which features to enable or not.

It was enabled in the mapserver Debian package because nothing pointed to its experimental nature. I've disabled it now after this issue was raised in [Debian Bug #801573](https://bugs.debian.org/801573).

**Comment by tbonfort** [comment]
@sebastic done. Sorry about that.
