### ISSUE TITLE
buffer([shape] resulting polygon ignores linejoin/endcap

### ISSUE THREAD

**Issue by artclifford** [mapserver/mapserver#5183]
I have a polygon layer styled in part using:
CLASS
      NAME ""
      EXPRESSION ("[name]" == "")
      LABEL
        FONT "RobotoMonoBold"
        SIZE 14
        BUFFER 1
        MINDISTANCE 0
        MINFEATURESIZE -128
        OFFSET 0 0
        OUTLINECOLOR 255 255 255
        POSITION AUTO
        SHADOWCOLOR 153 153 153
        SHADOWSIZE 2 2
        TYPE TRUETYPE
      END # LABEL
      STYLE
      END # STYLE
      STYLE
        GEOMTRANSFORM (buffer([shape], 7.5))
        LINECAP SQUARE
        LINEJOIN MITER
        OUTLINECOLOR 0 0 0
        SIZE 9.66667
        WIDTH 9.66667
      END # STYLE
    END # CLASS
  END # LAYER

Resulting in:

![render](https://cloud.githubusercontent.com/assets/15258290/10684099/2bfae270-78fe-11e5-9e35-ae6a309f78ac.png)

Note that the outer edge of the line has rounded corners.while the inner polygon is angular. 
Note too that the linejoin and linecap suggest that the intent is for the resulting line not to be rounded.

This becomes problematic with more complex line styles.

![render2](https://cloud.githubusercontent.com/assets/15258290/10684161/efc29414-78fe-11e5-8d58-7e213911dca9.png)

In the image above I'm attempting to have two patterned styles where the pattern would go around the edge of the polygon. However, because of the rounded corners the inner line is gaining pixels around each corner which throws the gap/pattern offset off.

The corresponding class is:
 CLASS
      NAME ""
      EXPRESSION ("[name]" == "")
      LABEL
        FONT "RobotoMonoBold"
        SIZE 14
        BUFFER 1
        MINDISTANCE 0
        MINFEATURESIZE -128
        OFFSET 0 0
        OUTLINECOLOR 255 255 255
        POSITION AUTO
        SHADOWCOLOR 153 153 153
        SHADOWSIZE 2 2
        TYPE TRUETYPE
      END # LABEL
      STYLE
      END # STYLE
      STYLE
        GEOMTRANSFORM (buffer([shape], 7.5))
        LINECAP SQUARE
        LINEJOIN MITER
        OUTLINECOLOR 0 0 0
        SIZE 9.66667
        WIDTH 9.66667
      END # STYLE
      STYLE
        OUTLINECOLOR 0 0 0
        SIZE 7
        WIDTH 7
      END # STYLE
      STYLE
        LINECAP SQUARE
        LINEJOIN MITER
        OUTLINECOLOR 254 254 254
        PATTERN
         12.00 24.00
        END # PATTERN
        SIZE 5
        WIDTH 5
      END # STYLE
      STYLE
        INITIALGAP 0
        GEOMTRANSFORM (buffer([shape], 7.5))
        LINECAP SQUARE
        LINEJOIN MITER
        OUTLINECOLOR 254 254 254
        PATTERN
         12.00 24.00
        END # PATTERN
        SIZE 5
        WIDTH 5
      END # STYLE
    END # CLASS

While it may be better for another issue or two, the following were also a quandary in attempting this pattern:
1) the pattern 12 and 24 are supposed to indicate on and off pattern, but one is half the other though the on and off pattern are equal.
2) in php mapscript, setting $style->set('linecap','square') results in LINECAP NONE. 
2a) to make it say LINECAP SQUARE in php I used $style->updateFromString('LINECAP square'); which resulted in LINECAP SQUARE.
3) while the outer /bottom line is ignoring the linecap the inner patterned lines seem to be recognizing the line cap at the ends of the dashes.
4) Setting a filled vector symbol for a polygon line renders the symbol without a fill
5) When attempting to use a vector symbol for a polygon outline the symbol does not truncate at the polygon border and will overshoot the polygon

![render3t](https://cloud.githubusercontent.com/assets/15258290/10684433/df7c6ae6-7901-11e5-9656-887d1623a867.jpeg)

I had contemplated using a filled symbol with two black polygons offset like I'm attempting in the pattern which would repeat, but if I did that it would have the problem depicted above.

Either there is a bug or two here, I'm missing something due to under-documentation, or this is not possible but should be.

I do apologize for possibly overloading this issue, but the issues noted are all related to trying to style a double nautical line.

**Comment by tbonfort** [comment]
That's what a buffer is supposed to do. You should be using the mailing list rather than the issue tracker for your case. And give an example of what you're trying to obtain.

**Comment by tbonfort** [comment]
You don't configure linejoins on a buffer, they are *round* by the very definition of what a buffer is. Granted you can set the linecaps when dealing with linear geometries, but that is out of scope when using polygons. 
>However, because of the rounded corners the inner line is gaining pixels around each corner which  >throws the gap/pattern offset off.
No, the rounded corners have nothing to do here. The perimeter of the buffered shape is longer than the one of the unbuffered shape, so the gap/pattern will be offset as soon as you hit the second segment.

**Comment by artclifford** [comment]
Ok, if that is the design of the buffer behavior that needs to be stated in the docs. 

 

However, I am not sure I would ever have read the docs to mean what you said. The buffer function is a geomtransform which I took to mean it is essentially doing an ST_Buffer postgis-like function to create a new polygon where each vertex is moved based on the buffer algorithm to return a new polygon.  That is what anybody geospatially minded is going to expect a buffer operation on their spatial geometry to do; after all this isn’t a vector drawing too. In other words if I start with a square and I buffer it by 10  I expect a square 10 times bigger than the first with 4 points and 4 lines; if I buffer it by -10 I expect to have a square 1/10th the original size with four points and lines. If moving the color and other style options out of the definition of symbols was an indication of an understanding of disambiguating style and symbol, then it follows that you should do the same with geometry; rounding corners has nothing to do with buffer.


In fact the buffer([shape])… routine is more or less doing that. 

If a geospatial notion of the buffer is what the original intent of buffer was for, then the resulting polygon should only be rounded if the style is set to be rounded.

 

If not, then I would change this to be a feature request for an inset/outset geotransform or st_buffer geomtransform option that works like buffer but produces an unrounded geometry that honors the style property.

 

In all of the other geomtransform options start, end, label, etc the style settings apply to the resulting geometry; so from my perspective this rounded buffer is inconsistent with system behavior as a whole.

 

My intent is not to be argumentative but rather contribute, at least through observation, to making the symbolizing tech better and consistent with its documentation. This comes after a week and a half of wrestling with symbolizer technology that met expectations brilliantly for most of my line needs and fell hard on polygon outline support. I’ve been using MapServer for over 9 years; I appreciate what y’all do and  I want to see it thrive.

**Comment by tbonfort** [comment]
maybe try running ```SELECT ST_AsText(ST_Buffer(ST_GeomFromText('POLYGON((0 0,0 1,1 1,1 0,0 0))'),1));```

**Comment by artclifford** [comment]
I was trying to do this at the style level for features that meet a class.


I am also trying to do what the documentation suggests is possible.

 

I don’t understand why you are resisting this so hard. The functionality is a style implementation away from working per what the documentation implies is possible.  If you stopped rounding the line implicitly and only rounded based on style, the default for a line style is that the line is rounded and would have the current rounded style effect. However, if a linecap and linejoin are specified that style should dictate the rendering of the transformed geometry.

 

I don’t see how this is the epically inappropriate requrest you seem to think it is.

 

Furhtermore I don’t want to do a select at a layer level for something that might only apply to individual features.

 

And honestly having to indicate that a line symbol should only be applicable on a polygon layer identified as a line type layer is assanine even if it works and completely destroys the utility of defining complex symbols using styles.

 

The ultimate question is whether you have any pride in your work and want to make the symbolizer style and symbol technology actually work, or do want to go several rounds with me defending your mediocrity?

 

I know what I’m talking about, and I know that you clearly don’t.

**Comment by artclifford** [comment]
I would like to propose the following experiment. If I’m wrong about the outcome I’ll shut up.

 

This will require someone setup with the source code and who can step through the code and/or log output.

 

I want to know what the geomtransform function for buffer([shape]… returns as a result.

 

Hypothesis:  If [shape] defines a polygon with four vertices, the method returns a polygon with four vertices defining four lines and not a polygon with extra vertices for rounding corners.

 

Assumption 1: 

IF Hypothesis is correct

Then: The rounded corners in the resulting rendering of the geometry are a result of applying the default line style (rounded corners), and your assumption about the buffer function is incorrect.

Assumption 2:

If Assumption 1 is correct

Then: the code in controlling rendering is neglecting to look up data provided by the style properties for geometries that are transformed by geomtransform buffer; likely because some geomtransform operations transform from polygon to point (like the label point) and so you don’t necessarily obey the style the same for the transformed geometry as you would from the source geometry.  In other words it would be an easy condition to ignore especially if you think buffering is supposed to result in rounded geometry. 

 

If my hypothesis and assumptions are completely wrong and the geom transform returns a geometry with more vertices than it started with, then I will ask the user group if anybody knows how to use the javascript geomtransform functionality to get a polygon back that behaves like postgis st_buffer. And/or I will ask the group how we might use the javascript geomtransform to convert polygons into lines with the hopes that if I apply a line style to the resulting geometry it will properly render line symbology rather than having to add another layer which defeats the whole ability to create complex symbols.

**Comment by tbonfort** [comment]
This will be my last comment here. If you had actually ran the SQL snippet I posted just before, you would have seen that postgis's ST_Buffer does exactly what Mapserver's buffer([geom]) is doing, i.e. creating rounded corners (as again, that is what a buffer is supposed to do). That is actually expected, as they are both applying the same geos::buffer() operation on the geometry.
You can now choose to continue ranting about how MapServer isn't doing what you are hoping for it to do, or you can do what I suggested in my first comment, which is to actually show what you are trying to obtain (the end result, not how you are trying to do to obtain it), take that to the mailing list, and have people who know how the rendering is done suggest how to obtain that.

**Comment by tomkralidis** [comment]
:+1:

**Comment by artclifford** [comment]
Ok, than you, that was illuminating and clarified the point of confusion/conflict. Discussing the issue further with a colleague of mine he pointed out that there have been discursions like this in Autocad user groups as well as GIS circles regarding the expected behavior of a buffer operation, and that he has seen differences in implementations.

 

However, here is the PostGIS ST_BUFFER doc page:

http://postgis.net/docs/manual-2.0/ST_Buffer.html

 

Note toward the end that it mentions the different line join types, looking almost like the mapserver docs for symbology.

 

That  is what I expected mapserver to be doing rather than assuming all buffers should be rounded lines (there are times when that should be done and times when it shouldn’t). I have little doubt the postgis function changed to support these types because people had the same sorts of unexpected behavior. If the buffer geomtransform could get the settings from the STYLE block the geomtransform is called in and use them per postgis st_buffer that would be the cleanest implementation from a developer-user perspective. And, since the default style for lines is rounded corners, you would be taken care of in terms of backward compatibility.

 

What it will facilitate is a wider range of options for doing multiple parallel line styles for polygons with patterns that won’t be stretched around the inner lines and therefore can stay in sync relative to each other around corners. 

 

If I were to write up a more complete report of what I attempted, expected, the limits I hit, and recommendations for improvements I know this is the wrong venue for something of that detail, but is the usergroup mail list appropriate or is there a better place?

**Comment by dmorissette** [comment]
@artclifford three things:

1- What MapServer currently does is a GIS buffer and everybody except you understands that. What you want is an offset of coordinates, that is NOT a GIS buffer. Period.

2- Please change your tone and do you research before insulting those who try to help you with comments such as "The ultimate question is whether you have any pride in your work...". NOBODY is obligated to cope with that.

3- Keep in mind that you have full source code access and are free to fork the source and implement the new behaviors that interest you or find someone who is willing to implement it for you, quite likely in exchange for large amounts of money given that this person would also have to cope with your attitude. Then write a RFC, discuss it with the PSC and propose your change for inclusion in the official source tree.

**Comment by artclifford** [comment]
I will adjust my tone.

 

“What MapServer currently does is a GIS buffer and everybody except you understands that What you want is an offset of coordinates, that is NOT a GIS buffer. Period.”

 

I’m not an authority on GIS buffers and given my past tone probably wouldn’t be listened to if I was.

 

I defer to the PostGIS documentation for st_buffer which allows for square endcaps and mitered line joins;

http://postgis.net/docs/ST_Buffer.html

 

If you read that and still think that the only definition of a GIS buffer is the one you are holding onto I’m not sure how to convince you what GIS people need and want. 

 

Regardless, there is still an *apparent* deficiency in the symbology technology in that it doesn’t allow for *equivalent* functionality as the ST_Buffer-with-support-for-endcap-and -linejoin; which I actually do agree is an offset.  However, it is offset with different behavior than the mapserver style offset x y functionality in that those offsets don’t work around corners as desired as they are not relative to the x and y origin before rotation, thus an offsety of 10 is always 10 down and not 10 pixels in the positive y direction on along a line 90 degrees from the origin. I can accept that is by design. When I originally searched for a solution to the offset problem, the recommendation was to use buffer[shape] geomtransform, which is fine for thin lines that you don’t notice the corners on or if you don’t need a pattern that depends on square endcaps, because the geomtransform makes the corners rounded and that cannot be altered by the style; for reasons which are now very clear, but are not documented in the documentation for buffer[shape] and so is unexpected, and are contrary to open GIS standards per ST_Buffer docs above.  

 

I use apparent above because I know that you all have done quite a bit of work and there may be something other than buffer or offset x y that does the job. There is not a clear way to achieve the kind of offset I and others are interested in that have been achieved for simpler cases by buffer.

 

My tone came from being dismissed offhanded without any apparent thought or attempt to understand the problem and from a general arrogant and incorrect assumption of superiority rather than receiving a tone of community. And given the discrepancy between your first point and postgis official docs, I think you might understand the point of frustration a community member may have raising an issue for something that does not appear to work only to get an it’s-not-a-problem response.

 

Please note that I have not put a timeframe on this or indicated any kind of priority. Its not about what I need, its about what mapserver needs. I’m illuminating a problem to be considered as either a bug, enhancement, or a feature request as appropriate because it would be nice to have the ability more interesting symbology than single line patterns or double/mutli line patterns that only work with rounded corners. That isn’t terribly unreasonable is it?
