### ISSUE TITLE
ShiftX and ShiftY as an alternative to OffsetX/Y

### ISSUE THREAD

**Issue by artclifford** [mapserver/mapserver#5184]
In issue #5183  I outlined problems I had trying to create a double nautical line.

When creating symbols the units are relative to the units use din the symbol. 
It would be nice to have a shift y or shift x so that if I made a symbol with points:
SYMBOL
NAME 'thin_horiz_rect' 
 POINTS
 0 0
 1 0
 1 .5
 0 .5
 1 0
 END
END 
Then if in my Style I could do
STYLE
SYMBOL "thin_horiz_rect"
SHIFTY 0.5
COLOR 0 0 0
END
STYLE
SYMBOL "thin_horiz_rect"
SHIFTY 0
COLOR 255 255 255
END

What that should mean is stack two of these symbols with one shifted down .5 units in the unrotated symbol-space prior to rotating the symbol such that with gaps properly set up the symbols would repeat and would always be stacked properly all around the polygon. This would differ from OffsetY in that OffsetY means Y pixels down/up regardless of rotation which looks unexpected:

![road_multi](https://cloud.githubusercontent.com/assets/15258290/10684796/7019a7fe-7906-11e5-9f71-418a50e10da3.png)

Note the bottom of the line as it turns back to the left on the bottom, what was the inner line becomes the outer line because the line is Y-pixels down, rather than being y-pixels up, or y-pixels left, because it is rotated. 

I think this implies that Shift X/Shift Y would more or less allow the style to shift the anchor point.
So maybe ShiftAnchor double double

**Comment by tbonfort** [comment]
Please take your issue to the mailing list first with what you are trying to obtain.
