### ISSUE TITLE
SymbolColor or ColorTarget for Class

### ISSUE THREAD

**Issue by artclifford** [mapserver/mapserver#5185]
Setting line styles for polygons is cumbersome without the ability to set Color for a filled symbol on a polygon outline. The documentation says to use outline color but for a filled symbol that sets the outline of the symbol not the fill color which cannot be set via STYLE for a polygon because COLOR sets the polygon fill color.

If you added a ColorTarget symbol to Style, at least for polygon layers, there could be values of:
ColorTarget SYMBOL | SHAPE
Where SYMBOL would indicate that COLOR applies to the symbol's fill color, whereas SHAPE would indicate fill in the polygon.

Or, alternatively you could have a SymboLColor option and simply identify which color you want to use with the symbol rather than the fill color for the polygon.

The issue of filled symbols only showing as outlines was referred to in passing in: #5183

**Comment by tbonfort** [comment]
Not happening. Use multiple STYLEs

**Comment by tbonfort** [comment]
Polygon outlines are just a shorthand to apply simple strokes to a polygon contour. If you need the more complex symbology that applies to lines, use a ```TYPE LINE``` layer (even if the geometry itself is a polygon). If you need to fill the actual polygon, add a second ```TYPE POLYGON``` with the fill you need.

**Comment by artclifford** [comment]
Ok, if that works it makes sense and since lines work that’s the behavior I want. but unless I missed something in the documentation that is there already, the fact that you can do this should be stated somewhere in the docs .
