### ISSUE TITLE
WFS 1.1.0 and 2.0.0 "wfs_return_srs_as_urn" "true" does not affect GetCapabilities

### ISSUE THREAD

**Issue by jratike80** [mapserver/mapserver#5186]
WEB - METADATA object  "wfs_return_srs_as_urn" affects how srsName is encoded in GetFeature with WFS 1.1.0. and 2.0.0. However, setting the value to "false" does not have an effect on DefaultSRS in GetCapabilities of WFS 1.1.0 and 2.0.0 but it is always
<DefaultSRS>urn:ogc:def:crs:EPSG::4326</DefaultSRS>

Tested with Mapserver 7.0 (MS4W) on Windows.

**Comment by rouault** [comment]
I'd say the current behaviour is intended. The intent was to just apply on GetFeature results and not on GetCapabilities that was already correct in WFS 1.1.0 and 2.0

See http://mapserver.org/development/rfc/ms-rfc-105.html :
"""
Regarding SRS, for WFS 2.0, it will always be reported with the “urn:ogc:def:crs:EPSG::” syntax. This should likely also be done for WFS 1.1.0. The “wfs_return_srs_as_urn” can be set to “true” or “false” to enable or disable this behaviour. It defaults to “true” for WFS 2.0 and to “false” for older versions.
"""

**Comment by jratike80** [comment]
Hmm, I suppose that WFS clients are supposed to do first GetCapabilities and then DescribeFeatureType and finally GetFeature. If short srsName "EPSG:4326" is not advertised in GetCapabilities then how the client can guess that it could/should use it instead of the advertised urn:ogc:def:crs:EPSG::4326"?

If I have  "wfs_return_srs_as_urn" "false" in mapfile I see urn-format in GetCapabilities but I still get EPSG:4326 even if I explicitly request long format:

http://localhost:8060/cgi-bin/mapserv.exe?map=c:/ms4w/apps/wms-wfs.map&service=wfs&version=1.1.0&request=getfeature&typename=states_table&srsName=urn:ogc:def:crs:EPSG::4326

I would say that it would be better to advertise what user will get in GetCapabilities.

**Comment by rouault** [comment]
> I would say that it would be better to advertise what user will get in GetCapabilities.

I don't want to take the responsibility of breaking happy existing clients of MapServer WFS 1.1.0 ;-) The aim of the option was to be able to selectively be more conformant than we are today.

**Comment by jratike80** [comment]
Selectively conformant, that's well said. Closing because any change would probably break more than fix.
