### ISSUE TITLE
Primary key/OGC_FID may be lost with OGR connection

### ISSUE THREAD

**Issue by jratike80** [mapserver/mapserver#5191]
With some drivers GDAL finds automatically the primary key or FID column and handles it in a special way which means that it is not advertised as a normal attribute. This has an side effect that such attribute cannot be used as  "gml_featureid" which will lead to invalid GML output from WFS services.

Issue was reported originally in https://lists.osgeo.org/pipermail/mapserver-users/2015-October/078369.html and thread includes suggestions for workarounds.

Related issue:
https://github.com/mapserver/mapserver/issues/2859

**Comment by tbonfort** [comment]
For reference, the workaround proposed by Even is:

> The GML output tries to find a item/field with the name of the gml_featureid. 
But the FID column in OGR is treated specially and not reported as a regular field. Which explains the error. In the case of "select * from table_name" as pk_uid is different from ogc_fid then it is just recognized as a regular column, which makes things work. So even "select * from table_name" isn't a guarantee that things are going to work. If the primary key field was named ogc_fid, you'd have to do "select ogc_fid as pk_uid, * from table_name" so it appears as a regular OGR field.

closing for now, if someone wants to champion the implementation of another behavior, this issue can be reopened/referenced.
