### ISSUE TITLE
NULL shapes not supported in WFS

### ISSUE THREAD

**Issue by jratike80** [MapServer/MapServer#5192]
While studying https://github.com/mapserver/mapserver/issues/3487 which was about a rendering bug when shapefile contains NULL shapes I noticed that NULL shapes lead to wrong result in WFS. They are not included in the data that is requested with GetFeature.

I edited a states shapefile by updating one geometry into NULL with ogrinfo. Feature count is still 49 as reported by ogrinfo:

ogrinfo states.shp -al -so
Layer name: states
Metadata:
  DBF_DATE_LAST_UPDATE=2015-11-01
Geometry: Polygon
Feature Count: 49

WFS DescribeFeatureType allows missing geometries for the feature type as can be seen from the schema:
<complexType name="states_shpType"><complexContent><extension base="gml:AbstractFeatureType"><sequence><element name="msGeometry" type="gml:GeometryPropertyType" minOccurs="0" maxOccurs="1"/>

However, the feature with empty geometry (Illinois in my test) is missing totally from the WFS GetFeature resultset that comes with
http://localhost:8060/cgi-bin/mapserv.exe?map=c:/ms4w/apps/null_test.map&service=WFS&version=1.1.0&request=getfeature&typename=states_shp

This happens both with native shapefile connection and through OGR connection.

Odd thing is that if I use OGR connection and input data as OpenJUMP JML instead of shapefile then Illinois is still missing from the plain GetFeature. However, in this case I can read data of Illinois by making a direct featureid query:

http://localhost:8060/cgi-bin/mapserv.exe?map=c:/ms4w/apps/null_test_jml.map&service=WFS&version=1.1.0&request=getfeature&typename=states_shp&featureid=states_shp.17

gml:featureMember<ms:states_shp gml:id="states_shp.17">gml:boundedBy<gml:Envelope srsName="urn:ogc:def:crs:EPSG::4326">gml:lowerCorner-1.000000 -1.000000/gml:lowerCornergml:upperCorner-1.000000 -1.000000/gml:upperCorner/gml:Envelope/gml:boundedByms:STATE_NAMEIllinois/ms:STATE_NAMEms:STATE_FIPS17/ms:STATE_FIPSms:SUB_REGIONE N Cen/ms:SUB_REGIONms:STATE_ABBRIL/ms:STATE_ABBRms:LAND_KM143986.61/ms:LAND_KMms:WATER_KM1993.335/ms:WATER_KMms:PERSONS11430602/ms:PERSONSms:FAMILIES2924880/ms:FAMILIESms:HOUSHOLD4202240/ms:HOUSHOLDms:MALE5552233/ms:MALEms:FEMALE5878369/ms:FEMALEms:WORKERS4199206/ms:WORKERSms:DRVALONE3741715/ms:DRVALONEms:CARPOOL652603/ms:CARPOOLms:PUBTRANS538071/ms:PUBTRANSms:EMPLOYED5417967/ms:EMPLOYEDms:UNEMPLOY385040/ms:UNEMPLOYms:SERVICE1360159/ms:SERVICEms:MANUAL828906/ms:MANUALms:P_MALE0.486/ms:P_MALEms:P_FEMALE0.514/ms:P_FEMALEms:SAMP_POP1747776/ms:SAMP_POPms:R_G_B//ms:states_shp/gml:featureMember

I guess that this could happen if Mapserver is always adding an "AND geom Intersects EXTENT" when it makes the query from data source.
Immediate fix would be to edit the schema of feature types and make geometry property to be "NOT NULL". Another alternative would be to make WFS to work with empty geometries.

**Comment by jratike80** [comment]
This is now partially fixed by a new metadata item "wfs_use_default_extent_for_getfeature". Setting it to "no" does remove the intersects filter from the query.

Mapserver does this query from Spatialite:
 msOGRFileWhichShapes: SQL = select * from states.

However, it discards the NULL geometry later:
msOGRFileNextShape: Rejecting feature (shapeid = 48, tileid=0) of incompatible type for this layer (feature wkbType 0, layer type 2)

**Comment by geographika** [comment]
Ran into a related issue today when attempting to output to GeoJSON, with some features created using: `geometry::STGeomFromText('POLYGON EMPTY', 3857)`

Error is `msOGRWriteShape(): General error message. Failed on odd polygon geometry` as there is a check for numlines [here](https://github.com/mapserver/mapserver/blob/9bb624f155b8fafbe680de218571f582b1e28347/mapogroutput.cpp#L380). 

From https://tools.ietf.org/html/rfc7946:

>       A GeoJSON Geometry object of any type other than
>       "GeometryCollection" has a member with the name "coordinates".
>       The value of the "coordinates" member is an array.  The structure
>       of the elements in this array is determined by the type of
>       geometry.  GeoJSON processors MAY interpret Geometry objects with
>       empty "coordinates" arrays as null objects.

A null output here rather than an error would be useful, but I'm not sure how empty geometries would be interpreted by other OGR outputs.

**Comment by jratike80** [comment]
Feels like resolved together with #6138 and #6731. Not bothered to test though.
