### ISSUE TITLE
No way to turn off partial labels via SLD

### ISSUE THREAD

**Issue by kungfujohnjon** [mapserver/mapserver#5198]
Even with setting label_cache_map_edge_buffer and labelcache ON for each layer, there seems to be no way in MapServer to turn off partial labels via SLD. The temporary map file produced when DEBUG is turned on shows that the LABEL block contains no PARTIALS line, and the schema definition for the TextSymbolizer block in mapogcsld.c seems to provide no ability to specify such an option. GeoServer handles this with the VendorOption element within the TextSymbolizer block to set styling options that are not part of the SLD spec (e.g. <VendorOption name="partials">false</VendorOption>), but another option would be to be able to set PARTIALS default behavior via CGI or during MapServer compilation.

**Comment by tbonfort** [comment]
I'm tempted to close this issue, as if SLD doesn't support the option, well, it doesn't support it :)
You should be able to override the partials with cgi commands try ```&map.layer[mylayer].class[myclass]=label+partials+false+end``` or ```&map.layer[mylayer].class[myclass].label=partials+false```. Or just set partials false in your mapfile.

**Comment by tbonfort** [comment]
and if you are OK to recompile, just set label->partials to MS_FALSE in mapfile.c->initLabel()

**Comment by kungfujohnjon** [comment]
SLD defined styles don't exist as classes until the temporary map file is made, so the first solution throws a "Class to be modified not valid" error right now. For future reference in case others run into this issue, this does in fact require modifying the source and recompiling.

**Comment by tbonfort** [comment]
FWIW if you want to make your case on the mapserver-dev mailing list, I'd be supportive of changing the default value of label->partials to false in the upcoming release. partial labels should be the exception, not the norm.

**Comment by tbonfort** [comment]
Applied to master in 590d51343eb
