### ISSUE TITLE
PHP mapscript 6.4 draw map with rotation and mask in a layer gives black picture

### ISSUE THREAD

**Issue by t1geomatika** [MapServer/MapServer#5204]
Hi, using mapscript 6.4.1 i try:

///////////////////////////
$map=ms_newMapObj($mapPath);
$map->setRotation($angle);
$map->zoomScale($scale,$center, $wCarto, $hCarto, $rect, $rect);
$mapImg = $map->draw();
///////////////////////////

When $angle != 0, the result is a black picture.
If $angle==0 no problems.
If I comment mask in my mapfile no problems.

This is an extract of my mapfile : 

```
LAYER
    NAME "scan1000"
    STATUS ON
    TILEINDEX "/data/ign/SCAN1000/scan1000.shp"
    TILEITEM "location"
    TYPE RASTER
    MINSCALEDENOM 245500
    MAXSCALEDENOM 50000000000000
            # This is causing trouble
    MASK "dep"
END

LAYER
    NAME "dep"
    STATUS OFF
    CONNECTION "user=u password=p dbname=ign host=localhost"
    CONNECTIONTYPE POSTGIS
    DATA "wkb_geometry from dep USING UNIQUE ogc_fid"
    TYPE POLYGON
    CLASS
        NAME ""
        TITLE "Masque"
        STYLE
            COLOR 0 0 0
        END
    END
END
```

**Comment by jratike80** [comment]
PHP mapscript is no more the same. Make a new ticket against currents MS and mapscript versions if needed.
