### ISSUE TITLE
Cluster Layers Failing with 7.0 Filter Translation

### ISSUE THREAD

**Issue by tbonfort** [mapserver/mapserver#5205]
The hijacking of ```layer->layerinfo``` by the clustering code is making requests after msLayerOpen to anything filter related fail due to that member being of the wrong type:

```
==14061== Conditional jump or move depends on uninitialised value(s)
==14061==    at 0x4F12E32: msPostGISParseData (mappostgis.c:1354)
==14061==    by 0x4F17D70: msPostGISLayerTranslateFilter (mappostgis.c:3642)
==14061==    by 0x4F4649B: msLayerTranslateFilter (maplayer.c:269)
==14061==    by 0x4F464E7: msLayerWhichShapes (maplayer.c:285)
==14061==    by 0x4F77E3F: msDrawVectorLayer (mapdraw.c:952)
==14061==    by 0x4F77517: msDrawLayer (mapdraw.c:795)
==14061==    by 0x4F75FE6: msDrawMap (mapdraw.c:384)
==14061==    by 0x4EC1F7D: msWMSGetMap (mapwms.c:3672)
==14061==    by 0x4EC71DB: msWMSDispatch (mapwms.c:5023)
==14061==    by 0x4ED9BD0: msOWSDispatch (mapows.c:286)
==14061==    by 0x4EE76E0: msCGIDispatchRequest (mapservutil.c:1712)
==14061==    by 0x40126F: main (mapserv.c:275)
```

this results in a segfault.

We also still have absolutely no autotests covering anything CLUSTER related, which is a pity because they would have caught that error...

**Comment by Manfred73** [comment]
Is this something that will be fixed in a future version? I found this posting: http://comments.gmane.org/gmane.comp.gis.mapserver.user/54973
and I'm running into the same issue.

**Comment by teeschke** [comment]
+1

**Comment by ErtanMG** [comment]
+2

**Comment by szekerest** [comment]
Fix is in branch-7-0

**Comment by Manfred73** [comment]
We are using a docker image of mapserver7 which is based on the master repository: https://github.com/pamtrak06/mapserver7-ubuntu14.04

Will this fix also be merged to master?

**Comment by tbonfort** [comment]
@Manfred73 it will make it's way in soon

**Comment by tbonfort** [comment]
let's close this one now, new issues about cluster+filter translations can be openened innew issues
