### ISSUE TITLE
Problem with mapsrcipt python

### ISSUE THREAD

**Issue by Namrod21** [mapserver/mapserver#5210]
Hi !

I am working with Mac OS X 10. 9 Mavericks, with Python 2.7.5 (default version) and Mapserver 7.0 compiled from source. I also installed the mapscript module for Python in the same time that Mapserver. The installation seems to be OK since this code works:

```python import mapscript```

However, I cannot use the RT MapServer Exporter module from QGIS, which produce an error:

``` File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/mapscript.py", line 99, in 
    MS_TRUE = _mapscript.MS_TRUE
AttributeError: 'module' object has no attribute 'MS_TRUE' ```

Any ideas about how I could solve this ?

**Comment by tbonfort** [comment]
This is better suited for the mailing list
