### ISSUE TITLE
I downloaded MapServer but can't find the application?

### ISSUE THREAD

**Issue by epyks23** [mapserver/mapserver#5211]
I downloaded the mapserver-7.0.0 from this website:
http://mapserver.org/download.html

I extracted the files but there are a lot of them (and many folders). What is the name of the application and in which folder does it reside?

**Comment by jratike80** [comment]
This is a bug tracker. Mapserver users mailing list is the right forum for asking questions and help may also be available from gis.stackexchange.com.

Mapserver is a cgi program and you need a http server, usually Apache, for running it. If you are on Windows I recommend to start with MS4W. This article should help if you run Linux http://paolocorti.net/2008/01/10/installing-mapserver-in-ubuntu/.
