### ISSUE TITLE
possible bug when specifying contour layer with tileindex

### ISSUE THREAD

**Issue by tomkralidis** [mapserver/mapserver#5212]
Using 6.4.1, when displaying a GRIB2 file via `CONNECTIONTYPE CONTOUR` combined with a `TILEINDEX`:

Request: 
http://localhost/cgi-bin/mapserv.exe?map=contour-tileindex/config.map&&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-69.31056534684074677,-180,90,180&CRS=EPSG:4326&WIDTH=1208&HEIGHT=535&LAYERS=RDPS.ETA_PN&STYLES=default&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

Response:
```xml
<?xml version='1.0' encoding="ISO-8859-1" standalone="no" ?>
<ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException>
msDrawMap(): Image handling error. Failed to draw layer named &#39;RDPS.ETA_PN&#39;.
msContourLayerOpen(): Image handling error. Unable to open GDAL dataset.
msBuildPath: Unable to access file. 
msBuildPath: Unable to access file. 
</ServiceException>
</ServiceExceptionReport>
```

When switching to a `DATA` directive directly to the GRIB2 file, the WMS request works.

Simple test case is provided at http://kralidis.ca/tmp/contour-tileindex.zip

**Comment by jrahkonen** [comment]
I can reproduse. Using absolute paths in tileindex did not help, neither renaming grib2 file to short "test.grib2".  Perhaps this output from shp2img has some meaning: ERROR 4: `0¨↑' does not exist in the file system

> C:\ms4w>shp2img -m c:\ms4w\apps\config.map -i png -o test.png -all_debug 5
> msLoadMap(): 0.000s
> msDrawMap(): rendering using outputformat named png (AGG/PNG).
> msDrawMap(): WMS/WFS set-up and query, 0.000s
> Entering msContourLayerOpen().
> msBuildPath: Unable to access file.
> msBuildPath: Unable to access file.
> ERROR 4: `0¨↑' does not exist in the file system,
> and is not recognised as a supported dataset name.

> msContourLayerOpen(): Image handling error. Unable to open GDAL dataset.
> msDrawMap(): Image handling error. Failed to draw layer named 'RDPS.ETA_PN'.
> msDrawMap(): Image handling error. Failed to draw layer named 'RDPS.ETA_PN'. <br>
> msContourLayerOpen(): Image handling error. Unable to open GDAL dataset. <br>
> msBuildPath: Unable to access file.  <br>
> msFreeMap(): freeing map at 05FFA3E8.
> freeLayer(): freeing layer at 07D8D398.
> Entering msContourLayerClose().
> freeLayer(): freeing layer at 07DAC890.

**Comment by rouault** [comment]
I've pushed a fix to raise an error when DATA isn't defined (as implied by http://mapserver.org/fr/development/rfc/ms-rfc-85.html). Tile-index are not supported in CONTOUR layers currently. You may have to use a GDAL VRT instead.
