### ISSUE TITLE
In the python mapscript is missing an option to set the VALIDATION block

### ISSUE THREAD

**Issue by aperi2007** [mapserver/mapserver#5221]
As in the subject:

In the python mapscript, almost reading the documentation, there isn't nothing able to set a VALIDATION block like this:

<pre>
VALIDATION
    	'idtpn' '^[a-zA-Z0-9\-_#]+$'
    	'default_idtpn' '%' 
END
</pre>

I dont know if this is a lack of documentation or a lack of python mapscript.

**Comment by tbonfort** [comment]
This isn't the only missing option. We don't have any mapscript maintainers so this is not unexpected.

**Comment by tbonfort** [comment]
validation is a hashtable that you can access like ```l.metadata```

```python
l=mapscript.layerObj
>>> l
<class 'mapscript.layerObj'>
>>> l.metadata
<property object at 0x7f55b49a29f0>
>>> l.validation
<property object at 0x7f55b49a2a48>
```
