### ISSUE TITLE
Filter default value integer

### ISSUE THREAD

**Issue by larsurilch** [mapserver/mapserver#5236]
Hello,

How to insert a default value for numeric fields in MapServer 7 ?
I tried to do using IN but it did not work.

```
PROCESSING "NATIVE_FILTER=(result ILIKE '%result%' AND stage IN (%stage%))"

VALIDATION
    'default_result' '%'
    'default_stage' '0,1'
END
```

Thanks

**Comment by sdlime** [comment]
@larsurilch, support questions should be taken to the mailing lists... --Steve
