### ISSUE TITLE
PHP Mapscript maplabel.c:166: msComputeTextPath: Assertion `ts->annotext && *ts->annotext' failed.

### ISSUE THREAD

**Issue by akrherz** [mapserver/mapserver#5240]
Using the current 7-0 branch build, PHP mapscript will core dump when attempting to draw a point with an "empty" label

`$pt->draw($map, $barbs, $img, 0, "");`

I am attaching a reproducer
[ms.zip](https://github.com/mapserver/mapserver/files/129119/ms.zip)

**Comment by tbonfort** [comment]
Fixed in 5a83df5
