### ISSUE TITLE
Blurry labels

### ISSUE THREAD

**Issue by rbovard** [mapserver/mapserver#5242]
After migrating to MapServer 7, I noticed that the labels are now a little blurry.

![ms6](https://cloud.githubusercontent.com/assets/4549666/13080910/012007be-d4cb-11e5-908f-32f7132f6147.png)

![ms7](https://cloud.githubusercontent.com/assets/4549666/13080915/0446bf1e-d4cb-11e5-8066-7bf8334e11ce.png)

Is this related to https://github.com/mapserver/mapserver/issues/4673? And if yes, is there a way to fix this in my `LABEL` definition:

```
LABEL
    TYPE         TRUETYPE
    FONT         "arial_b"
    SIZE         8
    ANTIALIAS    TRUE
    COLOR        255 255 255
    OUTLINECOLOR 243 70 72
    OUTLINEWIDTH 1
    POSITION     CC
    ALIGN        CENTER
    OFFSET       0 8
    WRAP         " "
    MAXLENGTH    8
END
```

Thank you in advance!

**Comment by tbonfort** [comment]
Some may argue that the agressive hinting that was used in versions prior to 7.0 was an issue and that the softer rendering that is here now is better. Closing. If you have a strong argument that the current rendering is a bug, and/or you are willing to champion the ability to configure this behavior, we can revisit.
