### ISSUE TITLE
PHP Mapscript can't set `type` on `labelObj`

### ISSUE THREAD

**Issue by akrherz** [mapserver/mapserver#5250]
[This email list post](http://lists.osgeo.org/pipermail/mapserver-users/2015-October/078289.html) denotes a PHP Mapscript7 issue with attempting to set `type` on `labelObj`. I am currently using a master build of mapserver and this fails.

```php
$lbl = new labelObj();
$lbl->set("type", MS_TRUETYPE);
```

PHP Fatal error:  Uncaught exception 'MapScriptException' with message 'Property 'type' does not exist in this object.  Thanks

**Comment by tbonfort** [comment]
This is a documentation issue. label->type was removed in 7.0 (all labels are now truetype)

**Comment by akrherz** [comment]
@tbonfort thanks for the quick help and sorry that my non-related code tree commit comment came back to this ticket, I'll refrain from that in the future!

**Comment by tbonfort** [comment]
no worries @akrherz

**Comment by tbonfort** [comment]
documented. closing
