### ISSUE TITLE
Issue between map_angle query string and ANGLE in the symbole

### ISSUE THREAD

**Issue by sbrunner** [mapserver/mapserver#5271]
Use mapserver version: 7.0.0

And we have the following results:
![7c9644a0-6e59-11e4-9e83-bd1d5c108558](https://cloud.githubusercontent.com/assets/353872/14344012/16129b94-fca5-11e5-92df-75731af68961.png)

Class definition:

```
    CLASS
        NAME "Manchon"
        EXPRESSION "ma"
        STYLE
            SYMBOL "eau_manchon"
            SIZE   5
            ANGLE  [orientation]
        END
    END
```

See also: https://github.com/camptocamp/c2cgeoportal/issues/1136

Thanks in advance

**Comment by tbonfort** [comment]
Looking through the code I believe there are quite a few places where the map rotation is ignored and/or incorrectly applied. The feature was mostly intended for raster data, and the support for it is minimal on the vector side. I'm available for contracting if this support on the vector side is important for you.

**Comment by sbrunner** [comment]
OK, thanks for the investigations :-)

**Comment by tbonfort** [comment]
see #1135 for the initial discussions around this

**Comment by rbovard** [comment]
Is there any chance to see this issue addressed? Or it still need a specific dev for it?

**Comment by sdlime** [comment]
Thomas isn't particularly active at the moment so I don't think we're going to see action without someone getting excited about fixing - it's not a feature I've ever used. I wish we had Thomas' exploratory notes on the topic. Patches gratefully accepted...

**Comment by sbrunner** [comment]
@rouault can we close this issue?

**Comment by rbovard** [comment]
Thanks a lot, it's working fine.
