### ISSUE TITLE
drawLegendIcon from mapscript should recalculate scale factor

### ISSUE THREAD

**Issue by szekerest** [mapserver/mapserver#5287]
Currently the scale factor of the previous drawing operation is considered when drawing the symbols in the legend image. This is not sufficient when symbolscale is used, the legend icon size should be independent from the actual zoom (scale),

**Comment by szekerest** [comment]
This issue is related to https://github.com/mapserver/mapserver/issues/1147

**Comment by tbonfort** [comment]
This was applied to branch-7-0, closing
