### ISSUE TITLE
WMS blank for classified raster with NaN

### ISSUE THREAD

**Issue by blazek** [mapserver/mapserver#5289]
In 7.0.1, WMS renders blank image if a classified raster has NaN values  and SCALE is not specified even if GDAL gives correctly NaN as nodata value.

The problem is that when min/max is calculated in mapdrawgdal.c, it skips nodata:
```
if( bGotNoData && pafRawData[i] == fNoDataValue )
    continue;
```
but not NaN which must be tested with isnan(). The result is min = max = NaN and blank image.
Here is my simple quick fix:
```
--- mapdrawgdal.c.orig  2016-06-03 09:42:03.007425561 +0200
+++ mapdrawgdal.c       2016-06-03 09:41:35.923290945 +0200
@@ -1270,6 +1270,9 @@
         if( bGotNoData && pafRawData[i] == fNoDataValue )
           continue;
 
+        if isnan( pafRawData[i] )
+            continue;
+
         if( !bMinMaxSet ) {
           dfScaleMin = dfScaleMax = pafRawData[i];
           bMinMaxSet = TRUE;
@@ -1764,6 +1767,9 @@
     if( bGotNoData && pafRawData[i] == fNoDataValue )
       continue;
 
+    if isnan( pafRawData[i] )
+        continue;
+
     if( !bGotFirstValue ) {
       fDataMin = fDataMax = pafRawData[i];
       bGotFirstValue = TRUE;
```

but a macro/function which tests both nodata value and NaN would be better. There are probably more places in mapserver where NaN is not correctly handled.

**Comment by rouault** [comment]
That's reasonable. Would you mind making a pull request for this  ? I'd suggest using CPLIsNan(), from GDAL headers, for portability.

**Comment by blazek** [comment]
But GDAL is not requirement, it is optional.

**Comment by rouault** [comment]
All code in mapdrawgdal.c is after #if defined(USE_GDAL) so no problem using CPLIsNan()
