### ISSUE TITLE
CLOSE_CONNECTION=ALWAYS not working correctly for raster layers?

### ISSUE THREAD

**Issue by AsgerPetersen** [mapserver/mapserver#5295]
I have a pretty simple fastcgi WCS service pointing to a master VRT-file which in turn points to some tiff files:

```
master.vrt
 |-a.tif
 |-b.tif
```

What makes this setup unusual is that `a.tif` and `b.tif` may be replaced by a new version of the file at any time. The new file is equivalent in terms of bbox, resolution, datatype etc. Just the actual pixel values are different. However the new file may have a different tiff structure (block size, compression etc).

When running this in CGI mode everything works nicely.

Running it in fastcgi things start to break when files get replaced. Mapserver returns errors like `drawGDAL(): Unable to access file. GDALDatasetRasterIO() failed: /mapserver/data/a.tif, band 1: IReadBlock failed at X offset 6, Y offset 20`

I am guessing this is because of mapserver is reusing the GDAL dataset between requests. So, I have tried adding `PROCESSING "CLOSE_CONNECTION=ALWAYS"` ([code](https://github.com/mapserver/mapserver/blob/cb0cb44eea8fc5738231fd556a453655a8ea73a2/mapraster.c#L790-L807)) to the WCS layer, but it still fails with the `IReadBlock failed` error message after a file is replaced.

Is `PROCESSING "CLOSE_CONNECTION=ALWAYS"` not working correctly or have I misunderstood what it does?

**Comment by AsgerPetersen** [comment]
I realized that of course block size shouldn't change because it should match the value stated in the VRT file. This is what has been fooling me.Closing the issue.

Fun fact: Replacing with a file with another block size makes fcgi mapserver go boink even with `"CLOSE_CONNECTION=ALWAYS"`. BUT if the server is then restarted mapserver WILL read the file correctly.

**Comment by jmckenna** [comment]
This made me notice that the docs don't reference CLOSE_CONNECTION=ALWAYS !  Adding now.  So your efforts are not wasted :)

**Comment by rouault** [comment]
The fact that changing block size of the sources of a VRT, and even changing any TIFF or VRT file while it is opened, causes issues is expected.
But I can't explain why "CLOSE_CONNECTION=ALWAYS" wouldn't work. I've run mapserv binary in standalone mode and looked at MapServer & GDAL traces and I can see the VRT & TIFF closed at the place you pointed, so they shouldn't be re-used between 2 FCGI requests. Hum...

**Comment by AsgerPetersen** [comment]
@rouault Thank you very much for looking into this! It is very nice to know that it _should_ work.

Side note: It would have been nice to have a debug level 5 log entry telling me that the dataset is being closed. I would like to rule out configuration problems and I am having a hard time verifying that it actually is closed.

**Comment by rouault** [comment]
You should be able to enable GDAL debug with CONFIG "CPL_DEBUG" "ON" (or as environement variable)

**Comment by AsgerPetersen** [comment]
Cool. Thanks! I wasn't thinking of using GDALs debugging capabilities.
