### ISSUE TITLE
Mapserver with java code project. Is real?

### ISSUE THREAD

**Issue by ArtemGits** [mapserver/mapserver#5304]
Hello. Please tell me if I could use mapserver project written in Java code. There is some java api? How to do it? Can you give a link to some examples?

Thank you.

**Comment by sdlime** [comment]
@ArtemGits, this really isn't the spot for support requests or questions. You should take your question to the MapServer-Users list (see http://mapserver.org/community/lists.html) where multiple individuals can reply. You're interested in Java MapScript in particular... 

Steve
