### ISSUE TITLE
Multi Line Label will not ALIGN when using a WRAP character

### ISSUE THREAD

**Issue by tyler541** [mapserver/mapserver#5309]
When a WRAP character is specified the label text is split onto multiple lines
but there is no way to specify how to align the lines of text, i.e. left, center
or right. For example the following string in the LABELITEM field:

United States*of America

always produces the label like this:
```
United States
of America
```

What I really want is something like this:
```
United States
 of America
```
I have tried using True type fonts as well as monospaced, but cannot get my labels to Center.

**Comment by sdlime** [comment]
What version of MapServer? What does your label block look like?

Steve

**Comment by tyler541** [comment]
MapServer version: 6.4

Here is the LABEL block:

      TEXT "N/F![owner1]![owner2]"
      LABEL
        WRAP "!"
        ANGLE AUTO
        ANTIALIAS true
        FONT "arial"
        SIZE 7
        TYPE truetype
        COLOR 0 0 0
        FORCE false
        ALIGN center
        OUTLINECOLOR 255 255 255
        PARTIALS false
        POSITION cc
      END

I have tried monospaced fonts such as courier as well as the true types, but no luck.

**Comment by tbonfort** [comment]
6.4 wraps/aligns at the character level, which may produce incorrect results with non monospaced fonts and/or line length combinations. v 7.0 aligns at the pixel level, so you'll probably want to upgrade to that.

**Comment by tyler541** [comment]
TEXT "N/F![owner1]![owner2]"
      LABEL
        WRAP "!"
        ANGLE AUTO
        ANTIALIAS true
        FONT "courier"
        SIZE 7
        #TYPE truetype
        COLOR 0 0 0
        FORCE false
        ALIGN center
        OUTLINECOLOR 255 255 255
        PARTIALS false
        POSITION cc
      END

Still same results

**Comment by tyler541** [comment]
Is there a way to center multi line labels on version 6.4?
