### ISSUE TITLE
The WFS request add always a spatial filtering to the query sql.

### ISSUE THREAD

**Issue by aperi2007** [MapServer/MapServer#5316]
Hi,
I notice the mapserver wfs when retrieving the data (I tested it using OGR provider and spatialite format for db) add always the casting to the query sql.

From the log of mapserver (debug 5 on layer)
I retrieve the filter applied to the dataset:
`
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ows="http://www.opengis.net/ows" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:gml="http://www.opengis.net/gml" handle="GeoTools PO11.x.1 WFS DataStore" maxFeatures="1000" outputFormat="text/xml; subtype=gml/3.1.1" resultType="results" service="WFS" version="1.1.0">
 <wfs:Query srsName="urn:ogc:def:crs:EPSG::6707" typeName="rt_cat.idcatpart.bbox.rt">
  ogc:Filter
   ogc:And
    <ogc:PropertyIsLike escapeChar="!" matchCase="false" singleChar="?" wildCard="%">
     ogc:PropertyNamecomune/ogc:PropertyName
     ogc:Literal%FIRENZE%/ogc:Literal
    /ogc:PropertyIsLike
    <ogc:PropertyIsEqualTo matchCase="true">
     ogc:PropertyNamefoglionum/ogc:PropertyName
     ogc:Literal4/ogc:Literal
    /ogc:PropertyIsEqualTo
    <ogc:PropertyIsEqualTo matchCase="true">
     ogc:PropertyNameparticella/ogc:PropertyName
     ogc:Literal1/ogc:Literal
    /ogc:PropertyIsEqualTo
   /ogc:And
  /ogc:Filter
 /wfs:Query
/wfs:GetFeature

`The filter in ogr language , as reported from the log is this:

`
FLTLayerApplyPlainFilterToLayer():  ( ("[comune]" ~\* "._FIRENZE._") And ( ([foglionum] =4) And ([particella] =1)) ) , rect=529998.608791,4664917.066756,799986.281320,4949981.407214

`

And finally the query sql corresponding and applied to the db is this:
`
msOGRFileWhichShapes: SQL = SELECT ROWID AS msFID, \* FROM PARTICELLEBB WHERE (((CAST("comune" AS text) LIKE '%FIRENZE%') AND ((CAST("foglionum" AS REAL) = 4.000000) AND (CAST("particella" AS REAL) = 1.000000)))) AND PARTICELLEBB.ROWID IN (SELECT ROWID FROM SpatialIndex WHERE f_table_name = 'PARTICELLEBB' AND f_geometry_column = 'bbox' AND search_frame = GeomFromText('POLYGON((1529999.980909 4664923.376323,1800000.190426 4664923.376323,1800000.190426 4950073.173287,1529999.980909 4950073.173287,1529999.980909 4664923.376323))')).

`

As noticeable the query sql produced from mapser is adding a spatial filter to the BBOX of the dataset.

I dont understand why add this if the query filter in the request is not apply-ing any explicit data filter.

The time are very different because.
The query sql using the spatial filter (on an huge dataset) on dataset bbox take about 24 seconds to end.
Instead the query without the spatial filter but with the alphanumeric filters take about 0.01 seconds.

`
SELECT ROWID AS msFID, \* FROM PARTICELLEBB WHERE (((CAST("comune" AS text) LIKE '%FIRENZE%') AND ((CAST("foglionum" AS REAL) = 4.000000) AND (CAST("particella" AS REAL) = 1.000000))));

`

**Comment by jratike80** [comment]
The default filter can be removed with

> wfs_use_default_extent_for_getfeature
> 
> (Optional, since MapServer 7.0.4) Whether the MAP.EXTENT should be used in request to datasources in the absence of other spatial filter. This is the default behaviour, but this might affect performance in some use cases. In those cases, setting this item to “false” will avoid he default spatial filter to be appended to the request. This is only implemented for OGR datasources (since 7.0.4) and MSSQL2008 connections (since 7.6)
