### ISSUE TITLE
mapfile.c: hashTableSubstituteString leaks memory

### ISSUE THREAD

**Issue by gogglesguy** [mapserver/mapserver#5325]
For the line:

msInsertHashTable(hash, key, msCaseReplaceSubstring(msStrdup(val), from, to));

The result of msCaseReplaceSubstring is never freed. HashTable stores a copy of it.

**Comment by tbonfort** [comment]
Can you create a pull request/patch for this please ?

**Comment by gogglesguy** [comment]
Something along the lines of this:
https://gist.github.com/gogglesguy/10c9745c98adff0bbd0ba93f777bf209

**Comment by tbonfort** [comment]
Perfect! If you want your name in the commit logs create a pr with that, if not i'll apply myself. Thanks.

**Comment by gogglesguy** [comment]
Just apply it!

**Comment by tbonfort** [comment]
applied to branch-7-0, thanks @gogglesguy
