### ISSUE TITLE
[featurerequest] ability to sort data coming from postgis for WMS

### ISSUE THREAD

**Issue by landryb** [mapserver/mapserver#5337]
Looking at the code, it seems sortBy is only used when a particular sorting order is passed by a WFS filter. It would be nice to pass an sql-like sort order to DATA statements so that data returned by postgis is sorted.

Usecase: with a TILEINDEX layer where the data comes from postgis, i have areas where several tiles are overlayed on top of each other (different times for aerial pictures) - so far, the order in which the tiles are used by mapserver depends on the internal-non-consistent order inside postgresql. I'd like to be able to say `DATA "the_geom from rtge.ortho using unique gid using srid=2154 order by my_date asc"`.

Right now, i have to manually set an `enabled` boolean on the tiles i know i want 'on top' and do `FILTER "enabled=1"` in the mapfile, which is passed to the sql query built by mapserver (but that wont work for tiles that are not of the same size/area...). The way the query is built doesnt allow to pass 'arbitrary SQL' to postgis.... unless i missed something in the doc on how to achieve this.

**Comment by msmitherdc** [comment]
You can do this now. Just do

`DATA "the_geom from (select the_geom from rtge.ortho order by my_date asc) using unique gid using srid=2154 "`

**Comment by msmitherdc** [comment]
You can pass arbitrary sql see http://mapserver.org/input/vector/postgis.html

**Comment by landryb** [comment]
Ah, thanks, now i feel stupid :) I had overlooked that possibility, will try.

**Comment by sdlime** [comment]
You should be able to this now using runtime substitution. Something like:

  DATA "mygeom from (select * from table order by %sort%) ..."
   
And then you'd set a validation value on the sort parameter to limit valid values. You could also set a default value in the mapfile.

Steve

________________________________________

**Comment by landryb** [comment]
Since that definitely works, should this issue become a 'this should be a documented example' PR ?

**Comment by jratike80** [comment]
Documentation may not be perfect but I close this feature request anyway. Doc issues are tracked elsewhere.
