### ISSUE TITLE
label text size with fractional value is converted to integer in mapserver 7

### ISSUE THREAD

**Issue by tomhel** [mapserver/mapserver#5339]
The documentation states that fractional values are supported on label size: http://mapserver.org/mapfile/label.html
However, looking at mapserver.h, the labelObj struct declares size as integer instead of double. Is this a bug or is the documentation not updated to reflect this change?

**Comment by tbonfort** [comment]
@tomhel correct, it's a documentation bug. The font renderer (freetype) will (AFAIK) only accept integer sizes, so there's no point in having the size be set as doubles.

**Comment by jmckenna** [comment]
@tomhel can you open a doc ticket in /mapserver/docs/ for this?

**Comment by jmckenna** [comment]
Indeed as the docs state, MapServer 5.4 did allow label size as a double: https://github.com/mapserver/mapserver/blob/rel-5-4-2/mapserver.h#L610

**Comment by jmckenna** [comment]
The latest release supporting label size as double was 6.4.3 release (https://github.com/mapserver/mapserver/blob/rel-6-4-3/mapserver.h#L1004)  MapServer 7.0.0 release apparently removed that.  I'll mention this in the docs.   Sorry for the noise.

**Comment by tbonfort** [comment]
No need to mention it. The parser accepted doubles but they were always silently converted to int.

**Comment by jmckenna** [comment]
ah ok I understand, thanks @tbonfort

**Comment by tomhel** [comment]
@tbonfort @jmckenna Ok, I see. Thanks for the fast response.

**Comment by jmckenna** [comment]
docs have been updated.
