### ISSUE TITLE
OPACITY not working with GetMap Requests for 7.0.2

### ISSUE THREAD

**Issue by jmckenna** [mapserver/mapserver#5343]
- small mapfile (and data and commands) to reproduce problem: http://gatewaygeomatics.com/dl/ticket-opacity-wms.zip (400 KB)

 - no problems using normal CGI

 - however, using 7.0.2 opacity is not applied for a GetMap request

 - GetMap output for 7.0.1 (notice parks polygons are transparent)
![mapserv1](https://cloud.githubusercontent.com/assets/1611709/19867792/02e9eb4e-9f84-11e6-884c-c00fb6f7ffbe.png)

 - GetMap output for 7.0.2 (parks polygons are not transparent)
![mapserv2](https://cloud.githubusercontent.com/assets/1611709/19867840/30c13978-9f84-11e6-9e5b-70511356b8f8.png)

 - interesting, if I try to execute the same GetMap request at the commandline....

```
mapserv -nh QUERY_STRING="MAP=opacity-wms.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=50.43646181818179741,-137.2127006060605936,81.69507636363634617,-85.115009696969679&CRS=EPSG:4326&WIDTH=990&HEIGHT=594&LAYERS=bathymetry,park&STYLES=,&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE%20HTTP/1.1" > test.png
```
the following message is returned (only with 7.0.2), and a map image without transparency is generated:
```
*** BUG ***
In ???: The expression bits == NULL || (rowstride_bytes % sizeof (uint32_t)) == 0 was false
Set a breakpoint on '_pixman_log_error' to debug
```

**Comment by rouault** [comment]
@jmckenna Your request for me with latest state of branch-7-0 (so nearly identical to 7.0.2) on Linux with cairo-1.10.2 (the polygons are transparent both in standalone mode "mapserv -nh" or within mongoose web server).
Running it under Valgrind doesn't show any problem reported. Reviewing (quickly) changes between 7.0.1 and 7.0.2, nothing strikes as being related. Could it be that something else than MapServer changed between your 7.0.1 and 7.0.2 build, like the cairo version used ?

Hum, I just found https://github.com/mapserver/mapserver/issues/5181 which seems related. Is it possible that your build have pixman enabled ? (my build has pixman disabled)

**Comment by jmckenna** [comment]
Indeed my builds have pixman enabled

**Comment by jmckenna** [comment]
wow good find that related issue even has similar error message

**Comment by jmckenna** [comment]
i will disable pixman and report back....

**Comment by jmckenna** [comment]
@rouault that was it! disabling pixman gives the proper map image, and no more error at the command.   yikes!

I guess this is a 'won't fix', but wow many will hit it with pixman in their builds.

**Comment by elzouavo** [comment]
Pixman is an CAIRO library dependency. I've compiled MapServer with Cairo. So I've got this issue. I think more and more people are going to use Cairo. So this problem will become increasingly embarrassing for the community. But I could be wrong ;-)

**Comment by jmckenna** [comment]
Here again.  I wonder if for MapServer 7.6.0 we should either 1) fix Pixman support, or 2) completely remove Pixman from the MapServer codebase.   I'm open to hearing thoughts on either option.
