### ISSUE TITLE
WFS GetFeature with attribute filter is null when "EXTENT" is not set

### ISSUE THREAD

**Issue by matrottier** [MapServer/MapServer#5344]
System : 
Ubuntu 16.04  
Mapserver 7.0.2
PostgreSQL 9.3.14 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit
Postgis 2.1 

Description : 
mapfile without 'extent' tag give nothing on a WFS getFeature request WITH a attribute filter.  
maybe it's related to #5316, because the spatial intersection contain a polygon with coordinate near one.  
example of the SQL from PG log: 
```sql
select * 
    from dpop_criminalite_generale_v_s 
    where geom_s && ST_GeomFromText('POLYGON((-0.999999999977581   -0.999999700236674,-0.999999999977581 -0.999999700236674,-0.999999999977581   -0.999999700236674,-0.999999999977581 -0.999999700236674,-0.999999999977581   -0.999999700236674))',find_srid('','dpop_criminalite_generale_v_s','geom_s')) 
    
```
In my test, i saw different polygon when i changed the order of the "wfs_srs" in the METADATA of the layer.   
Without the attribute filter, the GetFeature request is working and i saw in the PG log a "st_extent" of the layer and the intersection is OK
 
Set the EXTENT with the projection of the EXTENT fix the problem.

**Comment by jratike80** [comment]
Closing even I am not totally sure if there could be something worth keeping the issue open.
