### ISSUE TITLE
Are there plans for MINGW64 builds of Mapserver?

### ISSUE THREAD

**Issue by lixuzhang** [mapserver/mapserver#5345]
Please consider a MINGW 64 build for future releases, thank you.
https://github.com/Alexpux/MINGW-packages

**Comment by tigerfoot** [comment]
You could have 64 bits mapserver with osgeo4win installer

**Comment by jratike80** [comment]
Closing because the Mapserver project do not make builds. Re-open if source code can't be compiled with MINGW64.
