### ISSUE TITLE
Default Map Size too small

### ISSUE THREAD

**Issue by geographika** [mapserver/mapserver#5349]
Currently the maximum image size default is set to 2048 pixels. With increasingly large monitors and higher resolutions I keep hitting this limit when maximising browser windows, and getting an error message. 

It is confusing to new users, and requires having to always add a ``MAXSIZE 4096`` line to each new map file. 

I'd propose increasing the default to 4096. Users concerned about increased stress on their servers are more likely to know how to change this setting, than new users getting an error. 

I believe it should be a case of simply increasing the following?

`#define MS_MAXIMAGESIZE_DEFAULT 2048`

https://github.com/mapserver/mapserver/blob/66309eebb7ba0dc70469efeb40f865a8e88fafbd/mapserver.h#L262

It was last updated in 2003 - so hopefully most hardware has been updated since then..

**Comment by dmorissette** [comment]
I agree with your logic and would be +1 on increasing the default. Let's see what other devs think.

**Comment by tomkralidis** [comment]
+1, it's time.

**Comment by jmckenna** [comment]
+1 fully agree

**Comment by jmckenna** [comment]
Thanks @geographika !

(also filed a docs ticket for this: mapserver/docs/issues/162 )

**Comment by jmckenna** [comment]
also updated the related msautotest files.

**Comment by jmckenna** [comment]
docs updated.
