### ISSUE TITLE
RGB notation result in no colors 

### ISSUE THREAD

**Issue by ermoll** [mapserver/mapserver#5351]
"I've got a strange issue occuring when I dynamicly add a layerstyle using mapscript_csharp.dll 
..passing cls
  styleObj style style = new styleObj(cls);
  style.angle =360;
  style.width = 10;
  style.outlinecolor = _outlineColor.ToColorObj(); //RGBA color setting 128 0 128 0
  style.outlinewidth = 10;
...
results in Class string: 
 STYLE
	  ANGLE 360
	  OUTLINECOLOR \"#80008000\"
	  OUTLINEWIDTH 10
	  WIDTH 10
    END # STYLE

PS: Same apply for setting RGB colors on  BACKGROUNDCOLOR and COLOR.

generated :
"STYLE  ANGLE 360  OUTLINECOLOR "#c80008000"  OUTLINEWIDTH 10  WIDTH 10 END # STYLE"
"STYLE  ANGLE 360  BACKGROUNDCOLOR "#bfeeff00" END # STYLE"
"STYLE  ANGLE 360  OUTLINECOLOR "#66330000"  OUTLINEWIDTH 8  WIDTH 8 END # STYLE"

When getting the image from the map I get no colors at all !

but when I alter the style text to : 
"STYLE  ANGLE 360  OUTLINECOLOR 128 0 128  OUTLINEWIDTH 10  WIDTH 10 END # STYLE"
"STYLE  ANGLE 360  BACKGROUNDCOLOR 191 238 255 END # STYLE"
"STYLE  ANGLE 360  OUTLINECOLOR 102 51 0  OUTLINEWIDTH 8  WIDTH 8 END # STYLE"

it works fine.

I'm using mapscript_csharp.dll version 1.0.5970.20102

OSGeo.MapServer.mapscript.msGetVersion() = 
"MapServer version 7.0.1 (MS4W 3.1.4) OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=FASTCGI SUPPORTS=THREADS SUPPORTS=GEOS INPUT=JPEG INPUT=POSTGIS INPUT=ORACLESPATIAL INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE"
OSGeo.MapServer.mapscript.msGetVersionInt()   =  70000

map driver: "AGG/PNG"

Maybe I'm missing something here, like some basic settings for acceptence of the RGB notation.
why is RGB  notation not accepted when this is generated by cscript dll ?

PS:
Also strange is that in http://mapserver.org/mapfile/style.html#style definition it says that 
>>
BACKGROUNDCOLOR [r] [g] [b] - deprecated  since 6.2
<<
in conjunction with the 
http://mapserver.org/mapscript/mapscript.html#styleobj documentation clearly state the use of RGB colors.
Where the backgroudcolor element is still in the layerstyle object of mapscript dll of 7.0.2   but deprecated feature of mapfile ?

**Comment by tbonfort** [comment]
You don't detail how you're setting the colorObj... you should set alpha=255 for the color to appear (you set it to 0)

**Comment by ermoll** [comment]
you're right...the color definition was inhereted from other object where alpha was initialized as 0 instead of 255. Assumed that that was correct, but was not overrided when used for Style coloring.
Tnxs for the solution !
