### ISSUE TITLE
Not a single demo site on the MapServer list in community section works. 

### ISSUE THREAD

**Issue by anakaine** [mapserver/mapserver#5359]
New user: fired up MapServer home page, went looking for demos, found this: https://github.com/mapserver/mapserver/wiki/MapServer-Site-Gallery

Not a single referenced site works.

**Comment by sdlime** [comment]
The compass site is still functioning. The technology stack needs an update but it's still using MapServer and also MapCache Openlayers, Leaflet and PostGIS.

The next two by Alexandre Lagache are definitely stale and should be removed.

The Danish site link is also stale but looking at the parent site (http://www.geus.dk/UK/data-maps/Pages/default.aspx) there are lots of interesting apps there that seem to have at least some dependence on MapServer and/or MapScript. Needs update...

The ship location site is still working albeit painfully slow.

The Canadian weather WMS site is still working and uses 7.x...

Steve

**Comment by yjacolin** [comment]
I added one. @sdlime is it possible to make some improvment in this page, like URL, header, etc ?

**Comment by sdlime** [comment]
I updated the compass entry and added another for the mobile version of the same application. I also removed the two obviously dead sites. I don't know about changing the URL, I just not sure where all it might be referenced. Other improvements would be most welcome as it's a community driven page. What did you have in mind? --Steve

**Comment by jmckenna** [comment]
Absolutely community driven.  I have several times tried to get the community to edit this.  Will again send to the -users list, and hope we can get updates.

**Comment by jmckenna** [comment]
@yjacolin please do add whatever you like onto the page (there is already a footer image); all improvements are welcome, please edit it directly :)

**Comment by jmckenna** [comment]
- fixed formatting of all entries
- reordered by site name
- removed all broken entries (we're down to  4)
- will add a couple and send to -users for all of community for contributions

**Comment by jmckenna** [comment]
- added several more sites

**Comment by jmckenna** [comment]
@anakaine thanks for reporting this.  Much appreciated!
