### ISSUE TITLE
MapServer WFS Request via POST

### ISSUE THREAD

**Issue by byshine** [mapserver/mapserver#5366]
Using Mapserver 6.0.1

>     "<GetFeature                    
>     service="WFS"                    
>     version="1.1.0"                    
>     srsName="EPSG:900913"                    
>     xmlns:topp="http://www.openplans.org/topp"
>     xmlns:wfs="http://www.opengis.net/wfs"
>     xmlns:ogc="http://www.opengis.net/ogc"                    
>     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>     xsi:schemaLocation="http://www.opengis.net/wfs                     
>     http://schemas.opengis.net/wfs/1.0.0/WFS-basic.xsd">                    
>     <Query typeName="clc_he_site_e" srsName="EPSG:900913">                        
>     <Filter>
>     <Intersects>
>     <PropertyName>the_geom</PropertyName>
>     <Point srsName="EPSG:900913">
>     <coordinates>-13898086.230923885,6532736.454751344</coordinates>
>     </Point>
>     </Intersects>
>     </Filter>                   
>     </Query>                
>     </GetFeature>"

The following WFS Request works flawlessly, but does not in
Mapserver 6.4.1

>     <HTML>
>     <HEAD><TITLE>MapServer Message</TITLE></HEAD>
>     
>     <BODY BGCOLOR="#FFFFFF">
>     mapserv(): Web application error. Traditional BROWSE mode requires a TEMPLATE in the WEB section, but none was provided.
>     </BODY></HTML>

Anyone know why?

**Comment by jmckenna** [comment]
please send your questions direct to the mapserver-users mailing list: subscribe at https://lists.osgeo.org/listinfo/mapserver-users
