### ISSUE TITLE
OGR error messages too verbose on msBuildPath() too.

### ISSUE THREAD

**Issue by KiMaBa** [mapserver/mapserver#5368]
I am refering to this post on stackoverflow (http://gis.stackexchange.com/questions/219426/mapserver-hide-ogr-exception) which was taken as a bug report and fixed in v 7.0.3
https://github.com/mapserver/mapserver/pull/5356

The problem is that it seems that it is only fixed for msOGRFileNextShape() errors.
I get the same output, revealing the login info and sql statement through msBuildPath(): 

```
msDrawMap(): Image handling error. Failed to draw layer named &#39;Example_Layer&#39;.
msOGRFileNextShape(): OGR error. OGR GetNextFeature() error&#39;d. Check logs.
Unable to access file. (/etc/mapserver/&lt;OGRVRTDataSource&gt;
&lt;OGRVRTLayer name=&#39;example_data&#39;&gt;		&lt;SrcDataSource&gt;MYSQL:....,user=......,password=......,host=.....,port=.....,tables=.....&lt;/SrcDataSource&gt;&lt;SrcSQL&gt;SELECT...................
&lt;/OGRVRTDataSource&gt;): path is too long
msBuildPath: Unable to access file. 
msBuildPath(): Unable to access file. ((null)&lt;OGRVRTDataSource&gt;..........
```
*removed the sql-statement and other private data

Mapfile:
```
CONNECTIONTYPE OGR
CONNECTION "<OGRVRTDataSource>
		.......
</OGRVRTDataSource>"		
DATA "example_data"
```

CONFIG MS_ERRORFILE is set and Debug is OFF and its still revealing everything :(
I think it mistakes the text as a file path as it is possible to define a file here and therefore it prints everything. But i need to define my sql statement inside the mapfile to use runtime-substitution inside my sql-statement.

**Comment by jmckenna** [comment]
I tried to reproduce with an <OGRVRTDataSource> to PostgreSQL/PostGIS, but the connection details are not shown.
```
msDrawMap(): Image handling error. Failed to draw layer named 'provinces'. <br>
msOGRFileNextShape(): OGR error. OGR GetNextFeature() error'd. Check logs. <br>
```
Hmm.  I wonder why yours has a path of /etc/mapserver/ ??

**Comment by jmckenna** [comment]
ah I can reproduce if I put a long text of junk into the connection:
```
  CONNECTION '<OGRVRTDataSource><OGRVRTLayer name="myprovince"><SrcDataSource>PG:host=127.0.0.1 user=postgres password=postgres port=5431 dbname=gmap</SrcDataSource><SrcLayer>province</SrcLayer></OGRVRTLayer>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx8xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</OGRVRTDataSource>'
```
gives:
```
msDrawMap(): Image handling error. Failed to draw layer named 'provinces'. <br>
msOGRFileNextShape(): OGR error. OGR GetNextFeature() error'd. Check logs. <br>
msBuildPath(): Unable to access file. (C:\ms4w\apps\ticket-5368-ogr-verbose\map/.\<OGRVRTDataSource><OGRVRTLayer name="myprovince"><SrcDataSource>PG:host=127.0.0.1 user=postgres password=postgres port=5431 dbname=gmap</SrcDataSource><SrcLayer>province</SrcLayer></OGRVRTLayer>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx8xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</OGRVRTDataSource>): path is too long <br>
```

**Comment by jmckenna** [comment]
I honestly don't know how msBuildPath() would prevent this?   Anyone else have any thoughts??

**Comment by rouault** [comment]
@kimaba I don't think that the credentials displayed in the server log are a problem. The issue is if they are found in a XML error sent back to the client. Is it the case here ?

**Comment by KiMaBa** [comment]
yes that is the case, sorry i forgot to point that out.

**Comment by jmckenna** [comment]
@KiMaBa I did reproduce your problem.  I don't need any more info.

@rouault correct, the user/pass are part of a VirtualSpatial connection (http://www.gdal.org/drv_vrt.html).  Do we just live with that connection returned?

**Comment by jmckenna** [comment]
in summary: a long VirtualSpatial connection throws a "path is too long" error and MapServer (msBuildPath) returns the whole OGR connection.

**Comment by rouault** [comment]
@jmckenna a inline virtualspatial connection is considered by MapServer as a regular filename. It is just OGR that understand the meaning.

I couldn't reproduce (didn't try hard), but I think the following patch should fix it:
```
diff --git a/mapstring.c b/mapstring.c
index 122f4cd..24d8c31 100644
--- a/mapstring.c
+++ b/mapstring.c
@@ -728,8 +728,9 @@ char *msBuildPath(char *pszReturnPath, const char *abs_path, const char *path)
     abslen = strlen(abs_path);
 
   if((pathlen + abslen + 2) > MS_MAXPATHLEN) {
-    msSetError(MS_IOERR, "(%s%s): path is too long", "msBuildPath()",
-               abs_path, path);
+    msSetError(MS_IOERR, "Path is too long.  Check server logs.",
+               "msBuildPath()");
+    msDebug("msBuildPath(): (%s%s): path is too long.\n", abs_path, path);
     return NULL;
   }
```

**Comment by jmckenna** [comment]
with the patch here is the response:
```
msDrawMap(): Image handling error. Failed to draw layer named 'provinces'. <br>
msOGRFileNextShape(): OGR error. OGR GetNextFeature() error'd. Check logs. <br>
msBuildPath(): Unable to access file. Path is too long.  Check server logs. <br>
msBuildPath: Unable to access file.  <br>
msBuildPath(): Unable to access file. Path is too long.  Check server logs. <br>
```

I'm not sure why the message was repeated in the response.

**Comment by rouault** [comment]
> I'm not sure why the message was repeated in the response.

Likely because msBuildPath() is called from several places. Does the patch avoid any mention of the CONNECTION content in the response sent to the client ? This is all what we want.

**Comment by jmckenna** [comment]
Confirmed that the patch avoids mention of the CONNECTION content in response sent to the client.  I'll commit your patch to branch-7-0 now.  Thanks Even.

**Comment by dmorissette** [comment]
About the multiple calls to msBuildPath(), I didn't check this specific test case, but it is likely caused by a call to msBuildPath3() or msTryBuildPath3() which ends up callibg msBuildPath() twice. This is used for instance to deal with filenames that can be relative to shapepath, mapfile path, or a combination of both.

**Comment by jmckenna** [comment]
I also confirmed last night that it is likely to msBuildPath3() calling msBuildPath() twice

**Comment by jmckenna** [comment]
Unfortunately users are not aware of this :)   But I am now.   Looks like we must live with it.  So I applied and closed.

**Comment by jmckenna** [comment]
@dmorissette let me if we can live with this double-output for users.  I believe we must live with it, for reasons you noted.  (not much else we can do in this case)

**Comment by jmckenna** [comment]
@KiMaBa MapServer 7.0.4 is available now for your testing.  Download: http://download.osgeo.org/mapserver/mapserver-7.0.4.tar.gz  Changelog: mapserver.org/development/changelog/changelog-7-0.html#changelog-7-0-4
