### ISSUE TITLE
MINDISTANCE does not regard label bounds

### ISSUE THREAD

**Issue by olt** [mapserver/mapserver#5369]
Identical labels are placed too close together. MINDISTANCE should prevent this, but `msCheckLabelMinDistance` only calculates the distance from the label point (center?) and does not regard the complete bounds of the label.

The attached images shows this: Kreuzeskirchstr. are two separate linestrings and both labels are rendered even with a MINDISTANCE of 100.

![mindistance 100](https://cloud.githubusercontent.com/assets/235174/21926905/21bae2dc-d984-11e6-9486-33ff023b02d8.png)

The following image highlights a few labels that are too close together.
![min distance 50](https://gist.githubusercontent.com/olt/39ee2c4df38bd51e8983c8db69168988/raw/54d8f2f30979add203becf7fbcab02bf7be83f62/min_distance_old_50_annotated.png)

**Comment by tbonfort** [comment]
@olt I'd be OK with merging if you can provide a computationally efficient fix checking for this

**Comment by olt** [comment]
My proposed change in #5464 (still work in progress) would buffer the bbox of the current label to draw (in `msDrawLabelCache`). `MINDISTANCE` defines the buffer size.
All labels from current label cache with the identical text (`annotext`) are checked if they intersect this buffered bbox.

This not a 100% solution, as it does not use the actual text path the label, but it would be more complex to buffer this polygon. However, it does use the text path polygon from the label cache. This is still quite efficient as only identical text labels are tested for intersection and `intersectLabelPolygons` checks the bbox first.
My non-scientific benchmarks (`shp2img -c 100`) showed no measurable difference, but I will do a bit more testing.

My main question is: This will change the output of existing styles that use the MINDISTANCE feature. Less labels are expected as the MINDISTANCE is now calculated from the label bounds and not the label center. Is this OK, as long as it is documented in the changelog for 7.2? (As the current behavior does not match the documentation). Should I ask on mapserver-dev?

**Comment by olt** [comment]
I've uploaded images which show how it is now possible to evenly distribute labels. https://gist.github.com/olt/39ee2c4df38bd51e8983c8db69168988
`min_distance_old_x.png` are images created with current master, `min_distance_new_x.png` with #5464 
You will notice that the old version puts much more labels, as the mindistance calculated from the center requires a much larger value.

I also [annotated one image that shows how the current implementation gives unexpected results.](https://gist.githubusercontent.com/olt/39ee2c4df38bd51e8983c8db69168988/raw/54d8f2f30979add203becf7fbcab02bf7be83f62/min_distance_old_50_annotated.png)

I also did more performance tests. I did multiple runs of shp2img with -c 100, I switched between old and new version each time so that CPU throttling does affect both in the same way. 
I did test runs with actual label texts and one with a fixed text string to trigger mindistance check for each label. The minimum times were similar for both versions.

Note: The largest impact in rendering is still the font rendering. I used different MINDISTANCE values so that the old and new version both render the same number of labels.

**Comment by dmorissette** [comment]
My 0.02$: I like this enhancement (Thanks!) and I think it is okay for the new version to produce a different output for the same MINDISTANCE value since the new behavior is closer to what one would expect MINDISTANCE to do in my opinion. However it may be a good idea to bring this up on the -dev list to get more opinions and to make sure there is no bad surprise after the 7.2 release.

**Comment by olt** [comment]
Merged with #5464
