### ISSUE TITLE
Raster files are wrongly rendered if the map ANGLE is not set to 360°

### ISSUE THREAD

**Issue by MaklariAgoston** [MapServer/MapServer#5377]
The map file projection is WGS 84 / UTM zone 34N.

Every grey square in the map is exactly 50 meters high and wide and all of them is one pixel in a tiff file.

If the Map rotation value is set to 360° (ANGLE 360 in the map file or the Map rotation in the Map Manager) and after dragging the map I release the mouse button than the window-center-showing cross stays exactly the same place where it was before the releasing. That is OK.
But if in the Map Manager the Map rotation is set to 0 than after the mouse button releasing the map is
being moved to north or south depending on how close is the window-center-showing cross to the top or bottom of the closest pixel.
This adjusting moving after the mouse button release wrongly provides that the window-center-showing cross is always at the center of a pixel in the direction of the north-south.
 
This phenomenon appears only in the north-south, but not in the west-east direction.

Moving the map in the west-east direction a connected but different phenomenon appears:
The squares are becoming rectagles with different ratios between their widths and heights.

I illustrate this with some example picture on which the are some other vector graphic lines which could help noticing the problem.
The vector graphic lines are correctly always in the same places, but the grey squares are from a raster file which is rendered wrongly if the ANGLE of the map is not set to 360°.

I give four pictures about two places and with two ANGLE settings:
![centerisat312339 5281081 good 360](https://cloud.githubusercontent.com/assets/19466622/22286052/31e3d4ac-e2ee-11e6-960b-c8eb7fe139f6.png)
CenterIsAt312339 5281081 Good (360°)

![centerisat312339 5281081 wrong 0](https://cloud.githubusercontent.com/assets/19466622/22286058/3b6e7176-e2ee-11e6-949e-8566d8b9d57c.png)
CenterIsAt312339 5281081 Wrong (0°)

![centerisat312394 5281085 good 360](https://cloud.githubusercontent.com/assets/19466622/22286081/4ff83d98-e2ee-11e6-88de-1e9c4f66baab.png)
CenterIsAt312394 5281085 Good (360°)
![centerisat312394 5281085 wrong 0](https://cloud.githubusercontent.com/assets/19466622/22286086/55f0daca-e2ee-11e6-8146-7ab88355dc79.png)
CenterIsAt312394 5281085 Wrong (0°)

**Comment by MaklariAgoston** [comment]
PROJECTION
    "proj=utm"
    "zone=34"
    "datum=WGS84"
    "units=m"
    "no_defs"
  END # PROJECTION

  LAYER
    DATA "C:\\Maklari\\DDM50-GeoTiff-Raw\\L-34-13-B.tif"
    EXTENT 292850 5263700 312400 5282950
    METADATA
      "coordsys_name"	"WGS 84 / UTM zone 34N"
    END # METADATA
    NAME "L-34-13-B"
    PROJECTION
      "proj=utm"
      "zone=34"
      "datum=WGS84"
      "units=m"
      "no_defs"
    END # PROJECTION
    STATUS ON
    TILEITEM "location"
    TYPE RASTER
    UNITS METERS
  END # LAYER

**Comment by tbonfort** [comment]
OK. please try adding a ```PROCESSING RESAMPLE=average``` (or nearest, or, actually, any random string) to your layer definition.

**Comment by MaklariAgoston** [comment]
I am sorry I have not answered earlier, but it has solved the problems, thank you.

**Comment by jratike80** [comment]
Got solved 6 years ago.
