### ISSUE TITLE
PostGIS layers create "WARNING: Optional Ex_GeographicBoundingBox could not be established for this layer..."

### ISSUE THREAD

**Issue by nboisteault** [mapserver/mapserver#5379]
Mapserver 6.2.4 on Ubuntu 12.04.5

Hi,
Here is my [getCapabilities](http://wms.observatoire-environnement.org/sigore?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities)
With PostGIS layers and not shapefile ones I have a warning : 

``

For example the 'commune' layer get this problem, here is its definition : 

LAYER
	NAME commune
	STATUS ON
	TYPE POLYGON
	CONNECTIONTYPE POSTGIS
	CONNECTION "dbname=carto  user='cartouser' password=''"
	PROCESSING "CLOSE_CONNECTION=DEFER"
	DATA "the_geom from ( select the_geom, nom, depart, region, popul, surface, densite, code_insee from communes ) as subquery using unique code_insee using srid=2154"
	PROJECTION
		"init=epsg:2154"
	END
	METADATA
		"wms_title"           "Les communes d'Aquitaine-Limousin-Poitou_Charentes"
		"wms_abstract" "©IGN-RGE BDTOPO®2015."
		"wms_layer_group" "/Administratif"
		"gml_include_items" "all"
		"wms_include_items" "all"
	END
	TOLERANCE 15
	DUMP TRUE
	CLASS
		NAME "limite communale"
		OUTLINECOLOR 30 30 30
		SIZE 8
	END
	TEMPLATE "http://127.0.0.1/templates_mapserver/templatesPhp/O_commune.php?NOM=[nom_raw]&CODE_INSEE=[code_insee]&DEPART=[depart]&POPUL=[popul]&SURF_CAL=[surface]&DENSITE=[densite]"
 END

Is it a bug or did I miss something? Thank you for your help.

**Comment by nboisteault** [comment]
Ok I think I understand. msPostGISLayerGetExtent function is present in 7.0 but not below, am I wrong?
In this case I think the warning is misleading as there is no information that PostGIS layers extent can't be calculated on the fly.

**Comment by jmckenna** [comment]
Please ask your questions direct to the MapServer-users mailing list (subscribe at https://lists.osgeo.org/listinfo/mapserver-users).  Closing.

**Comment by nboisteault** [comment]
Hi,
I think the issue should be reopened. As I said the warning doesn't inform that PostGIS layers can't have their extent calculated with Mapserver < 7.0

**Comment by jratike80** [comment]
However, the warning gives two hints which are correct and work: "Consider setting the EXTENT in the LAYER object, or wms_extent metadata".
