### ISSUE TITLE
Compiling for visual studio 2015

### ISSUE THREAD

**Issue by AndreAhmed** [mapserver/mapserver#5380]
I get the following error : while compiling for VS2015 X32
 fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration

1>  mapogcfilter.c
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition
1>  c:\gdal\include\cpl_config.h(26): note: see previous definition of 'snprintf'

**Comment by AndreAhmed** [comment]
As a work around I have removed the define for snprintf and used the standard library.  however, I get the following error now 

1>  mapagg.cpp
1>d:\maps\mapserver.h(2239): error C2733: 'strdup': second C linkage of overloaded function not allowed

**Comment by jmckenna** [comment]
Please send your errors to the MapServer-users mailing list directly: subscribe at https://lists.osgeo.org/listinfo/mapserver-users
