### ISSUE TITLE
mapscript_csharp issue

### ISSUE THREAD

**Issue by ermoll** [MapServer/MapServer#5389]
Hello,
After upgrafing from Mapserver 7.0.2 to latest version 7.0.4 thru installing ms4w_3.2.0  and copied all dll's to my bin but I get an error when execute the map.draw() function:

{"drawGDAL(): Unable to access file. GDALDatasetRasterIO() failed: libpng: bad parameters to zlib"}
    [System.ApplicationException]: {"drawGDAL(): Unable to access file. GDALDatasetRasterIO() failed: libpng: bad parameters to zlib"}
    Data: {System.Collections.ListDictionaryInternal}
    HelpLink: null
    HResult: -2146232832
    InnerException: null
    Message: "drawGDAL(): Unable to access file. GDALDatasetRasterIO() failed: libpng: bad parameters to zlib"
    Source: "mapscript_csharp"

Could someone explain what I am missing and/or what file could not be accessed ? If any other info needed, let me know.

Update:
If I remove http WMS  layer from my map-file it works. Other layers are local shapes.

**Comment by oldbucsfan** [comment]
Same issue here on Windows using php mapscript. Seems to be because GDAL has some problem when the WMS layer is receiving a image/png.
