### ISSUE TITLE
Fails to open Shapefiles with long-field dBase file

### ISSUE THREAD

**Issue by Yogurt4** [MapServer/MapServer#5394]
If a .dbf has a >255 long field, mapserver fails to open it.
This issue is already fixed in GDAL (containing a copy of this function).

**Comment by jratike80** [comment]
Could you add a link to the corresponding GDAL fix?

**Comment by jratike80** [comment]
What software writes such invalid shapefiles?
http://resources.esri.com/help/9.3/ArcGISDesktop/com/Gp_ToolRef/geoprocessing_tool_reference/geoprocessing_considerations_for_shapefile_output.htm

**Comment by Yogurt4** [comment]
It may be invalid as part of a Shapefile (by Esri limitations) but it's still a valid dBase file.

Note that the linked Esri article is quite obsolete and it refers only to ArcGIS Desktop 9.3, not the Shapefile format itself. The original "ESRI Shapefile Technical Description" imposes no such limitations, it only mentions the INPRISE Corp. for information on the dBase format.

**Comment by jratike80** [comment]
dBase III format itself sets the limit. Later dBase versions may support longer strings but I would not recommend to utilize that possibility. Most software that I know of either do not read such data or truncates strings to 255 characters.

**Comment by jratike80** [comment]
People needing longer texts fields have already switched to GeoPackage.
