### ISSUE TITLE
MapServer via HomeBrew

### ISSUE THREAD

**Issue by AlokBansal8** [mapserver/mapserver#5398]
I have installed the version 7.0.4 through `brew install mapserver`.
Now I need to know how can I start the MapServer? What Apache settings I need to do?
How can I use the WMS service?
How can I use MapCache?

**Comment by sdlime** [comment]
@AlokBansal8, these would be good questions to ask on the mapserver-users mailing list. Github is for bugs and feature requests. --Steve
