### ISSUE TITLE
msResampleGDALToMap causes memory allocation error

### ISSUE THREAD

**Issue by szekerest** [mapserver/mapserver#5402]
Since this commit was added https://github.com/mapserver/mapserver/commit/e0a3448f3f42d20a0d271709c8629a5b40d13951 mapserver may cause memory allocation errors for certain rasters. Attached a sample map and a vrt file (couldn't attach the source ecw it is 700MB in size).
We can use shp2img to reproduce this as follows:

E:\Maps\DMS>shp2img -m ecwtest_vrt.map -o ecwtest_vrt.png
msDrawMap(): Image handling error. Failed to draw layer named 'test'. <br>
msImageCreate(): Memory allocation error. Unable to create new image object. <br>
agg2CreateImage(): Memory allocation error. ..\mapagg.cpp: 824: Out of memory allocating 10240256000 bytes.
 <br>

[test.zip](https://github.com/mapserver/mapserver/files/819660/test.zip)

**Comment by szekerest** [comment]
I'm afraid this fix doesn't solve the the issue, if we increase the zoom level, for example by changing the EXTENT in the mapfile to:

EXTENT 13523244.2497627 -3808739.10513869 13650837.2685289 -3716866.07739124

In my particular use case the user might want to zoom out to arbitrary levels which was possible before the referred commit was added.

**Comment by rouault** [comment]
OK, I've pushed another restriction that will definitely avoid the regression you saw with rasters of large dimensions
