### ISSUE TITLE
PHP MapScript project maximum extent

### ISSUE THREAD

**Issue by dshorthouse** [mapserver/mapserver#5406]
I'm trying to project from EPSG:4326 at maximum extent (i.e. -180,-90,180,90) to another projection like EPSG:54030 (World Robinson) using PHP MapScript but the resultant extent produced from setExtent is apparently well outside acceptable values & so no output is produced. No errors are thrown. If however I adjust the extent to be ever so slightly smaller in all cardinal directions (eg -179.99999, -89.99999, 179.99999, 89.99999), then I can use the PHP mapscript project method on that extent object & produce an output as expected. Have I missed something?

**Comment by sdlime** [comment]
@dshorthouse, this is a question that would be better asked on the mapserver-users mailing list. I'm guessing folks have run into it before but will need additional information to help. --Steve
