### ISSUE TITLE
Documentation Error Run-time Substitution

### ISSUE THREAD

**Issue by cgarancher** [mapserver/mapserver#5423]
Hello,

In documentation of `Run-time Substitution` there is an error on `VALIDATION` part.
[Run-time Substitution](http://mapserver.org/cgi/runsub.html)

It's written:
`'parcelid'      '^[0-9]{5,8)$'`
instead of:
`'parcelid'      '^[0-9]{5,8}$'`

Could you please fix it ? 
Or could you explain how to edit documentation ?

**Comment by geographika** [comment]
@cgarancher - well spotted!
If you'd like to fix this yourself you can go to the relevant page's source: https://github.com/mapserver/docs/blob/branch-7-0/en/cgi/runsub.txt

There will be a pencil icon (to the right of Raw/Blame/History) with the hover text "Edit this file in a fork of this project" - if you click this you can edit directly in your browser and create a pull request. 

If you get into difficulties post back here.

**Comment by jmckenna** [comment]
thanks @cgarancher !  Also next time please file your documentation ticket inside the docs repository: https://github.com/mapserver/docs/issues/
