### ISSUE TITLE
Add info about content dependent GetLegendGraphic

### ISSUE THREAD

**Issue by frodewj** [mapserver/mapserver#5432]
In http://mapserver.org/ogc/wms_server.html#getlegendgraphic-request there is no information about content dependent legend (http://mapserver.org/development/rfc/ms-rfc-101.html)

**Comment by jmckenna** [comment]
@frodewj can you please re-submit this ticket in the proper location for documentation issues?  https://github.com/mapserver/docs/issues   thank you.
