### ISSUE TITLE
Setting MS_MAPFILE does not work

### ISSUE THREAD

**Issue by printercu** [mapserver/mapserver#5433]
Hi!

I'm setting MS_MAPFILE, but get error `Web application error. CGI variable "map" is not set.`. I've found old discussion here http://osgeo-org.1560.x6.nabble.com/setenv-MS-MAPFILE-not-working-td4241371.html but it seems to be still unresolved.

As recommended, I've added `mode=map&layers=streets` but it does not help.

I'm working with MapServer version 6.4.1 on ubuntu.

Thank you for any help.

**Comment by jratike80** [comment]
Instead of creating a new issue to bug tracker you should start discussion by sending a mail to mapserver-users mailing list. MS_MAPFILE is too common setting for Mapserver so that it could have been broken for more than 7 years. Add also a relevant part of your httpd.conf file to your mail.

**Comment by jmckenna** [comment]
as @jratike80 said, please use the mapserver-users mailing list for your questions  (subscribe at https://lists.osgeo.org/listinfo/mapserver-users).  thanks,
