### ISSUE TITLE
[cascaded WMS] regression between 7.0.4 and 7.0.5

### ISSUE THREAD

**Issue by pmauduit** [mapserver/mapserver#5445]
A customer reported a regression with WMS cascading: the output is not the same for the same request (same mapfile, same parameters, the underlying WMS did not change between both tests).

Below is the query string used:

```
QUERY_STRING="map=/usr/src/mapfile/wms_recopesca.map&BBOX=-7.21916,48.40401621621622,-3.4696399999999996,50.43078378378378&SERVICE=WMS&REQUEST=GetMap&FORMAT=image/png&styles=&layers=continent&width=1000&height=541&srs=EPSG:4326&EXCEPTIONS=application/vnd.ogc.se_inimage&TRANSPARENT=TRUE&VERSION=1.1.1"
```

Below, the underlying mapfile extract for the queried layer:

```
LAYER
        NAME            "continent"
 
	PROJECTION
		"init=epsg:3395"
	END

	EXTENT -20037508.3428 -15496570.7397 20037508.3428 18764656.2314
 
        TYPE            RASTER
 
	CONNECTION		"http://www.ifremer.fr/services/wms1?"
        CONNECTIONTYPE  WMS
 
        STATUS          OFF
        DUMP            FALSE
        METADATA
                "wms_name"              "continent"
                "wms_title"             "continent"
		"wms_srs"		"EPSG:3395"
		"wms_server_version"	"1.1.1"
		"wms_format"          "image/png"
                "queryable"             "false"
        END 
END
```

And here is the result after having compiled against the 7.0.4 tag:
![out-ms-7 0 4-sources](https://cloud.githubusercontent.com/assets/594335/26783933/146c3f62-49fb-11e7-8901-49745590b125.png)

The same for 7.0.5:

![out-ms-7 0 5-sources](https://cloud.githubusercontent.com/assets/594335/26783945/1f2b8426-49fb-11e7-8da6-5d089cca27c9.png)

(Notice the offset between both results with the scalebar)

I first tcpdump'ed the HTTP traffic, and checked that both queries in both versions where producing the same WMS request on the cascaded WMS.

My next try has been to recompile a `7.0.5` tag but after having checked out the `7.0.4` version of the `mapresample.c` source file, and I obtained the expected image. Hence, the regression is likely isolated to this source file (I suspect the `msResampleGDALToMap()` function).

@rouault you seem to be the last one having touched the file relying on the git history, any idea of what is going wrong here ?

**Comment by rouault** [comment]
Fixed per https://github.com/mapserver/mapserver/pull/5447 : merged in branch-7-0 and master

**Comment by pmauduit** [comment]
thanks @rouault  !
