### ISSUE TITLE
bus error w/perl mapscript

### ISSUE THREAD

**Issue by ks-brlam** [MapServer/MapServer#5448]
relevant system info:

uname -a: OpenBSD BizzieLizzieBorden 6.1 GENERIC.MP#85 amd64

$ mapserv -v
MapServer version 7.0.5 OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=FASTCGI SUPPORTS=GEOS INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE

I have a test case using perl mapcript (attached, zipped
[buserror.pl.gz](https://github.com/mapserver/mapserver/files/1083159/buserror.pl.gz)
) which 100% of the time results in:

$ ./buserror.pl              
Bus error (core dumped)

the gdb backtrace from the coredump is as follows:

(gdb) bt
#0  0x000016e1bf368487 in msFreeSymbol () from /usr/local/lib/libmapserver.so.2.0
#1  0x000016e1bf368526 in msFreeSymbolSet () from /usr/local/lib/libmapserver.so.2.0
#2  0x000016e1bf3d089d in msFreeMap () from /usr/local/lib/libmapserver.so.2.0
#3  0x000016e237e8a777 in _wrap_delete_mapObj () from /usr/local/libdata/perl5/site_perl/amd64-openbsd/auto/mapscript/mapscript.so
#4  0x000016e228537dbb in Perl_pp_entersub () at /usr/src/gnu/usr.bin/perl/pp_hot.c:3987
#5  0x000016e228536d03 in Perl_runops_standard () at /usr/src/gnu/usr.bin/perl/run.c:41
#6  0x000016e22848d1e4 in Perl_call_sv (sv=0x16e235a04dd8, flags=45) at perl.c:2809
#7  0x000016e22854e267 in S_curse (sv=0x16e1db08f538, check_refcnt=true) at /usr/src/gnu/usr.bin/perl/sv.c:6853
#8  0x000016e22854d63f in Perl_sv_clear (orig_sv=0x16e1db08f538) at /usr/src/gnu/usr.bin/perl/sv.c:6457
#9  0x000016e22854daed in Perl_sv_free2 (sv=0x16e1db08f538, rc=Variable "rc" is not available.
) at /usr/src/gnu/usr.bin/perl/sv.c:6954
#10 0x000016e2284a7035 in Perl_leave_scope (base=0) at /usr/src/gnu/usr.bin/perl/scope.c:1096
#11 0x000016e22858ffa1 in Perl_pp_leave () at /usr/src/gnu/usr.bin/perl/pp_ctl.c:2067
#12 0x000016e228536d03 in Perl_runops_standard () at /usr/src/gnu/usr.bin/perl/run.c:41
#13 0x000016e22848de68 in perl_run (my_perl=Variable "my_perl" is not available.
) at perl.c:2485
#14 0x000016df6c700723 in main () from /usr/bin/perl
(gdb)

the issue appears to be not setting they style's color when having set the style's outlinecolor, as in these lines from the script:

#$style->{'color'} = $color;    # XXX -- not setting this seems to cause a core dump
$style->{'outlinecolor'} = $color;

**Comment by jratike80** [comment]
I consider that Perl mapscript is not maintained.
