### ISSUE TITLE
Add a way to specify location of CA bunde for Curl+SSL in a mapfile using a CONFIG directive

### ISSUE THREAD

**Issue by vitjok** [MapServer/MapServer#5463]
To enable https connections to WMS/WFS servers it is necessary to configure the location of CA bundle file as described in #3007. With c500e850a86f8aa537988f80ee2c503884c5258c it is implemented to configure the location by environment variable. This issue is about to configure the same by a CONFIG directive in a mapfile.

**Comment by vitjok** [comment]
Why is it necessary to configure the CA bundle file by a directive instead of using an environment variable?
As reported in #4436 there are problems to set the environment variable on some windows systems. The problem seams to appear on systems with **IIS**+FastCGI+64bit. When using mapserver through IIS, we have to setup variables like MS_ERRORFILE and PROJ_LIB by a CONFIG directive, environment variables do not working. A fix for this issue (#5463) would give us a workaround for #4436 whereas #4436 is may be an IIS issue.

**Comment by geographika** [comment]
Fixed with #6305
