### ISSUE TITLE
Python mapscript needs mapscriptvars, but it's not being built

### ISSUE THREAD

**Issue by DanielBaird** [mapserver/mapserver#5469]
The python mapscript build process expects a `mapscriptvars` file, but as far as I can tell that file is not generated by building MapServer in linux. The file *is* mentioned in `Makefile.vc`, so I think it's generated when building on Windows.

Have I missed something?

**Comment by geographika** [comment]
From HISTORY.TXT (2009!):

```
- Rework Python MapScript's setup.py to be more like Python's to fix
  a number of issues including (#2637) and to use mapserver-config 
  and ditch the old mapscriptvars approach
```

The .in files I think now contain these variables (MS_VERSION etc.), and are filled in by the build process.
E.g. https://github.com/mapserver/mapserver/blob/branch-7-0/mapserver-version.h.in

**Comment by geographika** [comment]
Python MapScript build process has been updated (see https://github.com/mapserver/mapserver/wiki/Python-MapScript-Updates-2018).
