### ISSUE TITLE
Segfault if geometry of type 'LINESTRING EMPTY'

### ISSUE THREAD

**Issue by citizenfish** [mapserver/mapserver#5473]
To reproduce use a postgis data layer with empty geometries, for example:-

ST_GEOMFROMEWKT('SRID=900913;LINESTRING EMPTY')

These are prevalent in openstreetmap data.

**Comment by jratike80** [comment]
Works for me with MapServer version 7.0.6 (MS4W 3.2.2) and an empty multipolygon geometry.
I made test data from the "states.shp" file that comes with Geoserver data_dir. Copied data into PostGIS and updated into empty geometry.

```
update states set geom=ST_GeomFromText('multipolygon empty',4326)
where state_name='Idaho';
```
I verified also that a NULL geometry works as well.

What is your platform and Mapserver version? Could you provide test data with a mapfile?

**Comment by jratike80** [comment]
No feedback and works for me, closing.
