### ISSUE TITLE
Cannot load more than one .kml layer

### ISSUE THREAD

**Issue by erimirtis** [mapserver/mapserver#5477]
I created a map with my region, radar data e lightning data.
It all works well if I have only one kml file with lightning data;
if I try to split the data in different layers only one layer is shown.

1. All layers are working separately. 
2. They don't work together when I load them all in the main mapfile trought an INCLUDE
(as shown in my example files) 
3. or even if I directly write them all in the main mapfile

Thank you for your support.
Any suggestion is appreciated.

[lightning map.zip](https://github.com/mapserver/mapserver/files/1310032/lightning.map.zip)

**Comment by geographika** [comment]
This should probably be sent to the user's mailing list - see http://mapserver.org/community/lists.html#mapserver-users

Your issue seems to be having an additional END which prematurely ends the Mapfile.

```
    CLASS
        STYLE
            SYMBOL "cross" # no need to have an END here as it is a string
            SIZE 8
            WIDTH 2
            COLOR 200 200 200
        END
    END
```

**Comment by erimirtis** [comment]
Thank you for your help (and for pointing me to the mailing list, I didn't know about it!)

**Comment by jratike80** [comment]
No confirmation from the reporter but the additional END is an obvious reason so no bug.
