### ISSUE TITLE
How to compile Mapserver for RHEL7

### ISSUE THREAD

**Issue by mapserversaurabh** [mapserver/mapserver#5481]
I am first time user of mapserver5. I have to compile mapserver for rhel7 so that I can deploy it as a WAR(application) on Websphere application server 8.5

**Comment by mapserversaurabh** [comment]
Can some help me with the steps for the same.

**Comment by tomkralidis** [comment]
Please post questions to the MapServer users mailing list. MapServer GitHub issues are for **software bugs/enhancements** and related tasks.
