### ISSUE TITLE
allow expressions in style parameters

### ISSUE THREAD

**Issue by pvgenuchten** [MapServer/MapServer#5495]
Would be nice if one could use expressions to provide values for style parameters like opacity, size, angle, eg: SIZE [size]*1.5, ANGLE 360-[angle]. I found various related issues, like #642

**Comment by geographika** [comment]
[SIZE](https://www.mapserver.org/mapfile/style.html#mapfile-style-size) and [ANGLE](https://www.mapserver.org/mapfile/style.html#mapfile-style-angle) now both support attributes, and as of 8.2 SIZE also support expressions.
