### ISSUE TITLE
WFS 1.1.0

### ISSUE THREAD

**Issue by richie21** [mapserver/mapserver#5496]
Hello,

It seems there is a typo.

https://github.com/mapserver/mapserver/blob/66309eebb7ba0dc70469efeb40f865a8e88fafbd/mapwfslayer.c#L448

I think it should be :
`bbox->minx, bbox->miny, bbox->maxx, bbox->maxy`

Thanks.

**Comment by rouault** [comment]
Good catch. Thanks
