### ISSUE TITLE
UVRASTER and lon_wrap=180

### ISSUE THREAD

**Issue by rouault** [mapserver/mapserver#5502]
```mapserv -nh QUERY_STRING="map=uvraster_lonwrap.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-90%2c-180%2c90%2c180&CRS=EPSG:4326&WIDTH=745&HEIGHT=372&LAYERS=OCEAN.GIOPS_UU2W&STYLES=&FORMAT=image/png&DPI=120&MAP_RESOLUTION=120&FORMAT_OPTIONS=dpi:120&TRANSPARENT=TRUE" ``` on the attached zip 
[uvraster_lonwrap.zip](https://github.com/mapserver/mapserver/files/1421744/uvraster_lonwrap.zip)
only displays the content on the right side of the image.

The issue is indeed linked to +lon_wrap that doesn't work very well with uvraster. From what 
I saw lon_wrap is applied both, once when doing the in-memory rendering of the reduced 
raster, and once for the vector points. 

CC'ing @tomkralidis

**Comment by tomkralidis** [comment]
Validated works.
