### ISSUE TITLE
Axis order in WCS

### ISSUE THREAD

**Issue by ajolma** [mapserver/mapserver#5504]
In version 1.1 DescribeCoverage response MapServer puts into the SpatialDomain part the following (an example from http://194.66.252.155/cgi-bin/BGS_EMODnet_bathymetry/ows)

`<ows:BoundingBox crs="urn:ogc:def:crs:EPSG::4326" dimensions="2">
          <ows:LowerCorner>30.01040372 9.83125</ows:LowerCorner>
          <ows:UpperCorner>46.18958333 22.23542659</ows:UpperCorner>
</ows:BoundingBox>
`

and

`<GridCRS>
          <GridBaseCRS>urn:ogc:def:crs:EPSG::4326</GridBaseCRS>
          <GridOrigin>9.833333335 46.187499995</GridOrigin>
</GridCRS>
`

The axis order is different in the two. This confuses GDAL as it sends GetCoverage request based on GridOrigin. MapServer replies with Requested BBOX (46.183333325,9.833333335,46.187499995,9.837500005) is outside requested coverage BBOX (9.83125,30.01040372,22.23542659,46.18958333).

GridOrigin is described for this purpose in OGC 07-067r2 Annex F. My interpretation of Table F.1 is that the correct GridOrigin in this case should be

`<GridOrigin>46.187499995 9.833333335</GridOrigin>`

which would also make GDAL not fail.

**Comment by ajolma** [comment]
However, if I fix GDAL to swap the axis when it writes the bounding box to the GetCoverage, all goes well. Hm.

**Comment by rouault** [comment]
Issue should be fixed per  https://github.com/mapserver/mapserver/commit/4f7520631f03d1347dadf529db6da55c2ea57186

> However, if I fix GDAL to swap the axis when it writes the bounding box to the GetCoverage, all goes well. Hm.

The GetCoverage code path does honour the EPSG axis order when parsing the input BBOX

**Comment by ajolma** [comment]
Does your commit mean that you concur in my interpretation of the standard?

**Comment by rouault** [comment]
> Does your commit mean that you concur in my interpretation of the standard?

Yes, the standard is rather clear on that. See the extract I quote in the commit message of https://github.com/mapserver/mapserver/commit/4f7520631f03d1347dadf529db6da55c2ea57186
