### ISSUE TITLE
segfault in msSLDApplySLD

### ISSUE THREAD

**Issue by wdc-rsat** [mapserver/mapserver#5505]
The typo in  /* opacity for sld raster */ code crashes mapserver 7.0.6 (the layer index is 'j' and not 'i')
-              pasLayers[i].compositer && pasLayers[j].compositer->opacity != 100)
should be
+              pasLayers[j].compositer && pasLayers[j].compositer->opacity != 100)

**Comment by rouault** [comment]
Do not hesitate to submit your fixes as pull requests. This makes it easier for us to review and regression tests are automatically run
