### ISSUE TITLE
Revive ANTIALIAS keyword in STYLE (for lines)

### ISSUE THREAD

**Issue by erik-h11** [MapServer/MapServer#5508]
The ANTIALIAS keyword seems to be silently ignored in the current version. We have a need for drawing aliased lines - with antialiased lines, the resulting colors (RGBA values) do not necessarily correspond to the values specified as COLOR, which prevents us from implementing an idea based on redrawing certain road segments with Javascript.

**Comment by jratike80** [comment]
Please read this long mail thread from mapserver-users https://lists.osgeo.org/pipermail/mapserver-users/2017-October/080278.html . That is also the right place for starting a new discussion, not this issue tracker.

**Comment by sdlime** [comment]
I don’t think we can do it at the STYLE level, more likely at the OUTPUTFORMAT level.
________________________________

**Comment by erik-h11** [comment]
Actually I was the one starting that mapserver-users thread. I managed to achieve my goal my modifying (mostly) mapfile.c and mapagg.cpp; I created this ticket because I wanted to create a Pull Request (but perhaps issues and PRs are not necessarily related).

Having some problems with the PR because I branched off branch-7-0, and the instructions in the WorkingWithGit Wiki page mention 'master'; getting compile errors with 'master'.

 I think 'master' needs some updates; will try again later.

**Comment by jratike80** [comment]
Sorry, I did not remember that. At least the mail thread is now recorded as background information. Perhaps the setting it could be implemented as a new FORMATOPTION. I was pondering about the existing GAMMA option, does it have anything common with this?

**Comment by erik-h11** [comment]
My solution was to use the ANTIALIAS keyword: the parser in the current code still recognizes it, but the loadStyle() method simply ignores it. I'm now setting a flag in styleObj if the symbol is MS_FALSE, then copy that flag to strokeStyleObj, and in agg2RenderLine (mapagg.cpp) I pick renderer_scanline_bin_solid if the flag is MS_FALSE.

**Comment by geographika** [comment]
Fixed with #6225
