### ISSUE TITLE
Crash with STYLE OFFSET -1 -99

### ISSUE THREAD

**Issue by pka** [mapserver/mapserver#5510]
We have a crash with the current version using the following style:
```
STYLE
  GEOMTRANSFORM 'labelpoly'
  OUTLINECOLOR 0 0 0
  WIDTH 1
  MAXWIDTH 3
  OFFSET -1 -99
END 
```

Without `OFFSET`, the mapfile is working. On Windows the mapfile is working _with_ `OFFSET`!

Versions:
* Debian Stretch: 7.0.4-2 and also 7.0.6-2~bpo9+1 from stretch backports
* Windows: 7.0.6 from MS4W 3.2.2

**Comment by jmckenna** [comment]
@pka please retry this against master, as there was a fix related to this through ticket #5529 just now.

**Comment by jmckenna** [comment]
here was the test provided, that used to give errors of "GEOS library error" but now works with master: 
[ticket-5529-geos.zip](https://github.com/mapserver/mapserver/files/4730215/ticket-5529-geos.zip)

**Comment by pka** [comment]
Honestly, I can't remember where we had this problem. I'm fine with closing this issue, Jeff.

**Comment by jmckenna** [comment]
ok Pirmin, sorry it took so long.
