### ISSUE TITLE
Interpretation of WCS 1.1 GetCoverage params when axis order is inverted

### ISSUE THREAD

**Issue by ajolma** [mapserver/mapserver#5518]
If the bbox is given in axis inverted order CRS, then it seems to me (after some testing with an existing MapServer and checking on the resulting images) that the code at mapwcs.cpp:1749-50 should take that into account and invert the origin coordinates.

**Comment by rouault** [comment]
I believe the inversion is done earlier at https://github.com/mapserver/mapserver/blob/branch-7-0/mapwcs.c#L1591

**Comment by ajolma** [comment]
Yes, if you have x0,y0; convert it to y0,x0 and assign x1,y1 to it; you have a conflict. The result was that the geotiff I got back was in Africa (long = 35, lat = 10) instead of Italy (long = 10, lat = 35) in a gdal_translate downscaling source in EPSG 4326.

**Comment by rouault** [comment]
I'm afraid I don't understand if your above comment means that you still think there's an issue on mapserver side

**Comment by ajolma** [comment]
Yes it means. I had to convert the GridOrigin parameter in the call from long,lat to lat,long when long,lat (x,y) is what would be expected.

**Comment by rouault** [comment]
Please give the full request. But if the SRS is a lat,long ordered one, then GridOrigin should be also ordered in lat,long order, no ?

**Comment by ajolma** [comment]
http://194.66.252.155/cgi-bin/BGS_EMODnet_bathymetry/ows?SERVICE=WCS&REQUEST=GetCoverage&VERSION=2.0.1&COVERAGEID=BGS_EMODNET_CentralMed-MCol&FORMAT=image%2Ftiff&SUBSET=long%289.9958465000000007,14.996246500000002%29&SUBSET=lat%2835.003271499999997,45.004071499999995%29&SCALESIZE=long(20),lat(40)

**Comment by ajolma** [comment]
Yes. GridOrigin should be inverted in this case. And MapServer is correct - and GeoServer is not. I guess.

**Comment by rouault** [comment]
Your report is confusing... So MapServer is correct ? And the code you mentionned (mapwcs.c) doesn't apply for WCS 2.0. GetCoverage WCS 2.0 is processed by https://github.com/mapserver/mapserver/blob/branch-7-0/mapwcs20.c#L4060

**Comment by ajolma** [comment]
So, perhaps this could be closed as not a bug. I was distracted by the MapServer docs.

**Comment by ajolma** [comment]
I pasted 2.0.1 request first by mistake, it's now 1.1.0. It's hard to do this on a sofa watching TV news. :)

**Comment by ajolma** [comment]
The above URL produces a correct looking geotiff. GridOrigin in it is max lat (maxY), min long (minX) because this is axis inverted CRS. What was confusing me was that I had already swapped minX with minY and maxX and maxY. Thus I was feeding minY,maxX or maxX,minY to GridOrigin. Oh my.
