### ISSUE TITLE
Modify osm-google.map

### ISSUE THREAD

**Issue by ankesharyan** [mapserver/mapserver#5524]
After modifying osm-google.map file as suggested and then "Test the OSM Mapfile->Testing with shp2img" run this command in cmd "shp2img -m osm-google.map -o output.png -map_debug 3" gives error "getDouble(): Symbol definition error. Parsing error near (_):(line 47) <br>"

**Comment by yjacolin** [comment]
> as suggested 

Where?

> (line 47) 

What is the content in this line?

Thanks.

**Comment by ankesharyan** [comment]
thanks for reply . I resolved this issue.
