### ISSUE TITLE
finding location on the map  using name

### ISSUE THREAD

**Issue by ankesharyan** [mapserver/mapserver#5532]
How Can i find the location by searching via name?
What parameters should i use in below URL to get location by searching via name.

http://localhost/cgi-bin/mapserv.exe?map=MY_MAPFILE&mode=browse&template=openlayers&layer=all

**Comment by jratike80** [comment]
This is a bug tracker. Send questions about how to use Mapserver into mapserver-users mailing list. It isn't very responsive nowadays and your question does not have a focus so it may be that you will not get many answers but that's the forum we have.

I believe that you should use mode=ITEMQUERY for name search and I hope that you can find some examples from the web. They could help you with writing a good question to the mailing list..
