### ISSUE TITLE
Map tiles naming convention

### ISSUE THREAD

**Issue by peterboccia** [mapserver/mapserver#5541]
Hello,

I cant' find a way to attach my already downloaded tiles into mapserver.
I have png images 512x512 from 0 to 9 level (I used ArcGis service to take them), but looking into the documentation there isn't a reference to the correct naming convention.

Can anyone explain how to perform that import/attachment/upload?

Thanks in advance

**Comment by pedros007** [comment]
I don't think you can do this directly with MapServer, but you might try asking this question in the [mapserver-users mailing list](https://lists.osgeo.org/pipermail/mapserver-users/).

An answer probably depends on what your goal is.  MapServer provides a WMS endpoint to imagery.  If you're trying to take your tile pyramids and serve them via WMS, here are some things you could try:
- You might be able to configure MapCache to act as a WMS endpoint to your tile pyramids.
- Take all the level 9 images, `gdalbuildvrt`and then `gdal_translate` to get the tile pyramids as a single image.  Then configure a WMS endpoint with MapServer to render the single image.  This may be impractical if your level 9s are too large.
- If you just need to serve the tile pyramids as a TMS/XYZ endpoint, you could configure Apache or Nginx to point to your tiles. Here's an [OpenLayers example which renders xyz tile pyramid](http://openlayers.org/en/latest/examples/xyz.html?q=xyz), which would work if your tiles are hosted via a standard web server.

**Comment by jmckenna** [comment]
As @pedros007 said, please use the MapServer-users mailing list for your questions (that way your question goes to 2000+ developers): subscribe at https://lists.osgeo.org/pipermail/mapserver-users/
