### ISSUE TITLE
I want to edit mapfile,are there better visualization tools？

### ISSUE THREAD

**Issue by weihl** [mapserver/mapserver#5556]
I want to create mapfile by  configuring layer styles.I find some tools in WIKI,but MapManager does work in win10,and about  gvSIG desktop,I can't find the export button. Are there any other visualization tools?The plug-in of qgis is not updated anymore? @jwall @ @sgillies

**Comment by jratike80** [comment]
This is a question that does not belong to issue tracker. Use mapserver-users mailing list instead.
As far as I know you are right with your thinking. One more alternative could be http://scribeui.org/. Myself I edit mapfiles by hand and use some WMS client for visualizing what happened.
