### ISSUE TITLE
SWIG 3 and C# Bindings not compiling

### ISSUE THREAD

**Issue by geographika** [mapserver/mapserver#5575]
The C# MapScript bindings fail to compile when using a newer version of SWIG.
The following error appears many times:

`error CS0246: The type or namespace name 'IntPtr' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\mapserver\build\mapscript\csharp\mapscript.vcxproj]`

This also appears to have happened in GDAL - https://trac.osgeo.org/gdal/ticket/6465

This issue https://github.com/robotology/yarp/issues/206 appears to be the same and was fixed by changing IntPtr to System.IntPtr.

**Comment by itbeyond** [comment]
Are you able to compile and make work without updating the SWIG library - I have been working on this all day and can compile with the older SWIG however the library always produces this: Unable to load DLL 'csharpmapscript': The specified module could not be found. (Exception from HRESULT: 0x8007007E) when running.

I have tried SWIG 3.0.12 and like you get errors during compile. I hoped the lastet SWIG would resolve the above problem - however also testing using the latest windows build from gisinternals also seems not to work using any V7 release?

**Comment by geographika** [comment]
Closed with #5583
