### ISSUE TITLE
MVT Tile Boundary Issue not lining up

### ISSUE THREAD

**Issue by itbeyond** [mapserver/mapserver#5578]
I have been doing extensive testing with mvt support against a very large (10K lines) map file and converting the png output to mvt with mixed results. Of course there are heaps of DB changes and updates I am applying however I have just started working with Polyline and cannot get the alignment between tiles to work - I have looked at and tried the EDGE_BUFFER from values of 0 to 50 and still see the same type of alignment issues my OUTPUTFORMAT statement is as follows:
```
OUTPUTFORMAT
    NAME "mvt"
    MIMETYPE "application/x-protobuf"
    DRIVER "mvt"
    EXTENSION "pbf"
	FORMATOPTION "EDGE_BUFFER=50"
  END # OUTPUTFORMAT
```
I am using mode=tile and pulling a road layer from postgres. The png output is fine and is cut in the right place - so using the same mapserve cmd and only changing the outputformat from png to mvt (mvt rendered in inspect mode on Maputnik, shows the same in mapbox gl) produes the images attached. NOTE the mvt layer is only showing major roads hence there is less visible in the mvt output than the png. The errors in the mvt are visible centre left and down - there is a 4 way tile join.
![mapserver_mvt](https://user-images.githubusercontent.com/1870615/38404932-e774ff36-399f-11e8-9863-9a3323ec5fd7.jpg)
![mapserver_png](https://user-images.githubusercontent.com/1870615/38404933-e7d17202-399f-11e8-8d77-b61606523e06.png)
I just booted the mvt-demo provided by @sdlime in the pull #5376 and zooming in shows the error exists in this output also as per the attached screenshot. You can see it in the road line and river line.
![demo](https://user-images.githubusercontent.com/1870615/38405409-4e57cd80-39a2-11e8-85b1-db634c029657.jpg)

**Comment by itbeyond** [comment]
A little more research yields this from Mapbox in relation to MVT format: All geometric coordinates in vector tiles must be between -1 * extent and (extent * 2) - 1 inclusive. Is this how mapserver sets the tile extent in mode=tile?

Additionally for mvt using Mapbox-gl all vector tiles must be sized at 512 pixels (trying to manually adjust this in mapbox-gl gives this error: Error: vector tile sources must have a tileSize of 512. The MapServer documentation for mode=tile states tile size will be 256 - I wonder if this conflict is what is causing the issue as I have noted that the output using the vector tiles seems to render a 256x256 tile in a 512x512 area - ie: the map looks twice as large rendered in gl using a vector source than the same raster source settings producing a png. In fact the png vs vector output images I uploaded above show this double up in size  (I first thought the png was being reduced in github render) both set of images from the tile zoom 11 and rendering the same 4 tiles.

**Comment by sdlime** [comment]
I'll have to dig into this (just got back into town)... thanks for the testing - I think you're one of the first. Hopefully this is something simple...

**Comment by fminuti** [comment]
I think the problem is 
https://github.com/mapserver/mapserver/blob/b74a3f4b021cd675f89d3afbb53166bee7406ca1/maptile.c#L457-L467

In this code the extent is made "bigger" and so the calculation of the 4096 pixel scale become wrong.
If you comment out this code you should obtain the correct tile.

Maybe " This is the way mapserver does it." should be changed or taken into account in code.

**Comment by itbeyond** [comment]
@fminuti Yes this is the problem - I commented out this section - recompiled the dll and presto. The tiles are now correctly aligned. So yes it appears that this case needs to be tested and a provision to turn off this re-calculation when tiles are being rendered in mvt. @sdlime - this does in fact resolve the problem as far as my testing goes - not sure how to put in the right test for this in code, hope you can sort this out in the base package easily. Thanks.

**Comment by sdlime** [comment]
I don't think we want to change maptile.c since that would hose up regular use of mode=tile. It's more likely that the mvt code was *also* applying a similar extent transformation and it could/should be disabled there. Thomas' original mvt implementation was using WFS which had no extent manipulation so that would make sense. --Steve

**Comment by sdlime** [comment]
The MVT now code assumes the submitted extent is given in pixel center. I added a bit of code to transform by adding back the half pixel. That seems to fix the tile generation, at least in my MVT demo.

Please give it a try and let me know how it goes.

--Steve

**Comment by itbeyond** [comment]
Will test asap thanks just out of the office for 10days. Will report when I get back.

**Comment by itbeyond** [comment]
Confirm this has fixed the problem - thanks.
