### ISSUE TITLE
mapserver wms raster  image stretching

### ISSUE THREAD

**Issue by javacoderpyl** [MapServer/MapServer#5598]
hi:

I used mapserver7.0 to publish a geoffiff-based wms service. When I visited the wms service, I found that the returned image was stretched. In order to verify this problem, I also published a service using geoserver.Found that the picture obtained through the service of the geoserver can completely match with the original TIFF file, but the picture obtained by the service of the mapserver and the original tiff file are superimposed and displayed, and a misplaced situation occurs. The smaller the resolution of geotiff, the more obvious this。

```
LAYER

  NAME "test"
  DATA "test.tif"
  TYPE RASTER
  STATUS ON
  PROJECTION
     "EPSG:3857"
  END
  PROCESSING "RESAMPLE=AVERAGE"
  CLASSITEM "[pixel]"
  CLASS
    EXPRESSION "0"
    STYLE
      COLOR 0 0 0
    END
  END
  CLASS
    EXPRESSION ([pixel] >= 64 AND [pixel] < 128)
    STYLE
      COLOR 255 0 0
    END
  END
END
```

when i not set ,
When I don't set "PROCESSING "RESAMPLE=AVERAGE"", stretching is especially noticeable

tip: this tiff,mapfile,layer and wms requert's epsg code same as  3857.

thanks

**Comment by jratike80** [comment]
Could you add screenshots about the current situation and what you would like to achieve?

**Comment by javacoderpyl** [comment]
I'm sorry.For some reason, I can't truncate the diagram of the problem. The current situation is that 
I opened the original tiff file with QGIS, and then added this WMS service in QGIS. Then they superimposed the display, found the original tiff file, and the grid of the picture obtained by WMS can not be completely coincident, there is a misplaced phenomenon, if set The transparency looks like a picture with ghosting. I hope to get the picture exactly the same as the original picture through WMS

thanks

**Comment by jratike80** [comment]
Feels like this issue is hard to re-produce now 5 years later.
