### ISSUE TITLE
Kerneldensity empty map

### ISSUE THREAD

**Issue by medeirosrafael** [mapserver/mapserver#5600]
Sorry to ask in here, but i can't find anything in anywhere..
https://gis.stackexchange.com/questions/284923/mapserver-kerneldensity-empty-map

**Comment by jmckenna** [comment]
Please ask all of your questions direct to the MapServer community through the mailing list, where there are hundreds of registered users available to help you: subscribe at https://lists.osgeo.org/listinfo/mapserver-users

Also please note that when sending messages to mailing lists, always be sure to not attach anything, like images or files, as mailing lists often reject these.  If you need to include an *image*, always use an external service such as https://pasteboard.co/ and include that link in your message; if you need to include long text such as *source code* or a *mapfile*, always use an external service such as https://pastebin.com/ and include that link in your message. 

Thank you,
