### ISSUE TITLE
Unused function msWrapText

### ISSUE THREAD

**Issue by olt** [mapserver/mapserver#5609]
I noticed that msWrapText is unused (function now in msLayoutTextSymbol?).
https://github.com/mapserver/mapserver/blob/4f67ecd18a64ae2af8a071677d3e06829a5d902e/maplabel.c#L57

**Comment by SunveerSingh** [comment]
please see https://github.com/mapserver/mapserver/pull/5691

**Comment by SunveerSingh** [comment]
@geographika We can close this issue now?

**Comment by geographika** [comment]
Closed with #5691
