### ISSUE TITLE
Investigate msautotest result changes due to upgrade to Ubuntu Trusty

### ISSUE THREAD

**Issue by rouault** [MapServer/MapServer#5617]
Per https://github.com/mapserver/mapserver/pull/5615 .travis.yml and Vagrant now use Trusty. This causes a lot of expected results to be refreshed due to changes in library versions (GDAL in particular). There are a few strange changes though that could/should be later investigated, like msautotest/wxs/expected/wfs_ogr_native_sql_37.xml , msautotest/wxs/expected/wfs_ogr_native_sql_37.xml msautotest/wxs/expected/wfs_ogr_native_sql_40.xml , and msautotest/wxs/wfs_query_cache.map wfs_query_cache_2.xml that I had to disable due to inconsistant result between Vagrant and Travis

**Comment by geographika** [comment]
I think this can now be closed with #6430
