### ISSUE TITLE
Centos 7 installation fail

### ISSUE THREAD

**Issue by sebalaini** [mapserver/mapserver#5635]
I'm trying to install Mapserver 7 on a CentOS 7 but it fail.

I'm following these instructions:
https://mapserver.org/uk/installation/unix.html#compiling

I installed CMAKE and it works (see next screenshot), i follow the steps, I copy the CMAKE command and i have some errors but it because I don't have all the libraries so it' OK, i arrive at step 7 and the MAKE command doesn't work.

![1](https://user-images.githubusercontent.com/17096352/43447609-bc04a1b2-94a3-11e8-8869-981bc50f9ff5.PNG)
![2](https://user-images.githubusercontent.com/17096352/43447611-bc20bbe0-94a3-11e8-8612-21c0435e604c.PNG)

how can I solve this problem?

**Comment by yjacolin** [comment]
That's mean you need to install the needed libraries or disable the feature:
* libodbc
* protobufc
* fastcgi
* ...

You can disable this feature as explained in the log you post:
cmake -DWITH_SVGCAIRO=0 ...

Or use ccmake (cmake gui).

Finally, please could you use the mailing list to post such request as this is not a bug.

**Comment by sebalaini** [comment]
Ok, so I need to disable every dependency I don't want to use, now it works thanks :)

**Comment by jmckenna** [comment]
@sebalaini please refrain from using Github for questions; please send all of your questions direct to the mapserver-users mailing list, where over 2 thousand users are waiting to help you: subscribe at https://lists.osgeo.org/mailman/listinfo/mapserver-users   thank you.
