### ISSUE TITLE
Obtain range values from GDAL stats

### ISSUE THREAD

**Issue by dbaston** [mapserver/mapserver#5637]
I have a layer that dynamically reads in one of many possible GeoTIFFs depending on variables that are provided as query-string parameters. The data in each file falls into different ranges, so I can't manually specify a scaling range with `PROCESSING "SCALE_1=200,400"` or the like. But if I use `PROCESSING "SCALE=AUTO"` then a range is determined for each request, which produces discontinuities when clients generated tiled requests:

![image](https://user-images.githubusercontent.com/6318931/43738151-a9b4684c-9991-11e8-979e-515b4de63ded.png)

Is it possible for MapServer to read the min and max values from GDAL, if they are available?

**Comment by jmckenna** [comment]
Please do not use Github issues for questions; do use the MapServer-users mailing list, where the community is awaiting to assist you (subscribe at https://lists.osgeo.org/mailman/listinfo/mapserver-users)

**Comment by dbaston** [comment]
Sorry, I was assuming that the answer to my question was "no" and that this ticket would be a feature request against which I could consider a pull request.
