### ISSUE TITLE
xml file support ver 7.2

### ISSUE THREAD

**Issue by aimdev** [mapserver/mapserver#5638]
Hi
I enabled DWITH_XMLMAPFILE, built and installed the binaries.
When I ran mapserv -v, the option was not shown, I expected to see supports=XMLMAPFILE or something similar.

Please can someone clarify if this is the case?
Is xmlmapfile supported?

Thanks

Aimee

**Comment by jmckenna** [comment]
Please do not use Github for questions; please send all of your questions direct to the MapServer-users community (subscribe at https://lists.osgeo.org/mailman/listinfo/mapserver-users).  thank you.
