### ISSUE TITLE
mapscript hashMapObj incompatible change 7.0.4 -> 7.0.(567) / 7.2

### ISSUE THREAD

**Issue by gogglesguy** [mapserver/mapserver#5643]
This commit 10fe3d78c3f3a3e2cbc64ede7c091a60f11a4e22 seems breaks python mapscript compatibility. We used to be able to:

`
ms.web.validation.set("PROCESSING", 'somepattern')
`

but that no longer works due to being a native python dict:

`
AttributeError: 'dict' object has no attribute 'set'
`

Also this commit only defines the typemap(out) which as far as I can tell means the hashTableObj is readonly from a python perspective.

**Comment by geographika** [comment]
See #5582 for similar issue, and proposed fix at #5620

**Comment by rouault** [comment]
I've just merged https://github.com/mapserver/mapserver/pull/5620 in branch-7-2
