### ISSUE TITLE
MapServer 7.2 produces empty MVT from point data

### ISSUE THREAD

**Issue by jratike80** [mapserver/mapserver#5652]
Discussed in mapserver-users thread https://lists.osgeo.org/pipermail/mapserver-users/2018-August/080679.html

Mapfile and data (OSM and Natural Earth) for reproducing the issue available for a limited period at http://193.167.189.71/temppi/.  Mapfile also as an attachment.
[osm_finland.txt](https://github.com/mapserver/mapserver/files/2310929/osm_finland.txt)

**Comment by sdlime** [comment]
Found the error, patch forthcoming...
