### ISSUE TITLE
Problem with  setting StyleObj.pattern on Ruby/Mapscript  

### ISSUE THREAD

**Issue by ss21** [mapserver/mapserver#5662]
Hello, I got a problem with mapscript/ruby.

Ruby code:
```
require 'mapscript'

sty = Mapscript::StyleObj.new()
sty.patternlength = 4
sty.pattern       = [1.0,1.0,1.0,1.0]
```

result:

Traceback (most recent call last):
        1: from ./test.rb:13:in `<main>'
./test.rb:13:in `pattern=': Expected argument 1 of type double [MS_MAXPATTERNLENGTH], but got Array [1.0, 1.0, 1.0, 1.0] (TypeError)
        in SWIG method 'pattern'

Making values '1.0'  to '1' ,  changing lenght of array, removing 'sty.patternlength',  makes same result. 
On the other hand , in Mapscript/Python, 

python code
```
import mapscript
sty = mapscript.styleObj()
sty.pattern       = [1.0,1.0,1.0,1.0]
```

Python code runs without problems.

software version.
OS   : CentOS 7.5 and 6.9
MS   : 7.2 and 6.4
ruby : 2.3 and 2.5
swig : 3.01

**Comment by geographika** [comment]
In Python the style object has been extended to allow a list of doubles to be set for the pattern, see https://github.com/mapserver/mapserver/blob/branch-7-2/mapscript/python/pyextend.i#L401

There is a now failing test in Python using the following approach, so maybe a style pattern in Ruby would work with this old way?

```
import mapscript
sty = mapscript.styleObj()
sty.setPattern(1.0,1.0,1.0,1.0)
```

See https://github.com/mapserver/mapserver/blob/master/mapscript/python/tests/cases/symbol_test.py#L147

**Comment by ss21** [comment]
Thank you.

But...

```
require 'mapscript'
sty = Mapscript::StyleObj.new()

 sty.setPattern([1,1,2,3])
# or
# sty.setPattern(1,1,2,3)

```
result:
Traceback (most recent call last):
./test.rb:13:in `<main>': undefined method `setPattern' for #<Mapscript::StyleObj:0x00000000028740e0> (NoMethodError)


In  Swig C code about Ruby , I could not find setPattern method .

**Comment by geographika** [comment]
The updateFromString method should be available in Ruby, so you could try:

```
sty = Mapscript::StyleObj.new()
sty.updateFromString('STYLE PATTERN 5 5 END END')
```

**Comment by ss21** [comment]
Thank you geographika.

Setting pattern useing updateFromString function has run with no error.
I will use this instead of pattern method.

**Comment by geographika** [comment]
Good! 
If you wanted to set patterns using the other approaches then you'd need to extend Ruby MapScript similar to Python in https://github.com/mapserver/mapserver/blob/master/mapscript/ruby/rbmodule.i
