### ISSUE TITLE
Documentation for compiling on Windows, needs to be updated.

### ISSUE THREAD

**Issue by SunveerSingh** [mapserver/mapserver#5663]
Hello,

I was going through the compiling process for Windows, And I found that the page[0] is totally outdated.
Instead of adding warnings we should update the page, I will install MapServer and will update the documentation if allowed by you guys. If someone can help me with compilation we will update the page as it is outdated. 

[0] https://www.mapserver.org/installation/win32.html

Thank You
Sunveer

**Comment by yjacolin** [comment]
Please, send a PR we will pleased to merge it into the doc. Many thanks!

**Comment by geographika** [comment]
There is already an issue at https://github.com/mapserver/docs/issues/126 
The best place to start is https://github.com/mapserver/mapserver/blob/master/appveyor.yml which has a fully working build process for Windows. 
Windows CMake instructions can also be found in https://github.com/mapserver/mapserver/blob/master/README.WIN32

**Comment by yjacolin** [comment]
Does someone can close this issue? We should comment on mapserver/docs#126. Thanks.

**Comment by geographika** [comment]
@SunveerSingh - please continue discussion at https://github.com/mapserver/docs/issues/126 - thanks!
