### ISSUE TITLE
Stucked in step prepare background data files

### ISSUE THREAD

**Issue by rawat123** [mapserver/mapserver#5665]
I am following his tutorial https://github.com/mapserver/mapserver/wiki/RenderingOsmDataWindows
and at a time I had a working setup, but mistakenly I deleted my osm database, then I tried configure this again, and stucked in this step https://github.com/mapserver/mapserver/wiki/RenderingOsmDataWindows#prepare-background-data-files

below is my default basemap/data/Makefile

```
SHPTREE=shptree

all: simplified_land_polygons.qix land_polygons.qix

%.qix: %.shp
	$(SHPTREE) $< 8


simplified_land_polygons.qix: simplified_land_polygons.shp
	$(SHPTREE) $< 8

land_polygons.qix: land_polygons.shp
	$(SHPTREE) $< 8

simplified_land_polygons.shp: simplified-land-polygons-complete-3857.zip
	unzip -o -D -j simplified-land-polygons-complete-3857.zip

simplified-land-polygons-complete-3857.zip:
	wget http://data.openstreetmapdata.com/simplified-land-polygons-complete-3857.zip

land_polygons.shp: land-polygons-split-3857.zip
	unzip -o -D -j land-polygons-split-3857.zip

land-polygons-split-3857.zip:
	wget http://data.openstreetmapdata.com/land-polygons-split-3857.zip
```
please have a look.

**Comment by yjacolin** [comment]
"prepare-background-data-files" section doesn't exist from your link. 

Could you send en mail to mapserver-user mailing list. Issue is for bugs.

**Comment by rawat123** [comment]
this is the link https://github.com/mapserver/mapserver/wiki/RenderingOsmDataWindows#prepare-background-data-files

it's not a bug but, at first try everything was working fine but I just forgot what changes I made in the basemap/data/Makefile when it was working

**Comment by MHTA** [comment]
the only changes how works for me is :     

SHPTREE=shptree

all: simplified_land_polygons land_polygons

%: %.shp;
	$(SHPTREE) $< 8


simplified_land_polygons: simplified_land_polygons.shp
	$(SHPTREE) $< 8

#land_polygons: land_polygons.shp
#	$(SHPTREE) $< 8

simplified_land_polygons: simplified-land-polygons-complete-3857.zip
	unzip -o -D -j simplified-land-polygons-complete-3857.zip

.INTERMEDIATE: simplified-land-polygons-complete-3857.zip
simplified-land-polygons-complete-3857.zip:
	wget http://data.openstreetmapdata.com/simplified-land-polygons-complete-3857.zip

land_polygons: land-polygons-split-3857.zip
	unzip -o -D -j land-polygons-split-3857.zip

.INTERMEDIATE: land-polygons-split-3857.zip
land-polygons-split-3857.zip:
	wget http://data.openstreetmapdata.com/land-polygons-split-3857.zip

**Comment by MHTA** [comment]
the only changes how works for me is   :   


SHPTREE=shptree

all: simplified_land_polygons land_polygons

%: %.shp;
	$(SHPTREE) $< 8


simplified_land_polygons: simplified_land_polygons.shp
	$(SHPTREE) $< 8

#land_polygons: land_polygons.shp
#$(SHPTREE) $< 8

simplified_land_polygons: simplified-land-polygons-complete-3857.zip
	unzip -o -D -j simplified-land-polygons-complete-3857.zip

.INTERMEDIATE: simplified-land-polygons-complete-3857.zip
simplified-land-polygons-complete-3857.zip:
	wget http://data.openstreetmapdata.com/simplified-land-polygons-complete-3857.zip

land_polygons: land-polygons-split-3857.zip
	unzip -o -D -j land-polygons-split-3857.zip

.INTERMEDIATE: land-polygons-split-3857.zip
land-polygons-split-3857.zip:
	wget http://data.openstreetmapdata.com/land-polygons-split-3857.zip

**Comment by jmckenna** [comment]
Please do not use the issue tracker for questions; please send all of your questions direct to the MapServer community, where thousands are waiting to help you.  Subscribe at https://lists.osgeo.org/listinfo/mapserver-users
