### ISSUE TITLE
GetMetadata request requires a layer, but RFC documentation says not

### ISSUE THREAD

**Issue by nmtoken** [mapserver/mapserver#5666]
The [RFC 82](https://mapserver.org/development/rfc/ms-rfc-82.html) documentation has as an example:

> Requesting service metadata:
> http://my.host.com/cgi-bin/mapserv?request=GetMetadata

but when I try this request:

> http://ogc2.bgs.ac.uk/cgi-bin/UGA_ARGI/ows?request=GetMetadata&

I get error:

    <?xml version="1.0"?>
    <ows:ExceptionReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows/1.1" version="1.1.0" xml:lang="en-US" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd">
      <ows:Exception exceptionCode="MissingParameterValue" locator="layer">
        <ows:ExceptionText>Missing layer parameter</ows:ExceptionText>
      </ows:Exception>
    </ows:ExceptionReport>

**Comment by tomkralidis** [comment]
@nmtoken I think between the time the RFC was written and implemented, thinking changed (on my part) in the value of providing a 19119 document, so I didn't implement it.  I'm not sure whether the RFC itself needs to be updated, or whether we should further discuss?

**Comment by nmtoken** [comment]
@tomkralidis, probably the RFC can be kept as it is, as the RFC is not the instructions.  I read the RFC before the instructions (https://mapserver.org/ogc/layer_metadata.html) where the example is correct, so raising this as a potential issue, to avoid confusion.  

I guess it is common for the RFCs to not be fully implemented, so common for RFCs to be different from instructions.  You are best placed to make the decision as to whether to edit the RFC.

**Comment by tomkralidis** [comment]
Thanks @nmtoken.  I would propose leaving the RFC as is (if we ever do want to implement in the future).  We don't make reference to the RFC in https://mapserver.org/ogc/layer_metadata.html.  Options:

1. do nothing
1. update https://mapserver.org/ogc/layer_metadata.html to say it implements [RFC82](https://mapserver.org/development/rfc/ms-rfc-82.html) for layers, and service implementation is deferred
2. something else?

**Comment by nmtoken** [comment]
option 1 is fine
