### ISSUE TITLE
GetMetadata response for layer offers format not supported by service

### ISSUE THREAD

**Issue by nmtoken** [mapserver/mapserver#5667]
The WMS GetCapabilities response gives as available GetMap formats:

    <GetMap>
        <Format>image/png</Format>
        <Format>image/jpeg</Format>
        <Format>image/tiff</Format>
        <Format>application/x-pdf</Format>
        <Format>image/svg+xml</Format>

configured through `"WMS_GETMAP_FORMATLIST" "image/png,image/jpeg,image/tiff,application/x-pdf,image/svg+xml"`

but the GetMetadata response for a layer in the WMS service offers `format=image/gif&` like:

> http://ogc2.bgs.ac.uk/cgi-bin/UGA_ARGI/ows?service=WMS&version=1.3.0&request=GetMap&width=500&height=300&styles=&layers=ENERGY_TYPE_2016&format=image/gif&crs=EPSG:4326&bbox=-1.318610,29.620170,3.697400,34.882710

**Comment by tomkralidis** [comment]
@nmtoken thanks for the report.  AFAIK `image/png` and `image/jpeg` are required by MapServer.  Any objection to reducing to just those then (for WMS) to keep things straightforward?

**Comment by nmtoken** [comment]
@tomkralidis if they are mandated image formats, then I'm happy with that
