### ISSUE TITLE
Incorrect protocol for WMS gmd:MD_DigitalTransferOptions in GetMetadata response

### ISSUE THREAD

**Issue by nmtoken** [mapserver/mapserver#5669]
The gmd:protocol for a WMS GetMap response is incorrect.  WMS is not a download service, but we have for example:

    <gmd:onLine>
      <gmd:CI_OnlineResource>
        <gmd:linkage>
      <gmd:URL>http://ogc2.bgs.ac.uk/cgi-bin/UGA_ARGI/ows?service=WMS&amp;version=1.3.0&amp;request=GetMap&amp;width=500&amp;height=300&amp;styles=&amp;layers=ENERGY_TYPE_2016&amp;format=image/jpeg&amp;crs=EPSG:4326&amp;bbox=-1.318610,29.620170,3.697400,34.882710</gmd:URL>
        </gmd:linkage>
        <gmd:protocol>
      <gco:CharacterString>WWW:DOWNLOAD-1.0-http--download</gco:CharacterString>
        </gmd:protocol>
        <gmd:name>
      <gco:CharacterString>ENERGY_TYPE_2016</gco:CharacterString>
        </gmd:name>
        <gmd:description>
      <gco:CharacterString>JPEG Format</gco:CharacterString>
        </gmd:description>
      </gmd:CI_OnlineResource>
    </gmd:onLine>

AFAIKT these protocol strings come from GeoNetwork and an appropriate replacement term here would be `OGC:WMS-1.3.0-http-get-map`

Note that for INSPIRE ISO19139 metadata (Version 2.0.1 ~ 2017-03-02) the recommendation is to have gmd:linkage, gmd:name, gmd:description, and gmd:function (and not gmd:protocol).  Where The gmd:function for a WMS service is **information** like:

    <gmd:function>
         <gmd:CI_OnLineFunctionCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml#CI_OnLineFunctionCode" codeListValue="information"/>
    </gmd:function>

**Comment by tomkralidis** [comment]
Fixed in branch-7-2
