### ISSUE TITLE
mapserv.exe is not working offline

### ISSUE THREAD

**Issue by rawat123** [mapserver/mapserver#5671]
hi I setup the mapserver in my windows machine and can access the map with url http://localhost/cgi-bin/mapserv.exe?mode=browse&template=openlayers&layers=all&map=C:/ms4w/apps/osm/basemaps/osm-google.map I can use the map but it Is not working in offline mode, I want to use it in offline. how can I manage that.

**Comment by yjacolin** [comment]
Please, could you send an email to MapServer-user mailing list. This tracker is for bug in MapServer, not for asking question :)

Thanks.

**Comment by geographika** [comment]
See https://github.com/mapserver/mapserver/blob/branch-7-2/CONTRIBUTING.md for links to mailing lists.
