### ISSUE TITLE
No way to opt out of automatically generated metadata?

### ISSUE THREAD

**Issue by nmtoken** [mapserver/mapserver#5683]
As there are a number of issues with the automatically generated metadata (through the request=GetMetadata& URLs) and even the links inserted in the WMS Capabilities response I would like to opt out of having it.  

Unfortunately there doesn't seem any way of doing this.

**Comment by tomkralidis** [comment]
@nmtoken would fixing these issues negate the need for opting out?  Or do we want the ability to explicitly turn OFF metadata generation by URL reference in Capabilities documents?  Note that most/all issues are now fixed in branch-7-2 (thanks much for reporting).

**Comment by nmtoken** [comment]
@tomkralidis for me fixing the issues negates the requirement for opting out.

**Comment by tomkralidis** [comment]
Thanks @nmtoken. I would propose closing the issue since this is now fixed.
