### ISSUE TITLE
Maps Server not running on IIS

### ISSUE THREAD

**Issue by reznikon** [mapserver/mapserver#5695]
Hi guys i am running 
MapServer on windows server 2016 with IIS V 10.

I followed the installation instructions but while running the demo app i'm still getting

msLoadMap(): Unable to access file. (C:/MapServer/apps/test/test.map)

IIS_IUSRS has full control access over the file.

Any idea ?

**Comment by geographika** [comment]
Hi @reznikon - questions should be directed to the mailing lists - see https://github.com/mapserver/mapserver/blob/branch-7-2/CONTRIBUTING.md#bugs-and-help for links. 

IIS_IUSRS with Read access should be fine. Try checking the Effective Permissions for the file, and double checking the file actually exists at that location (e.g. could it be C:/MapServer/apps/test.map ?). This would show the same error message.
