### ISSUE TITLE
MSSQL driver should accept driver specification in the connection string

### ISSUE THREAD

**Issue by szekerest** [mapserver/mapserver#5703]

**Comment by geographika** [comment]
@szekerest - is this commit in anyway related to #5702 ? 
If so I can compile and test this code using a native SQL Server driver rather than the ODBC driver which is used by default. 

Also does allowing a driver to be set allow in anyway the MSSQL Driver to be used on Linux?

**Comment by szekerest** [comment]
> @szekerest - is this commit in anyway related to #5702 ?
> If so I can compile and test this code using a native SQL Server driver rather than the ODBC driver which is used by default.
> 
> Also does allowing a driver to be set allow in anyway the MSSQL Driver to be used on Linux?

No, I'm still investigating that problem.

**Comment by geographika** [comment]
@szekerest - ok thanks. Let me know if I can provide any further information or testing.
