### ISSUE TITLE
mapquery.c "No matching record(s) found." filling up logfiles

### ISSUE THREAD

**Issue by computerchemist** [MapServer/MapServer#5706]
My mapserver wms service log files fill up very quickly with these messages: "No matching record(s) found.", even with '`DEBUG 0`'

The frontend is an openlayers query with many layers; sometimes there is no match for the area/filter, this is not an error in itself.

I would suggest that all messages in mapquery.c are changed to only include this verbose output if verbosity is required in debugging - in other words, for all occurrences of 
`msSetError(MS_NOTFOUND, "No matching record(s) found.",  ......`

add this following line above the seterror, to only trigger the errormessage (but still exit with an error condition) if debug is required
`if( lp->debug >= MS_DEBUGLEVEL_V )`

I have been routinely making this change for several versions now but it would be nice if it was in the codebase - comments?

**Comment by geographika** [comment]
That change sounds logical to me. Are you able to create a pull request with your change?

**Comment by computerchemist** [comment]
Seth, feel free to add it in!
There are 5 changes in total to make in mapquery.c .

**Comment by geographika** [comment]
@computerchemist - you can make these changes yourself directly in GitHub in the browser to create a pull request. See https://help.github.com/articles/editing-files-in-another-user-s-repository/ (I'm assuming you're not familiar with git - apologies if you are!). 
This will then trigger the test suite and can be reviewed by others.

**Comment by pedros007** [comment]
Linking issue to #5707
