### ISSUE TITLE
Internal Error while rendering svg in wms

### ISSUE THREAD

**Issue by JaegerFrank** [mapserver/mapserver#5716]
Rendering a SVG-Symbol in WMS GetMap crashes with "Internal Error" when "ANGLE 0".
Any other Angle renders OK, for example "ANGLE 0.0001"
The SVG-Symbol is part of the projekt PostNAS/ogr ALKIS.
SVG: https://github.com/norBIT/alkisplugin/blob/master/svg/alkis3632_2.svg 
PostNAS-Mail: https://lists.osgeo.org/pipermail/nas/2018-December/001078.html 
Mapserver Version 7.2.1 compiled on Debian 8
[alkis3632_2.zip](https://github.com/mapserver/mapserver/files/2643208/alkis3632_2.zip)

**Comment by jmckenna** [comment]
Cannot reproduce this, with MapServer 7.4.0  (MS4W 4.0 release), and testing through shp2img commandline, and also a WMS GetMap request.

Please also be sure to always submit a full test case, including a mapfile.   I've attached mine.  
[ticket-5716.zip](https://github.com/mapserver/mapserver/files/3282664/ticket-5716.zip)
