### ISSUE TITLE
Incorrect values in (Geo)JSON from WFS output with "/" in data?

### ISSUE THREAD

**Issue by nmtoken** [mapserver/mapserver#5721]
I have MapServer version 7.2.1 from [gisinternals](https://www.gisinternals.com/packageinfo.php?file=release-1911-x64-gdal-2-3-3-mapserver-7-2-1.zip) .

I have attempted to configure (Geo)JSON output with the following:

    OUTPUTFORMAT
        NAME "JSON"
        DRIVER "OGR/GEOJSON"
        MIMETYPE "application/json; subtype=geojson"
        FORMATOPTION "STORAGE=stream"
        FORMATOPTION "FORM=SIMPLE"
        FORMATOPTION "NATIVE_DATA=YES"
        FORMATOPTION "COORDINATE_PRECISION=8"
        FORMATOPTION "WRITE_BBOX=YES"
        FORMATOPTION "FILENAME=result.json"
        FORMATOPTION "DESCRIPTION=GeoJSON 2008"
    END
    # Intended for latest GeoJSON (CRS:84 only)
    # need to use outputformat=application/vnd.geo%2Bjson& in URL request
    # or shortcut use name like outputformat=GeoJSON
    OUTPUTFORMAT
        NAME "GeoJSON"
        DRIVER "OGR/GEOJSON"
        MIMETYPE "application/vnd.geo+json"
        FORMATOPTION "RFC7946=YES"
        FORMATOPTION "STORAGE=stream"
        FORMATOPTION "FORM=SIMPLE"
        FORMATOPTION "NATIVE_DATA=YES"
        FORMATOPTION "COORDINATE_PRECISION=8"
        FORMATOPTION "WRITE_BBOX=YES"
        FORMATOPTION "FILENAME=result.geojson"
        FORMATOPTION "DESCRIPTION=GeoJSON (RFC7946)"
    END

I find that on occasion, for example it seems to occur when there is a  "/" (Solidus) character in the data, that the JSON output is incorrect.

If we look at WFS request with GML output like below:

> http://ogc2.bgs.ac.uk/cgi-bin/UGA_ARGI/ows?service=WFS&request=GetFeature&version=2.0.0&typenames=INDMIN&srsName=EPSG:4326&bbox=1046611.16431066021323204,52065.82855911907972768,1473024.6636702548712492,711991.48232992039993405,EPSG:32635&

We can see for example feature with id INDMIN.81 we have a map sheet value of `61/3` reported and a representative Commodity URI with value `http://resource.geosciml.org/classifier/cgi/commodity-code/kaolin`

Using either JSON output format like:

> http://ogc2.bgs.ac.uk/cgi-bin/UGA_ARGI/ows?service=WFS&request=GetFeature&version=2.0.0&typenames=INDMIN&srsName=EPSG:4326&bbox=1046611.16431066021323204,52065.82855911907972768,1473024.6636702548712492,711991.48232992039993405,EPSG:32635&outputformat=JSON& 

Gives valid JSON but the values are not correct, for example the "representativeCommodity_uri" doesn't ever report an URI but rather an `N` value (from the GML) and other values are appear associated with the wrong member.  The number of properties is also one fewer than in the GML.

**Comment by sdlime** [comment]
I'm assuming this isn't limited to just MapServer 7.2?

**Comment by nmtoken** [comment]
Only tested with 7.2 and 7.2.1 will try to evaluate with older version

**Comment by nmtoken** [comment]
It appears it's some other data error, not mapserver
