### ISSUE TITLE
MVT: additional/missing data types

### ISSUE THREAD

**Issue by BergWerkGIS** [mapserver/mapserver#5726]
Similar to #5594 but I'm particularly interested in `Int64/BigInt/Long` support.

Looking at the code
https://github.com/mapserver/mapserver/blob/ffb119137bf339630ff9fd9b441a7745a9f84b6b/mapmvt.c#L270-L284
I see that only `Interger|Real|Boolean` get dedicated conversions whereas everything else gets converted to string.

However the docs for [`gml_[item name]_type`](https://mapserver.org/ogc/wfs_server.html#layer-object) state:
> Specifies the type of the attribute. Valid values are the OGR data types: Integer|**Long**|Real|Character|Date|Boolean. MapServer translates these to valid GML data types. 
Note: **Long is to be used for 64-bit integers, _starting with MapServer 7.0.1._**

Any change to get `Int64/BigInt/Long` support for MVT output format?

The [vector-tile-spec](https://github.com/mapbox/vector-tile-spec/blob/26b7823b16df1e15f55adb44243a3896acb7b804/2.1/vector_tile.proto#L17-L28) would support it 😄:

```proto
        message Value {
                // Exactly one of these values must be present in a valid message
                optional string string_value = 1;
                optional float float_value = 2;
                optional double double_value = 3;
                optional int64 int_value = 4;
                optional uint64 uint_value = 5;
                optional sint64 sint_value = 6;
                optional bool bool_value = 7;

                extensions 8 to max;
        }
```

----

Additional information:
* I use `CONNECTIONTYPE OGR` to connect to SQL Server
* `ogrinfo` identifies the data type correctly:
![image](https://user-images.githubusercontent.com/4549888/50988427-d8a51880-150c-11e9-9024-40b8ca860cce.png)
* By the way: `CONNECTIONTYPE PLUGIN / PLUGIN "msplugin_mssql2008.dll"` gets totally screwed by `BigInt`s.
Either empty string (even for `ogr_fid`) or garbage:
![image](https://user-images.githubusercontent.com/4549888/50988813-ffb01a00-150d-11e9-8585-27cfb8b4deff.png)

**Comment by sdlime** [comment]
I'm wondering if it's enough to have both GML types Int and Long use atol since internally both are handled as 64-bit ints in the MVT schema...

struct  _VectorTile__Tile__Value
{
  ProtobufCMessage base;
  char *string_value;
  protobuf_c_boolean has_float_value;
  float float_value;
  protobuf_c_boolean has_double_value;
  double double_value;
  protobuf_c_boolean has_int_value;
  int64_t int_value;
  protobuf_c_boolean has_uint_value;
  uint64_t uint_value;
  protobuf_c_boolean has_sint_value;
  int64_t sint_value;
  protobuf_c_boolean has_bool_value;
  protobuf_c_boolean bool_value;
};

**Comment by sdlime** [comment]
See https://github.com/mapserver/mapserver/pull/5747 where I added an explicit conversion for gml_[item]_type = long. --Steve

**Comment by sdlime** [comment]
Closing - can always re-open if necessary or create additional tickets for other type conversions. I think this covers what the GML documentation references in terms of supported types. --Steve

**Comment by BergWerkGIS** [comment]
Thanks for your fast response @sdlime.
I'll give it a spin this week and let you know how it works for me.

-----

> I'm wondering if it's enough to have both GML types Int and Long use atol since internally both are handled as 64-bit ints in the MVT schema...

I suppose for this use case it's ok to have both handled as int64 (less conditional statements 😄), although one might complain about memory usage when there are a lot of int properties.

Sorry if I come across nitpicky, that's not my intention, just want to add some additional information (at least how I understand it - might be completely wrong).

There's a difference between how numbers are stored in MVTs (as `varint`s, ints of variable length) and how they are represented in code:
* [Mapbox Protozero Cheat Sheet](https://github.com/mapbox/protozero/blob/a44efc34e5a86e93c06390aa19c89f8e115971f6/doc/cheatsheet.md)
* [Google proto docs](https://developers.google.com/protocol-buffers/docs/proto#scalar)
* [Decoding of varint in Mapbox protozero](https://github.com/mapbox/protozero/blob/51753d5146ffb8f57c67eb84c7b5dc2be0e829b0/include/protozero/varint.hpp#L33-L68)

**Comment by BergWerkGIS** [comment]
@sdlime it seems there's a bit more needed than the fix you provided.
But it's not urgent for me anymore as I've written my own MVT encoder in the meantime.

Nevertheless here are my latest findings which might help you pinpoint the problem.

* I tried with `Development Versions (daily)` from https://www.gisinternals.com/development.php as of today.
* My database schema (mainly `int`s and `bigint`s):
  ![image](https://user-images.githubusercontent.com/4549888/54298412-f9dfbf00-45b8-11e9-85ae-a078cfbf5dcc.png)
* **No `gml_type` definitions** (all properties are strings):
  ![image](https://user-images.githubusercontent.com/4549888/54298542-3d3a2d80-45b9-11e9-84ec-874140c0006b.png)
* **`"gml_types" "auto"`** some are strings and some are numbers:
  ![image](https://user-images.githubusercontent.com/4549888/54298579-4a571c80-45b9-11e9-8d93-72bb7e224007.png)
* With **`"gml_objectid_type" "Long"`** and **`"gml_fow_type" "Integer"`** both are still strings:
  ![image](https://user-images.githubusercontent.com/4549888/54299067-614a3e80-45ba-11e9-8832-7b8d4a2e82df.png)
