### ISSUE TITLE
building on Linux WIN32 is defined.

### ISSUE THREAD

**Issue by 3x0dv5** [mapserver/mapserver#5728]
Hi, trying to build c# mapscript on linux, for some reason the #if in 
https://github.com/mapserver/mapserver/blob/branch-7-2/mapscript/swiginc/map.i#L213
turns out to the TRUE so the generated file will have invalid code. __try is Microsoft VC instruction and not supported in Linux.

Anyone knows why would this be?

```
#if defined(WIN32) && defined(SWIGCSHARP)
    __try {
        return msDrawMap(self, MS_FALSE);
    }
    __except(1 /*EXCEPTION_EXECUTE_HANDLER, catch every exception so it doesn't crash IIS*/) {
        msSetError(MS_IMGERR, "Unhandled exception in drawing map image 0x%08x", "msDrawMap()", GetExceptionCode());
    }
#else    
    return msDrawMap(self, MS_FALSE);
#endif    
  }
```

**Comment by 3x0dv5** [comment]
Maybe something like https://cmake.org/cmake/help/v3.13/variable/CMAKE_COMPILER_IS_GNUCXX.html 

I wonder why would the #if defined(WIN32) would actually be true on Linux... 
Actually we would probably want to remove this exception handling, let the code calling this handle the exception. 

At the end I managed to compile mapscript_csharp for Linux but the bit above I ended commenting out the exception handling.
Here is a thread on what I had to do to make mapscript_c# on Linux:
http://osgeo-org.1560.x6.nabble.com/csharp-mapscript-dotnet-core-on-Linux-td5391329.html

**Comment by geographika** [comment]
@3x0dv5 - looks like this could be the reason WIN32 is set to True in SWIG? If the SWIG code can be made to be cross platform then I guess this flag could be removed?

https://github.com/mapserver/mapserver/blob/f49fa32641e8d95b048e4fd19fbef800013a6f4f/mapscript/csharp/CMakeLists.txt#L36

**Comment by 3x0dv5** [comment]
Yep that made the trick. 
https://github.com/3x0dv5/mapserver/commit/0e7c5e7f8fb14d16dd0c4112dab31e4bd49dbcdc

now I wonder why SWIG is generating twice the following for the file build/mapscript/csharp/mapscriptPINVOKE.cs
```c#
  static mapscriptPINVOKE() {
  }

```

**Comment by geographika** [comment]
@3x0dv5 - I think I ran into this too in https://github.com/mapserver/mapserver/pull/5583/commits/70ba3929f4b064c8bf8c34d7238b65179cbb51a6
Looks like the function was hard-coded, but in a more recent version of SWIG is now generated automatically. Not sure why this has reappeared for you though as you are updating against master which includes this change.

**Comment by 3x0dv5** [comment]
heck yeah! commenting the lines worked just great.

```csharp
%pragma(csharp) imclasscode=%{
//  static $imclassname() {
//  }
```
https://github.com/3x0dv5/mapserver/commit/318224d25bb6996951345a8f1e2611efd1b5f381

**Comment by 3x0dv5** [comment]
I raised a PR https://github.com/mapserver/mapserver/pull/5730, sorry I raised it against 7.2, didn't see 7.3, feel free to decline, change and use the code as part of any other PR.
