### ISSUE TITLE
Map DefResolution is double in mapscript and int in the docs

### ISSUE THREAD

**Issue by 3x0dv5** [MapServer/MapServer#5748]
in the docs says that DefResolution is int

> DEFRESOLUTION [int]
> 
>     Sets the reference resolution (pixels per inch) used for symbology. Default is 72.
> 
>     Used to automatically scale the symbology when RESOLUTION is changed, so the map maintains the same look at each resolution. The scale factor is RESOLUTION / DEFRESOLUTION.
> 
>     New in version 5.6.
_in https://mapserver.org/mapfile/map.html_

but the c# mapscript shows it as a double

```csharp
public double defresolution
    {
      set
      {
        mapscriptPINVOKE.mapObj_defresolution_set(this.swigCPtr, value);
        if (mapscriptPINVOKE.SWIGPendingException.Pending)
          throw mapscriptPINVOKE.SWIGPendingException.Retrieve();
      }
      get
      {
        double num = mapscriptPINVOKE.mapObj_defresolution_get(this.swigCPtr);
        if (mapscriptPINVOKE.SWIGPendingException.Pending)
          throw mapscriptPINVOKE.SWIGPendingException.Retrieve();
        return num;
      }
    }

```

**Comment by geographika** [comment]
Looking at https://github.com/mapserver/mapserver/blob/master/mapimagemap.c#L254 it seems it is the docs that are out-of-date. 

RESOLUTION is also an int in the docs (on the same page) but a double in the C code, so I believe this should also be changed.

**Comment by 3x0dv5** [comment]
isnt it a problem if defresolution is zero?

https://github.com/mapserver/mapserver/blob/ce2169f872009018c7bff1efa8853d7554669d23/mapimagemap.c#L275

```cpp
image->resolutionfactor = resolution/defresolution;
```

**Comment by 3x0dv5** [comment]
the PR for the docs correction

https://github.com/mapserver/docs/pull/272

**Comment by geographika** [comment]
> 
> 
> isnt it a problem if defresolution is zero?
> 
> [mapserver/mapimagemap.c](https://github.com/mapserver/mapserver/blob/ce2169f872009018c7bff1efa8853d7554669d23/mapimagemap.c#L275)
> 
> Line 275 in [ce2169f](/mapserver/mapserver/commit/ce2169f872009018c7bff1efa8853d7554669d23)
>  image->resolutionfactor = resolution/defresolution;

I'm getting errors such as `msGEOSError(): GEOS library error. @ÞÓV}` when using `DEFRESOLUTION 0` so it does look like it could be an issue.

**Comment by 3x0dv5** [comment]
because resolution and defresolution are double I think the result would be infinite ( NaN ) but wouldn't raise an exception. Although I could be wrong, my cpp skills are a bit rusty at this point.
