### ISSUE TITLE
PostGis dont create datanase

### ISSUE THREAD

**Issue by MajidDehnamaki** [mapserver/mapserver#5750]
hi
thank you for your sharing.
after i install PostgreSQL  and PostGIS i don't have template_postgis database

**Comment by yjacolin** [comment]
Just create a new database and enable postgis:
```
sudo -u postgres createdb mydb
sudo -u postgres psql -d mydb -c "CREATE EXTENSION postgis;"
```

template_postgis is not really usefull now.

Please, subscribe to the mapserver mailing list if you have any question on MapServer, don't create issue.
