### ISSUE TITLE
Label point calculation is not consistent

### ISSUE THREAD

**Issue by szekerest** [MapServer/MapServer#5752]
The formula when rotation != 0:

    sin_a = sin(rotation);
    cos_a = cos(rotation);

    x = x1 - tp->bounds.bbox.minx;
    y = tp->bounds.bbox.maxy - y1;
    q.x = p->x + (x * cos_a - (y) * sin_a);
    q.y = p->y - (x * sin_a + (y) * cos_a);

when rotation = 0:

  q.x = p->x + x1 - tp->bounds.bbox.minx;
  q.y = p->y + y1 ;

**Comment by sdlime** [comment]
@szekerest, can this be closed?

**Comment by szekerest** [comment]
I still haven't merged this pull, because I need to set up a linux environment and check the autotest failures (probably the expected result should be different because of this change)
