### ISSUE TITLE
Missing layer name in error messages

### ISSUE THREAD

**Issue by szekerest** [mapserver/mapserver#5755]
It is very annoying that most of the error messages miss the layer name, so it may be difficult to track the issue down for a complicted map configuration.
For example an invalid column name in a class/expression for an OGR layer (i.e. data schema has changed) generate this:

   msOGRLayerInitItemInfo(): OGR error. Invalid Field name: ZYONE

**Comment by sdlime** [comment]
@szekerest, can this be closed?

**Comment by thbaumann** [comment]
I think it would be very nice if for other error messages like MS_ORACLESPATIALERR (msOracleSpatialLayerWhichShapes,msOracleSpatialLayerNextShape...) there would also be the layername written in the error message. Normally (if you are not in debug mode) it is just:
`Map::outputMapimage: MS_ORACLESPATIALERR:
msOracleSpatialLayerWhichShapes(): 
Check your data statement and server logs
`
which makes it hard to track down errors in a production system.
