### ISSUE TITLE
c# mapscript OWSDispatch with OGR MSSQL fires query twice

### ISSUE THREAD

**Issue by BergWerkGIS** [mapserver/mapserver#5759]
I'm using c# mapscript bindings and MSSQL Server 2016 with ` CONNECTIONTYPE OGR` to generate vector tiles, but currently hitting a performance bottle neck which I think _could_ be due to all sql queries being fired twice when calling `OWSDispatch()`.

Also tried several `mapObj` on dedicated threads but always get the same number of tiles per second.

Any ideas how to prevent that or what could be wrong with my setup?

-----

<details>
<summary>(<= click) <b>OUTPUTFORMAT</b></summary>

```
OUTPUTFORMAT
  NAME "mvt"
  MIMETYPE "application/x-protobuf"
  DRIVER "mvt"
  EXTENSION "pbf"
  FORMATOPTION "EDGE_BUFFER=80"
  FORMATOPTION "EXTENT=4096"
END # OUTPUTFORMAT
```
</details>

<details>
<summary>(<= click) <b>Example layer definition</b></summary>

```
LAYER
  NAME "nodes"
  CONNECTIONTYPE OGR
  PROCESSING 'CLOSE_CONNECTION=DEFER'
  PROCESSING "MSSQL_READ_WKB=TRUE"
  EXTENT 9 46 19 49.5
  METADATA
    "wms_srs" "EPSG:31256 EPSG:3857 EPSG:4326"
    "coordsys_name" "+init=epsg:4326"
    "wms_description" "nodes"
    "gml_include_items" "all"
    "wms_title" "nodes"
  END # METADATA
  PROJECTION
    "init=epsg:4326"
  END # PROJECTION
  STATUS ON
  TEMPLATE "ttt"
  TILEITEM "location"
  TYPE POINT
  CLASS
    NAME "nodes"
    STYLE
      COLOR 255 0 0
      OUTLINECOLOR 0 0 0
      SIZE 5
      SYMBOL "circle"
    END # STYLE
    TITLE ""
  END # CLASS
END # LAYER
```
</details>

No `CONNECTION` set in the layer definition as that gets set in code:
```csharp
mapObj map = new mapObj(mapFileName);
layerObj lyrEdges = _maps[i].getLayerByName("edges");
layerObj lyrNodes = _maps[i].getLayerByName("nodes");
lyrEdges.connection = $"MSSQL:Server={GlobalConfig.SqlServerHost};database={GlobalConfig.SqlServerDb};uid={GlobalConfig.SqlServerUser};pwd={GlobalConfig.SqlServerUserPwd}";
lyrNodes.connection = $"MSSQL:Server={GlobalConfig.SqlServerHost};database={GlobalConfig.SqlServerDb};uid={GlobalConfig.SqlServerUser};pwd={GlobalConfig.SqlServerUserPwd};tables=nodes(geom)";
```

No table name in the connection string for layer `edges` as I need zoom dependent simplification and other data thinning.
`DATA` is also set via code:
```csharp
lyrEdges.data = Invariant($@"
SELECT 
[ogr_fid], [geom].Reduce({_tolerances[z]:0.00000}) AS geom{additionalFields}
FROM vw_edges 
WHERE geom.STIntersects(geometry::STGeomFromText('POLYGON(({poly}))',4326)) = 1 AND {frc}"
);
```

OWSRequest:
```csharp
OWSRequest ows = new OWSRequest();

ows.setParameter("SERVICE", "WMS");
ows.setParameter("VERSION", "1.1.1");
ows.setParameter("REQUEST", "GetMap");
ows.setParameter("SRS", "EPSG:4326");
ows.setParameter("BBOX", Invariant($"{lowerLeft.X},{lowerLeft.Y},{upperRight.X},{upperRight.Y}"));
if (format.Equals("image/png")) {
    ows.setParameter("WIDTH", "256");
    ows.setParameter("HEIGHT", "256");
} else {
    ows.setParameter("WIDTH", mvtExtent);
    ows.setParameter("HEIGHT", mvtExtent);
}
ows.setParameter("STYLES", "");
if (z < 16) {
    ows.setParameter("LAYERS", "edges");
} else {
    ows.setParameter("LAYERS", "nodes,edges");
}
ows.setParameter("FORMAT", format);

mapscript.msIO_installStdoutToBuffer();
int dispatchResult = map.OWSDispatch(ows);
```

As soon as I step over `map.OWSDispatch(ows)` I see in SQL Server Profiler that the exact same query gets executed twice.
The second one always taking somewhere between 2.5 and 3.5 times of the first one.

![image](https://user-images.githubusercontent.com/4549888/53839433-c3da8380-3f97-11e9-9e42-4c88f803ce7d.png)

**Comment by BergWerkGIS** [comment]
Maybe one stems from setting `lyrEdges.data` myself and the other one from the WMS `BBOX` parameter?

**Comment by geographika** [comment]
Are you running on Linux? If not did you try with the MSSQL driver?
From memory there are always 2 calls for most image generation with the MSSQL driver, but the first is a `SELECT TOP 0` used to get field types I think.

**Comment by BergWerkGIS** [comment]
thanks @geographika I'll double check if I overlooked `SELECT TOP 0`.
But IIRC from what I saw in SQL Profiler getting field properties only happens once in a while and not with every request.
Maybe because I'm using `PROCESSING 'CLOSE_CONNECTION=DEFER'` (That line got lost in my original post, added now).

I'm on Windows and tried `msplugin_mssql2008.dll` before but I faced some issues with fields being empty or containing garbage in the MVT (mentioned at the bottom of my comment https://github.com/mapserver/mapserver/issues/5726#issue-397960718):

![image](https://user-images.githubusercontent.com/4549888/50988813-ffb01a00-150d-11e9-8585-27cfb8b4deff.png)

**Comment by BergWerkGIS** [comment]
@geographika  wrt `SELECT TOP 0`: both queries are exactly the same.

**First:**
![image](https://user-images.githubusercontent.com/4549888/53989568-8fe19880-4126-11e9-8767-4774c89ff7df.png)

**Second:**
![image](https://user-images.githubusercontent.com/4549888/53989574-93751f80-4126-11e9-89c9-5871010b7d9e.png)

**Comment by geographika** [comment]
@BergWerkGIS - interesting with regards to MSSQL driver and bigints. Did you manage to track down where the problem is? It is probably worth opening a new issue with any details relating to this if you get a chance. 

Does SQL Profiler show 2 select statements when running the same OWS Request from the command line? Maybe save the Mapfile from within your MapScript script and the run something like: 

`mapserv -nh "QUERY_STRING=map=mapfile.map&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap..."`

**Comment by BergWerkGIS** [comment]
@geographika 

> interesting with regards to MSSQL driver and bigints. Did you manage to track down where the problem is?

Unfortunately not, had to get started as fast as possible and didn't spend a lot of time investigating.

> Does SQL Profiler show 2 select statements when running the same OWS Request from the command line? 

Yes.
I saved the mapfile ([geographika-test.map.txt](https://github.com/mapserver/mapserver/files/2946032/geographika-test.map.txt) - some information removed) from my code and executed from the commandline like this (without the line breaks of course):


```
mapserv -nh "QUERY_STRING=
map=geographika-test.map
&SERVICE=WMS
&VERSION=1.1.1
&REQUEST=GetMap
&SRS=EPSG:4326
&BBOX=15.64453125,48.385440826416,15.655517578125,48.3927383422852
&WIDTH=4096
&HEIGHT=4096
&STYLES=
&LAYERS=edges
&FORMAT=application/x-protobuf"
```

Result is still the same, same query gets executed twice:

![image](https://user-images.githubusercontent.com/4549888/54032407-d16b5580-41b1-11e9-9dbb-1e82184ffcee.png)

Maybe it's because I'm "misusing" OWS/WMS request with my own DATA definition to cut tiles?

I briefly had looked at [Tile Mode](https://mapserver.org/output/tile_mode.html#tile-mode) too but IIRC the C# bindings are still missing.

**Comment by geographika** [comment]
@BergWerkGIS - with regards to the MSSQL driver issue, did you set the gml_FIELD_type to "Long"?
A brief glance at the source shows it should also be support by setting "gml_types" "auto":

https://github.com/mapserver/mapserver/blob/7774a791eb9acfd4f18071c08f454a50b621e0d8/mapmssql2008.c#L873

The firing twice issue looks unrelated to MapScript if it also happens from the command line also. Possibly the OGR MSSQL driver? https://www.gdal.org/drv_mssqlspatial.html

**Comment by BergWerkGIS** [comment]
@geographika 
> with regards to the MSSQL driver issue, did you set the gml_FIELD_type to "Long"?
> A brief glance at the source shows it should also be support by setting "gml_types" "auto":

I had tried all the possible values `Long`/`Real`/..., except `auto` which I wasn't aware of.

> The firing twice issue looks unrelated to MapScript if it also happens from the command line also. Possibly the OGR MSSQL driver? https://www.gdal.org/drv_mssqlspatial.html

Good point, I'll check if I can reproduce with maybe `ogrinfo`.

**Comment by BergWerkGIS** [comment]
@geographika you were right, those redundant queries stem from `MSSQLSpatial`.
Thanks for your help.

```
ogrinfo -sql 
     "SELECT ogr_fid, geom FROM vw_edges WHERE ogr_fid=1" 
     "MSSQL:server=MyServer;database=MyDb;uid=MyUid;pwd=MyPwd"
```

![image](https://user-images.githubusercontent.com/4549888/54289578-b6ca1f80-45a9-11e9-98f3-533112b04855.png)
