### ISSUE TITLE
Use (and placement) of CONFIG section

### ISSUE THREAD

**Issue by jbelien** [mapserver/mapserver#5761]
When I use a `CONFIG` section in my mapfile (MapServer 7.2.2) it doesn't seem to read/process what's after the `CONFIG` section.

---

**Example 1:**

```
MAP
  NAME "TEST"

  CONFIG
    MS_ERRORFILE "/tmp/mapserver.log"
  END

  WEB
    METADATA
      "wms_title" "Test"
      "wms_enable_request" "*"
      "wms_srs" "EPSG:4326 EPSG:3857"
    END
  END

  LAYER
    ...
  END # LAYER
END
```

https://localhost/cgi-bin/mapserv?map=test.map&service=WMS&request=GetCapabilities returns: 
```
msWMSGetCapabilities(): WMS server error. WMS request not enabled. Check wms/ows_enable_request settings.
```

**Example 2:**

```
MAP
  NAME "TEST"

  WEB
    METADATA
      "wms_title" "Test"
      "wms_enable_request" "*"
      "wms_srs" "EPSG:4326 EPSG:3857"
    END
  END

  CONFIG
    MS_ERRORFILE "/tmp/mapserver.log"
  END

  LAYER
    ...
  END # LAYER
END
```

https://localhost/cgi-bin/mapserv?map=test.map&service=WMS&request=GetCapabilities returns the GetCapabilities but with the following warning: 
```
WARNING: No WMS layers are enabled. Check wms/ows_enable_request settings. 
```

**Example 2:**

```
MAP
  NAME "TEST"

  WEB
    METADATA
      "wms_title" "Test"
      "wms_enable_request" "*"
      "wms_srs" "EPSG:4326 EPSG:3857"
    END
  END

  LAYER
    ...
  END # LAYER

  CONFIG
    MS_ERRORFILE "/tmp/mapserver.log"
  END
END
```

https://localhost/cgi-bin/mapserv?map=test.map&service=WMS&request=GetCapabilities works just fine !

**Comment by jbelien** [comment]
Well ... My deepest apologies ...

Just checked the [documentation](https://www.mapserver.org/mapfile/map.html) and `CONFIG` is not a section !

Correct syntax is `CONFIG [key] [value]` and with the correct syntax, everything works (of course) just fine !
Sorry for the "spam" !

**Comment by jmckenna** [comment]
please @jbelien do not use the issue tracker for questions.  Please send your questions direct to the MapServer community on its mailing list (subscribe at https://lists.osgeo.org/mailman/listinfo/mapserver-users).  I am sorry if that was not clear to you.

**Comment by jbelien** [comment]
Thanks @jmckenna !

I know that I should use the mailing list for questions but, before reading the documentation more carefully, I really thought it was a real issue :)

**Comment by jmckenna** [comment]
Best to bring all of your issues direct to the MapServer community for discussion first, then once the community agrees that it is a bug, come here to report the bug.  The point is to get as much free help that you can, free eyes, on your issue as possible - and that is the mailing list, where over 2,000 eyes are waiting to help you. :)
