### ISSUE TITLE
Pip3 Mapscript install produces syntax error

### ISSUE THREAD

**Issue by jorgejesus** [mapserver/mapserver#5767]
Trying to install mapscript 5.6.3.0 with pip3 produced an error concerning syntax
`
pip3 install mapscript==5.6.3.0
`
Generates:
```
Collecting mapscript==5.6.3.0
  Using cached https://files.pythonhosted.org/packages/2a/4a/89ac6d24d2a93ee4f4bb1d3d9bdc0af8e86ba000a12a69fd3ed1e1907948/mapscript-5.6.3.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-w1fjp6yt/mapscript/setup.py", line 43
        except Exception, e:
                        ^
    SyntaxError: invalid syntax
```
This old python 2.6 syntax and is depreciated on python3 and newer versions of python

**Comment by geographika** [comment]
@jorgejesus - Python3 MapScript support was added in 7.2 following an 8 year hiatus. The Python bindings are now py2 and py3 compatible, along with the creation of a proper Python module and wheels. 

See https://github.com/mapserver/mapserver/wiki/Python-MapScript-Updates-2018 for further details. 

The changes probably could be backported to earlier releases, but focus is currently on updating the MapScript docs and examples which are a little out-of-date.

**Comment by geographika** [comment]
@jorgejesus - closing this as I can't see the build process being backported and pypi updated for MapServer 5.x
Let me know if you run into any problems with the new 7.x MapScript Python bindings.
