### ISSUE TITLE
PHP MapScript built but not installed

### ISSUE THREAD

**Issue by sebastic** [mapserver/mapserver#5770]
PHP MapScript in MapServer 7.4.0-beta1 builds, but doesn't install, because the install command is commented out:
```cmake
set_target_properties(php_mapscript PROPERTIES PREFIX "")
#install(TARGETS php_mapscript DESTINATION ${PHP_EXTENSION_DIR})
```

**Comment by geographika** [comment]
Thanks @sebastic 
I wasn't sure if this would maybe cause issues with the original PHPMapScript. The bulds seem fine on Travis so should be fine. 
Note also this came up at https://gis.stackexchange.com/questions/308999/how-to-compile-install-php-mapscript-with-php7

**Comment by sebastic** [comment]
> I wasn't sure if this would maybe cause issues with the original PHPMapScript.

This is the original PHP MapScript.

PHPNG installs `php_mapscriptng.so` instead of `php_mapscript.so`.

The mapserver Debian package now builds both and installs the libraries in the php-mapscript & php-mapscript-ng packages.

> The bulds seem fine on Travis so should be fine.

Travis doesn't test the install target, only the test target.
