### ISSUE TITLE
Switch Travis to use xenial or bionic (trusty EOL in April 2019)

### ISSUE THREAD

**Issue by sebastic** [mapserver/mapserver#5775]
With Ubuntu trusty going EOL in April, the Travis builds should be switched to xenial.

**Comment by geographika** [comment]
I think the main issue with updating is all the msautotest images will need to be regenerated and checked as per #5615 for the last update. 

Moving away from trusty will mean a newer version of SWIG can be used. Currently 2.0.11 is installed, but 3.0.11 is required for PHP7 support.

**Comment by rouault** [comment]
Travis-CI has now 18.04 / bionic. Would probably be a better target. We'd need to update Vagrant as well. Actually updating Vagrant first would probably be the easiest, so as to be able to locally debug issues. Perhaps a topic for the code sprint.

**Comment by geographika** [comment]
Also to note there are a number of improvements to CMake which is stuck at v2 on trusty. 
Ideally we can target CMake 3.12 as a minimum.
