### ISSUE TITLE
Perl MapScript not built as part of CI

### ISSUE THREAD

**Issue by geographika** [mapserver/mapserver#5777]
Currently Perl MapScript is not built as part of Continuous Integration on either Travis (Linux) or Appveyor (Windows). 

To add to Travis will require Perl dependencies (libperl-dev?) to be installed in .travis.yml (see https://github.com/mapserver/mapserver/blob/branch-7-4/.travis.yml#L55)

DWITH_PERL=1 will need to be added to the CMAKE FLAGS at https://github.com/mapserver/mapserver/blob/branch-7-4/Makefile#L9

Finally it would be good to run the [Perl MapScript examples ](https://github.com/mapserver/mapserver/tree/branch-7-4/mapscript/perl/examples) in the MakeFile or as part of perl/CMakeLists.txt/ to ensure nothing breaks with code changes.

**Comment by AndyColson** [comment]
Can CI run:
    cmake <whatever>
    make 
    make test

I'd like to put the tests into `make test`, if thats ok.  I've uploaded a little test that works for me:

[github](https://github.com/AndyColson/mapserver/commit/58d76a4c275353925ddb508b1d95627c74a860a4)

Is this direction ok?

**Comment by geographika** [comment]
There are currently 2 approaches for the different MapScript bindings:

1. Run the tests via CMAKE in a custom target, which calls custom commands. For example in Python MapScript see https://github.com/mapserver/mapserver/blob/branch-7-4/mapscript/python/CMakeLists.txt#L106 for the commands and https://github.com/mapserver/mapserver/blob/branch-7-4/mapscript/python/CMakeLists.txt#L73 for the custom target. 

Then call this custom target https://github.com/mapserver/mapserver/blob/branch-7-4/.travis.yml#L69

`make mspython-wheel `

The advantage of this approach is that the test can be more easily called and run across platforms (Windows and Linux). 

2. Write a shell script and call this via the Make file e.g for C# MapScript:

https://github.com/mapserver/mapserver/blob/branch-7-4/mapscript/csharp/run_test.sh

https://github.com/mapserver/mapserver/blob/branch-7-4/Makefile#L50

If you create a pull request with whichever approach is easiest for you it will trigger the Travis build and you can see the output. 

Just on the code changes, watch out for IDEs autoformatting code and adding spaces/new lines as it makes it harder to see the code changes. Also rename /t to /tests?

Hope this makes things clearer, and not more complicated!

**Comment by geographika** [comment]
Closed with #5778
