### ISSUE TITLE
layer Opacity in PHP Swig Mapscript for ms4w 4.0

### ISSUE THREAD

**Issue by jwgda** [mapserver/mapserver#5788]
Setting the opacity property on a layerObj in PHP Mapscript SWIG seems to be ignored in ms4w 4.0 -- the OPACITY attribute is not written out to the mapfile upon save.

E.g.

`$oLayer= new layerObj($oMap);
$oLayer->opacity = 30;`

Setting the OPACITY directly in a saved MAPFILE does work, however.

**Comment by jwgda** [comment]
Nevermind - I found the setOpacity method which sets the opacity in the COMPOSITE block by looking through the mapscript swig code.

It needs to be added to the documentation in https://mapserver.org/mapscript/mapscript.html#layerobj

**Comment by jmckenna** [comment]
@jwgda can you file this as a new docs ticket at https://github.com/mapserver/docs/issues please? I'll tackle that there once you do.

**Comment by jwgda** [comment]
Done.  Closing this ticket.
