### ISSUE TITLE
msProcessProjection(): Projection library error. proj error only one +init allowed for non-pipeline operations

### ISSUE THREAD

**Issue by akrherz** [mapserver/mapserver#5789]
I'm getting a strange error with current master build + proj4 5.2.0.  Making a previously working WMS request results in the following error
```html
<HTML>
<HEAD><TITLE>MapServer Message</TITLE></HEAD>
<!-- MapServer version 7.5-dev OUTPUT=PNG OUTPUT=JPEG SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=FASTCGI SUPPORTS=GEOS INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE -->
<BODY BGCOLOR="#FFFFFF">
msProcessProjection(): Projection library error. proj error &quot;only one +init allowed for non-pipeline operations&quot; for &quot;init=epsg:4326:init=epsg:4326&quot;
</BODY></HTML>
```
I can't seem to resolve where this issue could be coming from.  Is it just an incompatibility with that version of proj4 ?

**Comment by akrherz** [comment]
I was hoping the obvious bug would hit me when I made noise here....

The issue is that proj4 version 5.2.0 is more exact about my sloppy mapfile, which had this

```
  PROJECTION
    "init=epsg:4326"
    "init=epsg:4326"
  END
```

removing the redundant entry solved the issue.  Hopefully this issue helps others that hit this.  Sorry mapserver folks for the noise.

**Comment by jmckenna** [comment]
Please do not use the tracker to ask questions; instead, please ask your questions direct to the mapserver-users community on its mailing list. Subscribe at https://lists.osgeo.org/listinfo/mapserver-users  Thank you.
