### ISSUE TITLE
Not recieving attributes with MVT tiles

### ISSUE THREAD

**Issue by maeneak** [mapserver/mapserver#5791]
The key/value pairs of feature attributes/properties don't seem to be encoded in MVT tile output. Is this by design or am i missing something? I've tested with both SHP and OGR GeoJSON input and reading through the spec they should be available

**Comment by sdlime** [comment]
This should be a question for one of the mailing lists... Like with GML, KML or JSON output you must explicitly expose attributes for output through metadata. See my example mapfile: https://github.com/sdlime/mvt-demo/blob/master/demo.map. --Steve

**Comment by maeneak** [comment]
Thanks @sdlime ! I was missing the "gml_include_items" metadata attribute. Apologies ill get onto the mailing lists.
