### ISSUE TITLE
Having vsis3 issue, Credentials malformed error need someone to verify if its just on my end

### ISSUE THREAD

**Issue by bmulcahy** [mapserver/mapserver#5794]
I am having issues using vsis3 as a datasource in mapserver to get to a s3 hosted tif file that requires credentials.. but I am not sure if its just something I am doing or if it is actually a bug and would like someone to verify it is working.

To replicate create any non public s3 bucket, export access keys,  and upload a .tiff to it and then set up a mapfile to pull from that s3 bucket. 

Here is my call to the data in my mapfile 

`
DATA		"/vsis3/usace-dev-tiles-iwrss/usace-tiles-iwrss/tiles/%TABLE%/%TABLE_ID%/%RASTER_INFO_ID%_COG.tif"
`

Before that I include a .inc file with my config settings which are
`
CONFIG AWS_REGION "us-east-2"
CONFIG AWS_SECRET_ACCESS_KEY "redacted"
CONFIG AWS_ACCESS_KEY_ID "redacted"
`

the exact error message that is returned from mapserver is 
`
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException>
msDrawMap(): Image handling error. Failed to draw layer named 'cog_layer'. msDrawRasterLayerLow(): Unable to access file. Corrupt, empty or missing file '/vsis3/usace-dev-tiles-iwrss/usace-tiles-iwrss/tiles/FLOOD_DEPTH/5105962/148_COG.tif' for layer 'cog_layer'. Malformed AWS XML response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the Credential is mal-formed; expecting "&lt;YOUR-AKID&gt;/YYYYMMDD/REGION/SERVICE/aws4_request".</Message><RequestId>F5DC040AF393EF1E</RequestId><HostId>fFpAED2yfEn01rHTAjQWqcrptRJxwYP/jV6LehUv2E8FVSASWGdmI4NxY4reU0XETtXjepaIVrs=</HostId></Error>
</ServiceException>
</ServiceExceptionReport>
`

Now the weird thing is, and why I wanted someone to verify it is working, I can get gdalinfo to work fine via
`
gdalinfo --config AWS_REGION "us-east-2" --config AWS_ACCESS_KEY_ID "redacted" --config AWS_SECRET_ACCESS_KEY "redacted" /vsis3/usace-dev-tiles-iwrss/usace-tiles-iwrss/tiles/FLOOD_DEPTH/5105962/148_COG.tif
`
and it returns
`
Driver: GTiff/GeoTIFF
Files: /vsis3/usace-dev-tiles-iwrss/usace-tiles-iwrss/tiles/FLOOD_DEPTH/5105962/148_COG.tif
Size is 29527, 22291
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (-83.114935945986602,39.425952423637611)
Pixel Size = (0.000094663987169,-0.000094663987169)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=DEFLATE
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -83.1149359,  39.4259524) ( 83d 6'53.77"W, 39d25'33.43"N)
Lower Left  ( -83.1149359,  37.3157975) ( 83d 6'53.77"W, 37d18'56.87"N)
Upper Right ( -80.3197924,  39.4259524) ( 80d19'11.25"W, 39d25'33.43"N)
Lower Right ( -80.3197924,  37.3157975) ( 80d19'11.25"W, 37d18'56.87"N)
Center      ( -81.7173642,  38.3708750) ( 81d43' 2.51"W, 38d22'15.15"N)
Band 1 Block=512x512 Type=Float32, ColorInterp=Gray
  Min=0.000 Max=95.221
  Minimum=0.000, Maximum=95.221, Mean=26.750, StdDev=20.102
  NoData Value=0
  Overviews: 14764x11146, 7382x5573, 3691x2787, 1846x1394, 923x697, 462x349
  Metadata:
    STATISTICS_MAXIMUM=95.220764160156
    STATISTICS_MEAN=26.750223720123
    STATISTICS_MINIMUM=6.103515625e-05
    STATISTICS_STDDEV=20.10188641063
    STATISTICS_VALID_PERCENT=1.013
`

**Comment by pedros007** [comment]
Hi @bmulcahy this type of question should be asked on the [mapserver-users mailing list](https://lists.osgeo.org/mailman/listinfo/mapserver-users).

Can you load the image if you change your mapfile to point to `DATA` at a local path on the filesystem?  If you point to a GeoTIFF in a public bucket, can you get it working?

This portion suggests something might be wrong with the credentials in your `inc` file. 

```Malformed AWS XML response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the Credential is mal-formed; expecting "&lt;YOUR-AKID&gt;/YYYYMMDD/REGION/SERVICE/aws4_request".</Message><RequestId>F5DC040AF393EF1E</RequestId><HostId>fFpAED2yfEn01rHTAjQWqcrptRJxwYP/jV6LehUv2E8FVSASWGdmI4NxY4reU0XETtXjepaIVrs=</HostId></Error>```

**Comment by bmulcahy** [comment]
Will do at with the mapserver-users

I can get it to connect via normal vsicurl when it does not require credentials and if the file is local.

I was thinking the same thing as you about the credentials but I verified it multiple times

Is that the correct format for the inc file what I listed above with the values enclosed by quotations? Will mapserver/gdal throw an error if vsis3 cannot find the secret key or access key?

**Comment by pedros007** [comment]
my credentials look like this:
```
        # credentials.inc
        CONFIG "AWS_ACCESS_KEY_ID" "redacted"
        CONFIG "AWS_SECRET_ACCESS_KEY" "redacted"
```
and my MapFile includes this statement:
```
    INCLUDE                                   "credentials.inc"
```

**Comment by bmulcahy** [comment]
So this was an issue unrelated to MAPSERVER I got it working correctly today!

**Comment by jmckenna** [comment]
@bmulcahy please do send your future questions direct to the MapServer-users mailing list (subscribe at https://lists.osgeo.org/listinfo/mapserver-users ) where thousands are ready to assist you, and also readers there will benefit from your discussion and ideas.  Thanks again.

**Comment by kfaschoway** [comment]
how did you fix the issue?
