### ISSUE TITLE
Oracle Spatial latest OCI requires adding libnnz18 to the FindOracle.cmake script

### ISSUE THREAD

**Issue by bmulcahy** [mapserver/mapserver#5796]
Line 40 of the mapserver/cmakeFindOracle.cmake macro needs to have an additional file name added to support the latest Instant Client which uses libnnz18 and not libnnz12

```
set(ORACLE_NNZ_NAMES nnz10 libnnz10 nnz11 libnnz11 nnz12 libnnz12 ociw32)
```

to
```
set(ORACLE_NNZ_NAMES nnz10 libnnz10 nnz11 libnnz11 nnz12 libnnz12 nnz18 libnnz18 ociw32)
```

**Comment by bmulcahy** [comment]
Another option would be to add to the OCI plugin documentation to create a symbolic link for the libnnz18( or any future version number) to a generic libnnz name. That way you don't have to update the source code for each new iteration of the OCI library files. I can provide a pull request for either one. Thoughts?

**Comment by jmckenna** [comment]
I'm not sure how your second option would work for all versions.     However a pull request for either option is encouraged :)

**Comment by jmckenna** [comment]
Merged into master and branch-7-4     Thanks @bmulcahy
