### ISSUE TITLE
Does not detect postgresql 11

### ISSUE THREAD

**Issue by stoecker** [mapserver/mapserver#5808]
See build log:

https://build.opensuse.org/public/build/Application:Geo/openSUSE_Tumbleweed/x86_64/mapserver/_log

**Comment by jmckenna** [comment]
Please send your question direct to the MapServer-users community (subscribe at https://lists.osgeo.org/mailman/listinfo/mapserver-users).  Also be sure to include your full cmake command for the users to read there.

**Comment by stoecker** [comment]
I report a bug with complete log showing the issue and you close the ticket a month later directing me to a users forum. That's not real, isn't it?

**Comment by jmckenna** [comment]
It's real.  If you want faster support there are professional service providers available.  However it is true, questions should first be sent to the MapServer-users forum.

**Comment by stoecker** [comment]
I don't have a question. As you can see I'm packager of your software for openSUSE and reported a BUG because the software does not build anymore with a recent OS.

It's totally unclear how a users forum should help me here. I package this software and hundreds of others for years now and I know what I'm doing, but it seems you are even unable to see a bug when you are told about it.

For the records: The log contains all information about installed software versions and executed commands and thus everything needed to reproduce it. This is a "build service log". It builds software!

**Comment by jmckenna** [comment]
One month has went by, it is best for you to first send your questions and possible bugs to the mailing list, where thousands of eyes can help you first, give feedback, and help you narrow down the issue.

**Comment by jmckenna** [comment]
I am sorry I did not review you, this is nothing personal, I just feel that you can get more eyes on your issue by sending it to where the eyes are.   Someone I bet has been here before, your issue.

**Comment by jmckenna** [comment]
reopening your issues.   I tried to get more eyes on your issues by having you ask the community.  Very sorry for that.

**Comment by stoecker** [comment]
For postgresql 11 includes have been split in server and non-server includes. mapserver needs the server includes as well, so this issue could be fixed by providing the postgresql-server-devel package as well.

It would be nice if the INSTALL or README file had a list of dependencies which must be installed before building.
