### ISSUE TITLE
WMS Symbols on the edge of the tile will be incomplete

### ISSUE THREAD

**Issue by wangli-dev** [mapserver/mapserver#5809]
![brokenSymbol](https://user-images.githubusercontent.com/43267720/57921291-97b07c80-78cf-11e9-9698-6bb119dab71a.png)
![brokenSymbol1](https://user-images.githubusercontent.com/43267720/57921293-98491300-78cf-11e9-9fbe-1152ac082ca0.png)

**Comment by wangli-dev** [comment]
![Uploading brokenSymbol2.png…]()

**Comment by wangli-dev** [comment]
![brokenSymbol2](https://user-images.githubusercontent.com/43267720/57995714-3cac9e80-7af6-11e9-8daf-4d0c1816145b.png)

**Comment by sdlime** [comment]
What sort of meta-tile and edge buffer settings are you using? --Steve

**Comment by jratike80** [comment]
If you use Mapserver WMS directly with OpenLayers or Leaflet you should use the single tile mode as documented in http://dev.openlayers.org/examples/single-tile.html and http://heigeo.github.io/leaflet.wms/examples/.

The mapserver-users mailing list is the right forum for asking questions about how to use Mapserver. This is a bug tracker. If the conclusion from the discussion on the mailing list is that you have found a new bug you can then create an issue to Github.

**Comment by wangli-dev** [comment]
> What sort of meta-tile and edge buffer settings are you using? --Steve

I haven't used meta-tile and edge buffer settings for icons and tiles yet. Can these settings solve this problem? Can you tell me where I should go to find information?

**Comment by wangli-dev** [comment]
> If you use Mapserver WMS directly with OpenLayers or Leaflet you should use the single tile mode as documented in http://dev.openlayers.org/examples/single-tile.html and http://heigeo.github.io/leaflet.wms/examples/.
> 
We are using OpenLayers, the single tile does not have this problem, but the single tile cannot be cached, and the single tile is slower.

**Comment by jratike80** [comment]
If you use Mapserver directly all you can do is to use the single tile mode. WMS server renders each GetMap response individually and it does not know anything about the adjacent tiles. Alternative for single tile mode is to set up a special tile caching software in between. That can make over-sized requests to the WMS server and split the bigger initial map into 256x256 tiles and then labels and symbols are not cut, at least not as often. You probably want to use MapCache but GeoWebCache has better documentation about the concept of metatiles https://www.geowebcache.org/docs/current/concepts/metatiles.html.

There is no bug involved so you for sure understand why this issue will be closed soon.

**Comment by wangli-dev** [comment]
Well, so that mapserver can not handle this problem alone, need to use mapcache or geowebcache, I saw many such problems in mapserver-user, but it seems that they have not been effectively solved, I think can be buffered with the largest symbol size Drawing to the area should solve this problem. I will try it, thank you.


> If you use Mapserver directly all you can do is to use the single tile mode. WMS server renders each GetMap response individually and it does not know anything about the adjacent tiles. Alternative for single tile mode is to set up a special tile caching software in between. That can make over-sized requests to the WMS server and split the bigger initial map into 256x256 tiles and then labels and symbols are not cut, at least not as often. You probably want to use MapCache but GeoWebCache has better documentation about the concept of metatiles https://www.geowebcache.org/docs/current/concepts/metatiles.html.
> 
> There is no bug involved so you for sure understand why this issue will be closed soon.

**Comment by sdlime** [comment]
The MapServer CGI also has a mode=tile (https://mapserver.org/output/tile_mode.html) that can be used but is not WMS. It to uses a tile buffer option to deal with symbol/label clipping at the edge of tiles. It works pretty well but can be hard on a server since each tile is rendered separately with its own buffer. Metatiles are much more effective in my experience.

--Steve
