### ISSUE TITLE
GDAL Open/Options

### ISSUE THREAD

**Issue by woodmeister123** [mapserver/mapserver#5812]
Is there any method of passing open options through to the GDAL/OGR driver through map files? We would particularly like to enable auto zoom selection for MVT MBtiles.

**Comment by jmckenna** [comment]
Please do not use the issue tracker for questions.  Send your questions direct to the MapServer community (subscribe at https://lists.osgeo.org/mailman/listinfo/mapserver-users) where thousands of eyes are waiting to assist you.  Thank you.
