### ISSUE TITLE
PHP related documentation

### ISSUE THREAD

**Issue by arthur-clifford** [mapserver/mapserver#5814]
Less an issue, more a feature request.

With version 5.4 my understanding was that PHP7 mapscript should be part of the release.  But, the PHP MapScript page still has the warning about still being under development.

Also, the PHP part of the installation instructions are still referring to php5 instead of php 7.
https://mapserver.org/installation/php.html#php-install
Note it was last updated: 2016-06-15

Now that you have gotten things working with PHP 7, it would be good if the PHP related documentation should be reviewed for any changes that would help reflect the support for PHP 7.

**Comment by jmckenna** [comment]
Please file this ticket inside the /docs repository.   here--> https://github.com/mapserver/docs/issues/

**Comment by arthur-clifford** [comment]
Thank you for the quick reply, as requested :

https://github.com/mapserver/docs/issues/276
