### ISSUE TITLE
WMS layer cause crash if intersecting rectangle is 1px

### ISSUE THREAD

**Issue by wicksell** [mapserver/mapserver#5815]
MapServer will crash if a WMS layer cover only part of the requested extent and the resulting WMS request will be 1 pixel wide or high. 

I have tracked this down to a problem with MS_CELLSIZE which always subtract one from the pixel distance resulting in a division by zero and an invalid cell size. This will later cause MapServer trying to create an image of size -2147483648.

I do not know what the correct fix for this is. Maybe MS_CELLSIZE should be redefined as
`#define MS_CELLSIZE(min,max,d) (((max) - (min))/(MS_MAX((d)-1, 1)))`
or MS_OWS_CELLSIZE should be used in msDrawWMSLayerLow instead of MS_CELLSIZE

**Comment by ravhed** [comment]
I encountered this issue today. I believe the second option (using MS_OWS_CELLSIZE instead of MS_CELLSIZE) is correct since it is OK for MS_CELLSIZE to return a decimal value between 0 to 1 if I'm not mistaken. Can you make a pull request with the fix?

**Comment by wicksell** [comment]
I do not have the environment setup for making pull request since we build using GIS internals packages. We have plans to fix this but it will be in a couple of months.
