### ISSUE TITLE
SWIG - Export in CSV, SHP, GeoJSON or GML with FORM=zip

### ISSUE THREAD

**Issue by richie21** [mapserver/mapserver#5847]
Hi. I noticed a difference in exports between MapServer 6.4 and MapServer 7.4.

In MapServer 6.4, we can export in CSV, SHP, GeoJSON or GML with FORM=zip or FORM=simple. It works.

In Mapserver 7.4, we can export in CSV, SHP, GeoJSON or GML only with FORM=simple. 
With FORM=zip, we get a weird file containing the string "PKETXEOT-".
Same problem with MapServer 7.4.1 (linux) and MapServer 7.4-dev (ms4w).

I did a [ready to use testcase](https://github.com/mapserver/mapserver/files/3522837/SWIG.-.Export.in.CSV.SHP.GeoJSON.or.GML.with.FORM.zip.zip) containing :
- a minimum mapfile
- PHP code in MapServer 6.4
- PHP code in MapServer 7.4.1

Any idea please ?

**Comment by geographika** [comment]
If you add the output formats directly to the map with FORM=ZIP and try a command line export does it work correctly?

Are the following necessary?

```
$outputformatObj->set('imagemode', MS_IMAGEMODE_FEATURE);
$outputformatObj->set('transparent', 'FALSE');
```

Test from the command line with something like `mapserv -nh "QUERY_STRING=map=test.map&service=WFS&REQUEST=GetFeature&TYPENAME=layer1&version=1.1.0&outputformat=csv"`

EOT could be https://en.wikipedia.org/wiki/End-of-Transmission_character
ETX could be https://en.wikipedia.org/wiki/End-of-Text_character

**Comment by richie21** [comment]
```php
$outputformatObj->set('imagemode', MS_IMAGEMODE_FEATURE);
$outputformatObj->set('transparent', 'FALSE');
```
This does not seem necessary. I get the same results without.
 
If I add the output formats directly to the map with FORM=ZIP :
- with the given PHP code, it still does not work with MapServer 7.4.
- with the given command line (mapserv -nh ...), it works with MapServer 6.4 and 7.4.

**Comment by bragef** [comment]
I believe this issue may also be resolved by #5943. 

That `echo msIO_getStdoutBufferString();` only returns the Pkzip header is to be expected, since this function is not binary safe. Since the buffer is binary you need to call  `msIO_getStdoutBufferBytes()`, which should behave as expected after #5943 is applied.

**Comment by jmckenna** [comment]
@bragef is correct, I just used @richie21's testcase, with master on Windows, and the only change I made was as @bragef said, change line#58 to use msIO_getStdoutBufferBytes() instead; a valid archive 'export.zip' is returned containing a valid 'result.geojson' file

**Comment by richie21** [comment]
It works. Thanks @bragef and @jmckenna.
