### ISSUE TITLE
WFS GetFeature return error when dataset is empty

### ISSUE THREAD

**Issue by aperi2007** [MapServer/MapServer#5862]
I notice the wfs return an error when the dataset result from a filter with
the processing native filter produce an empty dataset.

The getfeature return an exception in gml or an error if the output format is a shapefile.
I guess it should return an empty GML or an empty shapefile.

**Comment by rouault** [comment]
Is this issue still current ? Can't reproduce with your succint description. If the issue is still current, mapfile + sample dataset + request would be helpful

**Comment by geographika** [comment]
I think was fixed with #6268

**Comment by sdlime** [comment]
Agree with @geographika , closing.
