### ISSUE TITLE
msautotest/sld/base.map and reference.map very similar

### ISSUE THREAD

**Issue by rouault** [mapserver/mapserver#5871]
@jbo-ads I've noticed that msautotest/sld/base.map and reference.map are very similar. The only difference is the data sources. Is that intended ?
size.map is also quite similar, except the SIZE (( [s12] * [s12] ) - 132 )

Other mapfiles in msautotest/sld also share a lot in common. I guess it could make sense to have a common.include file with that content and INCLUDE it.

**Comment by jbo-ads** [comment]
I finally found time to address this issue. See PR #5991

**Comment by rouault** [comment]
Fixed per https://github.com/mapserver/mapserver/pull/5991
