### ISSUE TITLE
PHP-SWIG-Mapscript, layerObj->addFeature not working

### ISSUE THREAD

**Issue by Ludwig-K** [mapserver/mapserver#5872]
Using Linux debian 9 with Apache 2 and PHP Version 7.0.33-0+deb9u3.
Compiled mapscript MapServer version 7.4.1 and using extension=libphp_mapscriptng.so

I'm in the process of testing and moving from php-mapscript to the SWIG-version and stumbled over a problem, which ran in old php-mapscript.
Old-PHP-Code, which outputs a user-defined shape on map:
```
$draw_shape = ms_shapeObjFromWkt ( 'POLYGON((669686.1006128711 6571574.341164448,687697.0526046992 6566676.626149127,685011.2088866195 6551509.508682325,666368.293667008 6552931.425944837,669686.1006128711 6571574.341164448))' );
$draw_layer->addFeature ( $draw_shape );
$draw_layer->draw ($msc_image_obj );
```
Same in SWIG:
```
$draw_shape = new \shapeObj ( MS_SHAPE_POLYGON );
$draw_shape->fromWKT ( 'POLYGON((669686.1006128711 6571574.341164448,687697.0526046992 6566676.626149127,685011.2088866195 6551509.508682325,666368.293667008 6552931.425944837,669686.1006128711 6571574.341164448))' );
$draw_layer->addFeature ( $draw_shape );
$draw_layer->draw ( $msc_map_obj, $msc_image_obj );
```
No error, but the shape is not drawn.
`$draw_layer->convertToString ()`
for **old** php-code shows a layer-object with inline feature
```
FEATURE
POINTS 669686.100612871 6571574.34116445 687697.052604699 6566676.62614913 685011.20888662 6551509.50868232 666368.293667008 6552931.42594484 669686.100612871 6571574.34116445
END # POINTS
END # FEATURE
```
same for the **SWIG**-version only an empty
`FEATURE END # FEATURE`
The appropriate SWIG-Documentation for addFeature shows a 

> "TODO: Is this similar to inline features in a mapfile? Does it work for any kind of layer or connection type?"

According to the functionality in old mapscript this _should_ be similiar to inline features.
As workaround I successfully tested
`$draw_layer->updateFromString ( "LAYER FEATURE POINTS 669686.100612871 6571574.34116445 687697.052604699 6566676.62614913 685011.20888662 6551509.50868232 666368.293667008 6552931.42594484 669686.100612871 6571574.34116445 END END END" );`
Another workaround could be a postgis-layer with layerObj->data =
`select geomFromEWKT('SRID=3857;POLYGON((669686.1006128711 6571574.341164448,687697.0526046992 6566676.626149127,685011.2088866195 6551509.508682325,666368.293667008 6552931.425944837,669686.1006128711 6571574.341164448))');`

**Comment by geographika** [comment]
@Ludwig-K - the following is a working Python snippet which uses the same API. 
I think the issue here is that the fromWKT "Returns a new shapeObj.." rather than updating the existing instance. A little clunky but setting the variable to the called function should work. 

```python
import mapscript
draw_shape = mapscript.shapeObj(mapscript.MS_SHAPE_POLYGON)
wkt = 'POLYGON((669686.1006128711 6571574.341164448,687697.0526046992 6566676.626149127,685011.2088866195 6551509.508682325,666368.293667008 6552931.425944837,669686.1006128711 6571574.341164448))'
draw_shape = draw_shape.fromWKT(wkt)
# print(draw_shape.toWKT()) # check the WKT here
draw_layer = mapscript.layerObj()
res = draw_layer.addFeature(draw_shape)
print(draw_layer.convertToString())
```

**Comment by Ludwig-K** [comment]
OK, tested the approach and it worked.

Carefull reading of the SWIG API Reference makes my mistake clear: 
_fromWKT( char *wkt )shapeObj_
_Returns a new shapeObj..._


Working PHP-code for SWIG:
```
$draw_shape = new \shapeObj ();
$draw_shape = $draw_shape->fromWKT ( 'POLYGON((669686.1006128711 6571574.341164448,687697.0526046992 6566676.626149127,685011.2088866195 6551509.508682325,666368.293667008 6552931.425944837,669686.1006128711 6571574.341164448))' );
$draw_layer->addFeature ( $draw_shape );
$draw_layer->draw ( $msc_map_obj, $msc_image_obj );
```
Thanks for the support!

**Comment by akrherz** [comment]
I stumbled into this issue whilst porting my php code and I think you just want to do like so to call the static class method

```php
$draw_shape = shapeObj::fromWKT ( 'POLYGON((669686.1006128711 6571574.341164448,687697.0526046992 6566676.626149127,685011.2088866195 6551509.508682325,666368.293667008 6552931.425944837,669686.1006128711 6571574.341164448))' );
$draw_layer->addFeature ( $draw_shape );
$draw_layer->draw ( $msc_map_obj, $msc_image_obj );
```
