### ISSUE TITLE
No more allowed to set partially transparency defining COLOR using RGBA and hex values

### ISSUE THREAD

**Issue by aperi2007** [mapserver/mapserver#5882]
After an update to the last Debian (burst) I update mapserver to the last trunk version and recompile. 
After this I notice that the mapserver was no more capable to produce a feature with partial transparency. All the polygons was full opaques.

With a rollback to the previous my version of trunk mapserver the system is newly capable to do the transparency.

The version I know is working transparency is:

<pre>
commit dd8ae3e21eb7465b32b01fee3c3b6f886b0863f4 (HEAD -> master, origin/master, origin/HEAD)
Author: Even Rouault <even.rouault@spatialys.com>
Date:   Mon Aug 26 15:05:09 2019 +0200

    valgrind-suppressions.txt: add extra for newer mongoDB
</pre>

**Comment by aperi2007** [comment]
Seth suggest a workaround.

Seem the sintax 

      STYLE
        COLOR "#e1cc4f7f"

(RGBA with hex number) stop to work in the 7.4 version of mapserver and instead is working the sintax

      STYLE
        COLOR "#e1cc4f"
	OPACITY 50

Where OPACITY 50 mean 50% opacity

**Comment by aperi2007** [comment]
Is confirmed the dismission of RGBA with hex number sintax or could be an issue this ?

**Comment by geographika** [comment]
@aperi2007 - I've not seen any mention of deprecating the RGBA/opacity syntax so it seems a valid regression bug, or at least outdated docs.

**Comment by aperi2007** [comment]
With some test I can see the issue was introduce in the 
4fbd7aee1fa2864bf320e9756296b0912774afeb - SLD: Add support to arithmetic expressions
commit.
