### ISSUE TITLE
commandline mapserver prefixes image with a header challenging pipe to image 

### ISSUE THREAD

**Issue by pvgenuchten** [mapserver/mapserver#5892]
When piping the output of wms-getmap request via commandline to an image, the image is prefixed with header "Content-Type: image/png", causing the piped image to be corrupt. Is there an alternative way to return the image, or an option to not prefix the output?

```
mapserv QUERY_STRING="SERVICE=WMS&REQUEST=GetMap&VERSION=1.3.0&service=WMS&layers=definition&bbox=4.70,51.89,4.71,51.90&width=800&height=800&map=groups.map&crs=epsg:4326&format=image/png" > dummy.png
```
Creates an image prefixed with

```
Content-Type: image/png
```
Tested on mapserver 7.2.2

**Comment by geographika** [comment]
@pvgenuchten add a `-nh` (no header parameter) to remove these. 
See https://mapserver.org/it/cgi/mapserv.html

**Comment by pvgenuchten** [comment]
thanx @geographika!
