### ISSUE TITLE
UTFGrid support for TrueType symbols

### ISSUE THREAD

**Issue by juliensam** [mapserver/mapserver#5901]
Has per RFC93 UTFGrid support RFC:
https://mapserver.org/development/rfc/ms-rfc-93.html

> Due to the upcoming changes to TrueType rendering, the renderTrueTypeSymbols method has not been implemented yet. All other types of symbols and labels are implemented.

The goal is to fix this limitation

**Comment by dmorissette** [comment]
Pull requests #5918 and #5917 have been pushed to address this. Closing.
