### ISSUE TITLE
Support group in WMS GetMap request with FILTER parameter

### ISSUE THREAD

**Issue by adube** [mapserver/mapserver#5919]
MapServer supports receiving the Vendor-Specific OGC FILTER parameter in WMS requests, which was implemented in RFC 118.

If a group is used instead of a layer in the url, then MapServer may return an error such as this:

```
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException code="InvalidParameterValue">
msWMSApplyFilter: WMS server error. Wrong number of filter elements, one filter must be specified for each requested layer.
</ServiceException>
</ServiceExceptionReport>
```

This is due to the fact that behind the scene, MapServer explodes the group into layer names and the number of filters given in the url does not match the number of layers. Let's say that `groupA` has 2 layers, then:

|**Url snippet**| **Output** |
|------|------|
|`&LAYERS=groupA&FILTER=(...)`| Error|
|`&LAYERS=groupA&FILTER=(...)(...)`| Okay|

## Solution suggestion

So, the goal would be to make MapServer apply the filter given to the group to all the layers in that group.

It is expected that the filter must be compatible with all the layers of the group. For example, the fields in the filter must be defined in each layer. If something is invalid, then MapServer would return an error.

## References

 * Original MapServer RFC: https://mapserver.org/development/rfc/ms-rfc-118.html
 * Original Pull Request for MapServer: https://github.com/mapserver/mapserver/pull/5480

**Comment by jratike80** [comment]
I agree with Andrea Aime https://stackoverflow.com/questions/34474852/how-to-filter-geoserver-layer-group-using-cql-filter#34479406 :

> The general answer is simple: you don't filter a group with CQL filter.
> 
> Getting into specifics, you can apply a single filter to the layer group, but it has to be valid for each and every layer in the group, which often is not the case. When you want to filter, it's best to split up the group into its individual layers, and apply a CQL_FILTER list (CQL filters separated by ;, one filter for each of them.
>

**Comment by adube** [comment]
Thanks for the quick reply.

The idea main idea behind this is to avoid requiring to duplicate the same filter over and over.  In a scenario where the a group would have (let's say) 10 layers, each sharing the same properties, then the URL would need to have 10 times the exact same filter.

I agree that this would not normally be recommended, as you need to make sure that the filter would be valid for all layers, but it simplifies the url and in the environment where we would use it we already validate the properties and provide a valid filter for each inner layers.

We are also willing to work on this.

Thoughts?

**Comment by jratike80** [comment]
I do understand the pain of repeated filters and I don't have strong opinions. The OGC filter thing is bit of a hack anyway because WMS service does not tell what kind of filters are supported. That is less pain with Geoserver that is publishing the layers through WFS as well and users can check the attributes with DescribeCoverage (that naturally does not return anything for the group layers because they do not exist in WFS). 

With Mapserver I think that the WMS service provider must inform the client side developers about what they can filter with some additional documentation and then it is possible to document also which group layers can be filtered with a single OGC Filter and which group layers must be filtered layer by layer.

**Comment by adube** [comment]
Thanks a lot for the feedback.

Expect more activity (comments / feedback) on this issue before the end of the month.

**Comment by jratike80** [comment]
Please use your imagination and try to find possibly difficult use cases and edit your suggestion to address them. For example is it also OK to use separate filters for all layers in the group. 
```
&layers=group_of_two&filter=(...) Okay
&layers=group_of_two&filter=(...)(...)  Okay?
&layers=group_of_two,regular_layer&filter=(...)(...) Okay or missing filter?
```

**Comment by adube** [comment]
>For example is it also OK to use separate filters for all layers in the group.

I would say no.  If you're using a group, then only one filter should be given to it.  So, in the above scenarios only A) and C) would be considered valid.
