### ISSUE TITLE
WCS server: output extent differs from request in 7.4, ok in master

### ISSUE THREAD

**Issue by marisn** [mapserver/mapserver#5940]
When making a WCS request to 7.4, returned image extent starts to differ after 5th place after period. In master the difference is only in the last place after period.
As QGIS checks for 10 positions after period, it refuses to load any data returned from WCS with "Received coverage has wrong extent" error.
https://github.com/qgis/QGIS/blob/master/src/providers/wcs/qgswcsprovider.cpp#L578

Here is data, map file and script for testing:
http://www.gisnet.lv/~marisn/wcs_extent.tgz

Here is output of testing script on my Ubuntu bionic machine (tested with 55a653d3164ed86fca51b4f6832c879925840191 and 6201f065fe8de4efc5dbd197d605517b2e3707dc):

> GDAL 2.4.2, released 2019/06/28
> Rel. 5.2.0, September 15th, 2018
> usage: proj [ -bdeEfiIlmorsStTvVwW [args] ] [ +opts[=arg] ] [ files ]
> MapServer version 7.5-dev OUTPUT=PNG OUTPUT=JPEG SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=ICONV SUPPORTS=WMS_SERVER SUPPORTS=WFS_SERVER SUPPORTS=WCS_SERVER SUPPORTS=GEOS INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE
> Corner Coordinates:
> Upper Left  (  730000.123,  360049.543) ( 27d49'14.54"E, 57d19'30.85"N)
> Lower Left  (  730000.123,  360000.123) ( 27d49'14.37"E, 57d19'29.26"N)
> Upper Right (  730049.543,  360049.543) ( 27d49'17.49"E, 57d19'30.76"N)
> Lower Right (  730049.543,  360000.123) ( 27d49'17.32"E, 57d19'29.17"N)
> MapServer version 7.4.2 OUTPUT=PNG OUTPUT=JPEG SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=ICONV SUPPORTS=WMS_SERVER SUPPORTS=WFS_SERVER SUPPORTS=WCS_SERVER SUPPORTS=GEOS INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE
> Corner Coordinates:
> Upper Left  (  730000.123,  360049.543) ( 27d49'14.54"E, 57d19'30.85"N)
> Lower Left  (  730000.123,  360000.123) ( 27d49'14.37"E, 57d19'29.26"N)
> Upper Right (  730049.543,  360049.543) ( 27d49'17.49"E, 57d19'30.76"N)
> Lower Right (  730049.543,  360000.123) ( 27d49'17.32"E, 57d19'29.17"N)
> Gold == master New == 7.4
> Files differ at the binary level.
> GeoTransforms Differ:
>   Golden: (730000.1234500001, 0.055527820224775246, 0.0, 360049.54321, 0.0, -0.06434864583325049)
>   New:    (730000.1234472804, 0.05552782021731105, 0.0, 360049.5431785807, 0.0, -0.06434864588303435)
> Differences Found: 2

**Comment by rouault** [comment]
Closing as it works with master
