### ISSUE TITLE
Nested SYMBOLSETs leak file handles

### ISSUE THREAD

**Issue by dmorissette** [mapserver/mapserver#5941]
We encountered a case of symbolset file handles leak in MapScript when we load a symbolset that references another symbolset (possibly via an INCLUDE), e.g.

my.map:
```
MAP
  ...
  SYMBOLSET "symbol_library.txt"
  ...
END
```
symbol_library.txt:
```
SYMBOLSET
  INCLUDE "symbolset1.txt"
  INCLUDE "symbolset2.txt"
END
```
symbolset1.txt:
```
SYMBOLSET
  SYMBOL
    NAME "circle"
    ...
  END
  ...
END
```
symbolset2.txt:
```
SYMBOLSET
  SYMBOL
    NAME "highway_shield"
    ...
  END
  ...
END
```
Before you ask, the reason to do this is that in a generic system that generates mapfiles on the fly, you may sometimes want to use symbolset1.txt and symbolset2.txt as standalone symbolsets, and at other times use them as part of a larger library of symbols via the include trick above.  This results in SYMBOLSETs inside a SYMBOLSET, but loadSymbolSet() in mapsymbol.c does not properly handle this case. A patch and msautotest are underway to properly handle the nested symbolset case.

**Comment by sdlime** [comment]
Conceptually related to #5942? If so, @dmorissette, are you guys working on a path for that bug too? --Steve

**Comment by dmorissette** [comment]
Yes, #5941 and #5942 are the same and PR#5944 addresses them. I have reviewed the PR and will merge it now.

**Comment by dmorissette** [comment]
Correction: PR#5944 does address the current issue (#5941), but it does not address #5942... my mistake.
