### ISSUE TITLE
Parse errors within INCLUDEd files leak file handles

### ISSUE THREAD

**Issue by alexbrault** [MapServer/MapServer#5942]
When the parser encounters an error, it immediately exits its loop, closes the current file and returns. If that happens while parsing a file included with the INCLUDE token, all the other files in the include stack are left open. This is especially a problem in MapScript since those files may not be reclaimed by the operating system until the parent process exits.

For example:
leaked.map:
```
map
include 'parse_error.map'
end
```

parse_error.map:
```
invalid token
```

**Comment by dmorissette** [comment]
Reopening... this is related to #5941, but PR#5944 does not address this, my mistake.  The fix will be more involved as it is related to generic handling of INCLUDEs in the parser.

@sdlime, you may be the best candidate to address this one.

**Comment by jmckenna** [comment]
@sdlime, as @dmorissette said, can you add this onto your plate?  I think this one is important.

**Comment by sdlime** [comment]
Yes, will try to find time this week.

**Comment by sdlime** [comment]
I have a pull request out there that aims to address this in master but it needs to be verified. @alexbrault, any chance you could take a look? I've tried with parse errors in the main map file, one include deep and two includes deep and the right code seems to be being called.

--Steve
