### ISSUE TITLE
WMS Filters and Multiple Styles causes crash

### ISSUE THREAD

**Issue by geographika** [MapServer/MapServer#5981]
## Overview 

Relates to [MS RFC 118: Support Vendor-Specific OGC FILTER parameter in WMS requests](https://mapserver.org/development/rfc/ms-rfc-118.html). 

If a layer name is repeated in a WMS request, along with multiple styles and filters then the following exception is thrown:

`Exception thrown at 0x00007FF83488D8D7 (mapserver.dll) in mapserv.exe: 0xC0000005: Access violation reading location 0x0000014F5B6985E8.`

An example use case for duplicating a layer name in a WMS request and applying a different styles is to allow the same layer to be displayed with and without labels. The ability to apply filters to this approach would be very useful. 

## Cause

If a layer name is repeated in a WMS GetMap LAYERS parameter (e.g. `LAYERS=road,road`) then a [copy is added to the map](https://github.com/mapserver/mapserver/blob/84274205449bca0377dd50d840ec1542416134a2/mapwms.c#L1738). 

However, filters are assigned to [layer indexes prior to this](https://github.com/mapserver/mapserver/blob/84274205449bca0377dd50d840ec1542416134a2/mapwms.c#L1104).  

When assigning the filters back to layers there are now more layers in the map than available in the array and the error is thrown [here](https://github.com/mapserver/mapserver/blob/84274205449bca0377dd50d840ec1542416134a2/mapwms.c#L374). 

Looping through the layers and applying the matching filter also means a duplicated layer can only ever have one filter (the last in the `filter` parameter) assigned. 

## Reproducing

I've added to a test to reproduce this at https://github.com/geographika/mapserver/commit/083b72f1979d1f3d33064ec63a3a0a56a4f81020

Allowing different filters to be applied to different styles may not be particularly useful. To get around the requirement of supplying the same number of filters as layers an empty filter could be supplied that would be ignored e.g.

`filter=()(<Filter><Intersects><PropertyName>the_geom</PropertyName><Polygon xmlns='http://www.opengis.net/gml' srsName='EPSG:3857'><exterior><LinearRing srsName='EPSG:3857'><posList srsDimension='2'>-858925.2754976595 6885868.508748529 -859033.9593972524 6885641.586320807 -858525.1754277291 6885406.303593117 -858230.1762716911 6885554.40033542 -858246.8968716285 6885678.610506383 -858629.0820130544 6885818.346948717 -858925.2754976595 6885868.508748529</posList></LinearRing></exterior></Polygon></Intersects></Filter>)`

**Comment by jratike80** [comment]
I have seen similar question somewhere lately, then the issue was about making GetFeatureInfo for two multiplied layers (same layer but differents styles). Query returns results from the first layer only.

I think that a possibility to repeat the same layer &LAYERS=layer1,layer1 may be a nice trick but I could not find anything about such use case from the WMS standard.

**Comment by geographika** [comment]
@jratike80 - if you manage to find the GetFeatureInfo issue could you link to it here?

The repeated layer approach is the only way to allow multiple layer styles in MapServer I know of, apart from creating duplicate layers in the Mapfile. Other use cases would be layers with left and right values, and an offset style for each. Most of the code is already written to handle this, but the newer `filter` option has a bug. 

I think the solution would be to check the `ows_request->layerwmsfilterindex` array for any associated filters when creating the layer copy, and then add a new entry for the new layer index, and copy the filter index into this.

**Comment by dmorissette** [comment]
CC'ing @charles-plante

**Comment by geographika** [comment]
Related issue/discussion - https://github.com/mapserver/mapserver/issues/5919
It may simply be a case of moving the code to link layers and filter indexes after the layer copies are added to the map?
