### ISSUE TITLE
Outputformat generation with PHPMapscript produces wrong result

### ISSUE THREAD

**Issue by nbhermann** [mapserver/mapserver#5985]
The gernation of a new new output format with PHP Mapscript (Mapserver 7.4.3, PHP 7.3)
produces wrong results
Code to duplicate it:

$map = ms_newMapObj('') or die('Unable to open mapfile.');

$geoJsonOutputFormat= new outputFormatObj('OGR/GEOJSON', 'geojson' );
$geoJsonOutputFormat -> setOption("mimetype", "application/json;
subtype=geojson");
$geoJsonOutputFormat -> setOption("FORMATOPTION", "STORAGE=stream");
$geoJsonOutputFormat -> setOption("FORMATOPTION", "FORM=SIMPLE");
$map->appendOutputFormat($geoJsonOutputFormat);

$layer = ms_newLayerObj($map);
$poClass = ms_newClassObj($layer);
$styleObj = ms_newStyleObj($poClass);

$status= $map->save( '/tmp/testmap.map');

produces this unexpected wrong outputformat:

OUTPUTFORMAT
    NAME "geojson"
    DRIVER "OGR/GEOJSON"
    IMAGEMODE FEATURE
    TRANSPARENT FALSE
    FORMATOPTION "MIMETYPE application/json; subtype=geojson="
    FORMATOPTION "FORMATOPTION=FORM=SIMPLE"
END # OUTPUTFORMAT

The 'mimetype' and 'formatoption' are not recognized properly.
Only one 'formatoption' from the specified once are "somehow"
recognized.

**Comment by sdlime** [comment]
I need to try with one of the other scripting languages to determine if it's PHP-specific or in the mapfile writer. Will try and report back.

**Comment by nbhermann** [comment]
Phython mapscript produces the same output.
See the code snippet below

import mapscript
mymap = mapscript.mapObj()

of= mapscript.outputFormatObj('OGR/GEOJSON', 'geojson') 
of.setOption("mimetype", "application/json; subtype=geojson")
of.setOption("formatoption", "STORAGE=stream");
of.setOption("formatoption", "FORM=SIMPLE");

mymap.appendOutputFormat(of);

layer = mapscript.layerObj
layerclass = mapscript.classObj
style = mapscript.styleObj
mymap.save('/tmp/testmap.map');

**Comment by geographika** [comment]
@nbhermann the following works fine in Python, and so should also work in PHP. Note "formatoption" should not be passed to the function. 

```python
import mapscript
mymap = mapscript.mapObj()

of= mapscript.outputFormatObj('OGR/GEOJSON', 'geojson')
of.setOption("mimetype", "application/json; subtype=geojson")
of.setOption("STORAGE", "stream");
of.setOption("FORM", "SIMPLE");

mymap.appendOutputFormat(of);

print(mymap.convertToString())

```

Outputs:

```
  OUTPUTFORMAT
    NAME "geojson"
    DRIVER "OGR/GEOJSON"
    IMAGEMODE FEATURE
    TRANSPARENT FALSE
    FORMATOPTION "mimetype=application/json; subtype=geojson"
    FORMATOPTION "STORAGE=stream"
    FORMATOPTION "FORM=SIMPLE"
  END # OUTPUTFORMAT

```

**Comment by nbhermann** [comment]
@geographika : Great. Thank you. 
I can confirm that this is working with PHP as well.
