### ISSUE TITLE
Can't add labels to issues

### ISSUE THREAD

**Issue by 0xbigshaq** [mapserver/mapserver#6005]
I know the documentation says 
>All security/vulnerability bugs should use the label Security/Vulnerability (Private). It is important to use that label for those bugs to be sure the security bugs maintainer is aware of the issue and that the right procedure is done

But unless I'm being really dumb and failing to understand GitHub's UI, there is no way for me to add labels to new issues. Maybe it's a permissions thing?

**Comment by rouault** [comment]
yes creating labels is only available to the administrators of the mapserver repository. The phrase you quote is outdated and related to when we used Trac. I don't think we have a mechanism in github to have privately reported issues. If you want to report a security related issue, you can email the project chair Steve Lime "sdlime at gmail.com" who will dispatch to relevant people if needed

**Comment by jratike80** [comment]
We do not have defined procedure for reporting security issues like GeoServer project has (see Reporting a security vulnerability in http://geoserver.org/issues/) .  Perhaps we should, or perhaps OSGeo could give common guidelines.

I was about to suggest to send mail to PSC members but Even was faster with the project chair suggestion.

**Comment by jmckenna** [comment]
@0xbigshaq can you point to the documentation page you are referring to?

**Comment by 0xbigshaq** [comment]
@jmckenna , sure: https://mapserver.org/development/bugs.html

I already wrote 2 reports in markdown styling so I think reporting here on github will be better and easier to understand.

And thanks for the quick comments, so what do you think about this workaround?
1. I'll open 2 new issues (because i found 2 vulns) with a dummy-text / "spam"
2. You'll add the "security / private" tag because you have permissions
3. Now when it's private, I'll edit the issues with the relevant bugs details

thanks!

**Comment by jmckenna** [comment]
@0xbigshaq I believe that should work, will watch for your dummy ticket, let's test this

**Comment by 0xbigshaq** [comment]
@jmckenna 
cool, issues were created :)
#6006 and #6007

**Comment by jmckenna** [comment]
But those tickets are still visible by public, after changing the label...hmmmmmm

**Comment by 0xbigshaq** [comment]
@jmckenna 
yeah i almost edited them but then noticed that too :/  
any ideas?

**Comment by jmckenna** [comment]
Github does not support private tickets, as Even mentioned here.  The labels we tried were automatically imported from Trac when we did the switch to Github, so, they are useless here.  For now you'll have to follow @rouault 's steps above to send the chair your report (the project chair will then forward to the PSC).  Steve Lime "sdlime at gmail.com        Sorry, and thanks!

**Comment by sdlime** [comment]
The "MapServer" account doesn't allow creating private repos. I could create a private repo under my own account and invite folks there.

**Comment by jmckenna** [comment]
will file a ticket now to create an alias of security@mapserver.org and will update the docs if/when created.  (I thought we had this alias, but I can't find record of it).

**Comment by jmckenna** [comment]
I have deleted those 2 labels from our repository, as they are useless.

**Comment by 0xbigshaq** [comment]
@jmckenna oh, bummer :( 
My github profile is pretty dead. I wanted to make interesting contributions so it will look better with my name on it (plus, those reports are super cool and fun to read 😉 it can help other researchers to find more vulns and report about it)

ok so i'll follow @rouault's steps and send those reports privately via email.
thanks again for the quick responses and the support!

**Comment by sdlime** [comment]
@0xbigshaq I did invite you to to a private repo for reporting purposes if you'd like.

**Comment by 0xbigshaq** [comment]
@sdlime cool! ok so I tried to browse the invitation link but it says 404
maybe try again?

**Comment by sdlime** [comment]
> I have deleted those 2 labels from our repository, as they are useless.

You can close the experimental tickets too... We can talk about retooling reporting process and documentation on mapserver-dev. I think using a combination of the email address and a private repo could work at the outset.

**Comment by jmckenna** [comment]
new alias created, that sends notice to all PSC members:  mapserver-security (at) osgeo (dot) org

Will discuss on mapserver-dev

**Comment by jmckenna** [comment]
Closing, security steps updated through https://github.com/mapserver/docs/commit/f4d2c372667f7c851b708975af4cb22d185f63c1
