### ISSUE TITLE
Tutorial is out-dated and doesn't work with after corrections for MapServer 6.2

### ISSUE THREAD

**Issue by jey-GIS** [mapserver/mapserver#6008]

**Comment by jmckenna** [comment]
@jey-GIS please re-file this ticket in the [docs repository](https://github.com/mapserver/docs)

Note that all tutorial/demo services were down overnight and just fixed through [docs/issues/311](https://github.com/mapserver/docs/issues/311)

**Comment by jmckenna** [comment]
By the way, the tutorial (since the changes this morning through [docs/issues/311](https://github.com/mapserver/docs/issues/311)) is running MapServer 7.4.3  ([example request](https://demo.mapserver.org/cgi-bin/mapserv?map=/osgeo/mapserver/tutorial/htdocs/example1-1.map&layer=states&mode=map))

But please open a new ticket in the [docs repository](https://github.com/mapserver/docs) to discuss your proposed enhancements/issue.

**Comment by jmckenna** [comment]
@jey-GIS also, in your new docs ticket, please be very specific in the steps you are referring to (what page you are referring to, or where you downloaded the files etc, and the steps that are incorrect).  Thank you for your feedback!

**Comment by jey-GIS** [comment]
G'day.
Could you, please, check this link:


https://demo.mapserver.org/cgi-bin/mapserv?map=/osgeo/mapserver/tutorial/htdocs/example1-8.map&layer=states&mode=map

 


I've just change example number from 1-1 to 1-8 (or any starting from 5 when labaling is introduced).

 

Kind regards,

Jey


 

Envoyé: samedi 29 février 2020 à 15:16
De: "Jeff McKenna" <notifications@github.com>
À: mapserver/mapserver <mapserver@noreply.github.com>
Cc: jey-GIS <jey_@caramail.com>, Mention <mention@noreply.github.com>
Objet: Re: [mapserver/mapserver] Tutorial is out-dated and doesn't work with after corrections for MapServer 6.2 (#6008)


By the way, the tutorial (since the changes this morning through docs/issues/311) is running MapServer 7.4.3 (example request)

But please open a new ticket in the docs repository to discuss your proposed enhancements/issue.

**Comment by jmckenna** [comment]
@jey-GIS thanks.  Can you please file a ticket for this change in the proper repository at [/docs] ?(https://github.com/mapserver/docs/) We can discuss this and tackle it there together.  Thank you.

**Comment by jey-GIS** [comment]
done

 
 

Envoyé: lundi 2 mars 2020 à 15:57
De: "Jeff McKenna" <notifications@github.com>
À: mapserver/mapserver <mapserver@noreply.github.com>
Cc: jey-GIS <jey_@caramail.com>, Mention <mention@noreply.github.com>
Objet: Re: [mapserver/mapserver] Tutorial is out-dated and doesn't work with after corrections for MapServer 6.2 (#6008)


@jey-GIS thanks. Can you please file a ticket for this change in the proper repository at [/docs] ?(https://github.com/mapserver/docs/) We can discuss this and tackle it there together. Thank you.
