### ISSUE TITLE
Is MapServer suppose to be able to serve hdf5 images?

### ISSUE THREAD

**Issue by andrewhongnguyen** [mapserver/mapserver#6013]
I downloaded ms4w via the setup.exe and added the following to \ms4w\apps\local-demo\local.map to check if MapServer can serve hdf5 files: 

OUTPUTFORMAT
  NAME "HDF5"
  DRIVER GDAL/HDF5
  #MIMETYPE "image/hdf5"
  #IMAGEMODE RGB
  #EXTENSION "H5"
END

But I get the following error: 
loadOutputFormat(): General error message. OUTPUTFORMAT (HDF5) clause references driver (GDAL/HDF5), but this driver isn't configured. msInitGDALOutputFormat(): General error message. GDAL `HDF5' driver does not support output.

Does this error message imply that GDAL/HDF5 isn't supported as an output image in MapServer?

**Comment by jmckenna** [comment]
Please do not ask questions on Github, MS4W has a dedicated mailing list for questions:  subscribe at https://ms4w.com/forum/
