### ISSUE TITLE
Problem with UNION LAYER using multiple shapefiles

### ISSUE THREAD

**Issue by minhduccse** [mapserver/mapserver#6025]
I'm using mapserver to serve a population map with data are some separate shapefile. I want to retrieve all shapefile with different colors because every shapefile is a district polygon.

I'm styling my map with this .map file to serve a google tile map client

MAP

  SIZE 256 256

  UNITS METERS

  EXTENT -180 -90 180 90

  NAME "test heat"

  IMAGETYPE "png"

  WEB

    METADATA

      "wms_srs"            "EPSG:4326 EPSG:3857"

      "wms_enable_request" "*"

      "wms_encoding"       "utf-8"

    END # METADATA

  END # WEB

  PROJECTION

    "+init=epsg:4326"

  END # PROJECTION

  LAYER

    NAME 'population'

    TYPE POLYGON

    STATUS ON

    CONNECTIONTYPE UNION

    CONNECTION "population_step1,population_step2"

    STYLEITEM "AUTO"

    CLASS

    END

  END

  LAYER

    NAME 'population_step1'

    TYPE POLYGON

    STATUS OFF

    DATA './shapefiles/population/step1/step1.shp'

    CLASS

      NAME 'population_step1'

      STYLE

        OUTLINECOLOR 0 0 0

        COLOR "#fdbb84"

      END

    END

  END

  LAYER

    NAME 'population_step2'

    TYPE POLYGON

    STATUS OFF

    DATA './shapefiles/population/step2/step2.shp'

    CLASS

      NAME 'population_step2'

      STYLE

        OUTLINECOLOR 0 0 0

        COLOR "#f8a21c"

      END

    END

  END

END # MAPFILE

But the server respone

`Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.29 (Ubuntu) Server at 192.168.29.137 Port 80`

I installed MapServer on a Ubuntu Server 18.04 virtual machine
`md@mapserver:~$ mapserv -v
MapServer version 7.0.7 OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=SVG_SYMBOLS SUPPORTS=RSVG SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=FASTCGI SUPPORTS=THREADS SUPPORTS=GEOS INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE`

Sorry for my bad English

**Comment by jmckenna** [comment]
@minhduccse could you first ask this question on the MapServer-users list?  Thanks.  Then if it is agreed that it is a bug you can file a new ticket.  
Subscribe at https://lists.osgeo.org/listinfo/mapserver-users
