### ISSUE TITLE
SLD: proposal for supporting "uom" attribute at <Symbolizer> level

### ISSUE THREAD

**Issue by jbo-ads** [mapserver/mapserver#6026]
People around me who use SLD want to set ground units through `uom` attribute of `<PolygonSymbolizer>`, `<LineSymbolizer>` and `<PointSymbolizer>`, as specified in _Symbology Encoding Implementation Specification_, version 1.1.0.

Currently MapServer has the concept of `SIZEUNITS` defined at `LAYER` level.

This issue proposes to add this concept to `classObj`, `styleObj` and `labelObj` internal data structures and to bind SLD `uom` attribute to these new internal `sizeunits` fields.

Supported ground units are the ones recommended by specification:

- `http://www.opengeospatial.org/se/units/metre`
- `http://www.opengeospatial.org/se/units/foot`
- `http://www.opengeospatial.org/se/units/pixel`

together with units already supported by MapServer: `inches`, `feet`, `miles`, `meters`, `kilometers`, `dd`, `pixels`, `percentages`, `nauticalmiles`, and theirs variations: `inch`, `foot`, `mile`, `meter`, `metre`, `metres`, `kilometers`, `kilometre`, `kilometres`, `dd`, `pixels`, `pixel`, `px`, `percentage`, `percent`, `percents`, `nauticalmile`, `nautical_mile`, `nautical_miles`.

Adding this feature to MapFile as well could be useful but is not part of this proposal.

This issue is addressed by pull request #6027.

**Comment by jmckenna** [comment]
This would be really nice for the mapfile as well.  But this is still a very useful enhancement for SLD.
