### ISSUE TITLE
SLD: broken sld_reference.png test

### ISSUE THREAD

**Issue by rouault** [mapserver/mapserver#6029]
@jbo-ads  I've disabled sld_reference.png test in commit 62efb0e as it didn't pass on Travis-CI . I suspect this must be an interaction between several SLD pull requests from you I've just merged. I let you re-enable it with the fixed reference file

**Comment by jmckenna** [comment]
@jbo-ads I also invited you to join the MapServer 'developers' GitHub 'team', which should help you on your workflow.

**Comment by jbo-ads** [comment]
@rouault True, this was a collision between multiple changes. This is fixed by pull request #6030.

@jmckenna Thank you for the promotion!
