### ISSUE TITLE
after I configure mapcache in the httpd.conf, the apache can not been started

### ISSUE THREAD

**Issue by kavan-lees** [mapserver/mapserver#6044]
apache : 2.4.41;  mapcache 1.6.0
when I copy the below code into httpd.conf , the apache can not been started (AH00526: Syntax error) . 
if I change MapCacheAlias  into ScriptAlias ，apache can work well . is something wrong ? which is right ? how can I  get a demo ? Thanks 

`
<IfModule mapcache_module>

        <Directory "/30wish/web/webroot/mapcache/">

                Header set Access-Control-Allow-Origin "*"

                Require all granted

        </Directory>

        MapCacheAlias /mapcache "/30wish/web/webroot/mapcache/mapcache.xml"

</IfModule>
`
__

**Comment by jmckenna** [comment]
Please do not use Github for questions; instead please send your questions direct to the MapCache/MapServer community at https://lists.osgeo.org/listinfo/mapserver-users  There are literally hundreds waiting for your question there.
