### ISSUE TITLE
Support for database using ODBC?

### ISSUE THREAD

**Issue by remi-sap** [mapserver/mapserver#6056]
Hello,
Do you know if the ODBC connection for virtual spatial data works with SAP HANA ?
Theoretically, it should work...

Thanks.

**Comment by remi-sap** [comment]
Nevermind, there is ongoing work to support HANA in gdal which should make it compatible.

**Comment by rouault** [comment]
>  ongoing work to support HANA in gdal which should make it compatible.

huh really ? Sources ? I'm not aware of that. But there's ongoing work in QGIS

**Comment by jmckenna** [comment]
@remi-sap please do not use Github for questions; send your questions direct to the community at https://lists.osgeo.org/listinfo/mapserver-users (there are literally over 1000 waiting there for your questions).  Thank you.

**Comment by rouault** [comment]
@remi-sap Are you a SAP employee, connected with people working on a potential GDAL driver? If so, I'd advise connecting with the GDAL community to discuss your plans early, rather than after the fact.

**Comment by remi-sap** [comment]
@rouault , I assume you're referring to the qgis saga you were involved with ;-)
Only planning has started with gdal, qgis remains the top priority from what I understood. I'm not in the development organization. My customer is drafting a roadmap to replace a legacy database by SAP HANA with a 2 to 4 years horizon so that should be fine.
