### ISSUE TITLE
GetFeature WFS request with Spatial Filter throws an error

### ISSUE THREAD

**Issue by Fran-1989** [mapserver/mapserver#6058]
Hi, I'm using the following request in order to get the closest feature from a layer given some specific coordinates:

`http://www.juntadeandalucia.es/medioambiente/mapwms/REDIAM_PPHH_2012/wfs?&VERSION=1.0.0&SERVICE=WFS&REQUEST=GetFeature&TYPENAME=MSPF_POLY&Filter=<Filter><DWithin><PropertyName>msGeometry</PropertyName><gml:Point<gml:coordinates>158380,4130457</gml:coordinates></gml:Point><Distance units='m'>10000</Distance></DWithin></Filter>`

But the result is:

 mapserv(): Web application error. Traditional BROWSE mode requires a TEMPLATE in the WEB section, but none was provided.

I also have tried with the following example of the documentation a the result is the same:

```
https://demo.mapserver.org/cgi-bin/wfs?&VERSION=1.0.0&SERVICE=WFS
  &REQUEST=GetFeature&TYPENAME=cities&Filter=<Filter>
  <DWithin><PropertyName>Geometry</PropertyName><gml:Point>
  <gml:coordinates>135.500000,34.666667</gml:coordinates>
  </gml:Point><Distance units='m'>10000</Distance></DWithin></Filter>
```
I would appreciate some help. Thanks in advance.

**Comment by jratike80** [comment]
The mapserver-users list is our support forum.

There was an extra space mark in the demo URL. This works, though the response looks somehow odd to me.

https://demo.mapserver.org/cgi-bin/wfs?VERSION=1.0.0&SERVICE=WFS&REQUEST=GetFeature&TYPENAME=cities&Filter=%3CFilter%3E%20%3CDWithin%3E%3CPropertyName%3EGeometry%3C/PropertyName%3E%3Cgml:Point%3E%20%3Cgml:coordinates%3E135.500000,34.666667%3C/gml:coordinates%3E%20%3C/gml:Point%3E%3CDistance%20units=%27m%27%3E10000%3C/Distance%3E%3C/DWithin%3E%3C/Filter%3E

There is something wrong also in your first example. This request gives another error about Invalid or Unsupported FILTER in GetFeature:

www.juntadeandalucia.es/medioambiente/mapwms/REDIAM_PPHH_2012/wfs?VERSION=1.0.0&SERVICE=WFS&REQUEST=GetFeature&TYPENAME=MSPF_POLY&Filter=<Filter><DWithin><PropertyName>msGeometry</PropertyName><gml:Point<gml:coordinates>158380,4130457</gml:coordinates></gml:Point><Distance%20units=%27m%27>10000</Distance></DWithin></Filter>

**Comment by Fran-1989** [comment]
@jratike80 Thank you. I have seen the error that yo mentioned:

`msWFSGetFeature(): WFS server error. Invalid or Unsupported FILTER in GetFeature : <Filter><DWithin><PropertyName>msGeometry</PropertyName><gml:Point<gml:coordinates>158380,4130457</gml:coordinates></gml:Point><Distance units='m'>10000</Distance></DWithin></Filter>`

I don't know what could be wrong because the URL is based on the documentation example.

**Comment by jmckenna** [comment]
@Fran-1989 please submit your questions direct to the MapServer-users list, where there are ~1,000 users waiting to assist you.  here----> https://lists.osgeo.org/listinfo/mapserver-users  Closing.
