### ISSUE TITLE
Change symbol color in mapfile if the source is a svgfile

### ISSUE THREAD

**Issue by 19Han88** [mapserver/mapserver#6067]
If i change the symbolcolor in mapfile, this has no reaction. The source of the symbol is an svgfile. The change of size is working. I use MS4W 4.0.0. Is there a way to change color?

SVG-File:
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<svg xmlns="http://www.w3.org/2000/svg" height="210" width="400">
  <path d="M150 0 L75 200 L225 200 Z" />
</svg>
```

Part of symbol-file:
```
SYMBOL
	NAME "ahoi"
	TYPE SVG
	IMAGE "C:/mapserver/svgs/ahoi.svg"
END
```
Part of Map-File:
```
STYLE
       SYMBOL "ahoi"
       SIZE 10
	COLOR "#00FF00FF"
	OUTLINECOLOR "#FF0000FF"
END
```

**Comment by jmckenna** [comment]
Please do not use Github for general questions; instead use the MapServer-users list which has ~1200 people waiting to answer your questions (subscribe at https://lists.osgeo.org/listinfo/mapserver-users).   Alternatively, you can also use the MS4W-users list directly as well (https://ms4w.com/forum/). Thank you.
