### ISSUE TITLE
msMSSQL2008LayerGetShape:  Invalid cursor state

### ISSUE THREAD

**Issue by geographika** [mapserver/mapserver#6077]
I've been getting several of the following error messages:

`[Microsoft][ODBC Driver Manager] Invalid cursor state`

Following this I need to restart the web server (IISReset on Windows Server) to allow MapServer to run again. 

```
[Thu May  7 16:23:48 2020].263000 Caching up to 1000 shapes
[Thu May  7 16:23:48 2020].700000 msMSSQL2008LayerGetShape(): Query error. Error executing MSSQL2008 SQL statement: SELECT convert(nvarchar(max
...
        ) as tbl WHERE GEOM.STIntersects(geometry::STGeomFromText('POLYGON((-1e+300 -1e+300,1e+300 -1e+300,1e+300 1e+300,-1e+300 1e+300,-1e+300 -1e+300))',3857)) = 1
[Microsoft][ODBC Driver Manager] Invalid cursor state
[Thu May  7 16:23:48 2020].700000 msWFSGetFeature(): WFS server error. ms_error->code not found
```

From web searches it appears the error is thrown if the initial position of a result set is before the first row.
It seems the error is thrown [here](https://github.com/mapserver/mapserver/blob/ac284f108228b1db3442595dc0e045d6ca9f4c2a/mapmssql2008.c#L2439), although the problem may occur prior to this and involves the cache (although the error sometimes is logged without the `Caching up to 1000 shapes` message. 

Errors are intermittent and may be related to data being deleted from the database between queries. I've added LAYER debugging to try to get more details next time this occurs (however it does occur on multiple different layers).

**Comment by szekerest** [comment]
@geographika  Which ODBC driver are you using actually?

**Comment by geographika** [comment]
@szekerest - MapServer logs report `[Microsoft][ODBC SQL Server Driver][SQL Server]`
I have `SQL Server` and `SQL Server Native Client 10.0`. 
In my connection strings I'm not setting a particular driver. 

I realise both drivers are very old (2010!) so I'll update to a newer version: https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver15 and see if this resolves the issue.

**Comment by szekerest** [comment]
@geographika If you don't specify Driver in the connection string, it is using "SQL Server" driver (sqlsrv32.dll) which is very ancient. I'd try to use the native client 11 driver or the ODBC 17 driver (I think gisinternals provides plugins for both versions). If the problem still persist a datset would probably be required to reproduce this.

**Comment by geographika** [comment]
@szekerest - thanks for the info. I've updated the docs with the details on setting a driver at https://github.com/mapserver/docs/pull/331/files

The error may have been caused by underlying database schema changes while these requests were being made. Will close if there are no errors in the logs for the next few days.

**Comment by geographika** [comment]
I've not seen this error again in the logs since updating the driver.
However, there were schema changes being made to database views during the period the errors occurred in the logs so that may have been the cause.
