### ISSUE TITLE
lines clustering and arrowlines

### ISSUE THREAD

**Issue by DakarXY** [mapserver/mapserver#6096]
Good day everyone. I need help of the community, and asking for it, sorry for making issue, but i can't find any live forum or some...

There is such a task: to draw a curved line with an arrow at the end between two symbols (points).

Questions:

1. What is the best way to bend a line defined by two points? (current solution: I find the coordinates of the third point, randomly adding from 0.25 to 0.75 of the difference between the ordinates and abscissas of the points, then I break the line into smaller segments and interpolate it. But since the difference between the ordinates or abscissas can be insignificant, the line can almost do not bend).

2. How to draw arrows at the ends of lines using MapServer? (current solution: using GEOMTRANSFORM, add a filled-in character 'V' to the end of the line, find the angle between the last two points to rotate the (POLAROFFSET) character so that the arrow points to the center of the character at the end of the line. Main problem: when scaling characters, the arrow shifts not along the line, but along the angle that is given, and since the line is a curve - the angle changes and the arrow moves off the line).

3. Add. clustering question: Is it possible, when clustering the points of the beginning and end of lines between themselves, to replace the lines with the line between the clusters (having new coordinates (between points in the cluster))?

MapServer 7.7-dev / 7.6.

Approximate image:

https://i.stack.imgur.com/a4Dbi.png

**Comment by jmckenna** [comment]
as I just wrote you on IRC, please do not use Github for questions - instead please send your questions direct to the MapServer community, subscribe at https://lists.osgeo.org/listinfo/mapserver-users
