### ISSUE TITLE
scaling problem with svg symbols

### ISSUE THREAD

**Issue by 19Han88** [mapserver/mapserver#6108]
I use an svgfile for drawing my geodatas and get an internal server error, if i try to get a map with a big section. Mapserver version is MS4W 4.0.0.
Here is an stand alone example. You only need to change the path.
It includes mapfile with a feature as geodata, symbolfile and svgfile. 
Successful request (small map section):
http://localhost:9080/cgi-bin/mapserv.exe?map=C:\MapServer_Example\MapFile.map&SERVICE=WMS&REQUEST=Getmap&version=1.1.0&LAYERS=TestLayer&WIDTH=600&HEIGHT=600&SRS=EPSG:31467&BBOX=3564240,5410240,3564260,5410260&FORMAT=PNG

Failed request (big map section):
http://localhost:9080/cgi-bin/mapserv.exe?map=C:\MapServer_Example\MapFile.map&SERVICE=WMS&REQUEST=Getmap&version=1.1.0&LAYERS=TestLayer&WIDTH=600&HEIGHT=600&SRS=EPSG:31467&BBOX=3560000,5406000,3580000,5426000&FORMAT=PNG
[MapServer_Example.zip](https://github.com/mapserver/mapserver/files/4891029/MapServer_Example.zip)

**Comment by jmckenna** [comment]
Your extents are so large, and your SIZE for your symbol is so small, that MapServer has a difficult time.  Instead, try a larger "SIZE 1000" in your STYLE.   Here is the resulting map image:
![map-image](https://user-images.githubusercontent.com/1611709/88294446-9dbf9b80-ccd2-11ea-9ce9-0342e8a7866c.png)

Also, in the future please send your MS4W questions direct to the MS4W community by using the dedicated forum for questions (subscribe at https://ms4w.com/forum/ )   Alternatively, if you find a bug you can report it in the MS4W issue tracker (https://ms4w.com/trac/).

Closing.
