### ISSUE TITLE
Unexpected number of features when using the WFS with BBOX 

### ISSUE THREAD

**Issue by boazhuisman** [mapserver/mapserver#6117]
### The Problem
Performing a WFS request to MapServer (mounted with a geo package) while supplying a bounding box (bbox) parameter results in a unexpected number of features. Is this behaviour normal?

**Query with bounding box and no count parameter (configured max_features is 1000):**
https://geodata.nationaalgeoregister.nl/kadastralekaart/wfs/v4_0?service=WFS&request=GetFeature&version=2.0.0&typename=perceel&srsname=EPSG:4326&bbox=160669,384999,162565,385691

![image](https://user-images.githubusercontent.com/15123825/87426814-12624e00-c5e0-11ea-9663-b55d5c960127.png)
The default max feature count for the request is 1000. The query outputs 995 features.

**Query with bounding box and and count parameter equal to 400:**
https://geodata.nationaalgeoregister.nl/kadastralekaart/wfs/v4_0?service=WFS&request=GetFeature&version=2.0.0&typename=perceel&srsname=EPSG:4326&bbox=160669,384999,162565,385691&count=400

![image](https://user-images.githubusercontent.com/15123825/87426845-24dc8780-c5e0-11ea-842f-f817296b5869.png)
The query outputs 399 features, while we know there are at least 1000 (or 995) features available.

**Query without bounding box and count parameter equal to 400**
![image](https://user-images.githubusercontent.com/15123825/87426926-476ea080-c5e0-11ea-98de-89cb8e943670.png)
When removing the bouding box parameter, the number of features is 400 as expected.

https://geodata.nationaalgeoregister.nl/kadastralekaart/wfs/v4_0?service=WFS&request=GetFeature&version=2.0.0&typename=perceel&srsname=EPSG:4326&count=400

### Expected behavior
We expect the number of features to be equal to the (default) count.

### Configuration:

**SQL for query including bbox and count**
`SELECT "Perceel"."gml_id" AS "gml_id", "Perceel"."msfid" AS "msfid", "Perceel"."perceelLabelID" AS "perceelLabelID", "Perceel"."identificatieNamespace" AS "identificatieNamespace", "Perceel"."identificatieLokaalID" AS "identificatieLokaalID", "Perceel"."beginGeldigheid" AS "beginGeldigheid", "Perceel"."tijdstipRegistratie" AS "tijdstipRegistratie", "Perceel"."volgnummer" AS "volgnummer", "Perceel"."statusHistorieCode" AS "statusHistorieCode", "Perceel"."statusHistorieWaarde" AS "statusHistorieWaarde", "Perceel"."kadastraleGemeenteCode" AS "kadastraleGemeenteCode", "Perceel"."kadastraleGemeenteWaarde" AS "kadastraleGemeenteWaarde", "Perceel"."sectie" AS "sectie", "Perceel"."AKRKadastraleGemeenteCodeCode" AS "AKRKadastraleGemeenteCodeCode", "Perceel"."AKRKadastraleGemeenteCodeWaarde" AS "AKRKadastraleGemeenteCodeWaarde", "Perceel"."kadastraleGrootteWaarde" AS "kadastraleGrootteWaarde", "Perceel"."soortGrootteCode" AS "soortGrootteCode", "Perceel"."soortGrootteWaarde" AS "soortGrootteWaarde", "Perceel"."perceelnummer" AS "perceelnummer", "Perceel"."perceelnummerRotatie" AS "perceelnummerRotatie", "Perceel"."perceelnummerVerschuivingDeltaX" AS "perceelnummerVerschuivingDeltaX", "Perceel"."perceelnummerVerschuivingDeltaY" AS "perceelnummerVerschuivingDeltaY", "Perceel"."perceelnummerPlaatscoordinaatX" AS "perceelnummerPlaatscoordinaatX", "Perceel"."perceelnummerPlaatscoordinaatY" AS "perceelnummerPlaatscoordinaatY", "Perceel"."geom" AS "geom" 
FROM "Perceel" 
JOIN "rtree_Perceel_geom" ms_spat_idx ON "Perceel".ROWID = ms_spat_idx.id 
AND ms_spat_idx.minx <= 162566.034956318  'orig. 162565'
AND ms_spat_idx.maxx >= 160668.224364439  'orig. 160669'
AND ms_spat_idx.miny <= 385693.480997444  'orig. 385691'
AND ms_spat_idx.maxy >= 384996.52023744   'orig. 384999'
ORDER BY "Perceel".ROWID 
LIMIT 401.`

We're using the following layer configuration:
```
        LAYER
          NAME   "perceel"
          STATUS  ON
          TYPE    POLYGON

          METADATA
            "wfs_title"         "perceel"
            "wfs_abstract"      "Een Perceel is een stuk grond waarvan het Kadaster de grenzen heeft gemeten en dat bij het Kadaster een eigen nummer heeft. Een perceel is een begrensd deel van het Nederlands grondgebied dat kadastraal geïdentificeerd is en met kadastrale grenzen begrensd is."
            "wfs_keywordlist"   "Kadastrale percelen,infoMapAccessService"
            "wfs_extent"        "-25000 250000 280000 860000"
            "wfs_include_items" "all"
            "wfs_bbox_extended" "true"
            "wfs_enable_request" "*"

            "gml_featureid"     "msfid"
            "gml_include_items" "all"
            "gml_exclude_items" "perceelLabelID,gml_id"
            "gml_geometries"    "begrenzingPerceel"
            "gml_types"         "auto"
            "gml_geom_alias"    "begrenzingPerceel"
            "gml_msfid_alias"   "id"

            "ows_metadataurl_type"     "TC211"
            "ows_metadataurl_format"   "text/plain"
            "ows_metadataurl_href"     "https://www.nationaalgeoregister.nl/geonetwork/srv/dut/xml.metadata.get?uuid=a29917b9-3426-4041-a11b-69bcb2256904"
            "wfs_authorityurl_name"    "Kadaster"
            "wfs_authorityurl_href"    "http://www.kadaster.nl"
            "wfs_identifier_authority" "Kadaster"
            "wfs_identifier_value"     "nl.kad.4"

            "wfs_use_default_extent_for_getfeature" "no"
          END

          CONNECTIONTYPE OGR
          PROJECTION
            "init=epsg:28992"
          END
          CONNECTION "#GPKG_LOCATION#/perceel.gpkg"
          DATA "Perceel"

          DUMP TRUE
          TEMPLATE void
        END
```

MapServer 7.4

Is this behaviour to be expected?

With kind regards,

Boaz Huisman

**Comment by sdlime** [comment]
Hi Boaz: You should probably should take this to the mailing list(s) first - lots more eyes. Since github is pretty useful for formatting your detailed issue description I'd recommend linking to the ticket in your message. Also include the versions of MapServer and GDAL/OGR being used.

This does look to be somehow projection related. If you remove the srsname parameter you get the expected counts (1000 and 400) so internally the output srs must be being used in conjunction with the bbox.

--Steve

**Comment by jmckenna** [comment]
Closing, as mentioned please do not use Github for questions - all questions should be sent directly to the MapServer users list, where over 1 thousand users are waiting to answer your questions (subscribe at https://lists.osgeo.org/listinfo/mapserver-users ).
