### ISSUE TITLE
Build with "vagrant up" fails: CMake can't find Python package

### ISSUE THREAD

**Issue by jbo-ads** [MapServer/MapServer#6154]
Just cloned official MapServer repository and launched `vagrant up`.

I got the following error:

    default: CMake Error at mapscript/python/CMakeLists.txt:4 (find_package):
    default:   By not providing "FindPython.cmake" in CMAKE_MODULE_PATH this project has
    default:   asked CMake to find a package configuration file provided by "Python", but
    default:   CMake did not find one.
    default: 
    default:   Could not find a package configuration file provided by "Python" with any
    default:   of the following names:
    default: 
    default:     PythonConfig.cmake
    default:     python-config.cmake
    default: 
    default:   Add the installation prefix of "Python" to CMAKE_PREFIX_PATH or set
    default:   "Python_DIR" to a directory containing one of the above files.  If "Python"
    default:   provides a separate development package or SDK, be sure it has been
    default:   installed.
    default: -- Configuring incomplete, errors occurred!

After some checks, I found that the first commit where error is present is "dd310d21 Test py3 MapScript Builds on Travis (#6136)".

Not being an expert in mapscript/python, I couldn't find what is wrong in the commit changes.

**Comment by geographika** [comment]
@jbo-ads - the dependencies in the script here:

https://github.com/MapServer/MapServer/blob/d91fec44118f7c421355e8632d20bd96c7152887/scripts/vagrant/packages.sh#L14 

should probably have the following added:

`python-dev python3-dev`

Travis has these already installed.

**Comment by jbo-ads** [comment]
Thank you, I'll try your fix and if successful i'll submit a PR.

**Comment by geographika** [comment]
The issue is CMake can't find Python. The pull request where it started to fail used the CMake 3.x `find_package (Python REQUIRED COMPONENTS Interpreter Development)`. 

If all else fails setting `Python_ROOT_DIR` environment variable to wherever Python is on the VM should work.

**Comment by geographika** [comment]
@jbo-ads - see also https://github.com/MapServer/MapServer/commit/dd310d211b465ed2c155fd8960ed292cc4194eb1#commitcomment-42941596

Is the version of CMake reported in the logs? 

The working Travis builds does a CMake  `apt-get install` and uses version `cmake-3.12.4`:

https://github.com/MapServer/MapServer/blob/8ff4d270813ffa32d7055430877f54122c7c2b04/ci/travis/before_install.sh#L10

If Vagrant uses the same version of CMake it should be fine.

**Comment by jbo-ads** [comment]
Version of CMake is the key. On the Ubuntu/bionic box specified by Vagrantfile, this is CMake 3.10, where one can find FindPythonInter.cmake and FindPythonLibs.cmake, but not FindPython.cmake.

I followed the instructions from Kitware at [https://apt.kitware.com/](https://apt.kitware.com/) in order to install a repository with a more recent version of cmake than the default one. With this, all msautotests run fine with vagrant. PR is on the way...
