### ISSUE TITLE
WFS 2.0: Omit WGS84BoundingBox when layer has no extent

### ISSUE THREAD

**Issue by mstefarov** [MapServer/MapServer#6170]
When a geographic bounding box cannot be established for a layer, MapServer currently emits an empty WGS84BoundingBox element and a warning comment:
https://github.com/MapServer/MapServer/blob/f035f4473c96149008355a3864b5710d55601c72/mapwfs11.cpp#L261-L265

The output looks like this:
```xml
<ows:WGS84BoundingBox/>
<!--WARNING: Optional WGS84BoundingBox could not be established for this layer. Consider setting the EXTENT in the LAYER object, or wfs_extent metadata. Also check that your data exists in the DATA statement-->
```

This empty element violates the OWS [schema](http://schemas.opengis.net/ows/1.1.0/owsCommon.xsd) &mdash; when this element is present, it _must_ have LowerCorner and UpperCorner children.  The standard-compliant thing to do would be to omit the empty `<WGS84BoundingBox/>` and to just emit the XML comment.

This issue was discovered while troubleshooting a [user-reported compatibility problem between ArcGIS Runtime and MapServer](https://community.esri.com/thread/261095-can-not-load-wfs-featuretable-from-url-hosted-on-mapserver).  This XML quirk caused parsing to fail for the entire capabilities document.

**Comment by sdlime** [comment]
@tomkralidis, what's your take on this?

**Comment by jmckenna** [comment]
Actually hopefully we can think about this issue for the upcoming OGC API changes - how to throw an error, not just a warning deep in the GetCapabilities response, so that service admins do not proceed to publish their service until all errors (here warning) are removed.

**Comment by rouault** [comment]
There might be uses cases where we would want to publish non-spatial layers. We might not be completely ready to do that (although not very far), but fundamentally WFS doesn't forbid that AFAIR.
And as far as I can see in https://github.com/opengeospatial/ogcapi-features/blob/master/core/openapi/schemas/collection.yaml, in OGC Features API, the extent is optional, so it could be as well used to publish non spatial layers.

**Comment by jmckenna** [comment]
(i've added this discussion to Tom's OGC-API page for MapServer, in the "Implementation considerations" section: https://github.com/MapServer/MapServer/wiki/OGC-API )

**Comment by tomkralidis** [comment]
@mstefarov thanks for the report.  IMHO in this case given we have schema breakage, a suitable approach would be to not emit the `ows:WGS84BoundingBox` element, but emit a warning as an XML comment.  This may or may not be the case for our other OWS support (would be good to scan across WMS/WFS/WCS accordingly.

I do agree on @jmckenna 's recommendation for server admins to do their due dliligence/curation in publishing their services.

Having said this, this is a great longer term opportunity to implement a `mapfile-check.py` utility that we can ship for users in order to healthcheck a mapfile with switches like `--wms`, `--wfs`, etc.

**Comment by geographika** [comment]
@tomkralidis - would you envisage a `mapfile-check.py` making use of MapScript and all the validation already available within MapServer, or as a pure Python module using OWSLib and/or mappyfile?

**Comment by jmckenna** [comment]
Since most of our users won't have mapscript (or Python/PHP installed), shouldn't the utility be written in C like all of our other utilities? (I suppose the possible answer is: "sure Jeff, please write it." which would definitely mean that the utility would be written in Python or PHP :) :)

**Comment by tomkralidis** [comment]
@geographika very good question.  Maybe both?

- bare bones mapfile syntax check using MapScript
- using OWSLib to run OGC requests and `xml.etree` to analyze responses/warnings

It would be great to have said tool in C/C++, but IMHO a tool like this would be too hard to maintain over the long term given the scope.  Or maybe `mapfile-check` would be plain old C, or an addition to `mapserv` like `mapserv --check-mapfile foo.map`, and then the deeper OGC checks would be a Python script which doesn't need MapScript per se

**Comment by jmckenna** [comment]
agreed on having both.  maybe it is something I can try to contribute someday (mapserv --check-mapfile) or (map2img --check-mapfile).

**Comment by sdlime** [comment]
I think you'd want a context parameter and probably a separate binary or script so something like:

  mapcheck --context=[cgi|ogc|wms|wfs|...|all]

Could do things like add modes to parse-only, validate data sources, security checks (do regex's use ^...$). 

--Steve
