### ISSUE TITLE
implement mapfile checker/linter

### ISSUE THREAD

**Issue by tomkralidis** [MapServer/MapServer#6172]
Opening this as its own issue (follow-on from #6170).  Summary/overview based on discussion

- it would be valuable to implement a mapfile checker/linter (`mapcheck`? `maplint`?) to assess mapfile fitness and OGC compatability/validity.  This will provide a value "pre-publish" step either as a standalone script or as part of a pipeline
- pure mapfile checking could be implemented in C, deeper checking can be done via Python script (OWSLib, mappyfile, `xml.etree`), or all the functionality in Python with MapScript and Python deps

example:
```bash
mapcheck --context=[cgi|ogc|wms|wfs|...|all]
```

Could do things like add modes to parse-only, validate data sources, security checks (do regex's use ^...$, clear text passwords), best practices and so on. Could be useful in an automated CI/CD setup, like a mapfile linter...

cc @sdlime @jmckenna @rouault

**Comment by sdlime** [comment]
Can this be closed? Seems like the domain of mappyfile IMHO. @geographika, what do you think? --Steve
