### ISSUE TITLE
Monitoring Timeout for a single request is fix

### ISSUE THREAD

**Issue by JaegerFrank** [MapServer/MapServer#6173]
The Value of "CAP_MONITORING_TIMEOUT" from mapbender.conf is not read in /lib/class_Monitor.php.
Always the default (20 sec.) is uses in /classes/class_connector.php.
Sometimes QGIS-Server with big Projektfiles take more then 20 sec. time.

**Comment by jmckenna** [comment]
@JaegerFrank I believe you meant to file this in Mapbender's repository: https://github.com/mapbender/mapbender

closing.
