### ISSUE TITLE
KML output issue if label is present

### ISSUE THREAD

**Issue by brunodomenget** [MapServer/MapServer#6174]
Hi all,

I found an issue with KML output if the mapfile contains features with labels. It just crashes, and only starts to work if I remove the LABEL entry from the mapfile.

If I use the following command **shp2img -m test_points_kml.map -o ttt.kml -i kml -all_debug 5**
I get the following answer :
**msDrawMap(): Image handling error. Failed to draw layer named 'points'.
GDAL: In GDALDestroy - unloading GDAL shared library.**

And the corresponding log :
```
[Thu Oct 15 15:36:02 2020].174254 msLoadMap(): 0.005s
[Thu Oct 15 15:36:02 2020].174344 msDrawMap(): rendering using outputformat named kml (KML).
[Thu Oct 15 15:36:02 2020].174348 msDrawMap(): WMS/WFS set-up and query, 0.000s
[Thu Oct 15 15:36:02 2020].174369 msINLINELayerOpen: Layer is already open!
[Thu Oct 15 15:36:02 2020].174564 msSaveImage(/home/mapserver/public_html/test/././5f885042_26ab_0.png) total time: 0.000s
[Thu Oct 15 15:36:02 2020].174629 msDrawMap(): Image handling error. Failed to draw layer named 'points'.
[Thu Oct 15 15:36:02 2020].174649 msFreeMap(): freeing map at 0x559913f1af60.
[Thu Oct 15 15:36:02 2020].174698 freeLayer(): freeing layer at 0x559914207ad0.
```

I asked for help at the mapserver-users mailing list, and the issue was confirmed by @jmckenna .
[Mailing list link](http://osgeo-org.1560.x6.nabble.com/Mapserver-7-6-1-PHP-7-Swig-Kml-output-issue-td5447855.html)

Here is an example of mapfile that causes this issue :
[https://pastebin.com/LFxZ1L9T](https://pastebin.com/LFxZ1L9T)

Setup used : Mapserver 7.6.1 / GDal 3.13 / Proj 7.1.1 
`MapServer version 7.6.1 OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=SVG_SYMBOLS SUPPORTS=RSVG SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=FASTCGI SUPPORTS=GEOS SUPPORTS=POINT_Z_M SUPPORTS=PBF INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE`

**Comment by jmckenna** [comment]
@brunodomenget Your choice of title for this issue is correct.   I did more testing, it seems to not have to do with inline features, as any test I do (such as a shapefile layer) that has KML outputformat, will break whenever the layer has a LABEL 
```
"msDrawMap(): Image handling error"
```
So as you stated here, there is a "KML output issue if label is present".  (no problem to generate KML output, but a problem if the original layer has a label).

It seems from past discussions that this once worked (users, years ago, were mentioning KML output with properly generated labels)  I also thought this worked before.  hmm.....

**Comment by jmckenna** [comment]
@msmitherdc  sorry to bother you.  Do you mind testing any of your mapfiles, with MapServer 7.6.1, and a KML outputformat, for any of your layers that has a LABEL?  (maybe I'm making a simple mistake here, as I thought this was always working).    I remember you were an early tester of the initial KML output.   thanks!

**Comment by brunodomenget** [comment]
> @brunodomenget Your choice of title for this issue is correct. I did more testing, it seems to not have to do with inline features, as any test I do (such as a shapefile layer) that has KML outputformat, will break whenever the layer has a LABEL
> 
> ```
> "msDrawMap(): Image handling error"
> ```
> 
> So as you stated here, there is a "KML output issue if label is present". (no problem to generate KML output, but a problem if the original layer has a label).
> 
> It seems from past discussions that this once worked (users, years ago, were mentioning KML output with properly generated labels) I also thought this worked before. hmm.....

I can confirm that kml output works on an old Mapserver 6.4.1 / Gdal 1.9.2 installation with the same mapfile.

If I add Shapezip output
```
OUTPUTFORMAT
        NAME "SHAPEZIP"
        DRIVER "OGR/ESRI Shapefile"
        #MIMETYPE "application/shapefile"   
        FORMATOPTION "STORAGE=filesystem"
        FORMATOPTION "FORM=zip"
        FORMATOPTION "FILENAME=result_shp.zip"
END
```
I get the same error using **shp2img -i shapezip**. But I can make it work with PHP Mapscript (SWIG) by using a OWS Request.

```
$req = new OWSRequest();
		
$args = ['service' => 'WFS', 'request' => 'GetFeature', 'version' => '1.1.0'];
foreach ($args as $param => $value) {
    $req->setParameter($param, $value);
}
$extent = $map->extent;
$req->setParameter('bbox', implode(',', [$extent->minx, $extent->miny, $extent->maxx, $extent->maxy]));
$req->setParameter('outputformat', 'SHAPEZIP');
$req->setParameter('typename', "points");
		
msResetErrorList();
    
msIO_installStdoutToBuffer();
		
$map->OWSDispatch($req);
		
msIO_stripStdoutBufferContentHeaders();
		
$result = msIO_getStdoutBufferBytes();
		
msIO_resetHandlers();

$file = fopen("./test_points.zip", 'w');
if (is_resource($file)) {
        fputs($file, $result);
}
fclose($file);
```

I don't know if it is related, but I had the same issue (same error messages) with SHP output when I first started using Mapserver 6.4 in 2014. I created a thread on the mapserver-users mailing list ( [here](http://osgeo-org.1560.x6.nabble.com/MapServer-6-4-1-OGR-output-error-td5172655.html) ) and that's where I was taught to use OWS Requests for OGR outputs.
