### ISSUE TITLE
WFS GetFeature request against PostGIS view fails when outputFormat=GeoJSON and wfs_features_cache_count is set

### ISSUE THREAD

**Issue by CrispinF** [MapServer/MapServer#6175]
MapServer version 7.4.3 running as CGI on Windows Server 2019 & IIS.

GetFeature requests all worked fine with default GML format, but with outputFormat=GeoJSON some requests would return this:

>  {
> "type": "FeatureCollection",
> "name": "xxxredactedxxx",
> "features": [
> 
> ]
> }
> Status: 400 Internal Server Error
> Content-Type: text/xml; charset=UTF-8
> 
> <ows:ExceptionReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows/1.1" version="2.0.0" xml:lang="en-US" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd">
> <ows:Exception exceptionCode="NoApplicableCode" locator="mapserv"/>
> </ows:ExceptionReport>

With DEBUG 5 on the layer, no errors were logged, and features were correctly retrieved from the database.

Behaviour is consistent - if a given request fails, it fails every time. If it works, it works every time. No discernible logic to what succeeds and what fails.

After much experimentation, the failures were eliminated by removing this setting from the map file:
"wfs_features_cache_count" "10000"

Note this also set in the map file, but removing/altering it made no difference:
	"wfs_maxfeatures" 				"1000"

Output format configured like this:
OUTPUTFORMAT
  NAME "GEOJSON"
  DRIVER "OGR/GEOJSON"
  MIMETYPE "application/json; subtype=geojson"
  FORMATOPTION "STORAGE=stream"
  FORMATOPTION "FORM=SIMPLE"
  FORMATOPTION "LCO:COORDINATE_PRECISION=2"
END

Layer configuration of data source:

	CONNECTIONTYPE POSTGIS
	INCLUDE "xxxredactedxxx_dbconnection.config"
	DATA "geom from v_xxxredactedxxx USING UNIQUE geom_id USING SRID=27700"
	PROCESSING "CLOSE_CONNECTION=DEFER"

Layer metadata like this:
 	"wms_title"  					"xxxredactedxxx"
	"wms_group_title" 				"xxxredactedxxx"
    "wms_abstract"					"xxxredactedxxx"
 	"wms_srs"  						"EPSG:27700"
 	"wms_include_items"  			"all"
	"wms_extent"					"0 0 660000 660000"
 	"wfs_srs"						"EPSG:27700"
	"gml_featureid" 				"geom_id" ## REQUIRED
	"wfs_title"						"xxxredactedxxx"
    "wfs_abstract"					"xxxredactedxxx"
	"gml_include_items" 			"xxxredactedxxx" 
	"wfs_getfeature_formatlist" 	"geojson,OGRGML"
	"wfs_geomtype"					"Geometry"
	"wfs_extent"					"0 0 660000 660000"

**Comment by rouault** [comment]
I'm afraid this is not actionable without a fully self contained reproducer.

**Comment by rouault** [comment]
Closing due to lack of feedback

**Comment by geographika** [comment]
@CrispinF - I was running into a (separate) issue with `wfs_features_cache_count` and came across a possibly related thread I started: https://lists.osgeo.org/pipermail/mapserver-users/2020-January/081531.html

I think I fixed this by adding the following to the GEOJSON `OUTPUTFORMAT`:

```
    FORMATOPTION "USE_FEATUREID=true"
```
