### ISSUE TITLE
describelayer operation shouldnt require height/width/sld_version ?

### ISSUE THREAD

**Issue by landryb** [MapServer/MapServer#6177]
not sure what the ogc specs say about this, but webgis using geoserver as a backend often use the `DescribeLayer` operation to get the WFS url of a displayed WMS layer, e.g https://ids.craig.fr/wxs/public/ows?service=WMS&version=1.1.1&request=DescribeLayer&layers=CRAIG_EMPRISE_RTGE_MAJ_DIFFERENTIELLE_2019 is used and returns
```
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE WMS_DescribeLayerResponse SYSTEM "https://ids.craig.fr/wxs/schemas/wms/1.1.1/WMS_DescribeLayerResponse.dtd">
<WMS_DescribeLayerResponse version="1.1.1">
<LayerDescription name="CRAIG_EMPRISE_RTGE_MAJ_DIFFERENTIELLE_2019" wfs="https://ids.craig.fr/wxs/public/wfs?" owsURL="https://ids.craig.fr/wxs/public/wfs?" owsType="WFS">
<Query typeName="public:CRAIG_EMPRISE_RTGE_MAJ_DIFFERENTIELLE_2019"/>
</LayerDescription>
</WMS_DescribeLayerResponse>
```

trying the same thing against a mapserver 7.6.1 layer with `wfs_onlineresource` set per the doc since  #1157 fails with
```
<?xml version='1.0' encoding="UTF-8" standalone="no" ?>
<!DOCTYPE ServiceExceptionReport SYSTEM "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">
<ServiceExceptionReport version="1.1.1">
<ServiceException>
msWMSLoadGetMapParams(): WMS server error. Image size out of range, WIDTH and HEIGHT must be between 1 and 3600 pixels.
</ServiceException>
</ServiceExceptionReport>
```

to get a proper describelayer response one needs to add width, height and sld_version queryparams which feels.. unneeded ? eg https://wms.craig.fr/ortho?service=WMS&version=1.3.0&request=DescribeLayer&layers=opendata_ortho&WIDTH=1&HEIGHT=1&SLD_VERSION=1.1.0 returns
```
<?xml version='1.0' encoding="UTF-8"?>
<DescribeLayerResponse xmlns="http://www.opengis.net/sld" xmlns:ows="http://www.opengis.net/ows" xmlns:se="http://www.opengis.net/se" xmlns:wfs="http://www.opengis.net/wfs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/DescribeLayer.xsd">
<Version>1.1.0</Version>
  <LayerDescription>
    <owsType>wfs</owsType>
    <se:OnlineResource xlink:type="simple" xlink:href="https://wfs.craig.fr/ortho"/>
    <TypeName>
      <se:FeatureTypeName>opendata_ortho</se:FeatureTypeName>
    </TypeName>
  </LayerDescription>
</DescribeLayerResponse>
```

seems height and width are required since #1088 but afaict this should only be for getmap operations?

**Comment by jratike80** [comment]
Hi,

It is easy to check what OGC standards say. DescribeLayer is documented in the SLD standard. The version 1.1.0 of Styled Layer Descriptor profile of the Web Map Service Implementation Specification has this example:

http://yourfavoritesite.com/WMS?
VERSION=1.3.0&
REQUEST=DescribeLayer&
LAYERS=Rivers,Roads,Houses

Not so surprisingly the example is copied from older SLD standard versions and is invalid by the SLD 1.1.0 because in that version parameter “sld_version” was introduced as a new and mandatory parameter.

I would say that it is definitely wrong to require WIDTH and HEIGHT, and it is definitely right to require SLD_VERSION with WMS version 1.3.0. The WMS 1.1.x version is using SLD 1.0.0 and therefore SLD_VERSION parameter should not be required because it is unknown to SLD 1.0.0.

**Comment by jmckenna** [comment]
I agree with @jratike80, this could be a nice thing to clarify for MapServer 8.0

**Comment by landryb** [comment]
i've had a quick look at mapwms.c and afaict the height/width param check is done in https://github.com/MapServer/MapServer/blob/master/mapwms.cpp#L1386 in the huge `msWMSLoadGetMapParams()` method, called by `msWMSDispatch`.

the check in https://github.com/MapServer/MapServer/blob/master/mapwms.cpp#L5029 makes sure that `msWMSLoadGetMapParams` is called in the `DescribeLayer` request, so either this check should be relaxed, or `msWMSLoadGetMapParams` itself shouldnt throw an exception if height/width isnt found in the `describelayer` case. (eg `if (request && strcasecmp(request, "DescribeLayer") == 0) ` ?)

i can propose a PR for that case, depending on which way is preferred.

**Comment by landryb** [comment]
looking a bit more, the two extra checks for height and width in https://github.com/MapServer/MapServer/blob/master/mapwms.cpp#L1693 seem redundant to the one in line 1386, and i think would also prevent `DescribeLayer` to succeed without the two queryparams

**Comment by landryb** [comment]
bah, disregard last comment, the check 10 lines above makes sure this codepath isnt taken for `DescribeLayer` requests.

**Comment by landryb** [comment]
fwiw, i've finally tested this codepath, and i can confirm that with 8.0.0beta1 i can successfully do a WMS DescribeLayer only specifying a layer name and the protocol version. I'll do further tests to figure out if mapstore2 can correctly link a WMS layer coming from mapserver to its WFS counterpart now.

Thanks @rouault !
