### ISSUE TITLE
Error doing make install on 7.4.4

### ISSUE THREAD

**Issue by phanohanover** [MapServer/MapServer#6185]
Environment:
- Amazon linux 2 virtual server (CentOS 7)
- Proj 6.1.1 compiled
- Gdal 3.2.0 compiled

(perl-devel and other perl-*devel installed too..)

Makefile option set as follow:

...//...
CMAKEFLAGS=-DCMAKE_C_FLAGS="--coverage ${CMAKE_C_FLAGS}" -DCMAKE_CXX_FLAGS="--coverage ${CMAKE_CXX_FLAGS}" \
                          -DCMAKE_SHARED_LINKER_FLAGS="-lgcov" \
                          -DWITH_CLIENT_WMS=1 \
                          -DWITH_CLIENT_WFS=1 \
                          -DWITH_KML=1 \
                          -DWITH_SOS=1 \
                          -DWITH_CSHARP=1 \
                          -DWITH_PHP=0 \
                          -DWITH_PERL=1 \
                          -DWITH_PHPNG=1 \
                          -DWITH_PYTHON=1 \
                          -DWITH_JAVA=1 \
                          -DWITH_THREAD_SAFETY=1 \
                          -DWITH_FRIBIDI=1 \
                          -DWITH_FCGI=0 \
                          -DWITH_EXEMPI=0 \
                          -DWITH_RUBY=0 \
                          -DCMAKE_BUILD_TYPE=Release \
                          -DWITH_RSVG=0 \
                          -DWITH_CURL=1 \
                          -DWITH_HARFBUZZ=1 \
                          -DWITH_POINT_Z_M=1 \
                          ${EXTRA_CMAKEFLAGS}
...//...

Compiling mapserver 7.4.4...

(success) # cd /root/inst/mapserver-7.4.4
(success) # make
(success) # cd build/ 246558
(fail)# make install

```
creating 'dist/mapscript-7.4.4-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing mapscript-7.4.4-py2.7-linux-x86_64.egg
removing '/usr/local/lib/python2.7/site-packages/mapscript-7.4.4-py2.7-linux-x86_64.egg' (and everything under it)
creating /usr/local/lib/python2.7/site-packages/mapscript-7.4.4-py2.7-linux-x86_64.egg
Extracting mapscript-7.4.4-py2.7-linux-x86_64.egg to /usr/local/lib/python2.7/site-packages
mapscript 7.4.4 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/site-packages/mapscript-7.4.4-py2.7-linux-x86_64.egg
Processing dependencies for mapscript==7.4.4
Finished processing dependencies for mapscript==7.4.4
-- Installing: /usr/lib64/php/modules/libphp_mapscriptng.so
-- Set runtime path of "/usr/lib64/php/modules/libphp_mapscriptng.so" to "/usr/local/lib64:/usr/local/lib"
CMake Error at mapscript/perl/cmake_install.cmake:44 (FILE):
  file INSTALL cannot find
  "/root/inst/mapserver-7.4.4/mapscript/perl/$<TARGET_FILE:perlmapscript>".
Call Stack (most recent call first):
  cmake_install.cmake:471 (INCLUDE)
```

Samething happens with Java if I enable the compilation flags in Makefile.

Expected result is a sucessfull make install

Any suggestions?

**Comment by jmckenna** [comment]
Please send this first to the mapserver-users list (there are 1,000+ eyes there), and once you confirm that this is a bug, please come back and re-open this ticket.  subscribe at https://lists.osgeo.org/listinfo/mapserver-users   thanks.  (in other words, always start by asking the MapServer community directly your questions, through the mapserver-users list)
