### ISSUE TITLE
Coveralls is failing due to small percentage changes

### ISSUE THREAD

**Issue by geographika** [MapServer/MapServer#6223]
Recent [pull requests](https://coveralls.io/builds/36714887) are showing as failing even when actual coverage is not reduced (see [discussion here](https://github.com/lemurheavy/coveralls-public/issues/565)). This is caused by the number of lines of code increase as the percentage of code coverage reduces. 

The percentage change rate can be set at https://coveralls.io/github/mapserver/mapserver/settings. @jmckenna I think you have access to this?

Maybe setting to 0.1% would mean we get the nice green ticks without risking adding too much untested code?

![image](https://user-images.githubusercontent.com/490840/106354191-25284000-62f0-11eb-8b37-3ee6974d2dbb.png)

**Comment by jmckenna** [comment]
I had already changed this early yesterday to 1%

**Comment by jmckenna** [comment]
Confirmed, the settings are already at 1% (I did this for my pull request a few days ago).  Checking why it is still erroring...

**Comment by jmckenna** [comment]
The settings already match those in that ticket (that was the same ticket I used yesterday morning to change the settings).  Checking into why they are not applied in builds...

**Comment by jmckenna** [comment]
![Screen Shot 2021-01-30 at 10 25 01 AM](https://user-images.githubusercontent.com/1611709/106358963-b3e38f80-62e5-11eb-802f-d8717da4696d.png)

**Comment by geographika** [comment]
Strange - sorry @jmckenna - thought it might be a quick change..
Perhaps it is something to do with pull requests not being on the main branch. I'll test on one of my repos to see if I can recreate.

**Comment by jmckenna** [comment]
From 2018 from the developer:  "Currently default behavior is fail for any decrease. If your coverage threshold for failure is set, the coverage decrease threshold for failure is ignored."

**Comment by jmckenna** [comment]
checking tickets for coveralls to see reports of this...

**Comment by geographika** [comment]
Ah ok - so maybe remove the 70% value and leave the 0.1%?

**Comment by jmckenna** [comment]
yes i was thinking the same...updating now...

**Comment by jmckenna** [comment]
![Screen Shot 2021-01-30 at 10 42 08 AM](https://user-images.githubusercontent.com/1611709/106359249-d5457b00-62e7-11eb-910c-e785ab423f20.png)

**Comment by jmckenna** [comment]
By the way, when I was looking at this yesterday I was unable to 're-trigger' coveralls for an existing pull request. Let's try a new pull request.

**Comment by jmckenna** [comment]
(I think we can safely merge the py3.8 ticket, and test this with new pull request)

**Comment by jmckenna** [comment]
That changed worked!  Thanks @geographika

**Comment by geographika** [comment]
Thanks @jmckenna!
