### ISSUE TITLE
WFS MultiPolygon & GeoJSON 

### ISSUE THREAD

**Issue by Cadfael31** [MapServer/MapServer#6235]
Hi,

Version: Mapserver 7.6
Protocol: WFS
Output format: GeoJSON

Issue: Multipolygons are replaced  by Polygons with multiparts. This is not compliant with GeoJSON specifications and it causes many errors when you want to use the geometries in computing libraries like TurfJS or others.

Thank you.

**Comment by jratike80** [comment]
Please clarify what you mean by "Polygons with multiparts". Add examples about what you get and what you would like to have.

**Comment by Cadfael31** [comment]
Thank you for your answer.

Please see the attached files:

In _t6235_multipolygon_ you can see the expected result: a multipolygon with two polygons, and the second polygon has a hole.

In _t6235_polygon_ you can see the result from Mapserver with the same geometry, but it is a polygon and three parts, like a polygon with two holes. But one hole is in fact outside the first ring.

[t6235_polygon.txt](https://github.com/MapServer/MapServer/files/5996687/t6235_polygon.txt)
[t6235_multipolygon.txt](https://github.com/MapServer/MapServer/files/5996689/t6235_multipolygon.txt)

![image](https://user-images.githubusercontent.com/34963305/108227187-ed1d5b80-713d-11eb-878b-bb8dd7d7f485.png)
![image](https://user-images.githubusercontent.com/34963305/108227254-00c8c200-713e-11eb-8511-4d7517e9c08c.png)

**Comment by jratike80** [comment]
Right, the faulty geometry is a technically a polygon with an outer ring and one inner ring. The inner ring outside the outer ring.

Please show relevant parts of your mapfile. How have you defined the outputformat? Where does the data come from? Is the default GML output valid?

**Comment by Cadfael31** [comment]
My output format is defined by

OUTPUTFORMAT
        NAME "geojson"
        DRIVER "OGR/GEOJSON"			
        FORMATOPTION "STORAGE=stream"
        FORMATOPTION "FORM=simple"
        FORMATOPTION "LCO:COORDINATE_PRECISION=7"
        FORMATOPTION "LCO:WRITE_BBOX=YES"		
        MIMETYPE "application/json"
	FORMATOPTION "USE_FEATUREID=true"
END

The data come from tiled shapefiles and the tile indexes were created with ogr2ogr. The data are the brazilan rural cadastre. In the attached file I put the layer definition.

[BRAZIL.txt](https://github.com/MapServer/MapServer/files/6001214/BRAZIL.txt)

In the other file I put the feature in GML. You can see that the geometry is correct, with two polygons and one with a hole.

[t6235_multipolygonGML.txt](https://github.com/MapServer/MapServer/files/6001169/t6235_multipolygonGML.txt)

**Comment by rouault** [comment]
Please provide a completely standalone reproducer: mapfile, source dataset and WFS request sent

**Comment by Cadfael31** [comment]
Hello,

here are a light dataset, a mapfile (you may have to change roots) and the querystring of the WFS request. 

You will see that the multipolygons are wrong (for example the one with the attribute IDF = 4727749 or 3079543)

Request: ...?VERSION=2.0.0&SRSNAME=urn:ogc:def:crs:EPSG::4326&BBOX=-9.728561,-36.378579,-9.667877,-36.307013,urn:ogc:def:crs:EPSG::4326&SERVICE=WFS&REQUEST=GetFeature&OUTPUTFORMAT=application%2Fjson&TYPENAME=TEST

[SAMPLE.zip](https://github.com/MapServer/MapServer/files/6100456/SAMPLE.zip)

**Comment by rouault** [comment]
Fix pending in https://github.com/MapServer/MapServer/pull/6254
You can workaround the issue by adding "wfs_geomtype" "MultiPolygon" in the LAYER.METADATA block.
You should also set FORMATOPTION "LCO:COORDINATE_PRECISION=8" since 7 isn't enough to get sufficient precision to avoid topological errors

**Comment by Cadfael31** [comment]
Thanks! The workaround works fine. I will  wait for the next release, but in the meantime it helps me a lot!
