### ISSUE TITLE
Missing Field to add Inspire relevant metadata url ?

### ISSUE THREAD

**Issue by apfelnymous** [MapServer/MapServer#6241]
Hey, this document:
https://inspire.ec.europa.eu/id/document/tg/download-wcs
mentions an attribute "**metadataURL**" for a datametadata link:

```
<inspire_dls:SpatialDataSetIdentifier 
	metadataURL="http://link-to-a-resolver-service/csw?">
	<!-- gmd:MD_Identifier --> 
	<inspire_common:Code> 
		ba209999-0c6c-11d2-97cf-00c04f8eea45 
	</inspire_common:Code> 
	</inspire_dls:SpatialDataSetIdentifier> 
<inspire_dls:SpatialDataSetIdentifier> 
	<!-- gmd:RS_Identifier --> 
	<inspire_common:Code>
		local-identifier-for-dataset 
	</inspire_common:Code>
	<inspire_common:Namespace>
		ftps://some/place/to/resolve-resourceids/
	</inspire_common:Namespace> 
</inspire_dls:SpatialDataSetIdentifier>
```

I couldnt find a field here: https://www.mapserver.org/ogc/inspire_dl.html#inspire-download-service
that would let me insert a value for that attribute.
Notice that I am not talking about the link for the service metadata.

Kind regards.

**Comment by jmckenna** [comment]
@apfelnymous I'm sorry that no-one has jumped on this here.  To be honest there are not many devs reading this here, so do you mind first sending this question (definitely a good question, that I don't know the answer) to the mapserver-users mailing list first?  There are thousands of eyes there.  You/we can always come back here and re-open this ticket, maybe you are asking for a new metadata parameter, but let's see.  Hope this plan is fair.  (well after 22 days of no action, this plan sounds better for now ha).   Subscribe to mapserver-users at https://lists.osgeo.org/listinfo/mapserver-users  Sorry, and thanks for using MapServer.
