### ISSUE TITLE
How to use MS_ENCRYPTION_KEY with AWS connection

### ISSUE THREAD

**Issue by jvaldezch** [MapServer/MapServer#6243]
Hi,
I'm trying to setup a mapfile by using and encrypting AWS credentials into CONFIG parameters, but it is not working.

`CONFIG "AWS_ACCESS_KEY_ID" "{ ... }"`
`CONFIG "AWS_SECRET_ACCESS_KEY" "{ ... }"`
`CONFIG "AWS_DEFAULT_REGION" "{ ... }"`

When I change into plain AWS credentials works. I have use MS_ENCRYPTION_KEY in the past when connecting to PostGIS.

Kind regards.

**Comment by jmckenna** [comment]
As the message in the ticket template said, please first ask your question direct to the MapServer users community (where literally thousands of eyes are awaiting your message): subscribe at https://lists.osgeo.org/listinfo/mapserver-users   Thanks.
Closing ticket.
