### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [MapServer/MapServer#6308]
It has been noticed that while using Gaurav0/backport@v1.0.26 your bot_token 0cba09450792aa8130ae6ef3de09915654afc8cb is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by jmckenna** [comment]
Fixed.  Thanks for the reports @raima-zachariah !!!!

**Comment by raima-zachariah** [comment]
Thanks for taking the time to respond
