### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [MapServer/MapServer#6309]
It has been noticed that while using Gaurav0/backport@v1.0.26 your bot_token_key 665c2358a46ddf0589de5e24a316cdcc64820b2e is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by jmckenna** [comment]
I think this was setup properly at beginning, but was recently switched...thanks for mentioning!

**Comment by jmckenna** [comment]
tackling now...

**Comment by rouault** [comment]
I believe that the value of bot_token_key should be provided as ``${{ secrets.BOT_TOKEN_KEY }}`` set in https://github.com/MapServer/MapServer/settings/secrets/actions/new

**Comment by jmckenna** [comment]
thanks @raima-zachariah & @rouault    

Closing.
