### ISSUE TITLE
msSmallCalloc(): Out of memory allocating -2145790015 bytes.

### ISSUE THREAD

**Issue by Trupix997** [MapServer/MapServer#6322]
MapServer 7.2
Debian 10.6

msSmallCalloc(): Out of memory allocating -2145790015 bytes.
[Thu May 06 03:42:22.781204 2021] [cgid:error] [pid 28448] [client 192.168.XX.XX] End of script output before headers: orto1992aktwcs,

**Comment by jratike80** [comment]
You have not identified any bug in Mapserver so please do not create issues into GitHub straight ahead. Ask questions on the mapserver-users mailing list and give all the details for re-producing the error.

May I guess that you have made a GetCoverage request. For some reason creating a result would require huge amount of memory. Perhaps you have a multiterabyte coverage without reasonable overview levels.

**Comment by rouault** [comment]
msSmallCalloc() failing with such a memory amount is likely a bug in Mapserver. But 7.2 is a bit old, so either it has already been fixed in later versions, either it is there, but we'd need to know which request has triggered this

**Comment by jmckenna** [comment]
@Trupix997 can you create a small test case that triggers this issue (through a shp2img command) and attach it here as a zip archive (including small mapfile, data snippet, commands to use)?  thanks.  (I did see this issue reported with early 7.0 release versions)

**Comment by rouault** [comment]
Closing as we can't do anything with this. Please re-open if you can provide a procedure how to reproduce
