### ISSUE TITLE
WMS Client Test Failing with Demo Server

### ISSUE THREAD

**Issue by geographika** [MapServer/MapServer#6328]
After merging the latest code there was a failing test for https://github.com/MapServer/MapServer/blob/main/msautotest/wxs/wms_client_130_axis_fail.map (which wasn't present in the pull request). 

It looks like `msCGILoadMap(): Web application error. Parameter 'map' value fails to validate.` is returned by the call to https://demo.mapserver.org/cgi-bin/wms? - likely due to `MAP=` security restrictions. 

See https://travis-ci.com/github/MapServer/MapServer/jobs/505584733#L3342 for failing test log.

**Comment by jmckenna** [comment]
I had this working earlier, with the new changes, on the server...hmmm...maybe a mapfile that I didn't configure for this...checking...

**Comment by jmckenna** [comment]
Fixed build, passes, sorry for delay.  Closing.

**Comment by geographika** [comment]
Thanks @jmckenna! I was worried I'd messed up the lexer somehow.
