### ISSUE TITLE
Opening and ending tag mismatch: template line 798 and apply-templates

### ISSUE THREAD

**Issue by gisspace** [MapServer/MapServer#6374]
[root@VM-0-11-centos testxml2map]# xsltproc mapfile.xsl mapfile-test.xml >test.map
mapfile.xsl:812: parser error : Opening and ending tag mismatch: template line 798 and apply-templates
    </xsl:apply-templates>
                          ^
mapfile.xsl:897: parser error : Opening and ending tag mismatch: stylesheet line 2 and template
  </xsl:template>
                 ^
mapfile.xsl:899: parser error : Extra content at the end of the document
  <xsl:template match="ms:Class">
  ^
cannot parse mapfile.xsl

![image](https://user-images.githubusercontent.com/6889060/125724860-e983af39-6e32-4d9b-ac24-bc4e43d2c70c.png)

**Comment by jmckenna** [comment]
@gisspace are you able to create a pull request for this, against the main branch?

**Comment by gisspace** [comment]
OK

**Comment by jmckenna** [comment]
Fixed by @gisspace through https://github.com/MapServer/MapServer/pull/6375
