### ISSUE TITLE
The "composite" is not described in the mapfile.xsl

### ISSUE THREAD

**Issue by gisspace** [MapServer/MapServer#6376]
![image](https://user-images.githubusercontent.com/6889060/126450926-22839f3d-c00f-4826-b81f-f61892c7f43e.png)
The "composite" is not described in the mapfile.xsl

**Comment by jmckenna** [comment]
Great catch @gisspace.  Can you create Pull Request for this change, against the main branch?

**Comment by gisspace** [comment]
OK

**Comment by jmckenna** [comment]
Fixed by @gisspace through https://github.com/MapServer/MapServer/pull/6377
