### ISSUE TITLE
AcceptLanguages - should return exception

### ISSUE THREAD

**Issue by jonathan-geoseer** [MapServer/MapServer#6378]
The MapServer docs say the following for the `AcceptLanguages` request parameter:

https://www.mapserver.org/ogc/inspire_dl.html#inspire-dl-multi-language-support

> "If the language is not supported (or no language parameter is present), the default language has to be used."

Basically the default language is used if the requested language can't be found.

However, the OGC Web Services Common Standard (2.0.0) says:

>  If
> there is no match between the list of languages in the AcceptLanguages parameter and
> the list of languages supported by the server, the service shall return an
> InvalidParameterValue exception.

So it should be returning a InvalidParameterValue exception instead. It should only return the default in this situation if `*` (wildcard) is specified in the `AcceptLanguages` list:

> the server shall support the single special value ―* which is used to indicate ―any
language

I've not tested it (I don't have a MS install), just looking at the docs.

**Comment by jratike80** [comment]
I believe that you are mixing two things. The Mapserver documentations is about the `&language=` parameter as defined in https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-download-services, not about the AcceptLanguages from the OGW standard.

This is from the INSPIRE guidance:

> The Network Services Regulation requires that multilingual aspects for network services are supported 
> [INS NS]. As there is no standard way to deal with multilingualism within the current ISO or OGC 
> specifications, the following basic principles shall be used for INSPIRE Network Services (including 
> Download Services):
> A network service [Download Service] metadata response shall contain a list of the natural 
> languages supported by the service. This list shall contain one or more languages that are 
> supported.
> A client may specify a specific language in a request. If the requested language is contained in 
> the list of supported languages, the natural language fields of the service response shall be in the 
> requested language. If the requested language is not supported by the service, then this 
> parameter shall be ignored.

**Comment by jonathan-geoseer** [comment]
Thanks for the clarification. I was basing it coming from this doc originally: https://www.mapserver.org/ogc/wcs_server.html

> Multi-language support
> Part of the INSPIRE download service support is the support for multi-lingual WCS services. With the wcs_languages a (comma-separated) list of language specifiers can be set. When this is set, client and server can negotiate the result language using the ACCEPTLANGUAGES parameter (or the <ows:AcceptLanguages>/<ows:Language> tags when using XML). The first item in the accept languages list contained in the list specified with wcs_languages will be used for the resulting capabilities document
> 
> Additional information can be found in the section for Multi-language support for certain capabilities fields.

with the last line pointing to the doc I originally quoted (how I got there).

Which seems to be conflating the two things as being the same, at least for MapServer purposes, even though as you implied, they both have different requirements for handling unknown languages.

I didn't test it, but here are some URL's which indicate the behavior is as I described (unless everyone has implemented *Korean* which seems... improbable given they're all ostensibly European services):

https://digitale-ws.cbnbl.org/cgi-bin/mapserv.exe?map=E:/ms4w/apps/ws/digitale2/gnw_wms_ST_NbObs_PV_ancien_MEL_com.map&request=GetCapabilities&service=WMS&version=1.3.0&ACCEPTLANGUAGES=ko

https://ows.gis.rotterdam.nl/cgi-bin/mapserv.exe?map=d:\gwr\webdata\mapserver\map\schoon_pub.map&request=GetCapabilities&service=WMS&version=1.3.0&ACCEPTLANGUAGES=ko

https://geodata.scb.se/mapserver/mapserv.exe?map=/wwwroot/geodata/mapfile/smaorter.map&request=GetCapabilities&service=WMS&version=1.3.0&ACCEPTLANGUAGES=ko

**Comment by jratike80** [comment]
There seems to be conflicting definition in https://inspire.ec.europa.eu/file/1635/download?token=7m3PXp4a "Technical Guidance for the implementation of INSPIRE Download Services using Web Coverage Services (WCS)"

> Yes, it [AcceptLanguages] is mandatory to be supported and shall be processed if the parameter is present in a client’s request with a supported language code. If the parameter is absent in a client’s request or it requested an unsupported language the service shall response in the service default language.

**Comment by jonathan-geoseer** [comment]
Good catch! 
The INSPIRE use of `AcceptLanguages` is explicitly meant to be the OGC implemention:
> WCS  2.0  services  that  are  more  than  trivially  conformant  to  the  language  handling  functionality 
described  in  [OWS  2] 

So it seems whoever wrote that part screwed up. Especially given the typo in the part you quoted  (`response` should be `respond`) which strongly indicates it wasn't properly proofed.

I'd suggest given this to ignore that part of the INSPIRE spec and simply go with the OGC version.

**Comment by jratike80** [comment]
Well, I must admit that I was the head of the temporary MIG working group who prepared the technical guidance, and James Passmore was the technical writer.

Perhaps the AcceptLanguages part as is got written was not totally intentional but it was in line with our general approach.
- We did not want to introduce new schema extensions to WCS because of not so good experience from INSPIRE WMS. Therefore no special INSPIRE &LANGUAGE= keyword that is unknown to standard WCS 2.0 clients (if such exist) but regular AcceptLanguages instead. We probably believed that it was interoperable.
- How "language" should work in INSPIRE was already written before OWS 2 existed. I am not sure what we would have done if we noticed that it is not possible to fulfill the INSPIRE requirement with AcceptLanguages. Perhaps make it mandatory to add "*" to the language list.
- The alternative language negotiation with Accept-Language headers is not strict either. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

> If the server cannot serve any matching language, it can theoretically send back a 406 (Not Acceptable) error code. But, for a better user experience, this is rarely done and more common way is to ignore the Accept-Language header in this case.

I admit that Mapserver does not work right according to OWS. But how critical it is? Do users want to get error messages with unsupported &AcceptLanguages=ko rather than in most cases totally usable response in the default language?

What is your use case? What trouble the current behavior make for you?

**Comment by jonathan-geoseer** [comment]
Investigating further, it seems like everyone just ignores it and uses the default in such cases:

ArcGIS: https://gis.kraj-jihocesky.gov.cz/arcgis/services/DMVS_upd/UP_Strasice/MapServer/WmsServer?request=GetCapabilities&service=WMS&version=1.3.0&ACCEPTLANGUAGES=ko

GeoServer: https://demo.geo-solutions.it/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities&ACCEPTLANGUAGES=ko

QGIS: https://geoservices.buergernetz.bz.it/qgis?request=GetCapabilities&service=WMS&version=1.3.0&ACCEPTLANGUAGES=ko

Deegree: https://geoportal.kreis-lup.de/deegree/services/sozialpflege_sn_wms?request=GetCapabilities&service=WMS&version=1.3.0&ACCEPTLANGUAGES=ko

None return an exception; all are returning a non-Korean GetCap

So either my query is wrong (possible), or it seems that everyone is just ignoring that part of the spec.

**Comment by jratike80** [comment]
WMS 1.3.0 is from year 2006, OGC Web Services Common Standard 2.0 is from year 2010. I do not think that WMS has any support for AcceptLanguages. And because &AcceptLanguages= is an unknown keyword WMS servers just skip it.

Your query is correct and WMS servers seem to behave right. Test AcceptLanguages with standards that implement OWS Common 2.0.

**Comment by rouault** [comment]
> And because &AcceptLanguages= is an unknown keyword WMS servers just skip it.

yes, only WCS 2.0 in MapServer honours AcceptLanguages, and it is indeed slightly non conformant as it will select the default language if the requested one(s) have no match on the server. I'm not sure we want to change that.

**Comment by sdlime** [comment]
Seems like this can be closed @rouault?
