### ISSUE TITLE
add colorrange  and datarange 

### ISSUE THREAD

**Issue by gisspace** [MapServer/MapServer#6381]
![image](https://user-images.githubusercontent.com/6889060/128657993-44ae564c-3642-4857-9b0c-09cabba91501.png)

Mapfile.xsd did not find the attributes colorrange [R] [g] [b] [R] [g] [b] | [hexadecimal string] [hexadecimal string] and datarange [integer|double] [integer|double]

**Comment by jmckenna** [comment]
fixed through https://github.com/MapServer/MapServer/pull/6383
