### ISSUE TITLE
Error MsDrawMap Image handling error when using PNG

### ISSUE THREAD

**Issue by gkvoelkl** [MapServer/MapServer#6386]
Hello,

 i installed the newest version of mapserver on Ubuntu.

when using a png image as symbol I got an error

Image handling error

When using a gif image all is fine.

mapserver issue? Install, cmake issue?

What can I do? Whatˋs wrong?

Where can I get more debugging Information?

Here an example Output:

/usr/lib/cgi-bin/mapserv QUERY_STRING="map=/data/ows/maps/test.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=725521.7,5433653.4,726708.5,5434495.5&CRS=EPSG:25832&WIDTH=1048&HEIGHT=317&LAYERS=test&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE"
libpng error: bad parameters to zlib
Content-Type: text/xml; charset=UTF-8
 
<?xml version='1.0' encoding="UTF-8" standalone="no" ?>
<ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException>
msDrawMap(): Image handling error. Failed to draw layer named &#39;test-layer&#39;.
</ServiceException>
</ServiceExceptionReport>
GDAL: In GDALDestroy - unloading GDAL shared library.

Thanks

Best regards Gerhard

**Comment by jmckenna** [comment]
Please do not use GitHub for asking questions: all questions should be sent to the MapServer-users list, where over 2,000 eyes are awaiting your question:  subscribe at https://lists.osgeo.org/listinfo/mapserver-users

**Comment by sdlime** [comment]
To be fair @gkvoelkl did post on mapserver-users but there were no replies. I'm not sure what to suggest though, that's not an error I've ever run into.

**Comment by gkvoelkl** [comment]
Thanks.👍
