### ISSUE TITLE
Internal server error using WFS GetFeature with resulttype=hits and outputformat=geojson

### ISSUE THREAD

**Issue by fsteggink** [MapServer/MapServer#6403]
## Expected behavior and actual behavior.

The following request returns an Internal Server Error:
http://localhost:9906/maps/panden_plus2?service=WFS&version=2.0.0&request=GetFeature&typename=pand&bbox=130000,450000,140000,460000&resulttype=hits&outputformat=geojson
(The CRS is EPSG:28992, but adding this doesn't make a difference.)

I was expecting to get a JSON output indicating somehow, the feature count, although I don't even know if this is supposed to work. At least an Internal Server Error should not be thrown.

The logging to stdout/stderr shows this:
```
[Mon Sep 06 15:30:54.252990 2021] [fcgid:warn] [pid 4120:tid 140526833628928] [client 192.168.16.1:51382] mod_fcgid: error reading data, FastCGI server closed connection
[Mon Sep 06 15:30:54.253043 2021] [core:error] [pid 4120:tid 140526833628928] [client 192.168.16.1:51382] End of script output before headers: mapserv.fcgi
192.168.16.1 - - [06/Sep/2021:15:30:50 +0200] "GET /maps/panden_plus2?service=WFS&version=2.0.0&request=GetFeature&typename=pand&bbox=130000,450000,140000,460000&resulttype=hits&outputformat=geojson HTTP/1.1" 500 908 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"
[Mon Sep 06 15:30:54.935749 2021] [fcgid:error] [pid 4118:tid 140527389385856] mod_fcgid: process /usr/lib/cgi-bin/mapserv.fcgi(4176) exit(communication error), get unexpected signal 11
```

Relevant MapFile config:
```
  DEBUG 5
  CONFIG "MS_ERRORFILE" "stderr"
```

The following request returns a WFS FeatureCollection indicating the number of features:
http://localhost:9906/maps/panden_plus2?service=WFS&version=2.0.0&request=GetFeature&typename=pand&bbox=130000,450000,140000,460000&resulttype=hits

The only difference is that the `outputformat` parameter is omitted.

Result:
```xml
<?xml version='1.0' encoding="UTF-8" ?>
<wfs:FeatureCollection
   xmlns:panden="<redacted>"
   xmlns:gml="http://www.opengis.net/gml/3.2"
   xmlns:wfs="http://www.opengis.net/wfs/2.0"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="<redacted> http://localhost:9906/maps/panden?SERVICE=WFS&amp;VERSION=2.0.0&amp;REQUEST=DescribeFeatureType&amp;TYPENAME=pand&amp;OUTPUTFORMAT=application%2Fgml%2Bxml%3B%20version%3D3.2 http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd"
   timeStamp="2021-09-06T16:32:24" numberMatched="15000" numberReturned="0"
   next="http://localhost:9906/maps/panden?service=WFS&amp;version=2.0.0&amp;request=GetFeature&amp;typename=pand&amp;bbox=130000%2C450000%2C140000%2C460000">
</wfs:FeatureCollection>

```
As you can see, the numberMatched attribute holds the value of `15000`, which is the value I've set as the maximum number of features to be returned in a WFS request.

The logging is:
```
[Mon Sep 06 15:30:17.215981 2021] [fcgid:warn] [pid 4120:tid 140527336261376] [client 192.168.16.1:51374] mod_fcgid: stderr: CGI Request 2 on process 4175
[Mon Sep 06 15:30:17.216023 2021] [fcgid:warn] [pid 4120:tid 140527336261376] [client 192.168.16.1:51374] mod_fcgid: stderr: mapserv request processing time (msLoadMap not incl.): 4.159s
[Mon Sep 06 15:30:17.216029 2021] [fcgid:warn] [pid 4120:tid 140527336261376] [client 192.168.16.1:51374] mod_fcgid: stderr: msFreeMap(): freeing map at 0x55f4dde25700.
192.168.16.1 - - [06/Sep/2021:15:30:13 +0200] "GET /maps/panden_plus2?service=WFS&version=2.0.0&request=GetFeature&typename=pand&bbox=130000,450000,140000,460000&resulttype=hits HTTP/1.1" 200 925 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"
```

The following requests returns a GeoJSON file with 10 features:
http://localhost:9906/maps/panden_plus2?service=WFS&version=2.0.0&request=GetFeature&typename=pand&bbox=130000,450000,140000,460000&maxfeatures=10&outputformat=geojson

The only difference is that the `outputformat` parameter is replaced by the `maxfeatures` parameter (in order to limit the results).

Result:
```json
{
"type": "FeatureCollection",
"name": "pand",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::28992" } },
"features": [
{ "type": "Feature", "properties": { <redacted> }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 132448.165, 459992.304 ], [ 132452.035, 459981.582 ], [ 132446.072, 459979.928 ], [ 132443.19, 459991.009 ], [ 132448.165, 459992.304 ] ] ] } }
<9 more features>
]
}
```

I've also tried to run the `mapserv` command in my Docker container, but in order for that to be working many different parameters need to be set. Apache is running as a non-root user. Perhaps the cause is a permission error, but it's strange that both GeoJSON is returned with a "normal' GetFeature request, and that the GML equivalent returns the expected result.

As for the probable cause: my primary suspicion is that there is no suitable place in a GeoJSON feature collection to hold the feature count. Perhaps the MapServer code is not able to handle this case. The error mentioned in the error log can have multiple causes, as mentioned here: https://serverfault.com/questions/364341/500-error-after-mod-fcgid-error.

## Steps to reproduce the problem.

See above.

## Attach simple test case (drag/drop it here)

Please let me know if additional info is required. 

## Operating system

Docker container with Linux (Debian Buster)

## MapServer version and installation method

I'm using MapServer version 7.6.4 on Linux (Debian Buster) in a Docker container, enabled by FastCGI in Apache.

**Comment by jratike80** [comment]
No internal server error with https://[demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=getfeature&TYPENAMES=continents&resulttype=hits&outputformat=geojson](https://demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=getfeature&TYPENAMES=continents&resulttype=hits&outputformat=geojson)

Gives instead
```<ows:Exception exceptionCode="InvalidParameterValue" locator="outputformat">
<ows:ExceptionText>msWFSGetFeature(): WFS server error. 'geojson' is not a permitted output format for layer 'continents', review wfs_getfeature_formatlist setting.</ows:ExceptionText>
</ows:Exception>
```

That's OK, we do not support that.

**Comment by fsteggink** [comment]
I'll retry with the latest version when I have time for it.
And as for the geojson format, I see that I've omitted an essential part of the config:
```
  OUTPUTFORMAT
    NAME "geojson"
    DRIVER "OGR/GEOJSON"
    MIMETYPE "application/json; subtype=geojson"
    FORMATOPTION "STORAGE=stream"
    FORMATOPTION "FORM=SIMPLE"
  END # OUTPUTFORMAT
```

In https://demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=getcapabilities I see that only GML variants are allowed as output format, so, unless you change the configuration, you will never be able to reproduce my error with this service.

**Comment by jratike80** [comment]
Sorry, I was too busy when reading the description. GetFeature with resulttype=hits is a valid request and there is no way to tell in the GetCapabilities that GeoJSON is supported only for resulttype=results. But am I right that even when GeoJSON is returned it is missing these:
`timeStamp="2021-09-06T16:32:24" numberMatched="15000" numberReturned="0"`? So probably you would not get the answer that you wish even if you would not face the Internal Server Error.

The additional outputformats are not well defined in the WFS standard. Maybe user should consider that everything that works is nice extra and if something does not work then there is always the standard GML alternative. For example, outputformat shape-zip certainly is not 
practical for querying the hits.

Geoserver seems to be in the same situation, no JSON for hits https://gis.stackexchange.com/questions/213372/geoserver-wfs-request-resulttype-hits. I also remember seeing requests for getting DescribeFeatureType responses in JSON. Developers may not be so willing to improve the JSON support in WFS because the OGC API Features is natively all JSON.

Do you suggest reopening this issue?

**Comment by jmckenna** [comment]
I've enabled GeoJSON as an outputformat on the demo server (but please use the `MAXFEATURES` parameter to not overwork the server), so a request like this should work now:  https://demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=getfeature&TYPENAMES=continents&OUTPUTFORMAT=geojson&MAXFEATURES=10

Let me know if that works for you locally.

**Comment by geographika** [comment]
Reopening this as I ran into the same issue today. If (any) OUTPUTFORMAT is set for a `resultType=hits` WFS request MapServer throws a segmentation fault.

**Comment by fsteggink** [comment]
Gentlemen, thank you for solving this issue. I'm okay with the fact that there is no result, since what exactly should be returned when `resulttype=hits` is combined with GeoJSON is not well defined. I agree that OGC API Features is a much better solution to deal with GeoJSON.
