### ISSUE TITLE
Layer-Tile-Index cannot open raster files from index locations.  msShapefileOpen(): Unable to access file.

### ISSUE THREAD

**Issue by ashleysommer** [MapServer/MapServer#6404]
## Expected behavior and actual behavior.
This is a follow up to a potential bug I posted about in the Mapserver-Users mailing list yesterday:
https://lists.osgeo.org/pipermail/mapserver-users/2021-September/082307.html

I'm starting this Github issue in order to more clearly document my efforts in trying to come to a solution (and creating a PR if required).

## Reproduction of some parts of my post to the mailing list:
I have a directory of raster files, tiled in the temporal axis, I wish to serve using WCS.
I've created a index using gdaltindex, adding and populating a date column in the dates of the files.
I've come up with the following example code in my mapfile (there's more explanation and background in my email above).
```
MAP
  WEB
    METADATA
        wcs_enable_request "*"
    END
  END
  LAYER
    TYPE TILEINDEX
    NAME "MyIndex"
    TILEINDEX "/datasets/mydataset/v1/layer1/index.shp"
  END
  LAYER
    TYPE RASTER
    NAME "MyData"
    TILEINDEX "MyIndex"
    TILEITEM "location"
    METADATA
        wcs_label "MyData"
        wcs_timeitem "date"
        wcs_extent "112.9049988 -43.7350006 153.9949951 -9.0050001"
        wcs_size "4110 3474"
    END
  END
END
```
This now works to some extent, but then I get an error:
>msTiledSHPTryOpen(): Unable to access file. Unable to open shapefile 'raster_2020-08-02.tif' for layer 'MyIndex' ... fatal error. msShapefileOpen(): Unable to access file. (/tmp/raster_2020-08-02.tif) msShapefileOpen(): Unable to access file. (/datasets/mydataset/v1/layer1/raster_2020-08-01.tif)

I believe I have tracked down why this is happening, and I believe it is a bug.
1) Mapserver _can_ open the .shp and .dbf file at the location. It must be able to to get the file location from the dbf index.
2) msTiledSHPTryOpen() is a helper fn that runs _after_ opening a tile index, to test if we can open the first-indexed file (to template some parts of the layer).
See comment here: https://github.com/MapServer/MapServer/blob/0d156a72893b1df712cb49c1b3ddaeed5365a68b/mapshape.c#L2028
See also msTileSHPTryOpen fn here: https://github.com/MapServer/MapServer/blob/0d156a72893b1df712cb49c1b3ddaeed5365a68b/mapshape.c#L1868
3) So msTiledSHPTryOpen() tries to open the first-indexed file: "/datasets/mydataset/v1/layer1/raster_2020-08-02.tif" but returns an error, even though it _can_ open that file.
The problem is, it is using msShapefileOpen() to do this, which in-turn uses msSHPOpen() to open the tif file:
See msShapefileOpen fn: https://github.com/MapServer/MapServer/blob/0d156a72893b1df712cb49c1b3ddaeed5365a68b/mapshape.c#L1665
See opener: https://github.com/MapServer/MapServer/blob/0d156a72893b1df712cb49c1b3ddaeed5365a68b/mapshape.c#L1686
4) msSHPOpen() assumes whatever file its opening will have a .shp file and a .shx file.
In this case, it's trying to open a .tif file. The function tries to open a non-existent /datasets/mydataset/v1/layer1/raster_2020-08-02.shp file.
See the implementation here: https://github.com/MapServer/MapServer/blob/0d156a72893b1df712cb49c1b3ddaeed5365a68b/mapshape.c#L194
And where it opens a file here: https://github.com/MapServer/MapServer/blob/0d156a72893b1df712cb49c1b3ddaeed5365a68b/mapshape.c#L252

So I believe it is a bug to use msShapefileOpen() to test if a tileindex can open a file at its first-indexed location, because that file may not be a .shp file.

I might be able to put in a PR to fix the bug, but I don't know the codebase well enough to not potentially introduce regressions.
Let me know what you think?

## Attach simple test case (drag/drop it here)
Building a test case now, will post it a bit later.

## Operating system
Ubuntu 20.04

## MapServer version and installation method
MS v7.6.4, compiled with GDAL v3.3.0 in a Docker container

**Comment by ashleysommer** [comment]
Looking deeper into the code, I'm trying to come up with a fix.
However it seems like this is going down completely the wrong codepath.
All of the `msTiledSHP*` functions should never be called on this dataset.
Looks like this is caused by setting the index layer `TYPE` to `TILEINDEX`. This inherently sets the internal type to TiledShapefile, which assumes each entry in the index points to another shapefile.

I changed the `TYPE` of the index layer to `RASTER`, however now I'm getting a different error:
> "General error message. This data driver does not implement filter translation support"
The WCS returns a tif file, but it is all NANs.

**Comment by ashleysommer** [comment]
Update: I've found a solution.
The LayerTileIndex itself should not have a TILEINDEX, instead it uses DATA to point to the shape file, like this.
```
  LAYER
    TYPE TILEINDEX
    NAME "MyIndex"
    DATA "/datasets/mydataset/v1/layer1/index.shp"
  END
```
I guess this is a documentation bug? There is nowhere in the documentation that shows a Layer with type TILEINDEX and a DATA parameter.
I worked out how to do it by looking in the code at how a Raster layer with a normal TILEINDEX sets up its index layer:
https://github.com/MapServer/MapServer/blob/7c65ac4256d94e0dcc2870ef6f7ccb549f3b0f70/mapraster.c#L256-L259

**Comment by jratike80** [comment]
I am not yet sure about what you want to achieve but LAYER - TYPE - TILEINDEX is not documented https://mapserver.org/mapfile/layer.html. Does it work in any way? 

There is one thing in tileindexes that is documented but it is not obvious for users and it lacks usage examples. It is that another Mapserver LAYER can be used as a tileindex.

> When a tileindex layer is used, it works similarly to directly referring to a file, but any supported feature source can be used (ie. postgres, oracle).

For example a tileindex layer we use for filtering and ordering an orthophoto layer is a bit like this

```
LAYER
        NAME "tileindex_for_orthophotos"
        STATUS ON
        TYPE POLYGON
        UNITS METERS
        SIZEUNITS PIXELS
        CONNECTIONTYPE OGR
        CONNECTION "ortho_footprints.sqlite"
        DATA "SELECT path||location as location, crs, resolution, max(time) as time, mapsheetID, GEOMETRY FROM orthos group by mapsheetID order by time"
```

Then the orthophoto layer refers to this layer by name:

```
LAYER
        NAME "orthophoto"
        STATUS ON
        TILEINDEX "tileindex_for_orthophotos"
        TILESRS "crs"
```

Mapserver unfortunatly does not support time as a dimension with WCS 2.0 https://lists.osgeo.org/pipermail/mapserver-users/2019-January/080918.html. For making time based WCS GetCoverages we have added the time attributes into the tileindex "start_time" and "end_time". The DATA that is used for the tileindex layer contains SQL like `and start_time>%time1% and end_time<%time2%`. User can send the variables time1 and time2 with the GetCoverage request. They have validation blocks and default values in the mapfile.

**Comment by ashleysommer** [comment]
The tiny little snippet of documetnation that I'm working with is on the page about WCS server:
https://mapserver.org/ogc/wcs_server.html?highlight=tileindex#spatio-temporal-indexes
That describes the need to create a shp/dbf index using gdaltindex and adding the time coloumn.

It also mentions "new style" tile indexes are easier to use, aka the TileLayerIndex feature.
Actually the WCS service doesn't even start up if you don't use the "new style" TileLayerIndex:
https://github.com/MapServer/MapServer/blob/7c65ac4256d94e0dcc2870ef6f7ccb549f3b0f70/mapwcs.cpp#L1920-L1925

And the demo wcs.map uses layers with `TYPE TILEINDEX`:
https://demo.mapserver.org/ogc-demos/map/wcs.map

I guess I missed the fact that they use "DATA" to point to the shape. If I noticed that, I would've solved my problem 24h earlier.

My client software is compliant with WCS v1.0 only, so I don't need v1.1 or 2.0 compatibility.

**Comment by jratike80** [comment]
I noticed that I did not read very carefully your original description and my previous comment was probably not very useful.

I can see that the mapfile https://demo.mapserver.org/ogc-demos/map/wcs.map is written by an experienced Mapserver user/developer and things obvious to them are not explained, like that `DATA "mod13"` is searching a shapefile mod13.shp from the shapepath directory.

**Comment by ashleysommer** [comment]
My configuration is working well now, I don't need any further help.
I too use SHAPEPATH to add a prefix to my DATA, its quite straightforward. As a software engineer I find it easier to read the sourcecode of the application, than to interpret the badly written and out of date documentation.

**Comment by jratike80** [comment]
We may want to care about other users by the same. You told you lost your way for 24 hours, what would you suggest to do to prevent that from happening for somebody else?
