### ISSUE TITLE
IIS server returns HTTP 500 errors outside of FastCGI loop

### ISSUE THREAD

**Issue by geographika** [MapServer/MapServer#6411]
As noted in #6303 - Windows IIS (and possibly other servers) return HTTP 500 errors if the program exits, rather than returning an HTTP response with an error. This makes it hard to diagnose the underlying issue - for example the path to the config file could be incorrect, or the environment variable is missing.

Examples:

https://github.com/MapServer/MapServer/blob/17d8fa9730768c2122cbc78f07598b365d1a6c37/mapserv.c#L144-L148

https://github.com/MapServer/MapServer/blob/b55b1281ed80592b469f259c10ec9830bf2894a8/mapserv.c#L156-L158

Attempts to exit within the `FCGI_Accept() >= 0` loop worked once and then failed.
Possible solution is to simply keep going to `goto end_request;`

**Comment by sdlime** [comment]
I have a feeling we'll need an alternative to msCGIWriteError() for this use case, something more independent of any initialization or setup.

**Comment by geographika** [comment]
A couple of things that didn't work:

- using `return (0)` instead of `exit(0)
- setting `finish_process = 1;` in the block where `if(config == NULL) ` (this variable comes from https://github.com/MapServer/MapServer/pull/6385/)

I think what we probably want to happen is either:

1. The process fails, but somewhere the issue of a missing config file is logged - currently on IIS the HTTP 500 error is returned. Request logging only produces:

```
ModuleName FastCgiModule 
Notification EXECUTE_REQUEST_HANDLER 
HttpStatus 500 
HttpReason
HttpSubStatus 0 
ErrorCode The operation completed successfully.  (0x0) 
```

2. We let the process continue (the FastCGI loop), but each request simply outputs the same MapServer error 

I'm interested how this appears on other web servers - does setting `MAPSERVER_CONFIG_FILE` to a missing file return HTTP 500 with no logs/messages?

**Comment by sdlime** [comment]
I can confirm the 500 error with FastCGI using Vagrant. Nothing in the logs other than the standard _"End of script before headers: mapserv.fcgi"_. The setup is:

1. No config file defined as an environment variable using SetEnv or FcgiidInitialEnv.
2. Using "wget -0 - http://localhost/cgi-bin/mapserv.cgi" or mapserv.fcgi.

The CGI returns the config file not found error.

**Comment by sdlime** [comment]
@geographika, if I change the configuration error handling to do some FastCGI related initialization before writing the error then I don't see a 500 error and get the expected error message.

```
  config = msLoadConfig(NULL); // is the right spot to do this?                                                                           
  if(config == NULL) {
#ifdef USE_FASTCGI
    msIO_installFastCGIRedirect();
    FCGI_Accept();
#endif
    msCGIWriteError(mapserv);
    exit(0);
  }
```

**Comment by geographika** [comment]
@sdlime - I can confirm with this update on IIS/FastCGI I get the following error with an invalid path, rather than a generic HTTP 500 error:

`msLoadConfig(): Unable to access file. (C:\MapServer\bin\mapserver.confx)`

And when missing the environ variable `MAPSERVER_CONFIG_FILE` (as it defaults to the default path):

`msLoadConfig(): Unable to access file. (/mapserver.conf)`

This will make it much easier for users to setup/diagnose the issue.

**Comment by sdlime** [comment]
Thing is that I don't think we should be outputting the config file name/path.

**Comment by sdlime** [comment]
IMHO, it would be nice to do something like:

  msLoadConfig(): Unable to access config file (see mapserver.org/config_file.html).

--Steve

**Comment by sdlime** [comment]
@geographika, think we can close this?

**Comment by geographika** [comment]
Yes, fixed as part of https://github.com/MapServer/MapServer/pull/6303/ - thanks @sdlime !
