### ISSUE TITLE
Corrupt Zip Outputs using Windows MapServer CGI (with GISInternal builds)

### ISSUE THREAD

**Issue by geographika** [MapServer/MapServer#6459]
When using MapServer CGI shapezip outputs are corrupt. 

This issue relates to the following mailing list posts: https://lists.osgeo.org/pipermail/mapserver-dev/2021-November/016669.html
https://lists.osgeo.org/pipermail/mapserver-users/2021-November/082429.html

The zip files are invalid, as the binary outputs have Windows carriage linefeeds added to them (`OD OA` - **CRLF** instead of `OA` **LF**). 

However, the following must both be true for this to occur:

- CGI is used (either via the command line or through a web server) - everything works fine when using FastCGI
- GDAL 3 is used (tested with `gdal303.dll`). The issue does not occur when MapServer is built using `gdal204.dll`. The same Mapfile and commands produce valid output in ms4w and `release-1911-x64-gdal-2-4-4-mapserver-7-4-3` from GISInternals.

**Comment by jmckenna** [comment]
For the record, I cannot reproduce this with MS4W 5.0 (beta2), that contains GDAL 3.4.0, MapServer-main.  MS4W 4.0.5 also does not produce this issue (GDAL 2.4.4, MapServer 7.6.4).

I am updating the wording of this issue title to reflect that this seems specific to gis internal builds.

**Comment by szekerest** [comment]
@geographika Which package are you using to reproduce this?

**Comment by geographika** [comment]
@szekerest - I'm using the development kit `release-1928-x64-dev` downloaded from https://www.gisinternals.com/query.html?content=filelist&file=release-1928-x64-dev.zip

I'm building with the lastest Mapserver (`main`) code. 

To recreate on the command line with an msautotest:

```
D:\MapServer\release-1911-x64-gdal-2-4-4-mapserver-7-4-3\SDKShell.bat
SET PROJ_LIB=D:\MapServer\release-1911-x64-gdal-2-4-4-mapserver-7-4-3\bin\proj\share
mapserv -nh "QUERY_STRING=map=D:\GitHub\mapserver\msautotest\wxs\wfs_ogr.map&service=WFS&REQUEST=GetFeature&TYPENAME=road&version=2.0.0&outputformat=shapezip" > D:\Temp\output.zip
```

When using CGI the zip contains `CR`, but strangely the build works fine under FastCGI, so I'm guessing something is written as text rather than binary at some point.

Attached are the two zips (one from FastCGI one from CGI):

[working.zip](https://github.com/MapServer/MapServer/files/7927940/working.zip)
[corrupt.zip](https://github.com/MapServer/MapServer/files/7927941/corrupt.zip)

**Comment by geographika** [comment]
A few more details. The differences between the working ms4w 5 beta and builds using the GISInternals buildkits are:

- ms4w uses GDAL 304.dll, GISInternals uses GDAL 303.dll
- ms4w builds are x32, the corrupt zips were generated using x64 builds:

From Even on the mailing list post: 

> Zipping is done by GDAL, so could be a GDAL related change (there were adjustments in the past regarding ZIP64 that could result in some bytes being different)

I've used various combinations of the following without success:

```
# in the map file
CONFIG "CPL_CREATE_ZIP64" "NO"
CONFIG "CPL_CREATE_ZIP64" "YES"
```

And on the command line:
```
SET CPL_CREATE_ZIP64=YES
SET CPL_CREATE_ZIP64=NO
```

**Comment by geographika** [comment]
I can confirm the patch to `libfcgi ` described in https://github.com/gisinternals/buildsystem/issues/193 fixes this issue, and the test case above now produces valid zips from the command line using `mapserv`. 
Thanks @szekerest !
