### ISSUE TITLE
Cmake not finding Postgres (main branch, SuSE)

### ISSUE THREAD

**Issue by sdlime** [MapServer/MapServer#6504]
I'm running into problems with cmake finding PostgreSQL using the main branch on SuSE 15.  This is not an issue with the 7.6 branch.

Looking at _cmake/FindPostgreSQL.cmake_ it is finding pg_config on the machine but the command

`exec_program( ${PG_CONFIG} ARGS "--libdir" OUTPUT_VARIABLE PG_LIB_PATH )`

Isn't returning a directory that contains libpq.so so when the following command executes it doesn't find the library.

```
find_library(POSTGRESQL_LIBRARY NAMES pq libpq
    PATHS
    ${PG_LIB_PATH}
    NO_DEFAULT_PATH
)
```

If I edit _cmake/FindPostgreSQL.cmake_ and add the necessary directory (e.g. /usr/lib64) to the above command it works as expected. This wasn't an issue before because the checked places like /lib, /usr/lib and /usr/lib64 by default. Introduced with pull request: https://github.com/MapServer/MapServer/pull/6269.  Perhaps this is just a SuSE issue but I ran into it with PostgreSQL 10.10 and PostgreSQL 13.4 packages.

--Steve

**Comment by rouault** [comment]
Suggestion: maybe we should use the CMake upstream FindPostgreSQL module ?
GDAL does that (we've vendored it when CMake < 3.20 since the version in CMake 3.20 is the first one to not require the server part of PostgreSQL, but just libpq): https://github.com/OSGeo/gdal/blob/master/cmake/modules/3.20/FindPostgreSQL.cmake

**Comment by sdlime** [comment]
> Suggestion: maybe we should use the CMake upstream FindPostgreSQL module ? GDAL does that (we've vendored it when CMake < 3.20 since the version in CMake 3.20 is the first one to not require the server part of PostgreSQL, but just libpq): https://github.com/OSGeo/gdal/blob/master/cmake/modules/3.20/FindPostgreSQL.cmake

That's a complex module but not re-inventing the wheel and relying on something authoritative make sense. I guess I don't understand what you mean by vendored it? (SuSE 15 packages are for cmake 3.17) Looks like we'd have to update CMakeLists.txt too. I guess I'm curious what drove https://github.com/MapServer/MapServer/pull/6269 in the first place?

**Comment by rouault** [comment]
> guess I don't understand what you mean by vendored it?

just that we have imported it in the GDAL repository and include if when CMake < 3.20 . For CMake >= 3.20, the module shipped with CMake is used.

**Comment by sdlime** [comment]
Are the cmake variables set by the module (e.g. PostgreSQL_LIBRARIES) case sensitive when referenced elsewhere?

**Comment by rouault** [comment]
> Are the cmake variables set by the module (e.g. PostgreSQL_LIBRARIES) case sensitive when referenced elsewhere?

yes
