### ISSUE TITLE
pk.eyJ1IjoiZGFuaWxvcm9xdWU1MDEiLCJhIjoiY2w0MXQxc2phMDBtdTNibW5qdDZqdGhjdyJ9.ibaySgLcFB3jZcEYvx_F1g

### ISSUE THREAD

**Issue by DaniloRoque501** [MapServer/MapServer#6532]
## Expected behavior and actual behavior.

For example (please modify !!!): I expected the following request to work 
(paste request) and it returns an error message instead (paste error).

## Steps to reproduce the problem.

For example (please modify !!!): "mapserv -nh QUERY_STRING='map=test.map&...'"

## Attach simple test case (drag/drop it here)

Please create a .zip file that contains:
 - small .map file
 - data
 - commands.txt (containing commands to reproduce your problem such as 
   map2img, mapserv, etc.

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

## MapServer version and installation method

For example (please modify !!!): the 7.6.1 version from ubuntugis-unstable PPA

**Comment by DaniloRoque501** [comment]
pk.eyJ1IjoiZGFuaWxvcm9xdWU1MDEiLCJhIjoiY2w0MXQxc2phMDBtdTNibW5qdDZqdGhjdyJ9.ibaySgLcFB3jZcEYvx_F1g

**Comment by DaniloRoque501** [comment]
https://github.com/MapServer/MapServer/issues/6532#

**Comment by DaniloRoque501** [comment]
https://github.com/MapServer/MapServer/issues/6532DaniloRoque501

**Comment by DaniloRoque501** [comment]
DaniloRoque501

**Comment by jratike80** [comment]
Spam?
