### ISSUE TITLE
8.0.0beta1 FastCGI only replies to one request in error, then is stuck

### ISSUE THREAD

**Issue by landryb** [MapServer/MapServer#6543]
on OpenBSD testing the 8 beta, using spawn-fcgi (without chrooting) eg `spawn-fcgi -s /var/www/run/mapserv.sock -u www -- /var/www/cgi-bin/mapserv` or supervisord, i have a strange behaviour of mapserver which only replies to the first request with an error message coming from https://github.com/MapServer/MapServer/blob/main/mapfile.c#L6288

outputs `msLoadMap(): General error message. getcwd() returned a too long path`

my test query is `http://serverip/cgi-bin/mapserv?map=/tmp/mapserver/ign.map`

`/etc/mapserver.conf` is super basic:
```
CONFIG
  ENV
    MS_MAP_PATTERN "^/tmp/mapserver"
    MS_DEBUGLEVEL "5"
    MS_ERRORFILE "/tmp/mapserver.log"
  END
   MAPS
  END
END
```

then the process ends up in a stuck state, eg doesnt replies anymore to requests, nginx returns a 502, the process still runs but needs to be killed.

i dont understand how/why this error codepath is taken.

**Comment by landryb** [comment]
at some point i thought this was related to params conflicting, eg i had `fastcgi_param MS_MAPFILE /tmp/mapserver/ign.map;` in my nginx config, but with that commented out it doesnt help.

**Comment by landryb** [comment]
after instrumenting the error message returned by getcwd() by printing errno, the failure is EACCES.

after fiddling with spawn-fcgi options, adding `-d /tmp` (which forces a chdir() to `/tmp`, otherwise i guess it chdir() to somewhere else ?) doesn't result in more errors from `getcwd()`, and i have ms8 working ... the error message was definitely not helpful.

**Comment by landryb** [comment]
thanks a lot @rouault ! #6545 looks much better

**Comment by landryb** [comment]
now that i dig deeper in this issue, i found out that the behaviour of 'only replies to one request with an error then is stuck' looks like a regression from adding ogc api support in #6180.

to summarize, with 7.6.4 configured as fastcgi spawned by spawn-fcgi server behind nginx, i can load http://localhost/cgi-bin/mapserv without any argument, i get `No query information to decode. QUERY_STRING is set, but empty. ` from https://github.com/MapServer/MapServer/blob/main/cgiutil.c#L237 which is expected, and if i repeat the same request i still get the same error message.

with 8.0.0beta1, the error message is returned at the first 'wrong' request, then mapserv process looks stuck in limbo. i need to restart spawn-fcgi process to make it reply to a single request.

locally reverting the changes from #6180 (which is a huuuge commit..) to cgiutil.c (https://github.com/MapServer/MapServer/commit/0db046cafcb9fce757e1fc652cdd467dfd9b5c28#diff-3aae315900ca0d05b5f92495b85119ee693081f0ee75367d317a53dedc322fc6) eg uncomment the 3 `msIO` lines, & comment out the `msSetError` line i can repeat the error message several times in a row without having the stuck process.

@sdlime ?

**Comment by landryb** [comment]
same thing if i just give a mapfile without other argument, mapserver will reply ' mapserv(): Web application error. Traditional BROWSE mode requires a TEMPLATE in the WEB section, but none was provided. ' as expected but the next request will fail. I have to dig deeper to figure out if its a regression or something wrong in my testing env.

**Comment by rouault** [comment]
I can't confirm issues with Apache and Fast-CGI: I can alternate right & wrong requests
```
curl "http://localhost/cgi-bin/mapserv.fcgi?MAP=bug_328"
curl "http://localhost/cgi-bin/mapserv.fcgi?MAP=bug_328&SERVICE=WMS&REQUEST=GetCapabilities"
curl "http://localhost/cgi-bin/mapserv.fcgi?MAP=bug_328"
curl "http://localhost/cgi-bin/mapserv.fcgi?MAP=bug_328&SERVICE=WMS&REQUEST=GetCapabilities"
```

**Comment by landryb** [comment]
thanks @rouault for checking, i'll try to figure out what's wrong then in my testing env.

**Comment by landryb** [comment]
> thanks @rouault for checking, i'll try to figure out what's wrong then in my testing env. Using spawn-fcgi and nginx, i cant get it to work....


this is getting weirder and weirder because i have the same issue with 7.6.4 in the same spawn-fcgi/nginx env. Using ktrace, at the first request (`GET /cgi-bin/mapserv7?map=bla`) i see an accept being done on the unix fastcgi socket, then the request:
```
 62744 mapserv7 CALL  read(3,0x401a2cec000,0x2000)
 62744 mapserv7 GIO   fd 3 read 864 bytes
       "\^A\^A\0\^A\0\b\0\0\0\^A\0\0\0\0\0\0\^A\^D\0\^A\^C2\^F\0\^O\^QSCRIPT_FILENAME/cgi-bin/mapserv7  \0PATH_INFO\f\aQUERY_STRINGmap=bla\^N\^CREQUEST_METHODGET\f\0CONTENT_TYPE\^N\0CONTENT_LENGTH\v\^QSCRIPT_NAME/cgi-bin/mapserv7\v\^YREQUEST_URI/cgi-bin/mapserv7?map=bla\f\^QDOCUMENT_URI/cgi-bin/mapserv7\r\aDOCUMENT_ROOT/htdocs\^O\bSERVER_PROTOCOLHTTP/1.1\^N\^DREQUEST_SCHEMEhttp\^Q\aGATEWAY_INTERFACECGI/1.1\^O\fSERVER_SOFTWAREnginx/1.22.0\v\rREMOTE_ADDR109.74.91.254\v\^EREMOTE_PORT64523\v\bSERVER_ADDR10.0.2.2\v\^BSERVER_PORT80\v     SERVER_NAMElocalhost\^O\^CREDIRECT_STATUS200    \fHTTP_HOST45.67.82.140\^OGHTTP_USER_AGENTMozilla/5.0 (X11; OpenBSD amd64; rv:103.0) Gecko/20100101 Firefox/103.0\vUHTTP_ACCEPTtext/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8\^T\^WHTTP_ACCEPT_LANGUAGEfr,en-US;q=0.7,en;q=0.3\^T\rHTTP_ACCEPT_ENCODINGgzip, deflate\b\^AHTTP_DNT1\^OHTTP_CONNECTIONkeep-alive\^^\^AHTTP_UPGRADE_INSECURE_REQUESTS1\0\0\0\0\0\0\^A\^D\0\^A\0\0\0\0\^A\^E\0\^A\0\0\0\0"
 62744 mapserv7 RET   read 864/0x360
```
mapserv replies
```
 62744 mapserv7 CALL  write(3,0x40173342000,0x280)
 62744 mapserv7 GIO   fd 3 wrote 640 bytes
       "\^A\^F\0\^A\^B`\0\0Content-Type: text/html\r
        \r
        <HTML>
        <HEAD><TITLE>MapServer Message</TITLE></HEAD>
        <!-- MapServer version 7.6.4 OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=FASTCGI SUPPORTS=GEOS SUPPORTS=POINT_Z_M SUPPORTS=PBF INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE -->
        <BODY BGCOLOR="#FFFFFF">
        msLoadMap(): Regular expression error. MS_DEFAULT_MAPFILE_PATTERN validation failed.
        </BODY></HTML>\^A\^F\0\^A\0\0\0\0\^A\^C\0\^A\0\b\0\0\0\0\0\0\0\0\0\0"
 62744 mapserv7 RET   write 640/0x280
```
then a shutdown/close on the socket.

the next request gets the same input, but then mapserv (process is still running) replies with less content:
```
 62744 mapserv7 GIO   fd 3 wrote 24 bytes
       "\^A\^F\0\^A\0\0\0\0\^A\^C\0\^A\0\b\0\0\0\0\0\0\0\0\0\0"
 62744 mapserv7 RET   write 24/0x18
```
to which nginx processes as "EOF" from the fcgi process
```
[error] 50209#0: *18 upstream prematurely closed FastCGI stdout while reading response header from upstream, client: xxxx, server: localhost, request: "GET /cgi-bin/mapserv7?map=bla HTTP/1.1", upstream: "fastcgi://unix:run/mapserv7.sock:
```
and returns a 502 to the client.

to me that looks that it's only the FCGI end of message content.. and the next subsequent requests will get the same reply, so technically the process is still running, just replying 'empty' content. Digging further....

**Comment by landryb** [comment]
running inside gdb, when voluntarly sending a wrong request (eg `?map=/var/ww/something` when MS_MAP_PATTERN is `^/home/landry`), at the second request `msCGILoadMap` returns NULL (as expected, since i provide it garbage) but apparently it wasnt called from `msCGIHandler` so `msCGIWriteError` isnt called.

**Comment by landryb** [comment]
digging more with egdb.. now i'm chasing a reuse of the static object returned by msGetErrorObj() where `isreported` wouldnt get reset to 0 (eg stays at 1), so that would explain why only the first failing request gets the error message, and why the subsequent ones dont per https://github.com/MapServer/MapServer/blob/main/mapservutil.c#L58

now to figure out why the static object isnt properly reset to 0.. memory corruption of some sort ?

**Comment by sdlime** [comment]
Been out on vacation the last week - need to catch up. I can confirm this FCGI behavior (first error returns but subsequent errors return a 500 (although they are logged correctly)) on my install. --Steve

**Comment by sdlime** [comment]
@landryb - how are you running a debugger against mapserv running as FastCGI?

**Comment by sdlime** [comment]
Note, even a empty call causes the issue on my install. That is, the first call to http://myserver.com/cgi-bin/mapserv.fcgi gets you the obligatory "loadParams(): Web application error. No query information to decode. QUERY_STRING is set, but empty." but the second generates a 500 error. So completely independent of mapfile processing. Hmmmm....

**Comment by landryb** [comment]
> @landryb - how are you running a debugger against mapserv running as FastCGI?

i attach to the running process with `gdb -p $process_pid /path/to/executable` then '`continue`' in gdb. Will be able to dig further in the coming days, was offline for the past 3 weeks.

**Comment by geographika** [comment]
For info - with the latest MapServer sourcecode I can't create this on Windows using FastCGI running under IIS. All calls are returning `loadParams(): Web application error. No query information to decode. QUERY_STRING is set, but empty.` as expected. 

Tamas did reapply a patch to libfcgi for the Windows builds (see [here](https://github.com/gisinternals/buildsystem/commit/6bb056af6ca75e68d252b901303887ec0a3eef87), but this was related to corrupt output rather than HTTP 500 errors so probably unrelated.

**Comment by sdlime** [comment]
Looks like the SUSE 15.3 package is version 2.4.0. Version 2.4.2 is current. I can't tell if there were changes in more recent versions that could explain this behavior.

**Comment by landryb** [comment]
> Looks like the SUSE 15.3 package is version 2.4.0. Version 2.4.2 is current. I can't tell if there were changes in more recent versions that could explain this behavior.

my tests are done with fcgi lib 2.4.0 here. @rouault did you test with apache & fcgi also used the fcgi lib ? if so which version ?

**Comment by rouault** [comment]
> my tests are done with fcgi lib 2.4.0 here.

same here (the one packaged on Ubuntu 20.04)

**Comment by jmckenna** [comment]
I'm not seeing a lot of progress on this issue, so I believe we must move on with the 8.0 beta release process.   If you have local changes ready here please give a yell as soon as possible.

**Comment by sdlime** [comment]
> gdb -p $process_pid /path/to/executable

Not having any luck with gdb... Not sure what I'm doing wrong and by no means a power user.

**Comment by geographika** [comment]
Does this issue only occur when using `spawn-fcgi`? Is this a typical way to set up MapServer?
@landryb - could you confirm this only happens with MapServer 8.0 and not 7.6.4 (it is unclear if you are having issues with both - it appears so, but they are different)?

Maybe worth a post on the mailing list to see if anyone has MapServer 8.0 running under nginx or with `spawn-fcgi`?
All seems fine on Apache and IIS with FastCGI based on comments in this thread.

**Comment by landryb** [comment]
> I'm not seeing a lot of progress on this issue, so I believe we must move on with the 8.0 beta release process. If you have local changes ready here please give a yell as soon as possible.

do what you think is right for mapserver testing & release management, but in my pov for the affected systems (we havent figured out in *which* conditions/environment the bug is present) it's a DOS - just send an empty query to the server, it will reply once with an error message, then the fcgi process is dead in the water :/

agreed, its only for a beta so maybe no widespread usage, but still bad press..

**Comment by landryb** [comment]
maybe related - i see in mserror.c that there's a distinct implementation depending on `USE_THREAD` of `msGetErrorObj` which is the method returning the 'error' object that i see being reused without resetting `reported`. On my install where the problem shows, `USE_THREAD` is undef. @sdlime @geographika @rouault what about you ?

**Comment by landryb** [comment]
Fwiw to exhibit/reproduce, here's what i'm doing:
bit of nginx config:
```
        location /cgi-bin/mapserv {
            fastcgi_pass   unix:/var/www/run/mapserv.sock;
            fastcgi_param SCRIPT_FILENAME /cgi-bin/mapserv;
            include fastcgi_params;
        }
```
start spawn-fcgi with the mapserv binary built from git:
```
sudo  spawn-fcgi -n -d /tmp -s /var/www/run/mapserv.sock -u www -- /usr/obj/ms/mapserv
```
start gdb against the running process, telling it to set a breakpoint and continue running the existing process
```
sudo gdb -ex 'b msGetErrorObj' -ex 'cont' -p $(pgrep mapserv) /usr/obj/ms/mapserv 
```
initiate a query:
```
curl 'http://localhost/cgi-bin/mapserv'
```
in gdb, the breakpoint on `msGetErrorObj` is reached and i can examine the objects.

**Comment by landryb** [comment]
i think i got it... here's my reasoning - Please correct me if i'm wrong!

When an error is triggered, the following functions call `msGetErrorObj` in this sequence:
- `msInsertErrorObj` - this one allocates an error object and initializes all its members to empty/0 values
- `msCGIWriteError` - this one returns early if `isreported` is MS_TRUE
- `msWriteErrorXML` - this one generates a proper string with the error messages, and sets `isreported` to MS_TRUE
- `msResetErrorList` - this one frees the ms_error linked list objects... **but** doesnt reset `isreported` to MS_FALSE

the next error request comes ... `isreported` is still MS_TRUE, and `msCGIWriteErrorObj` exits early, not writing the error.

This still feels wrong since `msInsertErrorObj` would have been supposed to create a new error object, properly initialized but ... with #6577 i cant reproduce the issue and can send several erroring requests in a row.

**Comment by jratike80** [comment]
We tried to run Mapserver with fcgi under nginx because we use it for other services including Mapcache. I do not remember exactly what problems we had. We did not investigate them much because we just changed to Apache and all was good.
But if Mapserver generally runs on nginx as fastcgi it would be interesting to see some numbers about performance of nginx vs. Apache.

**Comment by landryb** [comment]
Ah, `msInsertErrorObj` creates a new error object *only* if the 'first' element in the linked list already contains an error, otherwise it reuses the static one - in which `isreported` wasnt reset to MS_FALSE.

So i think my reasoning is right, #6577 fixes it and the bug is genuine - it just didn't show up before #6180 because `msSetError` was less called in the fastcgi codepaths, cf https://github.com/MapServer/MapServer/commit/0db046cafcb9fce757e1fc652cdd467dfd9b5c28#diff-3aae315900ca0d05b5f92495b85119ee693081f0ee75367d317a53dedc322fc6 ?

But more hindsight from people used to dive in this code is definitely welcome !!

Why this doesn't show up with IIS or Apache/FastCGI is a mystery to me though. Luck ?

@jratike80 fwiw at work i run all my mapserver services behind nginx, mapserver workers being handled/started by supervisord, and it works great - supervisord takes care of restarts upon segfaults, and killing workers that leak too much memory when using ecw/jp2 libs.

I use spawn-fcgi only when i need to quickly setup a mapserver fcgi for testing because it's easy to setup and lightweight, but doesn't handle restarts when it crashes, so not that good for production instances.

Havent really used apache since 2004 or so...

**Comment by geographika** [comment]
> maybe related - i see in mserror.c that there's a distinct implementation depending on `USE_THREAD` of `msGetErrorObj` which is the method returning the 'error' object that i see being reused without resetting `reported`. On my install where the problem shows, `USE_THREAD` is undef. @sdlime @geographika @rouault what about you ?

Using `-DWITH_THREAD_SAFETY=1` and `SUPPORTS=THREADS`. 

In IIS multiple instances of mapserver.exe are spun up when using FastCGI so maybe a new one starts up to handle requests and crashed instances so that may explain why it works in this case.

**Comment by sdlime** [comment]
FWIW I'm running on SUSE 15.x w/Apache (apache2-mod_fcgid package) and am seeing this behavior. Thread-safety support is disabled. I've never run FastCGI before - performance of the plain CGI has been good enough.

**Comment by geographika** [comment]
@sdlime - so should it be possible to test this by adding some failing requests to #6294 (which checks Apache/FastCGI, but not for requests that cause errors)?
