### ISSUE TITLE
flatgeobuf: suspicious recursion in flatgeobuf_decode_feature()

### ISSUE THREAD

**Issue by rouault** [MapServer/MapServer#6561]
CC @bjornharrtell 

flatgeobuf_decode_feature() at line 113 calls itself. This might potentially lead to too large stack depth, and furthermore the call at line 113 doesn't check the return value. It would be more prudent to rewrite this as a while() loop.

**Comment by bjornharrtell** [comment]
Hmm I was sure I made that behavior (i.e skip to next if null geometry) out of how the shapefile works, but now I can't seem to find that kind of code in mapshape.c.

**Comment by bjornharrtell** [comment]
Found the similar mapserv.c shape logic - https://github.com/MapServer/MapServer/blob/e1da7b0b84d7f2f7ab9ad5ec85a2cb189f573c7c/mapshape.c#L2806.
