### ISSUE TITLE
createLegendIcon Bug in Swig Version 4.0.2

### ISSUE THREAD

**Issue by bendwr** [MapServer/MapServer#6582]
## Expected behavior and actual behavior.

For example : I expected the following request to work 

    if($tmpLay){
		$tmpclass = $tmpLay->getClass($HTTP_VARS['cls']);
		if($tmpclass){
			if(is_numeric($HTTP_VARS['sz']) && is_numeric($HTTP_VARS['sz'])){
				error_log(print_r($tmpLay));
				# modified createLegendIcon due to change from 2 arguments to 4
				**$tmpImg = $tmpclass->createLegendIcon($HTTP_VARS['lay'], $tmpLay, $lw, $lw);**

and it returns an error message instead (paste error).

      **PHP Fatal error:  Type error in argument 2 of classObj_createLegendIcon. Expected 
      SWIGTYPE_p_mapObj in /usr/local/lib/php/pecl/20190902/mapscript.php on line 1527, referer: http://localhost/**

## Steps to reproduce the problem.

For example:  This is the Mapscript 7.6.4 class method of creating a legend icon with 2 arguments passed
				         	$tmpImg = $tmpclass->createLegendIcon($lw,$lw);

when you add the 2 new ones from swig, a map object and a layer object, it does not recognize the layer object as a layer object.

## Operating system

For example: macOS Big Sur Version 11.6.7 | Processor: 3.43 GHz | Memory: 16 GB DRAM

## MapServer version and installation method

For example: the 7.6.4 version with Swig version 4.0.2 (Migrating Mapserver WebServer from Mapscript to SWIG).

**Comment by bendwr** [comment]
Fixed bug by requiring is_null check for the size values of height and width for arguments 3 and 4.

**Comment by jmckenna** [comment]
@bendwr I've added a PHPUnit test for createLegendIcon through https://github.com/MapServer/MapServer/pull/6590 Please feel free to edit or contribute more tests (follow the [README  ](https://github.com/MapServer/MapServer/blob/main/msautotest/php/README.md)), thanks!
