### ISSUE TITLE
SWIG 8.0.0.-beta2 breaks Scalebar

### ISSUE THREAD

**Issue by bendwr** [MapServer/MapServer#6604]
## Expected behavior and actual behavior.

For example: Previous version using MapScript PHP displays the scalebar in the bottom utility panel. After SWIG migration, the scalebar displays but within the bounds of the map instead of in the previous position. Changing the offset to have a negative Y value to bring it down in the browser does "move" it but then it is hidden below the utility panel. Can't find any documentation in the API to fix this.

## Steps to reproduce the problem.

For example:  Here is how it is set in the .map file:

```
#********************
# Start of scalebar *
#********************
  SCALEBAR
    ALIGN LEFT
    IMAGECOLOR 255 255 255
    LABEL
        FONT helvetica
        TYPE TRUETYPE
        SIZE 8
        COLOR 0 0 0
    END
    STYLE 1
    SIZE 100 2
    COLOR 0 0 0
    UNITS MILES
    INTERVALS 1
    TRANSPARENT ON
    POSITION LL
    OFFSET 0 0
    STATUS EMBED
  END
```
## Operating system

For example: macOS Big Sur Version 11.6.7

## MapServer version and installation method

For example: 8.0.0.-beta2

**Comment by jmckenna** [comment]
It's not clear to me if you are reporting an issue with PHP SWIG MapScript, or just for the scalebar mapfile object. In either case, please include a sample archive here to execute (either .zip, .gz, with mapfile, data, and commands.txt with steps to reproduce).  Thanks.
