### ISSUE TITLE
Accessing FlatGeoBuf (.fgb) from S3 in .map file?

### ISSUE THREAD

**Issue by PostholerCom** [MapServer/MapServer#6605]
Using mapserver 7.6 or 8rc1 I've been unable to serve .fgb from an S3 bucket. Local disk works fine as does ogrinfo on S3 .fgb. COG raster data works fine off S3. Key/pw is set.

COG & .fgb are excellent ways to store/retrieve data from cloud storage. It's highly desirable to access .fgb from S3 within a .map file.

Map file configs:

v8rc1:
CONNECTIONTYPE flatgeobuf
DATA "/vsis3/bucket/path/data.fgb"

v7.6.4
CONNECTIONTYPE OGR
CONNECTION "/vsis3/bucket/path/data.fgb"
DATA "rm_trace"

v8rc ms_error log:
[Fri Aug 26 10:24:13 2022].854479 msDrawMap(): Image handling error. Failed to draw layer named 'rm_trace'.

v7.6.4 ms_error log
[Fri Aug 26 10:06:59 2022].388096 msOGRFileOpen(): OGR error. Open failed for OGR connection in layer `rm_trace'.  File not found or unsupported format. Check server logs.
[Fri Aug 26 10:06:59 2022].388132 Open failed for OGR connection in layer `rm_trace'.

**Comment by sdlime** [comment]
@PostholerCom, I thought here was some discussion on the mailing lists on this topic. Is this really a development issue at this point or can this be closed. Seems like more of an OGR issue anyway. --Steve

**Comment by rouault** [comment]
Probably a configuration issue from the user regarding adding the S3 credentials to mapserver configuration.

**Comment by PostholerCom** [comment]
Credentials are fine, they work for all other /vsi* raster urls. Has anyone tested .fgb to work from  S3?

I don't know if this a bug or it is intentional by design. I'd be curious if it works for anyone else, and if so I'd like to see their config.

Thanks guys!

**Comment by geographika** [comment]
@PostholerCom - both the native FlatGeoBuf and OGR drivers are working for me in MapServer 8.0:

```
MAP
    NAME "FlatGeoBuf"
    EXTENT -108.34897017301287 31.444473477833878 -94.22050060607745 43.29701803084875 
    PROJECTION
        "init=epsg:26915"
    END
    CONFIG "AWS_ACCESS_KEY_ID" "XXXX"
    CONFIG "AWS_SECRET_ACCESS_KEY" "XXXX"
    CONFIG "AWS_S3_ENDPOINT" "XXXX"
    
    LAYER
        NAME "UScounties"
        TYPE POLYGON
        STATUS ON
        
        # OGR driver
        #CONNECTIONTYPE OGR # data from https://github.com/flatgeobuf/flatgeobuf/tree/master/test/data
        #CONNECTION "/vsis3/mapserverstudio/data/UScounties.fgb"
        
        # native driver
        CONNECTIONTYPE flatgeobuf
        DATA "/vsis3/mapserverstudio/data/UScounties.fgb"
        PROJECTION
            "init=epsg:26915"
        END
        CLASS
            STYLE
                OUTLINECOLOR 0 0 0
                OUTLINEWIDTH 0.7
            END
        END
    END
END
```

**Comment by PostholerCom** [comment]
Thanks @geographika!

I cut and paste your above .map file and changed relevant values. Everything works fine. 

The problem was I failed to add ".fgb" to config CPL_VSIL_CURL_ALLOWED_EXTENSIONS

Dumb, dumb mistake. Apologies for misleading everyone. Thanks for all you folks do!

**Comment by jmckenna** [comment]
@PostholerCom great.  For your next question, as mentioned before, please do take your question straight to the `mapserver-dev` forum (not through a ticket).  Thanks.

**Comment by PostholerCom** [comment]
@jmckenna I did and didn't get a response. So I dropped it here. Thanks!
