### ISSUE TITLE
error message when no config file is found leads to 404

### ISSUE THREAD

**Issue by landryb** [MapServer/MapServer#6624]
if there's zero configuration file/env var, https://github.com/MapServer/MapServer/blob/main/mapserv-config.cpp#L146 points to https://mapserver.org/config_file.html which is a 404 right now.

either there should be a redirect on the servers, or it should point to https://mapserver.org/mapfile/config.html ?

**Comment by jmckenna** [comment]
@landryb thanks for catching this, I'll make that change now in a PR (your second option)

**Comment by bendwr** [comment]
Currently in the process of migrating to MapServer-8.0.0. Noticed in the mapscript.php that the mapObj constructor now has a $config variable for an argument: 

```
	    function __construct($filename="",$config=null) {
	    	    if (is_resource($filename) && get_resource_type($filename) === '_p_mapObj') {
			    $this->_cPtr=$filename;
			    return;
		    }
		    $this->_cPtr=new_mapObj($filename,$config);
	     }
```
	
Is this supposed to be a reference to the mapserver.conf file? I tried adding that in as a constant but getting the error:

           `PHP Fatal error:  Type error in argument 2 of new_mapObj. Expected SWIGTYPE_p_configObj in /usr/local/lib/php/pecl/20190902/mapscript.php on line 2562`

**Comment by sdlime** [comment]
@bendwr, it's a reference to a configObj created from a config file. It's optional and shouldn't be needed unless the map file is being used for both MapScript and CGI purposes, and uses plugins. Workflow would be (in Perl):

```
  my $config = new mapscript::configObj('my_config_file.conf') or die 'Unable to load config file.';
  my $map = new mapscript::mapObj('my_map_file.map', $config) or die 'Unable to load map file.';
```

Does that help? I hope the migration is going well.

--Steve

**Comment by jmckenna** [comment]
I think we're off-topic from this ticket now.

@bendwr for the record, for MapServer 8.0.0 you should be using SWIG-master (or the upcoming SWIG 4.1.0, see my call for help at https://lists.osgeo.org/pipermail/mapserver-dev/2022-September/016881.html ), which no longer generates/requires that external 'mapscript.php' file.

@bendwr for further discussion on the migration steps, please do ask for help on the `mapserver-dev` list and we can help there directly.
