### ISSUE TITLE
Projection invalid_argument at memory location

### ISSUE THREAD

**Issue by geographika** [MapServer/MapServer#6630]
While debugging #6628 exceptions were thrown at the following line:

https://github.com/MapServer/MapServer/blob/2fcc5b6c690b532be512738690625f68bdb9e7cf/mapproject.c#L923

Error: `Exception thrown at 0x00007FFF042A4FD9 in python.exe: Microsoft C++ exception: std::invalid_argument at memory location 0x00000059941ED3E0.`

See https://proj.org/development/reference/functions.html#c.proj_create_argv for function details. 

The args were the default projection ["proj=latlong", "ellps=WGS84"]

I'm not sure why the `p->numargs + 1` adds one to the index as `numargs` in this case is already 2. Removing the `+1` fixed the exception. I can add as a pull request, but unsure if this is the correct behaviour.

**Comment by rouault** [comment]
> I'm not sure why the `p->numargs + 1` adds one to the index as `numargs` in this case is already 2

because we allocate args to be p->numargs + 1 large at https://github.com/MapServer/MapServer/blob/2fcc5b6c690b532be512738690625f68bdb9e7cf/mapproject.c#L900, and set args[p->numargs] = (char*) "type=crs"; at line https://github.com/MapServer/MapServer/blob/2fcc5b6c690b532be512738690625f68bdb9e7cf/mapproject.c#L917

This code is correct as far as I can see.

**Comment by geographika** [comment]
Thanks @rouault. This is running through Python MapScript - I'll see if I can recreate using `mapserv`. 
I don't have proj debug symbols setup, so the exception could be anywhere in `proj_create_argv`. 

![image](https://user-images.githubusercontent.com/490840/192114758-22bf6ddb-4cd7-4b09-8682-bc75f72fd7bb.png)

**Comment by geographika** [comment]
A few further details - this can be recreated using any mapfile and `map2img` e.g. 

`map2img -m /mapserver/msautotest/misc/ogrbrush.map`

OS in Windows and using Proj 7.2 (`proj_7_2.dll`)

When debugging, after running the following:

https://github.com/MapServer/MapServer/blob/2fcc5b6c690b532be512738690625f68bdb9e7cf/mapproject.c#L917

Checking the value of `args[2]` always shows as NULL (`p->numargs` is 2). I've tried various combinations of `msStrdup`, `strcpy` with no luck.

**Comment by rouault** [comment]
> Checking the value of `args[2]` always shows as NULL

extremely weird! Would there be some crazy compiler optimization assuming that the cast from const char* to char* is illegal, and setting NULL instead ... ?
What if you replace this line with:
```
char szTypeCRS[] = "type=crs";
args[p->numargs] = szTypeCRS;
```

**Comment by geographika** [comment]
> assuming that the cast from const char* to char* is illegal

This seems to be the case - or at least when trying to set when debugging:

```
args[2] = (char*) "type=crs"
String literals are not supported in this context.
```

No luck with the above syntax change - this is the first tests/builds I;ve done with VS2022 so maybe something has got stricter. 

![image](https://user-images.githubusercontent.com/490840/192122099-0b8f50c7-a1ef-45b0-b77e-f10ffc8e7f5c.png)

**Comment by geographika** [comment]
An update on this - the issue occurs when the following arguments are passed to [proj_create_argv](https://proj.org/development/reference/functions.html#c.proj_create_argv)

`proj=latlong ellps=WGS84 type=crs`

The first 2 are created here:

https://github.com/MapServer/MapServer/blob/58512a6d624f2c4e10350231b70ed0b9058f3930/mapfile.c#L5694-L5698

Then the third is added in `msProcessProjection`. 

If I change the default projection to the following, it works fine:

```
  map->latlon.numargs = 1;
  map->latlon.args[0] = msStrdup("init=epsg:3857");
  //map->latlon.args[1] = msStrdup("ellps=WGS84"); /* probably want a different ellipsoid */
```
So are the current default projection parameters (`proj=latlong ellps=WGS84 type=crs`) now invalid in Proj7+?

**Comment by jratike80** [comment]
Proj 8.2.1 did not complain when I tried this transformation

```
projinfo -s "+proj=latlong ellps=WGS84 type=crs" -t epsg:4326
Candidate operations found: 1
-------------------------------------
Operation No. 1:

unknown id, Ballpark geographic offset from unknown to WGS 84, unknown accuracy, World, has ballpark transformation

PROJ string:
+proj=axisswap +order=2,1
```

Proj string for EPSG:4326 is `+proj=longlat +datum=WGS84 +no_defs +type=crs`. Could it be a better default?

**Comment by geographika** [comment]
Thanks, @jratike80. Testing the same command on PROJ 7.2 also works fine. 

With that in mind, I built debug versions of PROJ 7.2 and stepped through in the debugger. It turns out Visual Studio doesn't seem to distinguish between stopping on an exception and stopping on a handled exception..

The exception was thrown by PROJ and displayed as an error, but it is handled internally in PROJ so not an issue. 

For reference, it is thrown [here](https://github.com/OSGeo/PROJ/blob/8af84f9d770fd8e64991c1968acfa5ca83204f33/src/iso19111/internal.cpp#L280), as `iss` is an empty string

```C++
  if (!iss.eof() || iss.fail()) {
      throw std::invalid_argument("non double value");
  }
```

Call stack:

```
proj_7_2.dll!osgeo::proj::internal::c_locale_stod(s) Line 280	C++
proj_7_2.dll!osgeo::proj::io::getNumericValue(paramValue, pHasError=0x0000000000000000) Line 9072	C++
proj_7_2.dll!osgeo::proj::io::PROJStringParser::Private::buildGeographicCRS(iStep, iUnitConvert=-1, iAxisSwap=-1, ignorePROJAxis=false) Line 9105	C++
proj_7_2.dll!osgeo::proj::io::PROJStringParser::createFromPROJString(projString={...}) Line 10176	C++
proj_7_2.dll!osgeo::proj::io::createFromUserInput(text={...}, dbContext={...}, usePROJ4InitRules=false, ctx=0x0000023a75609a00) Line 6183	C++
proj_7_2.dll!osgeo::proj::io::createFromUserInput(text={...}, ctx=0x0000023a75609a00) Line 6660	C++
proj_7_2.dll!proj_create(ctx=0x0000023a75609a00, text=0x0000023a755f93e0) Line 470	C++
proj_7_2.dll!proj_create_argv(ctx=0x0000023a75609a00, argc, argv) Line 837	C++
mapserver.dll!msProcessProjection(p=0x0000023a75607788) Line 924	C
mapserver.dll!initMap(map=0x0000023a75606260) Line 5698	C
mapserver.dll!msLoadMap(filename=0x0000023a755d0030, new_mappath=0x0000000000000000, config=0x0000023a755e3b40) Line 6324	C
mapserver.dll!msCGILoadMap(mapserv=0x0000023a75605990, config=0x0000023a755e3b40) Line 221	C
mapserv.exe!main(argc, argv=0x0000023a755c8210) Line 264	C
```
