### ISSUE TITLE
Encoding of shapefile breaks OGCAPI: Features (both HTML and JSON response)

### ISSUE THREAD

**Issue by jmckenna** [MapServer/MapServer#6631]
(this was very difficult to isolate, but I did, took me over a week ha, to isolate this to one single record, with 3 attributes only: `name`, `id`, and `name_hu` where name_hu is `Tanzánia`)

_Declaration: this could be just for my documentation job for mapserver.org, ha, instead of an "issue" here, but, at least by reporting this here other readers will be warned before they hit this wall, which will likely save them a week of effort._

### Description
- testing with `main` branch, on Windows
- this same record works great inside a database (PostgreSQL, SpatiaLite) and served through OGCAPI: Features
- this same record works great served through OGC: WFS (as a Shapefile, PostgreSQL, SpatiaLite)
- however in testing these past few weeks, using the same dataset but in ESRI Shapefile format, breaks the OGCAPI: Features response

### Symptom 1
- request: `ogcapi/collections/countries/items?f=html`
- response: `{"code":"ServerError","description":"General template handling error."}`
  - yes the response is in JSON even though the request is for HTML

### Symptom 2
- request: `/ogcapi/collections/countries/items?f=json`
- response: blank (literally no response, as shown in browser Developer Tools)

### Solution attempt # 100
- change encoding in the templates (header.html, openapi.html) from `<meta charset="utf-8" />` to `<meta charset="ISO-8859-1" />`
- result: no change, same errors

### Solution attempt # 101
- in the mapfile LAYER section, add `ENCODING "ISO-8859-1"`
- result: fixes both the JSON and HTML item response

Are you interested in trying this locally? Here is that single record shapefile (it is only 2KB in size, as it is one polygon feature with 1 record) : https://gatewaygeomatics.com/dl/ogcapi-features-shp.zip

(I also realize that I just spent a week on creating what could be the perfect new shapefile for a new msautotest, ha, yikes)

**Comment by sdlime** [comment]
The first symptom is expected since all fundamental errors are returned as JSON. The second symptom should be trapped somehow.

**Comment by sdlime** [comment]
@jmckenna, by chance is there anything in the Apache or MapServer logs with call 2?

**Comment by geographika** [comment]
@sdlime - related to the OGCAPI and debugging - would it make sense to add in "standard" MS error logging to the `outputError` function?

https://github.com/MapServer/MapServer/blob/2fcc5b6c690b532be512738690625f68bdb9e7cf/mapogcapi.cpp#L87

Something along the lines of: `msSetError(MS_OGCAPIERR, description, "outputError()");` - or alternatively add a log statement to each of the functions where `outputError` is called?

I had some other errors using the OGC API services, and the errors were swallowed up by the proxy server with no signs of anything wrong in the MapServer logs, even with `DEBUG 5`.

**Comment by sdlime** [comment]
What about instead calling msDebug() in outputError()?

**Comment by geographika** [comment]
> What about instead calling msDebug() in outputError()?

Sorry - yes that was what I was thinking of - so that the same errors is logged in the MS Error file. At least if Debug level is 5.

**Comment by sdlime** [comment]
@jmckenna, do you have the associated mapfile for the service you were testing?

**Comment by sdlime** [comment]
@jmckenna, I can recreate partially:

- _ogcapi/collections/countries/items?f=html_ renders ok albeit with the odd character in name_hu
- _ogcapi/collections/countries/items?f=json_ renders as blank

Odd because JSON is fed to the template...

**Comment by sdlime** [comment]
From the nlohman docs...

_Note the library only supports UTF-8. When you store strings with different encodings in the library, calling [dump()](https://json.nlohmann.me/api/basic_json/dump/) may throw an exception unless json::error_handler_t::replace or json::error_handler_t::ignore are used as error handlers._

I'm not sure what the best fix is. We really only use the dump method once where this is an issue, when outputting the JSON. The default handler is json::error_handler_t::strict and we're not catching the exception - hence the blank response. So, we could:

- use either of the two referenced error handlers (but which one) OR
- leave as strict, catch the exception and throw an error about non-UTF8 encoding

Inja is handed the json object and throwing it's own exception (sometimes) that we report as a "General template handling error".

It doesn't look easy to get consistent behavior between both JSON and templated output. I think we'd something to validate the json object content is valid after it's built and before trying to output/render. Either that or check the encoding for every assignment.

@jmckenna, @geographika or @rouault - any thoughts?

**Comment by geographika** [comment]
@sdlime I'd be in favour of https://json.nlohmann.me/api/basic_json/error_handler_t/ which looks like it should replace these characters with � - better than no output. 

I presume as each layer can have its own encoding it would be very hard to convert all data to UTF before populating the template?

It would be good to also add a `msDebug()` call into `outputError()` so admins are aware if clients are getting errors.

**Comment by rouault** [comment]
> I presume as each layer can have its own encoding it would be very hard to convert all data to UTF before populating the template?

Well, since RFC https://mapserver.org/development/rfc/ms-rfc-103.html, Mapfile authors are strongly encouraged to properly define the layer encoding so that other parts of Mapserver only sees UTF-8.
My own inclination would be to catch the exception and emits an error suggesting to set ENCODING.
We may use a json::error_handler_t::replace strategy if we want to be more lenient, but that should be done only as a fallback when the exception is caught, and with a log message pointing that there's a missing/erroneous layer ENCODING.

**Comment by geographika** [comment]
Fixed with #6817
