### ISSUE TITLE
GetFeature PropertyIsLike doesn't allow filtering on parentheses

### ISSUE THREAD

**Issue by kad-dirc** [MapServer/MapServer#6751]
## Expected behavior and actual behavior

We have a GetFeature wfs request and want to filter on a string which contains parentheses, e.g. `Pand in gebruik (niet ingemeten)`.
Using the PropertyIsLike filter we expect to filter this feature with `*(niet ingemeten)`. 
But it fails to find the feature. 

PropertyIsLike snippet:
```xml
<PropertyIsLike escapeChar="[" singleChar="." wildCard="*" matchCase="true">
    <ValueReference>status</ValueReference>
    <Literal>* (niet ingemeten)</Literal>
</PropertyIsLike>
```

With debug log enabled we see that Mapserver converts the request to an sql stamenent and escapes these parentheses, e.g.
`... FROM "pand" WHERE ("pand"."status" GLOB '*\(niet ingemeten\)')`

Hence it doesn't find anything.

This makes it impossible to filter on strings containing parentheses. I would consider this as a bug, since the escaped parentheses in the sql doesn't seem to be of any use to me. 
Or am I wrong?

## Steps to reproduce

See zip file for a simple gpkg and mapfile config.

```shell
# Start a mapserver
docker run --rm -v `pwd`:/srv/data -e MS_MAPFILE=/srv/data/config/mapfile/service.map -p 8080:80 --name mapserver pdok/mapserver

# GetFeature request which fails (but should succeed)
curl --location --request POST 'localhost:8080/lv/bag/wfs/v2_0' \
--header 'Content-Type: application/xml' \
--data-raw '<GetFeature xmlns="http://www.opengis.net/wfs/2.0" service="WFS" version="2.0.0" outputFormat="application/json" startIndex="0" count="1000"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd">
    <Query typeNames="bag:pand" srsName="EPSG:28992">
        <Filter xmlns="http://www.opengis.net/fes/2.0">
            <PropertyIsLike escapeChar="[" singleChar="." wildCard="*" matchCase="true">
                <ValueReference>status</ValueReference>
                <Literal>* (niet ingemeten)</Literal>
            </PropertyIsLike>
        </Filter>
    </Query>
</GetFeature>'
# Corresponding SQL snippet (from mapserver debug log)
# ... FROM "pand" WHERE (("pand"."status" GLOB '* \(niet ingemeten\)'))

```

## System
[reproduce-issue.zip](https://github.com/MapServer/MapServer/files/9959603/reproduce-issue.zip)

- os: Debian buster
- mapserver verison: 7.6.4
- gdal version: libgdal20 2.4.0+dfsg-1+b1

**Comment by sdlime** [comment]
What DB backend are you using?

**Comment by kad-dirc** [comment]
The SQL query is executed on a geopackage, so the DB backend is SQLite.

**Comment by sdlime** [comment]
So, this is running through OGR - @dmorissette or @rouault, any thoughts?

**Comment by rouault** [comment]
It looks like the GLOB comes from 3cf682d17003521213868f1e727d7be7a3263c7e , but it is not ready for the escaping of PropertyIsLike that is done to transform PropertyIsLike as a regular expression in FLTGetIsLikeComparisonCommonExpression(). The code in mapogr.cpp should basically undo most of the escaping of the regular expression done by FLTGetIsLikeComparisonCommonExpression() to create a valid GLOB...

**Comment by rouault** [comment]
working on the fix

**Comment by jmckenna** [comment]
we should make sure to include an msautotest for this (so we don't face this again later).
