### ISSUE TITLE
Compiling mapserver 8.0.0 error libmapserver.so.8.0.0: undefined reference to `msWFSIsLayerSupported'

### ISSUE THREAD

**Issue by phlaluna** [MapServer/MapServer#6752]
Hi

We currently use the mapserver version 7.6.4 and we are not having any problems with the compilation, but on the mapserver 8.0.0 it is returns an error.

I cloned the project and ran the command below:
```
cmake ../ \
                -DWITH_KML=OFF \
                -DWITH_SOS=OFF \
                -DWITH_WMS=ON \
                -DWITH_FRIBIDI=ON \
                -DWITH_HARFBUZZ=ON \
                -DWITH_ICONV=ON \
                -DWITH_CAIRO=ON \
                -DWITH_SVGCAIRO=OFF \
                -DWITH_RSVG=OFF \
                -DWITH_MYSQL=OFF \
                -DWITH_FCGI=ON \
                -DWITH_GEOS=ON \
                -DWITH_CURL=OFF \
                -DWITH_CLIENT_WMS=OFF \
                -DWITH_WCS=OFF \
                -DWITH_CLIENT_WFS=OFF \
                -DWITH_WFS=OFF \
                -DWITH_LIBXML2=ON \
                -DWITH_THREAD_SAFETY=OFF \
                -DWITH_GIF=ON \
                -DWITH_PYTHON=OFF \
                -DWITH_PHP=OFF \
                -DWITH_PERL=OFF \
                -DWITH_RUBY=OFF \
                -DWITH_JAVA=OFF \
                -DWITH_CSHARP=OFF \
                -DWITH_ORACLESPATIAL=OFF \
                -DWITH_ORACLE_PLUGIN=OFF \
                -DWITH_MSSQL2008=OFF \
                -DWITH_EXEMPI=ON \
                -DWITH_XMLMAPFILE=ON \
                -DWITH_V8=OFF \
                -DBUILD_STATIC=OFF \
                -DLINK_STATIC_LIBMAPSERVER=OFF \
                -DWITH_APACHE_MODULE=OFF \
                -DWITH_GENERIC_NINT=OFF \
                -DCMAKE_PREFIX_PATH=/opt/gdal \
                -DUSE_PROJ=1 \
                -DWITH_PROTOBUFC=0 && \
                make && make install 
```
In version 7.6.4, although it has a warn (/usr/local/src/mapserver/textlayout.c:332:5: warning: 'hb_font_funcs_set_glyph_func' is deprecated), everything works.

In version 8.0.0, several warnings and ends with an error.

## Attach the build log
[build-mapserver-7.log](https://github.com/MapServer/MapServer/files/9974990/build-mapserver-7.log)
[build-mapserver-8.log](https://github.com/MapServer/MapServer/files/9974991/build-mapserver-8.log)

## Operating system
Is a Docker image debian:stretch

## MapServer version and installation method
The 8.0.0 version from compiling source

**Comment by geographika** [comment]
I'm guessing this is due to the use of `msWFSIsLayerSupported` in the new `mapogcapi.cpp`: https://github.com/MapServer/MapServer/blob/bdde4d58222f765c6fe9f7a5402e172d23d91284/mapogcapi.cpp#L113

Other uses are wrapped in `#if defined(USE_WFS_SVR)`. 

Can a layer be a WFS without being `msIsLayerQueryable`? If so, maybe that check is redundant?

**Comment by djhoese** [comment]
I'm running into this too. I was trying to reduce the size of a Dockerfile of mine that runs mapserver and I only needed WMS functionality so I removed the libxml2 dependency and added:

```
-DWITH_WCS=OFF -DWITH_WFS=OFF -DWITH_LIBXML2=0
```

to my cmake call and compilation failed with a lot of `msWFSIsLayerSupported` errors.

**Comment by djhoese** [comment]
Oh I should have said, I'm trying to compile 8.2.0.

**Comment by jmckenna** [comment]
Thanks @phlaluna & @djhoese, I confirm the issue here.

@sdlime is this just a documentation issue?  (eg. requires both `-DWITH_WFS=1` and `-DWITH_OGCAPI=1` ?  Let me know and I will add that to the docs, thanks.

**Comment by djhoese** [comment]
Ok so if you turn off WFS then OGCAPI should also be turned off and not built, right? I know very little about cmake, but I would have assumed that that kind of dependency would be handled by cmake. If I say "Don't build WFS support, but do build OGCAPI support" and that isn't possible then I should get a human-readable error, right?

**Comment by rouault** [comment]
Turns out the dependency from OGCAPI Features to WFS is really on this small helper function ``msWFSIsLayerSupported``. Fixed per https://github.com/MapServer/MapServer/pull/7113
