### ISSUE TITLE
Changing map file parameters via a form or a URL stoped working in version 8

### ISSUE THREAD

**Issue by bozhidarc** [MapServer/MapServer#6770]
## Expected behavior and actual behavior.

In the request bellow I'm passing some custom parameters and some styling parameters to the map server.
After some testing I'm sure that the custom parameters (such as `secondRange_1`) worked fine, the problem is with the ones which changes class style color. They just don't work.
This happened after I tried the MS version 8.

```
http://localhost:5001/cgi-bin/mapserv?SERVICE=WMS
&VERSION=1.1.1
&REQUEST=GetMap
&FORMAT=image/png
&TRANSPARENT=true
&MAP=/home/appuser/qnap_storage/storage_bg/storage/maps/wms.map
&access_token=
&map.layer[vra].class[0].style[0]=color+248+241+249
&firstRange_1=0
&secondRange_1=25
&map.layer[vra].class[1].style[0]=color+211+162+218
&firstRange_2=25
&secondRange_2=58
&map.layer[vra].class[2].style[0]=color+189+92+187
&firstRange_3=58
&secondRange_3=90
&map.layer[vra].class[3].style[0]=color+145+36+153
&firstRange_4=90
&secondRange_4=104
&map.layer[vra].class[4].style[0]=color+115+0+115
&firstRange_5=104
&secondRange_5=10000
&LAYERS=vra
&WIDTH=256
&HEIGHT=256
&SRS=EPSG:3857
&STYLES=
&BBOX=2816601.72495,5374646.07126,2816986.00826,5375087.18278
```

## Steps to reproduce the problem.
The returned image should be in this color `248 241 249`

```
mapserv -nh QUERY_STRING='http://localhost/cgi-bin/mapserv?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&MAP=/home/appuser/wms.map&access_token=&map.layer[vra].class[0].style[0]=COLOR 248 241 249&firstRange_1=0&secondRange_1=25&map.layer[vra].class[1].style[0]=COLOR 211 162 218&firstRange_2=25&secondRange_2=58&map.layer[vra].class[2].style[0]=COLOR 189 92 187&firstRange_3=58&secondRange_3=90&map.layer[vra].class[3].style[0]=COLOR 145 36 153&firstRange_4=90&secondRange_4=104&map.layer[vra].class[4].style[0]=COLOR 115 0 115&firstRange_5=104&secondRange_5=10000&LAYERS=vra&WIDTH=256&HEIGHT=256&SRS=EPSG:3857&STYLES=&BBOX=2816601.72495,5374646.07126,2816986.00826,5375087.18278'
```

## Attach simple test case (drag/drop it here)
[example.zip](https://github.com/MapServer/MapServer/files/10077732/example.zip)

## Operating system

MacOS 13.0.1

## MapServer version and installation method

MapServer version 8.0.0 from `camptocamp/mapserver:latest-arm64` docker hub image

**Comment by sdlime** [comment]
That functionality was actually dropped as part of 8.0. It's poorly documented, overly complicates the code and efforts to build finer access control just made things worse.  A quick survey on mapserver-users this summer showed little/no community use.

Anyway, looking at your example one workaround might be to use SLD to define the colors at runtime. There might be other options (includes, class groups) depending on how arbitrary your setup is.

--Steve

**Comment by bozhidarc** [comment]
Thank you for the answer. 
I'm already exploring some other options.
Maybe the documentation can be updated, instead of "Using MapServer version `<=` 8" to be "Using MapServer version `<` 8" :)
https://mapserver.org/cgi/controls.html#using-mapserver-version-8

**Comment by sdlime** [comment]
Good point on the docs. I added that change to an outstanding pull request I have to that page.

I'll be interested in where you land (assuming it's still using MapServer).

**Comment by bozhidarc** [comment]
In the company I work for we are big fans of MS, we are using it from almost 10 years and we don't plans to move from it :)
For the moment we downgrade to 7.6, but we reanalysed the situation for this feature and decided to make it as vector. 
Because basically we are running classification on the generated tiff with predefined classes, so we are planning to move this to separate Python script and polygonize it.
