### ISSUE TITLE
Tutorial broken and can use some more guidance for new 8.0 version?

### ISSUE THREAD

**Issue by jklymak** [MapServer/MapServer#6771]
## Expected behavior and actual behavior.

Tutorial examples no longer have what I assume are meant to be maps in them: 
https://mapserver.org/tutorial/example1-3.html#example1-3

Similarly, I am a completely new user, but the instructions for where to put the tutorial data and how to access from cgi are maybe outdated wrt to `mapserver.conf`?  

I ended up installing the data in `/usr/local/opt/mapserver/ms4w/` and then editing `mapserver.conf` to have 
```
  MAPS
    TEST_MAPFILE "/usr/local/opt/mapserver/test/test.map"
    TUTORIAL11 "/usr/local/opt/mapserver/ms4w/apps/tutorial/htdocs/example1-1.map"
  END
```

which seems to work OK.  I can also whitelist that directory and use full paths to access the examples.

**Comment by jmckenna** [comment]
thanks for reporting this @jklymak    Would you mind filing this in the documentation repository?  https://github.com/MapServer/MapServer-documentation  thanks.

**Comment by jmckenna** [comment]
thanks @rouault I was not aware of that, perfect, will-do now.  thanks.
