### ISSUE TITLE
MSSQL Driver Displays Password on failed connections

### ISSUE THREAD

**Issue by geographika** [MapServer/MapServer#6772]
Currently, the MSSQL driver hides the `password` parameter from a MSSQL connection string: See https://github.com/MapServer/MapServer/blob/1a45e6074b71738e576563ac39f60fd96ded50eb/mapmssql2008.c#L997

`Couldnt make connection to MS SQL Server 2008 with connect string 'DRIVER={ODBC Driver 17 for SQL Server};SERVER=MyServer;DATABASE=PMS;uid=myuid;password=********;'`

However, if `pwd` is used in the connection string (which is a valid alias for `password`) then it is shown to the client if a connection fails:

`Couldnt make connection to MS SQL Server 2008 with connect string 'DRIVER={ODBC Driver 17 for SQL Server};SERVER=MyServer;DATABASE=PMS;uid=myuid;pwd=mypassword;'`

**Comment by sdlime** [comment]
I think we should make a pass through things and remove the connection string from any error message. It's not worth playing whack-a-mole with that information. I can see a case for still logging that string. @rouault wrote a general function to mask passwords and that could be updated to also handle _pwd=_ as well. I'd leave the call to that function in place for both error and log writing. --Steve

**Comment by geographika** [comment]
Agree - leaking out the server name, database name and user id whenever a connection goes down probably isn't ideal behaviour. 
So the two changes would be:

1. Remove the connection string from the error message sent to clients (via WFS, WMS calls etc.)
2. Log the connection string in debug logs, but passing it to the generic masking function (do you recall the name of this?)/

**Comment by sdlime** [comment]
It's called msRedactCredentials(), see https://github.com/MapServer/MapServer/blob/ae65a28202c50fc134b98b3137e1735665a270e1/maperror.c#L332
Presumably there would just be a second pass for "pwd=".

**Comment by geographika** [comment]
Fixed with #6784
