### ISSUE TITLE
mapserver8: WMS-T layer backed by postgis broken with "No primary key was found"

### ISSUE THREAD

**Issue by akrherz** [MapServer/MapServer#6791]
:wave: The [documentation example](https://mapserver.org/ogc/wms_time.html#example-of-wms-t-with-postgis-tile-index-for-raster-imagery) of a WMS-T backed by postgis came from my server, which had worked up until Mapserver 8. :)

It appears 3864c3ea added a check that broke this usage case?

## Expected behavior and actual behavior.

The expected behavior is for a WMS-T request backed by postgis work.  Whilst using mapserver 8, I get:

```xml
<?xml version='1.0' encoding="UTF-8" standalone="no" ?>
<!DOCTYPE ServiceExceptionReport SYSTEM "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">
<ServiceExceptionReport version="1.1.1">
<ServiceException>
msDrawMap(): Image handling error. Failed to draw layer named &#39;nexrad-n0q-wmst&#39;.
msPostGISParseData(): Query error. Error parsing PostGIS DATA variable. No primary key was found. You must specify &#39;using unique&#39;.
</ServiceException>
</ServiceExceptionReport>

```

## Steps to reproduce the problem.

Run the documentation example.

## Operating system

Centos 9 Stream x64

## MapServer version and installation method

local cmake build.

I commented out the error/MS_FAILURE and got a different error with an invalid SQL, which appears to be `layerinfo->uid.c_str()` being empty.  Will effort this some more!

**Comment by geographika** [comment]
Thanks @akrherz - I believe this can now be closed with your docs fix. Please reopen if not.
