### ISSUE TITLE
styles parameter shouldnt be mandatory for WMS getfeatureinfo ?

### ISSUE THREAD

**Issue by landryb** [MapServer/MapServer#6812]
## Expected behavior and actual behavior.

Using 8.0 on debian 11, doing a `getfeatureinfo` on a layer without specifying a STYLES parameter complains about it while afaict my reading of the WMS spec on https://www.ogc.org/standards/wms doesn't mandate it... the requirement was added in #6012 for `getmap` (which makes sense) but im not sure its mandatory for GFI. @dmorissette @rouault @jmckenna  ?

WMS 1.3 & WMS 1.1.1 exhibit the same behaviour.

## Steps to reproduce the problem.

```
# wms 1.1.1
curl "https://wms.craig.fr/ortho?service=WMS&version=1.1.1&request=GetFeatureInfo&layers=dallage-all-ortho-rvb&query_layers=dallage-all-ortho-rvb&x=51&y=51&height=101&width=101&srs=EPSG:3857&bbox=352986.1966209439,5729261.0180871,383866.7560481551,5760141.577514311&feature_count=10&info_format=application/json"
<?xml version='1.0' encoding="UTF-8" standalone="no" ?>
<!DOCTYPE ServiceExceptionReport SYSTEM "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">
<ServiceExceptionReport version="1.1.1">
<ServiceException code="MissingParameterValue">
msWMSLoadGetMapParams(): WMS server error. Missing required parameter STYLES. Note to service administrators: defining the &quot;wms_allow_getmap_without_styles&quot; &quot;true&quot; MAP.WEB.METADATA item will disable this check (backward compatibility with behaviour of MapServer &lt; 8.0)
</ServiceException>
</ServiceExceptionReport>

#wms 1.3
curl "https://wms.craig.fr/ortho?service=WMS&version=1.3.0&request=GetFeatureInfo&layers=dallage-all-ortho-rvb&query_layers=dallage-all-ortho-rvb&x=51&y=51&height=101&width=101&crs=EPSG:3857&bbox=352986.1966209439,5729261.0180871,383866.7560481551,5760141.577514311&feature_count=10&info_format=application/json"
<?xml version='1.0' encoding="UTF-8" standalone="no" ?>
<ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException code="MissingParameterValue">
msWMSLoadGetMapParams(): WMS server error. Missing required parameter STYLES. Note to service administrators: defining the &quot;wms_allow_getmap_without_styles&quot; &quot;true&quot; MAP.WEB.METADATA item will disable this check (backward compatibility with behaviour of MapServer &lt; 8.0)
</ServiceException>
</ServiceExceptionReport>

```
## Operating system

debian 11.

## MapServer version and installation method

debian 11 backports from @sebastic (`8.0.0-2~bpo11+1`)

**Comment by rouault** [comment]
Good point @landryb . Fix queued in https://github.com/MapServer/MapServer/pull/6813

**Comment by sebastic** [comment]
FWIW, OpenLayers adds an empty STYLES parameters to its GetFeatureInfo requests:
```
?LAYERS=woonplaats
&QUERY_LAYERS=woonplaats
&STYLES=
&SERVICE=WMS
&VERSION=1.1.1
&REQUEST=GetFeatureInfo
&BBOX=79992.911117%2C6611219.830988%2C1119536.495651%2C7045382.151588
&FEATURE_COUNT=10
&HEIGHT=710
&WIDTH=1700
&FORMAT=image%2Fpng
&INFO_FORMAT=text%2Fhtml
&SRS=EPSG%3A3857
&X=843
&Y=231
```
There seems to be precedence to expect the parameter in GetFeatureInfo requests.

**Comment by jratike80** [comment]
Sure STYLES is mandatory in WMS.

> 7.3.3.4 STYLES
> The mandatory STYLES parameter lists the style in which each layer is to be rendered. The value of the STYLES
> parameter is a comma-separated list of one or more valid style names. There is a one-to-one correspondence
> between the values in the LAYERS parameter and the values in the STYLES parameter.

**Comment by geographika** [comment]
Although in the table just underneath STYLE isn't listed. 😕

![image](https://user-images.githubusercontent.com/490840/215115480-c6c1464b-6982-4a92-9d8b-8e1d42d87109.png)

**Comment by sebastic** [comment]
STYLE is assumed to be part of the "map request part", as it's one of the mandatory GetMap parameters.

**Comment by rouault** [comment]
oh, I read table 9 too far. Dropping my PR then...

**Comment by landryb** [comment]
right, sorry for the noise. damn specs...
