### ISSUE TITLE
rectObj wrong projection with PROJ9

### ISSUE THREAD

**Issue by geographika** [MapServer/MapServer#6824]
Issue #6478 seems to reappear when using MapServer main branch and PROJ9.1. 
Using the test case attached to #6478 I get different number of features returned based on if the fix below is applied or not. 

When the fix is skipped (which it is when compiling with PROJ9 due to `PROJ_VERSION_MAJOR < 9`) I get less features.
If I change `PROJ_VERSION_MAJOR < 10` then I get 2 additional features. 

https://github.com/MapServer/MapServer/blob/68fd623eddc772137952509a8008209a02cd1e85/mapproject.c#L2187-L2204

Also simply changing `int apply_over = MS_TRUE;` to `int apply_over = MS_FALSE` also appears to fix the issue. 
Proposed fix at https://github.com/geographika/mapserver/commit/d00f46e0d5c72d7b7dda31fbd590f527f0366870

Associated discussion at https://github.com/MapServer/MapServer/issues/6478#issuecomment-1416726125
PROJ fix (added in 9.0) at https://github.com/OSGeo/PROJ/pull/3055
Original patch commit: https://github.com/rouault/mapserver/commit/25171a48476558337dedfe449eb1e8daaa6a5b9a

**Comment by rouault** [comment]
I've built PROJ 9.1 and rebuilt GDAL and MapServer against it and test_reprojection_rect_and_datum_shift() passes fine. I'm wondering if there isn't some PROJ mismatch in your build configuration.

**Comment by geographika** [comment]
> I've built PROJ 9.1 and rebuilt GDAL and MapServer against it and test_reprojection_rect_and_datum_shift() passes fine. I'm wondering if there isn't some PROJ mismatch in your build configuration.

This does seem to be working again. It was failing when I tried to update in #6827. I have re-enabled the test in #6888.
