### ISSUE TITLE
mapserver 7.6 build crash

### ISSUE THREAD

**Issue by antoniocasino** [MapServer/MapServer#6830]
I have a issue running mapserver 7.6

It seems like that the file 

https://github.com/MapServer/MapServer/blob/branch-7-6/mapfile.c

on line 6719:21 has a missing semicolon. 

Can you please check and fix?

Thanks

**Comment by rouault** [comment]
Indeed. Just fixed per 9e7578d391d656d78429fe9f345af4dfc8b31aba

**Comment by antoniocasino** [comment]
Thanks a lot to both :)

**Comment by szekerest** [comment]
@geographika It is using an older SDK (release-1911) which hasn't been updated.
