### ISSUE TITLE
Restructure repository, to move all source code into /src folder

### ISSUE THREAD

**Issue by jmckenna** [MapServer/MapServer#6837]
## Reasoning

- for the user, it is much easier to understand a repository when the general files (READMEs, markdown files, CMakelists.txt, .yaml files) only exist in the root directory, and the source files (.c, .h, cpp, etc) live in `/src`
- this is the common structure now, in FOSS4G projects (such as the QGIS repo)
- it is so much easier to come to a new repository for the first time, and understand it, as the important markdown files are easily found

## Proposed layout

```
MapServer/
      .github/
      ci/
      cmake/
      etc/
      fonts/
      fuzzers/
      msautotest/
      scripts/
      share/
      src/
          apache/
          flatgeobuf/
          mapscript/
          opengl/
          renderers/
          third-party/
          *.c
          *.cpp
          *.h
      symbols/
      tests/
      xmlmapfile/
      .travis.yml
      appveyor.yml
      CMakeLists.txt
      CONTRIBUTING.md
      HISTORY.md
      LICENSE.md
      README.md
      SECURITY.md
```
## Timing

I would love to do this for the imminent `8.0.1 release`, but this is a major impact to packagers, so instead I propose to tackle this for `8.2.0` instead.  (likely also include #6593  )

**Comment by landryb** [comment]
fine with me as a packager whenever you want, and welcomed !

**Comment by sebastic** [comment]
At first glance it seems like well intended but pointless busywork.

Git makes tracking renamed/moved files easier, but the diff for this source tree reorganisation will likely be a PITA to review. Fortunately the source tree for MapServer is relatively small (unlike QGIS for which I've already spent a few hours today reviewing the changes between 3.22.16 and 3.28.3 being nowhere near finished), so it might not be such a pain.

A source tree reorganisation like this is completely inappropriate for a patch release like 8.0.1, for a new minor release like 8.2.0 it's fine.

**Comment by sdlime** [comment]
I actually like the idea but agree with @sebastic on timing. Might also be worth thinking about separating the apps (e.g. map2img, mapserv, etc...) from the library source. I see gdal has an "apps" directory for that purpose.
