### ISSUE TITLE
PHPMapscript 8 : save mapfile with CONNECTIONOPTIONS

### ISSUE THREAD

**Issue by linea974** [MapServer/MapServer#6852]
## Expected behavior 

The layer is an OGR layer (raster Geopackage) defined in a mapfile containing only one layer as follows : 
``` LAYER
    NAME "Orthophoto_2017"
    STATUS ON
    TYPE RASTER
    CONNECTIONTYPE ogr
    DATA "/the_path/ortho_2017_definitif_pyr.gpkg"
    CONNECTIONOPTIONS "TABLE" "974-2017-0325-U40S-0M20-E080" END
    TEMPLATE "template.html"
    PROJECTION
      "init=epsg:2975"
    END # PROJECTION
    METADATA
      "wms_srs" "EPSG:2975 EPSG:32740 CRS:84 EPSG:4326 EPSG:4627 EPSG:3857 EPSG:900913"
      "wms_name"            "Orthophoto_2017"
      "wms_server_version"  "1.1.1"
      "wms_format"          "image/jpeg"
      "wms_exceptions_format" "application/vnd.ogc.se_xml"
      "wms_extent" "307947 7648384 347249 7689475"
      "WMS_TITLE" "Orthophoto_2017"
      "WMS_ABSTRACT" "Orthophoto_2017"
    END
  END
```
When using map2img to create an image the result is OK.

In a PHP script, a clone of this layer is merged with other layers by cloning it in a new mapObj : 
`
$new_layer = $layer -> clone;
$new_map -> insertLayer($new_layer);
`
In the script, the resulting layer ($new_layer) contains the connectionoptions hashTable with the good key/value.
When all layers are merged, the new map is saved in a new mapfile : 
`
$new_map -> save($new_mapfile);
`
## Actual behavior.

The section CONNECTIONOPTIONS for the OGR layer is lost in the resulting mapfile :
```
  LAYER
    CONNECTIONTYPE OGR
    DATA "/the_path/ortho_2017_definitif_pyr.gpkg"
    METADATA
      "wms_srs"	"EPSG:2975 EPSG:32740 CRS:84 EPSG:4326 EPSG:4627 EPSG:3857 EPSG:900913"
      "wms_exceptions_format"	"application/vnd.ogc.se_xml"
      "WMS_ABSTRACT"	"Orthophoto_2017"
      "wms_extent"	"307947 7648384 347249 7689475"
      "wms_name"	"Orthophoto_2017"
      "nom_base"	"Orthophoto_2017"
      "wms_format"	"image/jpeg"
      "wms_server_version"	"1.1.1"
      "WMS_TITLE"	"Orthophoto_2017"
    END # METADATA
    NAME "lDED4540A-21DF-11EC-B065-005056B3A0A1_0"
    PROCESSING "NODATA=0"
    PROCESSING "RESAMPLE=NEAREST"
    PROJECTION
      "init=epsg:2975"
    END # PROJECTION
    STATUS ON
    TEMPLATE "template.html"
    TILEITEM "location"
    TYPE RASTER
    UNITS METERS
    VALIDATION
    END # VALIDATION
  END # LAYER
```
In mapfile.c, the writeLayer() function calls the writeHashTableInline function to save layer->connectionoptions (like for CONFIG key/value). Is it the right way ?

## Operating system

Ubuntu 20.04.6 LTS (Focal) 64 bits

## MapServer version and installation method

MapServer version 8.0.0 OUTPUT=PNG OUTPUT=JPEG SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=SVG_SYMBOLS SUPPORTS=RSVG SUPPORTS=ICONV SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=OGCAPI_SERVER SUPPORTS=FASTCGI SUPPORTS=THREADS SUPPORTS=GEOS INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE INPUT=FLATGEOBUF

The mapserver installation has been compiled from source.

**Comment by jmckenna** [comment]
@linea974 what happens if your layer contains the usual CONNECTION method (see https://mapserver.org/input/vector/geopackage.html#step-2-add-the-layer-in-your-mapfile ) such as:

```
LAYER
  ...
  CONNECTIONTYPE OGR
  CONNECTION "/the_path/ortho_2017_definitif_pyr.gpkg"
  DATA "974-2017-0325-U40S-0M20-E080"
   ...
```

Does that workaround the issue?

**Comment by jmckenna** [comment]
@linea974 I just tested this locally (with today's `main` checkout, and PHP 8.1.0, with MS4W on Windows).  My test layer looks like:

```
  CONNECTIONTYPE OGR
  CONNECTION "ttt.gpkg"
  CONNECTIONOPTIONS "TABLE" "ttt" END
  TYPE POINT
```
The saved mapfile (not using clone, but just inserting that layer in a new mapObj) comes out as:
```
    CONNECTION "ttt.gpkg"
    CONNECTIONTYPE OGR
    CONNECTIONOPTIONS "TABLE" "ttt"
 ```

**Comment by jmckenna** [comment]
@linea974 in fact you were 100% correct, the `writeLayer()` function should call `writeHashTable`.   In my testing I finally noticed that the written mapfile lacked the proper `CONNECTIONTYPE ... END` syntax (which then of course fails with map2img)

So my test layer was:
```
  CONNECTIONTYPE OGR
  CONNECTION "ttt.gpkg"
  CONNECTIONOPTIONS "TABLE" "ttt" END
```

which is now written out as:
```
    CONNECTION "ttt.gpkg"
    CONNECTIONTYPE OGR
    CONNECTIONOPTIONS
      "TABLE"	"ttt"
    END # CONNECTIONOPTIONS
```
I filed this change as https://github.com/MapServer/MapServer/pull/6853

**Comment by linea974** [comment]
Hi,

I made a mistake in my first post. After some test with a very simple script, I confirm that CONNECTIONOPTIONS is lost only after cloning the layer.
Therefore, I added a line in the function msCopyLayer (mapcopy.c) :
msCopyHashTable(&dst->connectionoptions,&src->connectionoptions);

Now it’s ok.

I made some tests also on Mapfile syntax and I noticed that there there are differences between raster and vectore gpkg.
For a raster layer the syntax is :


  CONNECTIONTYPE OGR

  DATA "ttt.gpkg"

  CONNECTIONOPTIONS "TABLE" "ttt" END

Thanks
De : Jeff McKenna ***@***.***>
Envoyé : mercredi 5 avril 2023 00:54
À : MapServer/MapServer ***@***.***>
Cc : Jean-Pierre Maloberti ***@***.***>; Mention ***@***.***>
Objet : Re: [MapServer/MapServer] PHPMapscript 8 : save mapfile with CONNECTIONOPTIONS (Issue #6852)


@linea974<https://github.com/linea974> in fact you were 100% correct, the writeLayer() function should call writeHashTable. In my testing I finally noticed that the written mapfile lacked the proper CONNECTIONTYPE ... END syntax (which then of course fails with map2img)

So my test layer was:

  CONNECTIONTYPE OGR

  CONNECTION "ttt.gpkg"

  CONNECTIONOPTIONS "TABLE" "ttt" END

which is now written out as:

    CONNECTION "ttt.gpkg"

    CONNECTIONTYPE OGR

    CONNECTIONOPTIONS

      "TABLE"  "ttt"

    END # CONNECTIONOPTIONS

I filed this change as #6853<https://github.com/MapServer/MapServer/pull/6853>

**Comment by jmckenna** [comment]
Thanks @linea974 I also confirmed locally the issue of CONNECTIONOPTIONS not cloned, through PHP's cloneMap(), cloneLayer(), etc.   I have updated https://github.com/MapServer/MapServer/pull/6853/commits/7c179101f3c951d9f7c11a34144d9f74ba5315bb to include that fix, as well as documenting the missing syntax for those clone* methods in PHP.    Thanks.
