### ISSUE TITLE
SLD styling ignored without error when CONNECTIONTYPE is POSTGIS.

### ISSUE THREAD

**Issue by oshawa-connection** [MapServer/MapServer#6913]
## Expected behavior and actual behavior.
When I pass a url in the `SLD` url parameter for a getMap request, the SLD is read by MapServer, but not applied to the layer. Instead it uses the style defined in the .map file. I would either expect the SLD styling to occur, or for mapserver to return an error about layer type support. When I do the request for a layer with the `CONNECTIONTYPE OGR`, it works perfectly as expected and styles the layer according to the SLD.

If needed, I can spend some time digging into which connection types work and which don't. However, I have noticed that OGR connections work and POSTGIS connections do not.

## Steps to reproduce the problem.

I have provided a test case - the example requests could look like this:

`http://localhost:8082/cgi-bin/mapserv.exe?service=WMS&version=1.3.0&MAP=PATH_TO_MAPFILE.map&request=getmap&LAYERS=places&CRS=EPSG%3A4326&BBOX=-20.029,4.311,6.137,24.745&FORMAT=image%2Fpng&WIDTH=255&HEIGHT=255&styles=&SLD=http://localhost:5253/somesld.sld`

I am careful to make sure that the name for the layer in the sld matches that in the mapfile in both cases.

## Attach simple test case
[reproducibleexample.zip](https://github.com/MapServer/MapServer/files/11982772/reproducibleexample.zip)
If this is indeed a bug, I will happily provide some POSTGIS data for this example!

## Operating system
Windows 10 64 bit using MS4W

## MapServer version and installation method
MS4W
mapserve.exe -v outputs:
```
MapServer version 7.7.0-dev (MS4W 4.0.5) OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=SVG_SYMBOLS SUPPORTS=SVGCAIRO SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=FASTCGI SUPPORTS=THREADS SUPPORTS=GEOS SUPPORTS=POINT_Z_M SUPPORTS=PBF INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE
```

**Comment by jratike80** [comment]
One good way to debug is to ask Mapserver to send the SLD of the layer with GetStyles. See what it sends for your PostGIS layer.

**Comment by oshawa-connection** [comment]
Hi @jratike80 thank you very much, that helped me debug. I was using the wrong layer name in the SLD which did match that in the map file 🤦‍♂️ Closing
