### ISSUE TITLE
Exception thrown with mapserv.exe & PROJ 9.2.1

### ISSUE THREAD

**Issue by jmckenna** [MapServer/MapServer#6915]
This occurs with `MODE=map` CGI calls, and is terribly difficult to reproduce & share, however so far I've narrowed it down to:

## Error reported
```
Exception thrown at 0x7753D902 in mapserv.exe: Microsoft C++ exception: std::invalid_argument at memory location 0x00EFE614.
```
## Call Stack
```
proj_9_2.dll!osgeo::proj::internal::c_locale_stod(const std::string & s) Line 280
	at proj-9.2.1\src\iso19111\internal.cpp(280)
proj_9_2.dll!osgeo::proj::io::getNumericValue(const std::string & paramValue={...}, bool * pHasError=0x00000000) Line 10783
	at proj-9.2.1\src\iso19111\io.cpp(10783)
proj_9_2.dll!osgeo::proj::io::PROJStringParser::Private::buildGeodeticCRS(int iStep=0, int iUnitConvert=-1, int iAxisSwap=-1, bool ignorePROJAxis=false) Line 10814
	at proj-9.2.1\src\iso19111\io.cpp(10814)
proj_9_2.dll!osgeo::proj::io::PROJStringParser::createFromPROJString(const std::string & projString={...}) Line 11978
	at proj-9.2.1\src\iso19111\io.cpp(11978)
proj_9_2.dll!osgeo::proj::io::createFromUserInput(const std::string & text={...}, const std::shared_ptr<osgeo::proj::io::DatabaseContext> & dbContext={...}, bool usePROJ4InitRules=false, pj_ctx * ctx=0x012e5130) Line 7269
	at proj-9.2.1\src\iso19111\io.cpp(7269)
proj_9_2.dll!osgeo::proj::io::createFromUserInput(const std::string & text={...}, pj_ctx * ctx=0x012e5130) Line 7897
	at proj-9.2.1\src\iso19111\io.cpp(7897)
proj_9_2.dll!proj_create(pj_ctx * ctx=0x012e5130, const char * text=0x01273cf8) Line 594
	at proj-9.2.1\src\iso19111\c_api.cpp(594)
proj_9_2.dll!proj_create_argv(pj_ctx * ctx=0x012e5130, int argc=3, char * * argv=0x012a2550) Line 1080
	at proj-9.2.1\src\4D_api.cpp(1080)
libmap.dll!msProcessProjection(projectionObj * p=0x012f0880) Line 805
	at MapServer-git-main\mapproject.c(805)
libmap.dll!initMap(mapObj * map=0x012ef360) Line 5754
	at MapServer-git-main\mapfile.c(5754)
libmap.dll!msLoadMap(const char * filename=0x0126cec8, const char * new_mappath=0x00000000, const configObj * config=0x012d9c70) Line 6380
	at MapServer-git-main\mapfile.c(6380)
libmap.dll!msCGILoadMap(mapservObj * mapserv=0x0125d100, configObj * config=0x012d9c70) Line 215
	at MapServer-git-main\mapservutil.c(215)
mapserv.exe!main(int argc=3, char * * argv=0x0126a218) Line 264
	at MapServer-git-main\mapserv.c(264)
```
## MapServer's last call
- mapproject.c [line#805](https://github.com/MapServer/MapServer/blob/main/mapproject.c#L805)
## PROJ exception occurs in
- iso19111\internal.cpp [line#280](https://github.com/OSGeo/PROJ/blob/9.1/src/iso19111/internal.cpp#L280)
## Versions
- MapServer-main
- GDAL-master
- PROJ-9.2.1

## Discussion
I'm not sure if this is a "red herring" (something that has me looking in the wrong place), but, I'm taking the chance to report this (even if it is in the wrong issue tracker).  I'm praying my bold report here turns a lightbulb on in someone.  I also realize that these specific PROJ source files look to be untouched in a while, so, I'm not sure if this is a PROJ issue.

**Comment by geographika** [comment]
@jmckenna - seems to be similar to the issue at https://github.com/MapServer/MapServer/issues/6630#issuecomment-1281966070
In that case the PROJ exception was a handled exception and the actual issue was elsewhere - as per your "red herring" comment.

**Comment by jmckenna** [comment]
thanks @geographika, yes indeed I agree that this could be a red herring, very similar to that other issue.  Closing for now (will reopen when I know the exact issue).   I'm close to finding it I feel.  Back here in a bit ha.

**Comment by rouault** [comment]
https://github.com/OSGeo/PROJ/pull/3834 should help

**Comment by geographika** [comment]
> [OSGeo/PROJ#3834](https://github.com/OSGeo/PROJ/pull/3834) should help

Thanks @rouault - this will definitely help with debugging using Visual Studio.

**Comment by jmckenna** [comment]
@rouault thank-you very much for this, I tested that branch and the exceptions through the MSVC debugger are gone.  This helps immensely.
