### ISSUE TITLE
PHP-/SWIG-Mapscript WFS GetPropertyValue: HTTP Headers in Textbody

### ISSUE THREAD

**Issue by ghschier** [MapServer/MapServer#6942]
I use Mapscript for a WFS Server.

The following Request works as expected:

....?SERVICE=WFS&REQUEST=GetPropertyValue&VERSION=2.0.0&TYPENAMES=zweckverband&valueReference=NAME

If there is a error (for example because of non existing typename or valueReference), the output is:

```
Status: 400 Bad request
Content-Type: text/xml; charset=UTF-8

<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows/1.1" version="2.0.0" xml:lang="en-US" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd">
  <ows:Exception exceptionCode="InvalidParameterValue" locator="valuereference">
    <ows:ExceptionText>msWFSGetPropertyValue(): WFS server error. Invalid VALUEREFERENCE NAM</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```

That means, the HTTP-Headers are contained in the body of the response. I tried  `ms_iostripstdoutbuffercontentheaders`, but it is the same behaviour.
Expected behaviour would be to get only the ServiceException as output.

I tested in 2 environments:

## 1 with PHP-Mapscript
Ubuntu 20.04 64Bit, Apache 2.4.41, PHP 7.4.3,  MapServer 7.4.3

## 2 with SWIG-Mapscript
Debian Bookworm 64Bit, Apache 2.4.57, PHP 8.2.7,  MapServer  8.0.0

**Comment by jratike80** [comment]
Regular http query from the demo server does not print http headers

https://demo.mapserver.org/cgi-bin/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=getfeature&TYPENAME=foo&MAXFEATURES=100

Could you try similar query with your server? If issue appears to be something specific to Mapscript, please try to write ans attach a re-producible example. It would be excellent if you could make the issue to happen with demo.mapserver.org.

**Comment by ghschier** [comment]
OK, it seems that `msIO_getAndStripStdoutBufferMimeHeaders` solves the problem, as described here: #6762

For testing (to demonstrate the problem) I used the following code (SWIG-Mapscript):
```php
<?php 

$mapfile = <<<MAPFILE
MAP
  WEB
    METADATA
      "ows_enable_request"	"*"
      "wfs_onlineresource"	"http://127.0.0.1/cities"
    END # METADATA
  END # WEB

  LAYER
    CONNECTION "cities.gml"
    CONNECTIONTYPE OGR
    ENCODING "UTF-8"
    METADATA
      "gml_include_items"	"all"
    END # METADATA
    NAME "cities"
    PROJECTION
      "init=epsg:4326"
    END # PROJECTION
    TYPE POINT
  END # LAYER
END
MAPFILE;

$objMap = mapscript::msLoadMapFromString($mapfile, NULL);

$request = new OWSRequest();
foreach ($_GET as $key => $value) $request->setParameter($key, $value);

mapscript::msIO_installStdoutToBuffer();

$objMap->owsdispatch($request);

$contenttype = mapscript::msIO_stripStdoutBufferContentType();
mapscript::msIO_stripStdoutBufferContentHeaders();

//to show the plain output in the browser:
header('Content-Type: text/plain');

print mapscript::msIO_getStdoutBufferBytes();
```

The following request works as expected:
`example.php?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=cities`

This request outputs the HTTP-headers in the HTTP-Body:
`example.php?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=foo`

As said above, with `msIO_getAndStripStdoutBufferMimeHeaders` it works, but the function didn't exist in PHP-Mapscript.
I agree with the author of #6762 in that the functionnames are misleading.
Any documentation would be fine.

**Comment by jmckenna** [comment]
@ghschier thanks for the research.  I'm sure we'd be open to renaming these confusingly-named functions, but that would have to be for a MapServer 9.0 release.   Would you mind filing a new issue for the renaming (and stating the new and old names there)?  Thanks.

Regarding documentation (it sounds like it is perfect timing as it is so fresh in your mind) we're always open for pull requests.

**Comment by ghschier** [comment]
Opened new issue #6944.

**Comment by jmckenna** [comment]
Thanks @ghschier the new issue is very clear, I'd be in support of those changes.

Closing this issue here.
