### ISSUE TITLE
Expressions containing <> do not throw parsing errors

### ISSUE THREAD

**Issue by geographika** [MapServer/MapServer#6950]
I ran into this issue when checking SLD output from LAYER CLASS EXPRESSIONS. 

I'd not thoroughly read the [logical expression docs](https://www.mapserver.org/mapfile/expressions.html#arithmetic-expressions-that-return-a-logical-value) and so had been unaware that `NOT` expressions in MapServer can be represented by `!=` or `ne`, but not `<>`. 

The following layer parses fine in MapServer, but the `<>` gets parsed as `MS_TOKEN_COMPARISON_LT` and `MS_TOKEN_COMPARISON_GT` in https://github.com/MapServer/MapServer/blob/24d36f842c243f96eba88ff896db1bf34d8a687a/src/maplayer.c#L679

```
    LAYER
      NAME "Test18"    
      TYPE POINT
      CLASS
        EXPRESSION ( [FID] <> 1 AND [FID] <> 10 )
        STYLE
            COLOR 220 0 0
            WIDTH 1
        END
      END
    END
```

This probably causes strange issues when rendering data, but is more noticeable when generating SLD as it returns:

```xml
  <ogc:Filter>
    <ogc:And>
      <ogc:PropertyIsLessThan>
        <ogc:PropertyName>FID</ogc:PropertyName>
        <ogc:Literal>> 1</ogc:Literal>
      </ogc:PropertyIsLessThan>
      <ogc:PropertyIsLessThan>
        <ogc:PropertyName>FID</ogc:PropertyName>
        <ogc:Literal>> 10 </ogc:Literal>
      </ogc:PropertyIsLessThan>
    </ogc:And>
  </ogc:Filter>
```

Ideally I think the MapServer expression parser should throw an error when reading the Mapfile (or we attempt to support `<>` in expressions).

**Comment by sdlime** [comment]
Maybe easiest to support <>…
