### ISSUE TITLE
Some SVG files doesn't display in 8.x

### ISSUE THREAD

**Issue by mapcentia** [MapServer/MapServer#6956]
I've a MapFile with a point layer using a class style with a SVG symbol:

CLASS
     NAME 'point'
     STYLE
         SYMBOL
'https://raw.githubusercontent.com/NordjyllandsTrafikselskab/gisimages/ca64d7a849c7cf0290ec41ec263a97b9195d0ff8/01.01.01.Bus.svg'
     END
END

In 7.6 this works fine, but in 8.x the SVG symbol is not showing (no
errors but the image is blank). But it works if I change the SVG file to e.g.:

https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/AJ_Digital_Camera.svg

Initial research conducted by MapServer devs yielded:

- Removing the viewBox attribute from the SVG makes it work.
- Adding a width and height attribute to the SVG also works, without having to remove the viewBox:

MapServer version 8.1-dev PROJ version 7.2 GDAL version 3.4 OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=SVG_SYMBOLS SUPPORTS=RSVG SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=OGCAPI_SERVER SUPPORTS=FASTCGI SUPPORTS=GEOS SUPPORTS=PBF INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE INPUT=FLATGEOBUF

**Comment by jratike80** [comment]
See also https://lists.osgeo.org/pipermail/mapserver-users/2023-July/083198.html

**Comment by mapcentia** [comment]
Pr for this issue #7028
