### ISSUE TITLE
BoundingBox is wrong in wms getcapablites in 1.3.0 but correct in 1.1.0

### ISSUE THREAD

**Issue by kungzlatan** [MapServer/MapServer#6978]
![image](https://github.com/MapServer/MapServer/assets/61743853/55bd5343-921c-4d56-a771-e0f6ff774440)

from 1.1.0

```
<Layer queryable="0" opaque="0" cascaded="0">
        <Name>bluemarble</Name>
        <Title>Blue Marble World Elevation and Bathymetry Raster</Title>
        <SRS>EPSG:4326</SRS>
        <LatLonBoundingBox minx="-180.000000" miny="-90.000000" maxx="180.000000" maxy="90.000000" />
        <BoundingBox SRS="EPSG:4326"
                    minx="-180.000000" miny="-90.000000" maxx="180.000000" maxy="90.000000" />
```

from 1.3.0
```
<Layer queryable="0" opaque="0" cascaded="0">
<Name>bluemarble</Name>
<Title>Blue Marble World Elevation and Bathymetry Raster</Title>
<CRS>EPSG:4326</CRS>
<EX_GeographicBoundingBox>
<westBoundLongitude>-180.000000</westBoundLongitude>
<eastBoundLongitude>180.000000</eastBoundLongitude>
<southBoundLatitude>-90.000000</southBoundLatitude>
<northBoundLatitude>90.000000</northBoundLatitude>
</EX_GeographicBoundingBox>
<BoundingBox CRS="EPSG:4326" minx="-90.000000" miny="-180.000000" maxx="90.000000" maxy="180.000000"/>
<Attribution>

```
service used to test with

https://demo.mapserver.org/cgi-bin/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

**Comment by jratike80** [comment]
The latitudes and longitudes in the WMS 1.1.0 and WMS 1.3.0 capabilities are in different order but it does not mean that they are wrong in one or the other.
As a comparison, this is how GeoServer presents bounding boxes with WMS 1.3.0

```
<EX_GeographicBoundingBox>
<westBoundLongitude>143.83482400000003</westBoundLongitude>
<eastBoundLongitude>148.47914100000003</eastBoundLongitude>
<southBoundLatitude>-43.648056</southBoundLatitude>
<northBoundLatitude>-39.573891</northBoundLatitude>
</EX_GeographicBoundingBox>
<BoundingBox CRS="CRS:84" minx="143.83482400000003" miny="-43.648056" maxx="148.47914100000003" maxy="-39.573891"/>
<BoundingBox CRS="EPSG:4326" minx="-43.648056" miny="143.83482400000003" maxx="-39.573891" maxy="148.47914100000003"/>

```
The axis order in EPSG:4326 is officially latitude-longitude and WMS 1.3.0 respects it. Probably that was the meaning also in previous WMS versions but that was never properly written into the standard. Therefore it is common in WMS 1.1.x to use the longitude-latitude order.

**Comment by jratike80** [comment]
I am sorry but I don't get the point. In WMS 1.3.0
SouthBoundLatitude=MinLatitude=MinX=-90 degrees
WestBoundLongitude=MinLongitude=MinY=-180 degrees
and so on.

**Comment by kungzlatan** [comment]
Should not minx be the same as westboundlongitude?

**Comment by jratike80** [comment]
Minx is the minimum value of the first coordinate axis, that is latitude for EPSG:4326, thus minx = SouthBoundLatitude.
