### ISSUE TITLE
PHPScript

### ISSUE THREAD

**Issue by farid-teymouri** [MapServer/MapServer#6995]
while i using this 
`cmake .. -DCMAKE_INSTALL_PREFIX=/opt -DCMAKE_PREFIX_PATH=/usr/local/pgsql/91:/usr/local:/opt -DWITH_CLIENT_WFS=ON -DWITH_CLIENT_WMS=ON -DWITH_CURL=ON -DWITH_PHPNG=ON -DWITH_PR
OTOBUFC=0`

then i got this error 
`/usr/local/lsws/admin/misc/MapServer/src/mapscript/mapscript.i:255: Error: Unable to find '../../mapserver-version.h'
make[2]: *** [src/mapscript/phpng/CMakeFiles/php_mapscriptng_swig_compilation.dir/build.make:76: src/mapscript/phpng/CMakeFiles/php_mapscriptng.dir/mapscriptPHP7.stamp] Error 1
make[2]: *** Deleting file 'src/mapscript/phpng/CMakeFiles/php_mapscriptng.dir/mapscriptPHP7.stamp'
make[1]: *** [CMakeFiles/Makefile2:485: src/mapscript/phpng/CMakeFiles/php_mapscriptng_swig_compilation.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`

anyone could you help me ?!

**Comment by geographika** [comment]
@farid-teymouri - you are best to follow the CI scripts which build MapServer and PHP MapScript - see https://github.com/MapServer/MapServer/blob/main/.github/workflows/start.sh (which calls a couple of other scripts). 
If you still have issues please post a question to the mapserver-users list at https://mapserver.org/community/lists.html

**Comment by geofranzi** [comment]
I had the same issue and fixed it by changing line 255  in the following script: 

https://github.com/MapServer/MapServer/blob/branch-8-0/mapscript/mapscript.i

from `%include "../../mapserver-version.h"` to `%include "../../mapserver-version.h.in"`

after that it worked for me.
