### ISSUE TITLE
ability to use non existing properties in (FI) templates

### ISSUE THREAD

**Issue by pvgenuchten** [MapServer/MapServer#7014]
i want to reuse featureinfo templates in multiple grid layers, the number of bands varies between grids. The fi template should not fail if a grid does have limited number of bands

## Expected behavior and actual behavior.

Current: 
- if I use [value_1] on a single band grid the text is rendered as is.
- if i use [item name="value_1" nullformat="na"] on a single band grid i get error: `processItemTag(): Web application error. Item name (value_1) not found in layer item list.`

Expected:

3 options:
- If the "nullformat" attribute is set, do not error in the case a property does not exist, but use the value of nullformat='na'
- Introduce a new "missingfield" attribute (like nullformat), for if the field isn't found in the dataset? 
- Add a config option to neglect field-missing errors, if set, just leave missing fields blank

My favourite is 1st

## Simple test case 

```
<!-- MapServer Template -->
Band 1: [value_0]<br/>
[item name="value_1" format="Band 2: $value" nullformat=""]<br/>
```

## Operating system

ubuntu

## MapServer version and installation method

8.01 Docker-camp2camp

**Comment by geographika** [comment]
This seems a useful enhancement to me. From https://mapserver.org/mapfile/template.html#general

```
nullformat = String to output if the attribute value is NULL, empty or doesn’t match the pattern (if defined). If not set and any of these conditions occur the item tag is replaced with an empty string.
```

So `nullformat` is already used for a couple of cases - both NULL values and values that don't meet a regex, so could be expanded to missing fields. The downside would be possibly breaking backwards compatibility with current templates - although as noted in this issue if a field is missing the template would be throwing an error.

**Comment by sdlime** [comment]
> This seems a useful enhancement to me. From https://mapserver.org/mapfile/template.html#general
> 
> ```
> nullformat = String to output if the attribute value is NULL, empty or doesn’t match the pattern (if defined). If not set and any of these conditions occur the item tag is replaced with an empty string.
> ```
> 
> So `nullformat` is already used for a couple of cases - both NULL values and values that don't meet a regex, so could be expanded to missing fields. The downside would be possibly breaking backwards compatibility with current templates - although as noted in this issue if a field is missing the template would be throwing an error.

Perhaps setting an item-level attribute to ignore missing a item - potentially paired with the nullformat - would be a way to avoid backwards compatibility issues.

**Comment by geographika** [comment]
> Perhaps setting an item-level attribute to ignore a missing item - potentially paired with the nullformat - would be a way to avoid backwards compatibility issues.

@sdlime - sounds good to me. What about an `ignoremissing` property, which can take a `"true"` value, to ignore missing fields, and if the field is missing it populates the template with the `nullformat` value e.g.

```
<!-- MapServer Template -->
Band 1: [value_0]<br/>
[item name="value_1" format="Band 2: $value" nullformat="" ignoremissing="true"]<br/>
```

**Comment by sdlime** [comment]
Yeah, that's what I was thinking. I can't think of a more concise name...
