### ISSUE TITLE
undefined symbol: msCGIWriteLog when calling any mapserver command

### ISSUE THREAD

**Issue by geovannyAvelar** [MapServer/MapServer#7026]
## Expected behavior and actual behavior.

Any mapserv binary invocation (even when calling `mapserv -v`) throws the following symbol lookup error:

`mapserv: symbol lookup error: mapserv: undefined symbol: msCGIWriteLog`

## Steps to reproduce the problem.

Install mapserv-bin version 7.6.4 package in Ubuntu 22.04, from [Ubuntu GIS](https://wiki.ubuntu.com/UbuntuGIS) repo:

`apt install mapserver-bin=7.6.4-2build2`

Next, try to run any mapserv command:

`mapserv -v`

Any command, even a simple `mapserv` throws this error. It started after an Ubuntu dependecy upgrade (`apt upgrade`)

## Operating system

Ubuntu 22.04

## MapServer version and installation method

7.6.4 version from ubuntugis-unstable PPA

**Comment by geographika** [comment]
Maybe you are mixing the `cgi-mapserver` CGI executable for MapServer (7.4) package with the `libmapserver2` Shared library for MapServer pacakge (8.0.1)?

Ubuntu 22.04 (jammy) seems to list MapServer 8.0.1 as the release at https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable/+packages and not 7.6.4. 

Probably best to uninstall all packages and run `apt-get install cgi-mapserver mapserver-bin` from scratch.

**Comment by geovannyAvelar** [comment]
@geographika Thank you. We unadvertedely updated libmapserver2 to 8.x.x. That's the cause of the problem.
