### ISSUE TITLE
Parser IO error is ignored if map include is a directory

### ISSUE THREAD

**Issue by PPazderski** [MapServer/MapServer#7043]
If map file parsing fails with an IO error this error is (at least sometimes; maybe always) ignored.

This issue is not very sever because often some other code will report an error instead. I found only one path were a read error from the parser is fully ignored.

See `emptyinclude.zip` for a minimal example. It has an INCLUDE with empty argument which basically is the same as if the argument is './'.
For this issue it is only relevant that the include file is actually a directory.

If the include file cannot be opened for any reason the lexer will report an error but a directory can be opened but the next read in the `YY_INPUT` macro will set an error.
But this error is more or less ignored and processing continues and if the include file is not essential for the map file it will report no error at all.

I assume this is related to 05d44e6a4dd3195511b9d0eb0c78de3c6e5c7730. I had some crashes with empty INCLUDE arguments in version 8.0.0 and while I tried to find the reason I stumbled upon this. I could not reproduce my crashes with the latest version anymore.

The example I provided shows that the lexer calls `msSetError` -- it can be seen with debug enabled -- but without debug enabled nothing indicates a problem.

Because it no longer crashes I don't care whether this bug (if you see it as bug at all) is fixed or ignored.

[emptyinclude.zip](https://github.com/MapServer/MapServer/files/14531007/emptyinclude.zip)

**Comment by sdlime** [comment]
I believe this was fixed as a result of the oss-fuzz fix you referenced. @rouault, can this ticket be closed?
