### ISSUE TITLE
msRedactCredentials removes too much content especially for postgis connections

### ISSUE THREAD

**Issue by PPazderski** [MapServer/MapServer#7046]
The function to hide passwords in debug and error output removes to much content.

## Expected behavior and actual behavior.

Expected:

Only the password is removed.

```
msPostGISLayerOpen called: the_geom from something
msPostGISLayerOpen: No connection in pool, creating a fresh one.
msPostGISLayerOpen: Connection failure.
Database connection failed (invalid port number: "99999"
) with connect string 'dbname=nonexistingdatabase user=AzureDiamond password=******* port=99999'
Is the database running? Is it allowing connections? Does the specified user exist? Is the password valid? Is the database on the standard port? in msPostGISLayerOpen()msPostGISLayerOpen(): Query error. Database connection failed. Check server logs for more details.Is the database running? Is it allowing connections? Does the specified user exist? Is the password valid? Is the database on the standard port?
msDrawMap(): Image handling error. Failed to draw layer named 'not_working_connection'.
msDrawMap(): Image handling error. Failed to draw layer named 'not_working_connection'. <br>
msPostGISLayerOpen(): Query error. Database connection failed. Check server logs for more details.Is the database running? Is it allowing connections? Does the specified user exist? Is the password valid? Is the database on the standard port? <br>
msPostGISLayerIsOpen called.
```

Actual:

In most cases the password and all content after is removed.

```
msPostGISLayerOpen called: the_geom from something
msPostGISLayerOpen: No connection in pool, creating a fresh one.
msPostGISLayerOpen: Connection failure.
Database connection failed (invalid port number: "99999"
) with connect string 'dbname=nonexistingdatabase user=AzureDiamond password=*********************************************************************************************************************************************************************************************msPostGISLayerOpen(): Query error. Database connection failed. Check server logs for more details.Is the database running? Is it allowing connections? Does the specified user exist? Is the password valid? Is the database on the standard port?
msDrawMap(): Image handling error. Failed to draw layer named 'not_working_connection'.
msDrawMap(): Image handling error. Failed to draw layer named 'not_working_connection'. <br>
msPostGISLayerOpen(): Query error. Database connection failed. Check server logs for more details.Is the database running? Is it allowing connections? Does the specified user exist? Is the password valid? Is the database on the standard port? <br>
msPostGISLayerIsOpen called.
```

## Steps to reproduce the problem.

The attached example shows the problem by logging a failed postgis connection.

[redact_credentials.zip](https://github.com/MapServer/MapServer/files/14540978/redact_credentials.zip)

## MapServer version

Since 8.0.1.

## My opinion on the issue

This is an annoying and at the same time nasty and difficult problem. It is related to #6784.

https://github.com/MapServer/MapServer/blob/9240625b87880421b48bb5e66230275e08a2c6eb/src/maperror.c#L355-L363

When processing a debug or error message it will first search for `password=` and remove anything after until the first space.
Then it will take the redacted message will again search for `password=` and will find it again and now remove anything after until the first semicolon.

Apparently my example message has no semicolon so everything after `password=` is replaced.

I have no good idea how to fix this in general. At the point this redaction is applied there is no context, only a plain message and no way to know the required delimiter for a particular message for sure.
In the extrem there is no way to distinguish a OGR MySQL connection with connection string `MySQL:test,user=root,password=mysql,port=3306` and a PostGIS connection where my connection string is for some reason `host=myhost dbname=gis user=name password=mysql,port=3306 port=5432`.
And keywords could be case insensitive... :/

But I have two suggestions to improve the situation.

1. One annoyance is that the redaction also removes the newline (it is not clearly visible in my example because the postgis debug message happens to miss the newline anyways). Would already help if the replace function stops on newline.

2. While writing this issue I noticed that there are more possible database connection strings than the three mentioned in `msRedactCredentials`. I added such a case in my example.zip inspired from https://mapserver.org/input/vector/mysql.html#create-mapserver-layer.
The second thing I noticed is that the MapServer documentation and #6784 mention `pwd` for MSSQL as keyword but in code the MSSQL case (according to the comment) has `password`. If this was a mistake and `pwd` till semicolon is enough for MSSQL the second `msRedactString` could be removed which would fix the problem for PostGIS.

**Comment by geographika** [comment]
@PPazderski - thanks for looking into this. 
MSSQL uses both `pwd` and `password` for connections depending on the database driver used. 

One option could be to replace both the password and the keyword which I think would solve the issue. For example:

```
\SQL2019;DATABASE=msautotest;pwd=Password12!;uid=sa;
```

Would become something like:

```
\SQL2019;DATABASE=msautotest;***************;uid=sa;
```

This would then skip any subsequent replacements. It could also stop at a linebreak if no delimiter is found, although if the above approach is used I'm not sure if that would still be necessary.

**Comment by PPazderski** [comment]
> One option could be to replace both the password and the keyword which I think would solve the issue.

Unfortunately that would not work. Imagine the case with a space in password for MSSQL. With the current code plus replacing the `password=` it would first replace the password until the space in the password plus the key but then the second replacement for MSSQL with semicolon delimiter would not apply anymore. E.g.
```
\SQL2019;DATABASE=msautotest;password=Password with space;uid=sa;
```
would become
```
\SQL2019;DATABASE=msautotest;***************** with space;uid=sa;
```

**Comment by rouault** [comment]
Proposed fix in https://github.com/MapServer/MapServer/pull/7048
