### ISSUE TITLE
Mapserver unable to read config file

### ISSUE THREAD

**Issue by Revo2022** [MapServer/MapServer#7050]
## Expected behavior and actual behavior.

We installed mapserver 8.0.1 and cant get it running. The only thing working is the map2img call. Any browser call will result in: `msLoadConfig(): Unable to access file. See mapserver.org/mapfile/config.html for more information.`
Sadly theres no output in the logs if the file is there, has invalid access rights or invalid content.

## Steps to reproduce the problem.

- Install mapserver
- rename conf file to mapserver.conf
- set env variable to path of mapserver.conf
- gave rights to conf file directory (probably no problem because small test machine only has root user anyway)

## Operating system

Debian 11

## MapServer version and installation method

`MapServer version 8.0.1 PROJ version 7.2 GDAL version 3.2 OUTPUT=PNG OUTPUT=JPEG SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FRE             ETYPE SUPPORTS=ICONV SUPPORTS=WMS_SERVER SUPPORTS=WFS_SERVER SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=OGCAPI_SER             VER SUPPORTS=FASTCGI SUPPORTS=GEOS INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE INPUT=FLATGEOBUF`

**Comment by snb452** [comment]
Yesterday I got the same problem. Mapserver v8.0.1 
Solution:
1. Create /usr/local/etc/mapserver.conf (content I took from https://mapserver.org/mapfile/config.html#config)
2. In /etc/apache2/sites-enabled/mapsrv.conf (in my case) I added: SetEnv MAPSERVER_CONFIG_FILE /usr/local/etc/mapserver.conf (after ScriptAlias)
3. sudo systemctl reload apache2.service
4. sudo systemctl restart apache2.service

After that everything works fine)
Good luck!

**Comment by jmckenna** [comment]
Closing.  @Revo2022 please use the MapServer-users mailing list for support questions.  Subscribe at https://lists.osgeo.org/mailman/listinfo/mapserver-users thanks.
