### ISSUE TITLE
Enforce code formatting

### ISSUE THREAD

**Issue by marisn** [MapServer/MapServer#7114]
While preparing a new contribution, I encountered problems with code formatting – running astyle on existing files changed way more than just my code. It would be nice if it would be possible to run a code formatter without worrying of reformatting a lot of old code.

* File scripts/astyle.sh has not been updated to work with the new code layout
* Wiki does not mention scripts/astyle.sh (https://github.com/mapserver/mapserver/wiki/CodingStyle)
* Coding style should be enforced for all new code contributions. See e.g. GRASS GIS pre-commit + GitHub CI tests

**Comment by geographika** [comment]
@marisn - as far as I know `astyle.sh` is no longer used. Instead, `pre-commit` is used to enforce coding styles:

https://mapserver.org/development/dev_practices.html#commit-hooks

```
pip install pre-commit
cd /mapserver
pre-commit run --all-files
```

**Comment by rouault** [comment]
I've updaed the wiki page to point to https://mapserver.org/development/dev_practices.html and removed the outdated scripts/astyle.sh file
