### ISSUE TITLE
MS_LEGEND_KEYSIZE_MAX 200

### ISSUE THREAD

**Issue by gu-LGB** [MapServer/MapServer#7152]
I'm currently migrating from MS 7.6 to 8.0 and I have a problem with this limitation:
https://github.com/MapServer/MapServer/pull/6458/files/28ed62920876660838063846a8184a489cee1a36#r1743994033

So far I could provide legends consisting of a PNG like this:   
https://inspire.brandenburg.de/services/bobasensorp_wms?&service=WMS&version=1.3.0&request=GetLegendGraphic&sld_version=1.1.0&layer=sorp&format=image/png&STYLE=default&   

with this configuration:

```
LEGEND
   KEYSIZE 216 216
   KEYSPACING 7 7
   STATUS ON
END

CLASS
  KEYIMAGE "./inspire_lbgr/symbol/legende-sorption_matrix.png"
  NAME " "
END
```
Is there anything against raising the limit to:   
**MS_LEGEND_KEYSIZE_MAX 1000**
?
   
   
## Operating system

Debian 6.1.106-3 

## MapServer version and installation method

8.0.0-3+b8 (Debian Repo)

**Comment by geographika** [comment]
@sdlime - I thought `KEYSIZE` might be a value that could be changed by a user e.g. with `&"map.legend=keysize+40+40` but this approach was removed in MapServer 8 -https://www.mapserver.org/cgi/controls.html#using-mapserver-version-8. 
So it seems the only risk of overloading a server is by a Mapfile author, so I'm in favour of increasing `MS_LEGEND_KEYSIZE_MAX ` to a larger value (why not 1000).

**Comment by sdlime** [comment]
Yeah, the 200px was a somewhat random selection based on sample mapfiles
identified at the time. I’m ok with a larger value, although 1000px seems
huge, but you’re right, there is little risk.

I did figure there might be a few other things to tweak. For example, maybe
we should fix the ANGLE limits at the same time. There was a suggestion to
simply convert other angles to 0-360 rather than bailing. Might help with
8.x upgrades as well.

**Comment by gu-LGB** [comment]
> although 1000px seems huge

Our largest PNG legends are 870 px. Hence the suggestion of 1000px.

**Comment by geographika** [comment]
I'm guessing there may be a difference between using `KEYSIZE` for generating symbols for many classes in a layer, and using `KEYIMAGE` to point to a ready-made legend file (which could be large) for a layer with a single class. 

@gu-LGB - if you remove `KEYSIZE 216 216` completely from your `LEGEND` do your request work?

**Comment by gu-LGB** [comment]
If I omit the `KEYSIZE `option, my `KEYIMAGE` (the PNG) comes out extremely small (39x20px):

![grafik](https://github.com/user-attachments/assets/8388c426-f317-4739-9604-7bf2133aec5b)

**Comment by gu-LGB** [comment]
@sdlime can you estimate when there will be a new version with the adjusted KEYSIZE limit?

**Comment by geographika** [comment]
@gu-LGB - if you can open a new pull request, and add a link back to this issue it can be merged for the next release. 

Just to confirm - are your large PNGs pre-generated legends rather than MapServer generated CLASS icons?

**Comment by gu-LGB** [comment]
PR ist merged.
