### ISSUE TITLE
WMS GetFeatureInfo -> no data -> not linked to "EMPTY"-Option -> MS 8.2.2

### ISSUE THREAD

**Issue by gu-LGB** [MapServer/MapServer#7158]
I'm migrating from MS 7.6 to 8.2.2:
In MS 7.6, when I clicked on a coordinate with no data in the GFI, I was redirected to the web page specified with the "EMPTY" parameter in mapfile:

```
MAP
    ........
    WEB
		HEADER '../templates/header_bildflugplan.html'
		FOOTER '../templates/footer_bildflugplan.html'
		EMPTY    'https://isk.geobasis-bb.de/error_pages/wms_gfi_empty.html'
		ERROR    'https://isk.geobasis-bb.de/error_pages/wms_error.html'
		QUERYFORMAT text/html
	......
    END
    .......
END

```
-->[GFI to Area **with** data](https://isk.geobasis-bb.de/ows/bildflug_wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&BBOX=274166.00338692212244496,5788468.08162481803447008,413411.75338692212244496,5955482.49275198485702276&CRS=EPSG:25833&WIDTH=692&HEIGHT=830&LAYERS=bfp_2&STYLES=&FORMAT=image/png&QUERY_LAYERS=bfp_2&INFO_FORMAT=text/html&I=380&J=365&FEATURE_COUNT=10)

-->[GFI to Area **without** data](https://isk.geobasis-bb.de/ows/bildflug_wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&BBOX=274166.00338692212244496,5788468.08162481803447008,413411.75338692212244496,5955482.49275198485702276&CRS=EPSG:25833&WIDTH=692&HEIGHT=830&LAYERS=bfp_2&STYLES=&FORMAT=image/png&QUERY_LAYERS=bfp_2&INFO_FORMAT=text/html&I=437&J=625&FEATURE_COUNT=10)

Now in MS 8.2.2 I get a blank page (HTTP 200). Unfortunately, my test environment with the new version is not available on the Internet.

Does anyone have an idea why the redirection no longer works? I couldn't find any changes in the documentation.

Is it related to this PR? Or does it only apply to WFS:
https://github.com/MapServer/MapServer/pull/6268/files#diff-a99a8b14c4928ecf3b2391cf7582c904388c792dfb33a304b9f506326fb8130c

## Operating system

Debian 6.1.106-3

## MapServer version and installation method

![grafik](https://github.com/user-attachments/assets/fc64f2a2-1492-4135-aea7-ce875a6c069d)
--> Backport from Debian 13 for Debian 12

**Comment by jratike80** [comment]
I wonder if hardened security rules block access to external site. Have you tried to place also the error html file into /templates/?

**Comment by gu-LGB** [comment]
Unfortunately the same behavior with the local storage:

```
HEADER '../templates/header_bildflugplan.html'
FOOTER '../templates/footer_bildflugplan.html'
EMPTY  '../templates/error_pages/wms_gfi_empty.html'
ERROR  '../templates/error_pages/wms_error.html'
QUERYFORMAT text/html
```

> BTW it was correct to ask a question on the mailing list, sometimes it just takes time before someone reacts.

Sorry, you're right. I created the issue to better describe the problem (40 KB limit in the user mailing list).

**Comment by gu-LGB** [comment]
I have attached 2 logs, one from the call where data is found and one where no data is found.

[GFI_with_Data.log](https://github.com/user-attachments/files/16973933/GFI_with_Data.log)
[GFI_without_data.log](https://github.com/user-attachments/files/16973939/GFI_without_data.log)

I can't see any problem:
```
msPostGISLayerWhichShapes got 0 records in result.
.....
msQueryByPoint(): No matching record(s) found.
```
What amazes me is that the empty page has the same title as the HTML template where the GFI is presented when a find is made.

**Comment by geographika** [comment]
@gu-LGB - if you set `MS_EMPTY_URL` in your mapserver.config file do you get the expected results?

```
CONFIG
  ENV
    MS_EMPTY_URL "https://isk.geobasis-bb.de/error_pages/wms_gfi_empty.html"
```

**Comment by gu-LGB** [comment]
@geographika - no, same result:

![grafik](https://github.com/user-attachments/assets/4598c9d3-bc54-421f-bb16-5bd1441dcdc8)

with this option:

![grafik](https://github.com/user-attachments/assets/3fc2ab3a-de8d-4c50-8578-d12f70d6508c)

**Comment by sdlime** [comment]
Is the query done via WMS, WFS or one of the CGI methods? It’s possible functionality restored in 8.2 doesn’t address OGC protocols. My original bug report was specific to CGI-based queries. We’ll need to go back to the 7.6 branch and see where EMPTY was referenced. The code I patched still had the blocks that used EMPTY, but they were being bypassed.

**Comment by gu-LGB** [comment]
Exactly, WMS.    
That would be great if you find the time to fix it. We are still using version 8.2 productively, as this problem is not that serious for us. So take it easy..
